### ISSUE TITLE
Support for complex grouped layouts

### ISSUE THREAD

**Issue by astrism** [formly-js/angular-formly#1]
We should be able to create multiple column layouts so that forms can be displayed more compactly.

On the JSON side I think this should use a new field type which allows you to nest arrays of new fields. The format I'm proposing is below, the current array format would remain unchanged, but a new field type (`group`) would be added that takes a `fields` and `label` argument. The group would also apply the appropriate responsive bootstrap classes.

```
$scope.formData = [
	{
		type: 'group-column',
		label: 'Project Details',
		fields: [
			{
				type: 'text',
				label: 'Project Name',
				key: 'projectName'
			}
		]
	}, {
		type: 'group-row',
		label: 'Contact Data',
		fields: [
			{
				type: 'text',
				label: 'First Name',
				key: 'firstName'
			},
			{
				type: 'text',
				label: 'Last Name',
				key: 'lastName'
			}
		]
	}
];

```

Which would roughly produce something link this (plus the approprite ng attrs). I could use a suggestion on how to handle label styling, currently using `.lead`...
```
<form>
	<!-- group-column -->
	<div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="lead">Project Details</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<label for="">Project Name</label>
			<input class="form-control" type="text">
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<label for="">Project Due Date</label>
			<input class="form-control" type="text">
		</div>
	</div>
	<!-- group-row -->
	<div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="lead">Contact Data</div>
		<div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6">
			<label for="">First Name</label>
			<input class="form-control" type="text">
		</div>
		<div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6">
			<label for="">Last Name</label>
			<input class="form-control" type="text">
		</div>
	</div>
</form>
```
And render something like this:
![screen shot 2014-02-14 at 3 56 16 pm](https://f.cloud.github.com/assets/48418/2176452/a0d36384-95d3-11e3-971c-264e742d8445.png)

**Comment by kentcdodds** [comment]
@vptcnt and @astrism, I'm going to go ahead and close this issue. If you think it's unresolved, please feel free to open it again and we can talk about what we're lacking.
