### ISSUE TITLE
Demo: Better Error Description

### ISSUE THREAD

**Issue by gizmoboy** [formly-js/angular-formly#102]
I'd like to enhance the demo page with some additional information when the form is invalid.

Right now, if you end up with issues, you'll see something like this"

$error	{"required":[{},{},{},{},{},{},{},{},{}],"mask":[{}]}

I'd like to put more useful information in there, but I can't tell where myFormName.$error is getting populated. I'm guessing it's in the angular guts somewhere, so I'd like to add some logic to flesh it out a bit in the demo app and bind to that fleshed-out presentation as opposed to just the $error object for the form.

If someone could point me in the right direction, I'd be happy to work on this and submit a PR.

**Comment by kentcdodds** [comment]
Closing this issue for now. If you want to take a whack at it, that'd be awesome. Just trying to clean things up a bit.
