### ISSUE TITLE
Validation for Form Schemas

### ISSUE THREAD

**Issue by quietlyconfident** [formly-js/angular-formly#114]
## Definitions

* **Form Schema** *(AKA "Schema")* A JSON document which describes a form (e.g. a Contact Name & Address Form)

* **Form Schema Specification**  *(AKA "Spec")* - A [JSON Schema](http://json-schema.org/) document which can be used to validate a Form Schema.

## Issue
There should be a Spec against which a Schema can be validated.  [angular-schema-form](https://github.com/Textalk/angular-schema-form) creates the form from the schema and also validates the form fields against the same schema.

**Comment by kentcdodds** [comment]
There's the beginnings of a form schema specification [here](https://github.com/formly-js/angular-formly/wiki/JSON-Specification). It's a little difficult to generalize things because different formly components can require such different things, but I think most of the common stuff is there.
