### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#123]
@astrism, could you publish a new version? I've added two things that my project is dependent on. See what they are in the Changelog. One is a breaking change, though it's not seriously breaking. But if we're going to be strict semver (I vote yes) then this will be angular-formly 2.0. I'll leave that up to you. Thanks!

**Comment by eyolas** [comment]
+1

**Comment by kentcdodds** [comment]
Done :-)
