### ISSUE TITLE
Using angular-formly for CRUD

### ISSUE THREAD

**Issue by nolandubeau** [formly-js/angular-formly#125]
Hi,

I'm interested to use this module for a CRUD application as opposed to just a simple form submission.  I can setup the formly JSON to map to the field names for the data that is being retrieved (as JSON) from the database. Could you recommend the best approach to populate angular-formly with the dynamic data?  I was thinking that I would need to do some sort of loop over one of the objects and try to find the matching key in the other object.  Thoughts?  Thank you!

**Comment by kentcdodds** [comment]
Coming back through some issues. Reading this again, I think I misunderstood the question. If you want to pre-populate a form with values, you simply need to set values on the model. The form is a reflection of the current state of the model (aka `result`). So, if I had:

```html
<formly-form result="user" fields="fields"></formly-form>
```

```javascript
$scope.fields = [
  { type: 'text', key: 'firstName' }
];
```

then all I would have to do to pre-populate the form with some default value would be

```javascript
$scope.user = {
  firstName: 'Grant'
};
```

Does this make sense/cover your use case?
