### ISSUE TITLE
Add angular-formly-templates-lumx repo

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#140]
Hi @astrism, 

I recently created [a project](https://github.com/ShMcK/angular-formly-templates-lumx "angular-formly-templates-lumx") combining angular-formly with the LumX Framework. Have a look.

I'm told you might be the guy to talk to about making it an official sub-repo at formly-js/angular-formly-templates-lumx.

**Comment by kentcdodds** [comment]
Hi @ShMcK, you've been invited to be a team member on the formly-js templates team. Could you follow [these instructions](https://help.github.com/articles/transferring-a-repository/) on how to make the transfer? Thanks! :D And welcome aboard :D

**Comment by ShMcK** [comment]
Unfortunately, transferring fails with "You don't have admin rights to formly-js".

Option A is to (temporarily) change group permissions to grant me admin rights for the repo. You can find repo permissions [explained here](https://help.github.com/articles/permission-levels-for-an-organization-repository/).

Option B is to transfer the account to a specific user, in which case: either yourself or astrism.

**Comment by kentcdodds** [comment]
Gave you amin rights. Try again :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
Excellent! It's done!

**Comment by kentcdodds** [comment]
Awesome! Thanks again for your awesome work!
