### ISSUE TITLE
ng-class

### ISSUE THREAD

**Issue by rahil471** [formly-js/angular-formly#142]
Please help me with adding a class , using ng-class in angular-formly.

**Comment by kentcdodds** [comment]
Please be more specific with what you're trying to accomplish. We do [add classes](https://github.com/formly-js/angular-formly#css-classes) to `formly-forms` and `formly-fields`. What do you want to have an `ng-class` on? If you need it on the templates, which template library are you using, bootstrap or vanilla? What version of angular-formly are you using?

**Comment by kentcdodds** [comment]
@rahil471, have you resolved your issue?

**Comment by rahil471** [comment]
Hey Thanks for following up ,  this issue is solved.
I've another issue , I'll start a new thread if required.

I wanted to ask is that , I'm unable to retrieve form name in my controller, is it because of the `<ng-from />` tag , or may be because the library is adding `form` by it self into the name attribute.

For eg: If i name the form as `activateSimForm` , the DOM shows it as `name="activateSimForm form"`

**Comment by kentcdodds** [comment]
Yes, angular-fromly adds the name attribute for you and binds a form attribute for you to alleviate confusion. So, you'd do this instead:

```html
<formly-form form="activateSimForm" model="simModel" fields="simFields"></formly-form>
```

If that doesn't solve your issue, please open a new issue :-)

**Comment by rahil471** [comment]
Hey Thanks man ,
That worked.
I'm enjoying using this.
