### ISSUE TITLE
Is there any way to organize fields of a form in different groups using formly?  

### ISSUE THREAD

**Issue by AlessandroGurgel** [formly-js/angular-formly#143]
I would like know if there is any option or type that can be used to group different fields in a form.
For instance, I will build a form having the fields:
                field_1: time
		field_2: time
		field_3: enum
		field_4: boolean
		group_1:{ 
			field_5: boolean
			field_6: boolean
		}*
and i want to group the elements field_5 and field_6 in a particular panel. 

If there is no built-in support, what is the best way to extend or implement such feature?

**Comment by kentcdodds** [comment]
I would recommend doing something like this:

```html
<form ng-submit="submit()"
  <formly-form model="vm.user" fields="vm.mainFields"></formly-form>
  <div class="sub-panel">
    <formly-form model="vm.user" fields="vm.subFields"></formly-form>
  </div>
  <button type="submit">Submit</button>
</form>
```

and then your controller would look like this (using controller as)

```javascript
var vm = this;

vm.user = {};
vm.mainFields = [ /* your main field config here */ ];
vm.subFields = [ /* your sub field config here */ ];
```

Does that solve your issue?

**Comment by AlessandroGurgel** [comment]
Thanks. Actually, this was what i done :D. It works. thxs!
