### ISSUE TITLE
Multi angular-formly 

### ISSUE THREAD

**Issue by abodacs** [formly-js/angular-formly#146]
How to implement multi forms every form with its submit button?

**Comment by kentcdodds** [comment]
I'm not sure I understand your question. What do you mean?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by abodacs** [comment]
first Thanks for this greet work
i have use case a user can enter new form or edit previous entered forms in same page.
Previous forms loaded as timeline style to edit

**Comment by kentcdodds** [comment]
I'm still not certain what your use case is. So, you want to be able to
create/edit using the same form fields? This is easily done by providing
the right `model`. For "create" just provide an empty model (`{}`), for
"edit" provide the model you're trying to edit.

Kent C. Dodds
<https://twitter.com/kentcdodds>
<https://plus.google.com/114245123507194646768>  <kent@doddsfamily.us>
<http://www.linkedin.com/profile/view?id=67772537>
<http://mormon.org/me/1J5N/Kent>

**Comment by abodacs** [comment]
Thanks @kentcdodds  i use your form for building a survey application something like this https://showroom.typeform.com/to/aCZKbD
I have multi-use cases  ,like multi-select and muti small -form inside one form "ex, person contacts"
and upload-files any suggestions

**Comment by kentcdodds** [comment]
Yeah, you're going to need custom templates for those. For the multi-small-form stuff, I would recommend what we ended up doing in #76 [here](http://jsbin.com/jaloz/edit). For multi-select, you'll have to come up with something on your own, though I know there are several libraries that claim to do this quite easily. For file upload, you'll need to create your own template to do this. I recommend using a directive similar to the `exampleSubform` in the multi-small-form example so you can add a controller to do the actual upload. Good luck!

**Comment by kentcdodds** [comment]
@abodacs, have you resolved your issue?

**Comment by abodacs** [comment]
thanks yes
