### ISSUE TITLE
Support for specifying mask expressions to fields through the integration with angular-ngMask

### ISSUE THREAD

**Issue by AlessandroGurgel** [formly-js/angular-formly#149]
I was wondering why formly does not support the specification of masks (i.e. HH:MM:SS or dd/mm/yyyy) for form fields. 

Actually, I am using the formly last release (1.0.0) and I implemented this feature through the steps

1- includes ng-Mask into the project (bower.json)
"angular-ngMask": "3.0.8"
2- creates a template similar to form-field-text including the attribute mask
<div class="form-group"
     ng-class="{'has-error': options.formField.$invalid}">
	<label for="{{id}}">
		{{options.label || 'Text'}}
		{{options.required ? '*' : ''}}
		{{options.mask}}
	</label>
	<input type="text"
	       class="form-control"
	       id="{{id}}"
	       formly-dynamic-name="options.key"
	       formly-custom-validation="options.validators"
	       placeholder="{{options.placeholder}}"
	       aria-describedby="{{id}}_description"
	       ng-required="options.required"
	       ng-disabled="options.disabled"
	       *mask="23:59:59*"
	       ng-model="result[options.key || index]">
	<p id="{{id}}_description"
	   class="help-block"
	   ng-if="options.description">
		{{options.description}}
	</p>
</div>
3- creates a new type 'time' that points out to the new template
  # set formly tempaltes
  formlyConfigProvider.setTemplateUrl('time', 'templates/custom-formly/form-field-time.html')

A better implementation would be to create a mask attribute to the specification of a field and uses it on the form-fields tempaltes (masks={{options.mask}}). How I could do this?

**Comment by kentcdodds** [comment]
I'm not sure I understand your question... It sounds like you know what to do. You have the right idea that you'll want to create a custom template for this functionality. From there you can do whatever you like. See [the wiki](https://github.com/formly-js/angular-formly/wiki/Tips-&-Tricks#custom-templates) on custom templates for what's available.

**Comment by AlessandroGurgel** [comment]
Ok.
Sorry, I was not clear.  I suggested that this feature (mask) could be implemented to provide native support of formly in future. 
For instance, I could specify a field as {key: 'start', type: 'text', label: 'start', mask: '23:59:59'} which represent as time whose format is HH:MM:SS. It is a suggestion of a nice and easy-to-implement feature. 
thx

**Comment by kentcdodds** [comment]
And what I was saying is that the option "mask" doesn't have to be implemented in formly for you to use it in a custom template. Either way, we're definitely not going to implement it in formly core as it wouldn't make sense. If you would like it added to one of the template libraries, create an issue there and we can discuss it...
