### ISSUE TITLE
Ckeck list possibility

### ISSUE THREAD

**Issue by maryampashmi** [formly-js/angular-formly#151]
I need to use check list in my survey which when i select then will open another hidden input to the user. I couldn't find anythings related to check list.I could find only check box. Please let me if there is any way to do that?

This is an example of what i want to do:

```js
{
    "key": "Q2",
    "type": "checkbox",
    "label": "What are the most important language to learn?",
    "options": [
      {
        "name": "english",
        "value": "eng"
      },
      {
        "name": "spanish",
        "value": "spnsh"
      },
      {
        "name": "french",
        "value": "frnch"
      },
      {
        "name": "more",
        "value": "more",
        "key": "checkThis"
      },
      {
        "key": "hiddenWhenUnchecked",
        "type": "text",
        "line": 4,
        "label": "Please write down if you consider another languages",
        "placeholder": "chinese",
        "expressionProperties": {
          "hide": "!model.checkThis"
        }
      }
    ]
  },
```

Thank you.

**Comment by kentcdodds** [comment]
So, just to confirm, you want the user to be able to check multiple of those right? Or are they limited to only one? If they're limited to one, then just use the radio button. If you just want to have one field label associated with multiple checkboxes (each with their own label) then you'll have to make your own template. I would recommend copying the radio button template and changing it to a checkbox. Like so:

```html
<div class="radio-group"
     ng-class="{'has-error': options.formControl.$invalid}">
	<label class="control-label">
		{{options.label}}
		{{options.required ? '*' : ''}}
	</label>
	<div class="radio"
	     ng-repeat="(key, option) in options.options">
		<label>
			<input type="checkbox"
			       formly-dynamic-name="id"
			       formly-custom-validation="options.validators"
			       id="{{id + '_'+ $index}}"
			       aria-describedby="{{id}}_description"
			       ng-value="option.value"
			       ng-required="options.required"
			       ng-model="$parent.model[$parent.options.key || $parent.index]">
			{{option.name}}
		</label>
		<p id="{{id}}_description"
		   class="help-block"
		   ng-if="option.description">
			{{option.description}}
		</p>
	</div>
</div>
```

**Comment by maryampashmi** [comment]
In above example which i put yesterday. I did exactly what you wrote. I mean i change radio with check box. but moreover  i need to an extra option when user choose the last check box then should open another hidden text box where ask him to input his / her preferences. It means one hidden text box inside check list . so first i would like you inform that if my above json file is correct or not? then if it is correct what is the next step? because with this json file i didn't get any answer and my survey is seems so messy.

**Comment by maryampashmi** [comment]
there is still my missing part remains which i couldn't solved that.please look at this json file:
{
    "key": "Q2",
    "type": "checkbox-template",
    "label": "What are the most important language to learn?",
    "options": [
      {
        "name": "english",
        "value": "eng"
      },
      {
        "name": "spanish",
        "value": "spnsh"
      },
      {
        "name": "french",
        "value": "frnch"
      },
      {
        "name": "more",
        "value": "more",
        "key": "checkThis"
      },
      {
        "key": "hiddenWhenUnchecked",
        "type": "text",
        "line": 4,
        "label": "Please write down if you consider another languages",
        "placeholder": "chinese",
        "expressionProperties": {
          "hide": "!model.checkThis"
        }
      }
    ]
  },

There is still one hidden text box which when i check last option should appear which is not working at all.Please if somebody knows solution let me to know. 
Thank you.

**Comment by kentcdodds** [comment]
@maryampashmi, it's because you have the `hiddenWhenUnchecked` field as part of the `options` of the `checkbox-template` field. Also, unless your template is doing something interesting/odd, `options` shouldn't have a `key`. Your `hide` `expressionProperty` should reference `Q2` being the value of the `more` option. Try this:

```json
{
    "key": "Q2",
    "type": "checkbox-template",
    "label": "What are the most important language to learn?",
    "options": [
      {
        "name": "english",
        "value": "eng"
      },
      {
        "name": "spanish",
        "value": "spnsh"
      },
      {
        "name": "french",
        "value": "frnch"
      },
      {
        "name": "more",
        "value": "more"
      }
    ]
  },
  {
    "key": "hiddenWhenUnchecked",
    "type": "text",
    "line": 4,
    "label": "Please write down if you consider another languages",
    "placeholder": "chinese",
    "expressionProperties": {
      "hide": "model.Q2 !== 'more'"
    }
  }
```

If that doesn't work, please provide an example using [this jsbin](http://jsbin.com/biqesi/edit) as a template.

**Comment by kentcdodds** [comment]
@maryampashmi, did this resolve your issue? Please close this issue if so.

**Comment by maryampashmi** [comment]
thank you for your help. It was great and helpful. I only have a suggestion if you provide video tutorial so  it is more easier to learn about building templates especially for beginners.
Thank you.

**Comment by kentcdodds** [comment]
Good point. I'm actually in the process of creating a series on egghead.io for angular-formly. Stay tuned! :D

**Comment by maryampashmi** [comment]
This is  good link ... seems useful to me. ...  :)
