### ISSUE TITLE
Using ng-pattern, with custom templates.

### ISSUE THREAD

**Issue by rahil471** [formly-js/angular-formly#152]
Hi, 
Is it possible to use ng-pattern ?
I'm using custom templates , where I assign the value `"options.pattern"` , this works , but the problem is that i don't need pattern for all fields, and hence angular throws me an error as ng-pattern is `""`.

Is there a way to over come this issue ?

**Comment by kentcdodds** [comment]
What you're experiencing is why the pre-built templates don't support ng-pattern already. You have a few options. You can either:

1. Create a custom template that uses ng-pattern (called `pattern-input` for example) and just use it when you need to supply a pattern
2. Use a `validator` instead (I recommend this) where you validate it based on regex.

Good luck

**Comment by kentcdodds** [comment]
@rahil471, did this resolve your issue? Please close this issue if so.

**Comment by kentcdodds** [comment]
Closing this. Let me know if your issue was unresolved.
