### ISSUE TITLE
bower versionn 1.0.0

### ISSUE THREAD

**Issue by brusand** [formly-js/angular-formly#153]
Hi Kent,

i see an issue in the bower version 1.0.0, when i see bower.json, it is still 0.0.16 (and generate an error in my formly form. However, if i import the library from rawgit.com/formly-js/angular-formly/master/dist/formly.js and rawgit.com/formly-js/angular-formly-templates-vanilla/master/dist/angular-formly-templates-vanilla.js

my code work fine .
Bruno
.

**Comment by kentcdodds** [comment]
Whoops, can't believe we didn't see that earlier. I'm not certain that it's worth fixing at this point. I'll be releasing 2.0.0 in the next week or two anyway. Also, `master` and `1.0.0` have some significant differences. So if you're trying to compare your code with the two, you're going to have a hard time.
