### ISSUE TITLE
Support for nested keys?

### ISSUE THREAD

**Issue by luisfarzati** [formly-js/angular-formly#154]
I'm not sure as I haven't yet tried, but by the looks of https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L54 it seems you expect a simple key for the field, right?

To give a concrete example: if I want my model to have a 

```
{
    "name": {
        "last": "...",
        "first": "...",
        "middle": "..."
    }
}
```

is there a way I can define the key value as "name.last", "name.first", etc...?

I guess it's faster to just go and try, but I'm not sure when I'll be trying this so in the meantime I just ask you :)

Anyway, thanks for this cool module! I'm sure I'll be using it soon.

**Comment by kentcdodds** [comment]
Good question... Unfortunately, this is not currently possible, though I wanted it to be #132.

However! I closed #132 because there's a reasonable workaround. From the #132:

---------

This can be accomplished by specifying a model for the field like so:

```js
$scope.foobar = {
  foo: {
    bar: 'hello'
  }
};
$scope.fields = [{
  model: $scope.foobar.foo,
  key: 'bar'
}];
```

```html
<formly-form result="foobar" fields="fields" />
```

This is supported as of 9f10f57

---------

Hopefully that's a reasonable workaround for you!

If you want to take a whack at a PR to support `'name.first'` that would be way awesome because I think it's a much better api. However, there are some issues with using getter/setters with ng-model-options (which I mention in [my egghead lesson](https://egghead.io/lessons/angularjs-new-in-angular-1-3-ng-model-options-getters-and-setters) on it).

**Comment by kentcdodds** [comment]
One thing that we may consider is simply syncing an internal value with an external value using $watch... This would avoid the use of a getter/setter... But that may not be the right approach...

P.S. Thanks for angulartics! :D

**Comment by luisfarzati** [comment]
Thanks for the prompt response! I think it's a nice workaround, let me close this for now. I'll try it out the way you said and see if maybe I can come up with a better support. 

Glad you like angulartics, and thanks for contributing! :)

**Comment by TheAcadianYeti** [comment]
Hi there,
I'm just wondering if I could employ this in a situation where I'm using the multi-input portion of formly as well.  This is a portion of what I have, using some other portions as well.  The issue I am having is that the key within the field group isn't being associated with the model of the controller.  Anyway thanks for the input regardless.
`key: 'claim',
                type: 'multiInput',
                templateOptions: {
                    label: 'Claims',
                    inputOptions: {    
                        className: 'row',
                        fieldGroup:
                        [
                            {
                                className: 'col-md-2',
                                type: 'datepicker',
                                //key: 'claimDate',
                                templateOptions : {
                                    label: 'Claim Date',
                                    placeholder: 'Enter date',
                                    type: 'text'
                                }
                            },
                        ]
                    }`

**Comment by evenicoulddoit** [comment]
And if the model isn't exposed within the same scope, you can use `expressionProperties`:

```js
let fields = [
  {
    expressionProperties: {
      model: 'model.nested'
    },
    key: 'field'
  }
];

// binds to model.nested.field
```
