### ISSUE TITLE
1.0 -> 2.0 Changes?

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#155]
I recently noticed that the Lumx templates weren’t binding with Angular-Formly 2.0, though working fine on 1.0.  Are there breaking changes with 2.0 to update to or are 'things just blowing up but it’s going to be awesome'? Looking forward to progress.

**Comment by kentcdodds** [comment]
There were big breaking changes from 1.0 to 2.0. But what's in matter
should be compatible with 2.0. See the changelog. :-D

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Also, if you've seen [the new site](https://formly-js.github.io/angular-formly), we're using jsbin to do examples now. Would love to see some LumX examples on there :-) https://github.com/formly-js/angular-formly/edit/master/demo/app/states/root/components/data/examples.js

**Comment by ShMcK** [comment]
I have some time this week, I'll see what I can do.

**Comment by kentcdodds** [comment]
Thanks. Maybe you can provide me with some feedback.

I've been thinking about making a change to the field config api to make things more clear what is for templates and what is for formly core. So changing the api to be this:

```javascript
{
  type: 'text', // or template/templateUrl
  key: 'first',
  wrapper: 'someWrapper', // new api in master, you'll love this one. You may actually want to build your templates with this and wait for me to release this officially. Should be in the next few days. Also, the api is not finished because I'm planning on being able to specify an array where the first wrapper would be wrapped in the second wrapper and so on :-D
  model: vm.user.name,
  expressionProperties: {},
  data: {}, // reserved for users
  modelOptions: {}, // currently created in formly core, but I'm thinking that we should pull it out and let this be part of the template
  watcher: {},
  validators: {}, // this is technically used only in the template using the formly-custom-validation directive. So perhaps it should go in the templateOptions? But I think that all templates that use ng-model should support validators so it may be better just to keep it here.
  templateOptions: { // and here's the change. All template-specific options would be moved to here
    label: 'First Name',
    placeholder: 'Please be honest',
    required: true,
    options: [],
    description: 'Enter your first name so we can know what it is',
    // etc...
  }
}
```

What do you think? I've presented on formly, and the biggest confusion for people was figuring out what was part of the formly core and what was necessary/supported by the template library. I think this api makes it much more clear. I'm anxious to get your feedback so I can make this change if you think it would be useful. We could then cut a 3.0.0 release. And don't worry, it wont drag on like the 2.0.0 :-) I'm speaking on formly at [ng-nl](http://ng-nl.org) next week, so I'll want to cut a new release before then.

So, anyway, I really like this new api. I think it's more clear. Let me know what you think :-)

**Comment by ShMcK** [comment]
Exciting stuff!

I second `type` changing to `template`/`templateUrl`. I found it quite confusing when building `input` templates that use the same attribute name.

Looking forward to the `wrapper`. Actually, I had issues in my current project where it was simpler to avoid using Formly in order to render the inputs on the page properly. I imagine the `wrapper` could even be used to create in-line styled forms, or even drop-down menus. I assume this will grant the ability to finally organize fields on the page by wrapping them in boxes with custom css classes. Great!

`modelOptions` & `validators` is a tough call. Personally, I used both of them in the LumX templates with ng-Messages, but I wouldn't necessarily classify them as `templateOptions`. 

I wish I could give you better feedback, but I appreciate the opportunity and the heads up. I'll get prepared with e2e tests for the 3.0.0 drop to catch up to speed. Good luck with the talk next week!

**Comment by kentcdodds** [comment]
Actually @ShMcK, I still want to keep `type`. I was just saying that you can still specify a `type` OR a `template` OR a `templateUrl`. With this new paradigm, you would have a `templateOptions.type` to specify a different type for the `input` template type.

I'm working on documenting the `wrapper` api a little better. It's pretty cool. You can have wrappers in wrappers, which should make ng-messages and labels really handy! It's mostly tested and I'm going to have an example on the site for it as well so you should be able to figure out how to leverage it fairly easily.

I'm going to leave `modelOptions` and `validators` where they are. I think it makes sense to keep them there.

But be aware that I am going to move all template configuration to `templateOptions` and I'm going to throw an error if anyone specifies a property that does not belong in the main configuration. Users will have free reign over both the `data` and `templateOptions` objects, but the rest of the field api will be limited to what is explicitly allowed.

Thanks for working with me on this as I try to make this the best forms abstraction for angular :-)

**Comment by kentcdodds** [comment]
Note, I'm also changing `setTemplate` and `setTemplateUrl` to simply `setType`. Keep an eye on the README for that simpler api.

**Comment by kentcdodds** [comment]
I've been having a lot of fun this evening making a bunch of changes. Most of them will simply require you to change from `options` to `options.templateOptions`. Also, there are several other nice updates as well (including wrapped wrappers). I recommend taking a look at how I altered the other template libraries (like [bootstrap](https://github.com/formly-js/angular-formly-templates-bootstrap) to see what changes you'll need to make. Also check out [the changelog](https://github.com/formly-js/angular-formly/blob/master/CHANGELOG.md).

**Comment by kentcdodds** [comment]
Also, be advised that I've released a beta version of this to npm. You can `npm install angular-formly@3.0.0` to see it.

**Comment by ShMcK** [comment]
Awesome, I'll try to have it all up-to-date by the end of the week.

**Comment by kentcdodds** [comment]
Terrific! I want to wait until your library is up to date before releasing the next version to make sure that you're able to go through and double check the api. I want you to let me know if I was just being crazy or something :-)

**Comment by ShMcK** [comment]
Then I better get on that right away! 

I was working on making a simple grunt/gulp tool to compile formly templates to make future updates smoother, but I think I'll just stick to using ng-templates + copy/paste. Ran into a frustrating lack of know-how. If you have an existing solution, let me know!

**Comment by ShMcK** [comment]
Already loving the wrappers. 

But I'm a little confused about the API. So `templateOptions` refers to template specific parameters. That's clearly needed. At first I thought `required` belonged outside of `templateOptions`, but now I realize it's in the right place. 

However, I don't understand why `options: []` is under templateOptions. Is it not the basic data options i.e. for radio buttons?

**Comment by ShMcK** [comment]
As a suggestion, perhaps `options.templateOptions.someName` could be shortened to `templateOptions.someName` (with some difficulty) or `options.template.someName`?

**Comment by ShMcK** [comment]
Another crazier suggestion, as it's getting late on this side of the world:

A lot of `templateOptions` can be linked to core angular directives: `ng-required`, `ng-disabled`, `ng-checked`, etc. Perhaps these could be differentiated if deemed necessary? On second thought, maybe not.

**Comment by ShMcK** [comment]
Typo in CHANGELOG 3.0.0 (Unpublished)
`mode[options.key]` - > model

**Comment by kentcdodds** [comment]
Hi @ShMcK, I'm actually in Sweden right now, but still suffering from jetlag. So sorry I wasn't available earlier. Here are a few things:

 - Hopefully the wrappers will be sufficient to help you avoid repeating yourself
 - `options: []` for radio buttons are specific to radio buttons and are not needed at all by formly core. That's the basic premise of everything. If it's not common to all templates (ie, used by formly core) then it belongs in either `templateOptions` or in `data` (though `data` is more reserved for users, not template writers).
 - I thought about using `template` instead of the more verbose `templateOptions`. However, `template` is already in use because you can specify a `template` instead of a `type` or `templateUrl`
 - I'm thinking that perhaps it may be nice to have somehow a way that formly would attach the `ng-required`, `ng-disabled`, etc. directives based on the `templateOptions` automatically for you. But that would require a recompilation of the template which would likely lead to a performance issue. And I believe that formly actually already has poor performance sometimes so I'd like to avoid making it worse. But I think I would like to explore this possibility as it would make the templates MUCH easier to write.

Thanks for your work on this! Please let me know if there's anything you'd like me to do. I think I'll look into that last point. If there's a way I can do this without hurting performance, I think I will because that would be great!

**Comment by ShMcK** [comment]
I see what you mean now about `options: []` & `templateOptions` and I'm happy with that part of the API.

**Comment by kentcdodds** [comment]
Excellent! :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
I fixed up the angular-formly-templates-lumx. There's a demo [here](https://formly-lumx.herokuapp.com/text).

I haven't been able to get any `select`ers to work with 3.0.0, any thoughts? I'll try again later.

**Comment by kentcdodds** [comment]
A couple thoughts:

 - On the fm.formFields preview on the right, I would actually make a copy of the fields in your controller and display those. Formly attaches several things to the fields that are not entirely necessary showing (like model options or the form control)
 - Speaking of the form control, if you open your console, you'll notice some warnings complete with links to explanations. Look into those :-)

It could be that last one is related to the `select` components not working, but I'm not certain about that...

**Comment by kentcdodds** [comment]
Just playing around with one of those selects, it appeared that it may have just been a css issue. I found the parent element of the dropdown and the opacity was set to 0. I changed it to 1 and everything started working...

**Comment by ShMcK** [comment]
99% working. Thanks for the help!
