### ISSUE TITLE
Add examples to the demo!

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#156]
So the demo has been updated to allow examples to be created in jsbin. Makes things a little easier to deal with by having them split out and consumers are free to play around with the example. However, we need more (there is currently only one). If you've used formly and would like to contribute an example of something you've done, please follow the instructions in [this file](https://github.com/formly-js/angular-formly/edit/master/demo/app/states/root/components/data/examples.js)

**Comment by abodacs** [comment]
examples doesn't work @kentcdodds in demo

**Comment by kentcdodds** [comment]
@abodacs, could you be more specific? They seem to be working for me...

**Comment by abodacs** [comment]
https://formly-js.github.io/angular-formly/#/example/intro/introduction
when https doesn't work

**Comment by kentcdodds** [comment]
Well, I fixed it as much as I could, but

**Comment by kentcdodds** [comment]
For now, you can click "load unsafe scripts" and that'll make things work for mixed https and http.

![screen shot 2015-02-01 at 10 01 10 pm](https://cloud.githubusercontent.com/assets/1500684/5993853/e5b05378-aa5d-11e4-9a63-4613ca2254f8.png)

**Comment by abodacs** [comment]
ok thanks

**Comment by kentcdodds** [comment]
@abodacs, so the "solution" is to force non-ssl because the jsbin examples will come from the community and I can't force people to upgrade to jsbin pro (which is how you enable ssl for jsbin) so now if you come to the page with https, it will downgrade you to http... :-(

**Comment by abodacs** [comment]
ok @kentcdodds  you can close it

**Comment by kentcdodds** [comment]
@abodacs, I would, except the original issue is still valid. I still want more examples on the site :D Feel free to submit a PR if you have time to create a specific example! :D
