### ISSUE TITLE
Better error when model is not defined

### ISSUE THREAD

**Issue by JamyDev** [formly-js/angular-formly#157]
Hi!

TLDR: Still using the 1.0.0 result="data" instead of the new model="data" should throw a better error.

I was migrating from 1.0.0 to 2.0.0 and all of a sudden this error popped up, I couldn't type in the fields anymore either.

```
Error: [$compile:nonassign] Expression 'field.model || model' used with directive 'formlyField' is non-assignable!
http://errors.angularjs.org/1.2.28/$compile/nonassign?p0=field.model%20%7C%7C%20model&p1=formlyField
    at VALIDITY_STATE_PROPERTY (angular.js:80)
    at $get.parentSet (angular.js:6662)
    at Object.parentValueWatch (angular.js:6676)
    at Scope.$get.Scope.$digest (angular.js:12644)
    at Scope.$get.Scope.$apply (angular.js:12917)
    at HTMLInputElement.listener (angular.js:17177)
    at HTMLInputElement.m.event.dispatch (jquery.min.js:3)
    at HTMLInputElement.m.event.add.r.handle (jquery.min.js:3)
```

Now I already found out that this is due to my form still using result="data" instead of the new model="data" but the error didn't really make that apparent.

I suggest you add in a check and throw an appropriate error message, as I'm probably not the only one who is going to have this error after migrating.

With kind regards
Jamy

**Comment by kentcdodds** [comment]
Thanks for the tip @JamyDev. I think that's a good idea. I'll try to get it in soon.

**Comment by kentcdodds** [comment]
This is now supported: e29ad3dc37e46b9dbab7b05a77185b6396684e63

Note: This is a breaking change and will result in a 3.0.0 release. I hope this release comes soon. Also note, with this 3.0.0 release comes `templateWrappers` which you're going to love if you use many custom templates :-)

**Comment by kentcdodds** [comment]
To be more clear, it's going to be shipped with other breaking changes. I think the simple errors thrown wouldn't be a problem necessarily since you couldn't do this in 2.0 anyway, but I've got a bunch of other things that are definitely breaking changes that this will ship with. Should be a much easier migration from 2.0 to 3.0 than it was from 1.0 to 2.0.
