### ISSUE TITLE
Formly with advanced select ?

### ISSUE THREAD

**Issue by piernik** [formly-js/angular-formly#158]
Can I use formly with advanced selects like https://github.com/angular-ui/ui-select or https://github.com/lordfriend/nya-bootstrap-select ?
I mean keeping all options like ajax, multiple and so on?

**Comment by kentcdodds** [comment]
Absolutely. You simply need to [create a custom template](http://formly-js.github.io/angular-formly/#/example/intro/custom-templates) and use those directives in your custom template. I'm actually doing this currently with ui-select.

```html
<div class="input-group col-md-12">
  <div class="form-control"
       type="text"
       name="{{::id}}"
       ng-attr-placeholder="{{options.placeholder}}"
       ng-required="options.required"
       formly-custom-validation="options.validators"
       az-autofocus="{{options.focus}}"
       ui-select2="options.data.select2Options"
       ng-model="model[options.key || index]"
       az-ui-select2-disabled="options.disabled"></div>
</div>
```

There are likely a few things in there that you'd need to change from my example, but the concept is fairly straightforward :-) Good luck!

**Comment by kentcdodds** [comment]
Also, if you do get this implemented, I would love to have an example on [the website](https://formly-js.github.io/angular-formly/). Create an example by following the instructions [here](https://github.com/formly-js/angular-formly/edit/master/demo/app/states/root/components/data/examples.js)

**Comment by kentcdodds** [comment]
@piernik, do we need to keep this issue open?

**Comment by piernik** [comment]
no thanks
