### ISSUE TITLE
Wrapper Options ?

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#161]
Would it be possible to provide options for a `wrapper`?

A use-case would be when creating a form grid, passing in the column size. For example: `class="col{{wrapper.options.colSize}}"`. Another use case may be setting inline display, i.e. `style="display: {{wrapper.options.display || 'block'}};"`

The current strength of Angular-Formly (quick, easy forms) is also it's weakness (one size, block display). I hope to take advantage of greater flexibility with 3.0.0.

**Comment by kentcdodds** [comment]
I've got an idea. What if we gave you something like this:

```javascript
formlyConfigProvider.templateManipulators.preWrapper.push(function(template, fieldOptions, scope) {
  // do whatever you want to here and return the template. You can even return a promise
  // this will be called before all of the wrappers have have run
});
```

```javascript
formlyConfigProvider.templateManipulators.postWrapper.push(function(template, fieldOptions, scope) {
  // this will be called after all of the wrappers have have run
});
```

What do you think about that? I think I sort of like that. Would allow you to add classes or styles or even wrap it further. AND it would allow you to add all the `ng-` directives we were talking about automagically :-)

**Comment by ShMcK** [comment]
The pre/post wrapper can have definite uses. I'll put some thought into it.

However, what about changes in context? These should be handled in the JSON for easier usability rather than at the provider level.

I quickly googled "grid form" for an [example](http://kumailht.com/gridforms/media/images/form-zoomed-out.png). Formly + any css framework should be able to create complex form grids. 

I was thinking adding an optional `wrapperOptions` to the api could handle all of this. It would perform in essentially the same way as `templateOptions`.

**Comment by ShMcK** [comment]
I just realized `formlyConfigProvider.setWrapper({})` forces all of the wrappers on the template. As a result I was getting 3 sets of ngMessages on my text-fields, one for each wrapper. I'm not sure the usefulness of `setWrapper` other than saving a little template code.

**Comment by kentcdodds** [comment]
Saving template code is the main usefulness. But you need to make sure that
you're specifying the right types on the wrapper when it's defined or
specifying the right wrappers when the type is defined. That may be a bit
confusing....

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
I see now that `wrapperOptions` are not needed.  `templateOptions` can already fill them out. Excellent! Issue closed for me.

**Comment by kentcdodds** [comment]
So, this is amazing. I am seriously considering removing `wrapperOptions` in favor of the new `templateManipulators` pipeline (and therefore only have one pipeline and no longer have a need for the pre and post wrapper ones). Let me know what you think: https://github.com/formly-js/angular-formly#templatemanipulators

I just want to verify with you that it covers all use cases you can think of. If so, I'm going to go through and fix the bootstrap and vanilla templates to support this. Also, formly core has a built-in `templateManipulator` that you may find interesting. It's the reason that `ngModelAttrs` was introduced: https://github.com/formly-js/angular-formly#ngmodelattrs-object
See an example of that in code [here](https://github.com/formly-js/angular-formly/blob/d55483204cb41d7196565730517d7cf72f89fbbf/local-examples/components/app.js#L35)

Let me know what you think. I'm planning on removing wrappers on the 6th (tomorrow depending on your timezone) because it's such a cleaner, more reasonable api I think.

**Comment by ShMcK** [comment]
I posted up some examples with docs on the [templates-lumx](https://formly-lumx.herokuapp.com) site, have a look and tell me what you think. So far, I'm loving the flexibility `wrappers` bring. Thanks!

**Comment by ShMcK** [comment]
One of the new features is using `flexbox` with form fields. :)

**Comment by ShMcK** [comment]
Sorry, I just checked my email and found I had completely missed that previous message! FYI - I'm in the South Korea time zone (UTC+09:00).

So far, I think one pipeline is fine. I'll look into the template manipulator ASAP.

**Comment by ShMcK** [comment]
I hadn't realized the power of `ngModelAttrs`. They can drastically reduce the bloat on form fields.

I think the docs could use an example. I'm not entirely sure how to use them. 

Are they set by an `ngModelAttrs` array that can hold multiple `ng`-directives with values? 

```
    ngModelAttrs = ['ng-required': true, 'ng-pattern': '/[A-Za-z]/', 'ng-disabled': false]
```

Or can they only be set and changed in `expressionProperties`?

```
expressionProperties: {
    options.ngModelAttrs[ng-required] = true,
    options.ngModelAttrs[ng-pattern] = /[A-Za-z]/
    options.ngModelAttrs[ng-disabled] = false
    }
```

**Comment by kentcdodds** [comment]
Yeah, they're way way awesome :-D Not only will it Dave boat in templates,
but it saves a ton on unnecessary watchers. Look in the local-examples
directory, in components/app.js

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
/Dave/save/s

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
I'm trying to setup `flex-box` with `angular-formly-templates-lumx`. Unfortunately, I haven't been able to get it to work based on [this `jsbin` example](http://jsbin.com/jaloz/2/edit?html,js,output).

    Error: `Formly Error: You have specified field properties that are not allowed: "fields"`.

# Questions
1. How could I add a custom field `fields: []` to my template?
2. Is it possible to define and add other custom fields? Hmm...

***

# Current Proposed API

### lx-wrapper-flex-container API
```javascript
{
  'key': 'modelName',
/* type or wrapper? type is required by formly */
  'type': 'lx-wrapper-flex-container', 
  'templateOptions': {
    'container': 'row', // row | column | row-reverse | column-reverse
    'wrap': 'nowrap', // nowrap | wrap | wrap-reverse
    'align': 'space-between', // flex-start | flex-end | center | space-between | space-around | stretch
    'class': 'bgc-red-500', // ng-class
    'style': 'height: 200px'
  },
/* as in the jsbin example. */
  'fields': [{
    /* 'lx-wrapper-flex-item' fields here */
  }]
}
```

### lx-wrapper-flex-item API
```javascript
{
  'key': 'modelName',
  'type': 'lx-whatever-type'
  'wrapper': 'lx-wrapper-flex-item', // <- add the wrapper
  'templateOptions': {
    'flex': {
      'item': '1' // flex-value number, higher weights the space ratio more 
      'order': '1', // value for ordering boxes
      'class': 'bgc-red-500' // ng-class
    }
  }
}
```

**Comment by kentcdodds** [comment]
The fields need to be part of the templateOptions object :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
I would recommend changing the "class" property with "className" so I don't
have to put it in quotes if I don't want to.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
My brain just went *click*! 

Gotcha, I'll just create an `ng-repeat` inside to handle the inner `flex-item`'s. Easy peezy.

**Comment by kentcdodds** [comment]
Woot! :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
`<formly-form>` inside a `<formly-form>`. Good idea, bad idea?
```html
<!-- lx-wrapper-flex-container -->

<div ng-class="::options.templateOptions.flexContainer.className"
     style="::options.templateOptions.flexContainer.style"
     flex-container="{{::options.templateOptions.flexContainer.container}}"
     flex-align="{{::options.templateOptions.flexContainer.align}}"
     flex-gutter="{{::options.templateOptions.flexContainer.gutter}}">

	<formly-form model="vm.formData" fields="options.templateOptions.fields"
	             ng-class="::field.flex.className"
	             flex-item="{{::field.flex.item || 1}}"
	             flex-order="{{::field.flex.order || 1}}">
</div>
```

**Comment by ShMcK** [comment]
Binding the inner form to `model[options.key].fields` may mess up the form data. But should work.

**Comment by kentcdodds** [comment]
Oh yeah, I was going to mention that. After looking at it, I think you definitely need to do this because it adds a few things to your fields that are necessary (including the key if one is not specified, and it adds the watchers). Without the formly-form, you'll miss out on a few things that I think are important.

**Comment by kentcdodds** [comment]
I'm not sure I know what you mean by binding to `model[options.key].fields`.... The fields should not be on the `model` at all. I think what you really want is what you have above: `fields="options.templateOptions.fields"`

**Comment by ShMcK** [comment]
I'm a bit worried about your sleep cycle! Take your time.

`Error: Couldn't set the formControl`

Any thoughts? Keep in mind this is a `form` within a `form`...

I think it has something to do with the inner `form`'s model.

```html
<!-- outer form field -->
 <formly-form model="vm.formData" fields="vm.formFields"></formly-form>
```

```html
<!-- inner form field -->
<!-- lx-flex -->
<div id="{{::id_container}}"
     ng-class="::options.templateOptions.flex.className"
     style="::options.templateOptions.flexContainer.style"
     flex-container="{{::options.templateOptions.flex.container}}"
     flex-align="{{::options.templateOptions.flex.align}}"
     flex-gutter="{{::options.templateOptions.flex.gutter}}">

	<formly-form fields="options.templateOptions.fields"
	             model="::$parent.model">
</div>
```

```javascript
/* vm.formFields */
[
  {
    "key": "row",
    "type": "lx-flex",
    "templateOptions": {
      "flex": {
        "container": "row",
        "align": "space-between"
      },
      "fields": [
        {
          "key": "rowItem1",
          "type": "lx-text",
          "wrapper": "lx-wrapper-flex-item",
          "templateOptions": {
            "flex": {},
            "type": "text",
            "fixedLabel": true,
            "label": "Item 1"
          }
        },
        {
          "key": "rowItem2",
          "type": "lx-text",
          "wrapper": "lx-wrapper-flex-item",
          "templateOptions": {
            "flex": {},
            "type": "text",
            "fixedLabel": true,
            "label": "Item 2"
          }
        },
        {
          "key": "rowItem3",
          "type": "lx-text",
          "wrapper": "lx-wrapper-flex-item",
          "templateOptions": {
            "flex": {},
            "type": "text",
            "fixedLabel": true,
            "label": "Item 3"
          }
        }
      ]
    }
  }
]
```

**Comment by kentcdodds** [comment]
Is there not a link with that error? There should be a url link to a wiki that explains why you're getting that error and how to fix it. I'm guessing this is the error you're seeing: https://github.com/formly-js/angular-formly/wiki/Errors-and-Warnings#couldnt-set-the-formcontrol-after-timems

**Comment by kentcdodds** [comment]
Basically, if that error is what I believe it is, you need to make sure that all of your `ng-model` attributes specify a `name` attribute or that the field config specifies `noFormControl: true`

**Comment by kentcdodds** [comment]
And yes, I need to get some sleep :sleepy:

**Comment by ShMcK** [comment]
That's the one. I'll take a look at it again tomorrow. Also time for a break. Take care of yourself!

Again, I appreciate the help.

**Comment by kentcdodds** [comment]
Yep! I appreciate you're help. We're building something awesome :D

**Comment by kentcdodds** [comment]
@ShMcK you'll want to look at this commit: b02d0a652d956895e092125321196c0aca7969ab see the changes to tests, docs, and examples :-D You could also benefit from looking at these changes in templates bootstrap: https://github.com/formly-js/angular-formly-templates-bootstrap/commit/1e7d12876318f9dd4406c6ade77de2f61019102b Your life should be much easier now!
