### ISSUE TITLE
ngModelAttrs

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#163]
Based on this example from `angular-formly/local-examples/components/app.js`:

```
{
        type: 'input',
        key: 'myKey',
        ngModelAttrs: {
          bound: {
            'ng-maxlength': 6,
            'ng-disabled': false
          },
          unbound: {
            pattern: '"^abcd|^qrst"'
          }
        },
        templateOptions: {
          label: 'My Input',
          required: true,
          description: 'This is an awesome description'
        },
        expressionProperties: {
          'ngModelAttrs.bound["ng-disabled"]': 'model.mine'
        }
      }
```

I can't get `ngModelAttrs` to work with `angular-formly-templates-lumx`. Using `angular-formly@3.0.0` from `npm`.
```
{
        key: 'switch1',
        type: 'lx-switch',
        ngModelAttrs: {
         bound: {
          'ng-checked': true
           }
        },
        templateOptions: {
          label: 'Switched Switch'
        }
      }
```
The `lx-switch` template looks like this:
```
<div class="switch">
  <input type="checkbox"
         id="{{::id + '_'+ $index}}"
         class="switch__input"
         ng-model="model[options.key]"
         formly-dynamic-name="::id"
         aria-describedby="{{::id}}_switch"/>
</div>
```
Any thoughts why?

**Comment by kentcdodds** [comment]
Sorry, I haven't published that yet. Just do this:

npm install git://
github.com/formly-js/angular-formly#84ba8248efa4fe54ac3d078e37cbf9959acc1bd3



-Kent C. Dodds

**Comment by ShMcK** [comment]
Working. It's a beautiful thing. Thanks!

**Comment by kentcdodds** [comment]
Great! Do you think we can remove template wrappers?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Again, if you're going to use `::` in your templates, then that means you're running angular 1.3, and if you're doing that, then you don't need the `formly-dynamic-name`, simply do: `name="{{::id}}"`. Should be more performant I think.

**Comment by ShMcK** [comment]
Thanks! Once I get a full understanding of `angular-formly`, I'll start contributing the jsbin docs as well.

**Comment by kentcdodds** [comment]
Great!

What do you think about removing wrappers?

-Kent C. Dodds

**Comment by ShMcK** [comment]
I think `wrappers` have a lot of great benefits. They don't necessarily need their own `formlyConfig.setWrapper` when `formlyConfig.setType` basically does the same thing. 

But I am a big fan of the functionality of `wrappers`.

**Comment by kentcdodds** [comment]
Could you jump on [Gitter](https://gitter.im/formly-js/angular-formly) really quick?

**Comment by kentcdodds** [comment]
Do we need to keep this open?
