### ISSUE TITLE
Example of custom controller for a field

### ISSUE THREAD

**Issue by gboersma** [formly-js/angular-formly#171]
Can someone give me an example of how to specify a custom controller for a field, and how to access the scope from a wrapper / template for the field? The examples, and the templates projects, don't really help.

**Comment by kentcdodds** [comment]
I'm not sure what you need more than [this example](http://formly-js.github.io/angular-formly/#/example/advanced/template-wrappers) for the template wrappers. I just added a [new example](http://formly-js.github.io/angular-formly/#/example/advanced/custom-controller-and-link) for custom controller and link functions. Let me know if there's anything else I can help you with!

**Comment by gboersma** [comment]
I think the custom controller and link example is what I am looking for. But it is still not clear to me how I can declare my own controller somewhere, and then pass it in (as opposed to declaring methods directly within the setType call). So let's say I declare a module called 'forms' and set the templates there. Can I define a controller for this module and then pass it in when a call setType? Or define a new controller locally within the module and then pass it in through setType?

Sorry if some of this is basic angularJS. Still trying to understand how to fit all the pieces together.

**Comment by kentcdodds** [comment]
I believe you could specify the name of the controller as a sting as long
as it's been registered with angular and it should work. Haven't tried that
myself. For the link, it must be a function.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by gboersma** [comment]
That worked like a charm. Thanks so much!
