### ISSUE TITLE
Support for grid-layout

### ISSUE THREAD

**Issue by stefanzweifel** [formly-js/angular-formly#173]
Hi

My team and I are using formly in our recent Angular project. We use Foundation as our frontend framework and wan't to build the grid-layout with formly.

So for example, we want to set two input fields in one row. The HTML would look like this:

```html
<div class="row">
    <div class="medium-6 columns">
        FORMLY-FIELD
    </div>
    <div class="medium-6 columns">
        FORMLY-FIELD
    </div>
</div>
```

We made our own custom formly-template (Maybe we can push some of our code into your foundation-template) and figured out, how to build a fullsize-row (`<div class="row"><div class="medium-12 columns">FORMLY-FIELD</div></div>`).

So is there a way to hook into the "wrapping-process" and paste two input fields into a wrapper?
Maybe we could set the wrappers more dynamically like so?

````javascript
formlyConfigProvider.setType({
        name: 'input',
        template: '<input class="formly-field-input" ng-model="model[options.key]">',
        wrapper: ['label', ['grid-six', 'grid-six'], 'grid-row']
});
````
I think this could be a frequently used feature (even if you use Bootstrap or another custom grid-layout).

Sorry if this is like a noobish questions. Just started learning AngularJS. Maybe someone can guide us to the right solution

:v:

**Comment by ShMcK** [comment]
I found a way to do this today using flex-box. There's an [example here](https://formly-lumx.herokuapp.com/#/flex).

The trick is to create a `type` with another `<formly-form>` inside of it.
```
<div>
	<formly-form fields="options.templateOptions.fields"
	             model="$parent.model" form="::id" root-el="div"
	             flex-container="{{::options.templateOptions.flex.container}}"
	             flex-align="{{::options.templateOptions.flex.align}}"
	             flex-gutter="{{::options.templateOptions.flex.gutter}}">
	</formly-form>
</div>
```

You don't need all of those attributes, but notice the `model` links to the `$parent.model` and the `fields` link to `options.templateOptions.fields`. In other words, fields sit inside of templateOptions.

Styles can then be applied using a `wrapper`.

```
<div ng-class="'{{::options.templateOptions.flex.className}}'"
	flex-item="{{::options.templateOptions.flex.item}}"
	flex-order="{{::options.templateOptions.flex.order}}">
	<formly-transclude></formly-transclude>
</div>
```

The end result produces fields that looks like this:
```
{
  'key': 'modelName',
  'type': 'lx-wrapper-flex',
  'templateOptions': {
    'container': 'row', // row | column | row-reverse | column-reverse
    'wrap': 'nowrap', // nowrap | wrap | wrap-reverse
    'align': 'space-between', // flex-start | flex-end | center | space-between | space-around | stretch
    'className': 'bgc-red-500', // ng-class
    'style': 'height: 200px'
     'fields': [{
        {
          'key': 'modelName',
          'type': 'lx-whatever-type'
          'wrapper': 'lx-wrapper-flex-item', // <- add the wrapper
          'templateOptions': {
            'flex': {
              'item': '1' // flex-value number, higher weights the space ratio more 
              'order': '1', // value for ordering boxes
              'className': 'bgc-red-500' // ng-class
            }
          }
        }
      }]
  },
}
```

If you have any questions, shoot me an email (me@shmck.com).

**Comment by stefanzweifel** [comment]
Wow! Thanks Shawn. 
Looks like a great solution! Will try this out.

**Comment by kentcdodds** [comment]
Dear @ShMcK, you rock. Thanks for being an awesome OSS contributor! Or, as @aaronfrost would say: a "bridge builder" :-D

**Comment by kentcdodds** [comment]
@stefanzweifel, let me know if there's anything that could be changed about the core library to make this process easier. I agree that this is a common thing many people will want to do, so I want to make it as easy as it can be without complicating the API.

Also, I would totally love for a team like yours who's doing Foundation work to own the [Foundation Templates](https://github.com/formly-js/angular-formly-templates-foundation) :D

**Comment by stefanzweifel** [comment]
@kentcdodds I will try @ShMcK's solution and then we will see how easy it was for me to implement it :smiley: 

I'm aware of your Foundation Templates repo. We use formly to render forms which where created with a custom build of [dobtco/formbuilder](https://github.com/dobtco/formbuilder). We added a ton of functionality to this formbuilder and are mirroring those features now to our Foundation template.

I will ask my team mates, if we could support you with the Foundation Template but I can't guarantee it. (But I hope I can do some PR's to improve some stuff)

**Comment by GuilhermeMedeiros** [comment]
In my opinion the problem is bigger than just adding flexbox properties to the form fields. 
Today we have form fields, which is a literal array, but I'd imagine in the future we can write/extract each form fields and add it to a more complex container (layout).
That way, we could define named areas to create complex layouts.

```js
$scope.formData = {};
$scope.formFields = [
    {
        //the key to be used in the model values {... "username": "johndoe" ... }
        key: 'username',

        type: 'text',
        label: 'Username',
        placeholder: 'johndoe',
        required: true,
        disabled: false, //default: false
        description: 'Descriptive text'
    },
    {
        key: 'password',
        type: 'password',
        label: 'Password',
        required: true,
        disabled: false, //default: false
        expressionProperties: {
            hide: '!model.username' // hide when username is blank
        }
    }
];

$scope.formAreas = {
    area1: ['username'],
    area2: ['password']
}

$scope.onSubmit = function() {
    console.log('form submitted:', $scope.formData);
};
```

```html
<formly-form model="formData" fields="formFields">
    <div class="row">
        <div class="col-md-6">
            <formly-area name="area1"></formly-area>
        <div>
        <div class="col-md-6">
            <formly-area name="area2"></formly-area>
        <div>
    </div>
    <button ng-click="onSubmit()">Hello World</button>
</formly-form>
```

**Comment by ShMcK** [comment]
This could be achieved now by just manipulating classes. However, I totally agree, the current system is for achieving a form grid is kind of a hack and could be improved.

The outer field could use a `grid` type with an `ng-class`, in this case it'll take `row`.
```
<div>
<formly-form fields="options.templateOptions.fields" model="$parent.model"
ng-class="options.templateOptions.className"></formly-form>
</div>
```

Your inner fields could be wrapped with, let's say `wrapper-div` for lack of a better name. It also needs an `ng-class`, they'll take a `col-md-6` in our example.
```
<div ng-class="options.templateOptions.div.className">
    <formly-transclude></formly-transclude>
</div>
```

Then your fields would go inside the grid type.
```
$scope.formFields = [
	{
		key: userGrid,
		type: grid,
		templateOptions: {
                        className: 'row'
			fields: [{
				key: 'username',
				type: 'text',
                                wrapper: 'wrapper-div'
				templateOptions: {
					div: {
						className: 'col-md-6'
					},
					label: 'Username',
					placeholder: 'johndoe',
					required: true,
					disabled: false, //default: false
					description: 'Descriptive text'
				}, {
				key: 'password',
				type: 'password',
                               wrapper: 'wrapper-div',
				templateOptions: {
					div: {
						className: 'col-md-6'
					},
					label: 'Password',
					required: true,
					disabled: false, //default: false
					expressionProperties: {
						hide: '!model.username' // hide when username is blank
					}
				}
			}]
		}
	}];
```

That twisted Christmas tree doesn't look pretty, but it may work. Thanks to @kentcdodds for helping figure that pattern out earlier.

**Comment by kentcdodds** [comment]
So, I've been thinking about this a little bit, what would you think of an api like this:

```javascript
vm.formFields = [
  { /* field config */ },
  [
    { /* field config */ },
    { /* field config */ },
    { /* field config */ },
  ],
  { /* field config */ },
  { /* field config */ },
  [
    { /* field config */ },
    { /* field config */ },
    { /* field config */ },
  ],
  { /* field config */ }
];
```

And then you pass the `vm.formFields` as the `fields` attribute on `formly-form` and `formly-form` would somehow logically group those together for you. I'm not sure how this would best be accomplished. But I like to work "backward" and consider the desired api first, then come up with a solution (I guess that's sort of the TDD style). Would this be an acceptable API?

**Comment by stefanzweifel** [comment]
:+1: 

I like the approach with the arrays. Keeps the API pretty clean and is easily understandable.

**Comment by kentcdodds** [comment]
I'm wondering what this would actually result in. Right now, `formly-form` just uses `ng-repeat` on the fields so they wind up being siblings of one another. I'm thinking that with this array approach, it might group them into a `div` with a class like `formly-field-group` or something. Do you think this would really solve the problem?

**Comment by GuilhermeMedeiros** [comment]
I wouldn't change the current api. Adding a new directive and a map to the areas wouldn't break any current implementation.
I even think this could be a different module, because it adds complexity to the implementation. Which is exactly what we are trying to avoid.

**Comment by kentcdodds** [comment]
> it adds complexity to the implementation. Which is exactly what we are trying to avoid.

:+1: to that @GuilhermeMedeiros. I think I may have misunderstood your other comment. But I think that formly can do a little more work for you and I don't think that adding the ability to specify fields as an array of grouped fields would complicate the implementation too much. But I'm still uncertain of whether this will actually solve the problem. Perhaps the issue in my understanding is that where I'm using formly, the label is on the left rather than on top, so putting fields in a grid layout doesn't make as much sense for me.

**Comment by GuilhermeMedeiros** [comment]
The templateOptions can customise each field and it's label as a unit. The problem is when you need to place each field in a different place. I imagine also possible to have a directive for single unit fields:

```html
<formly-form model="formData" fields="formFields">
    <div class="row"> <!-- .row is just an example of course, you could have a class that changes the way you present certain fields -->
        <div class="col-md-6">
            <formly-field name="name" /> <!-- map to the input with name = name -->
        <div>
        <div class="col-md-6">
            <formly-field name="password" /> <!-- map to the password field -->
        <div>
    </div>
    <button ng-click="onSubmit()">Hello World</button>
</formly-form>
```

**Comment by GuilhermeMedeiros** [comment]
1. Render all fields on the same element: `fields="formFields"`
2. Render group of fields: `$scope.formAreas` + `<formly-area />`
3. Render each field separately: `<formly-field />` 

#### Advantages ####
- Keep simple api
- Forms are configurable via javascript without loosing layout flexibility
- Backwards compatible

**Comment by kentcdodds** [comment]
@GuilhermeMedeiros, I'm not certain that I understand what you're suggesting. If I understand it correctly, it feels like a bit of a more complicated API. Also, what you suggested with the `formly-field` is sort of possible because the `formly-field` directive exists (you simply need to provide the proper attributes). Anyway, I'm sorry if I'm having a hard time understanding what you're suggesting. Thanks for your patience.

**Comment by GuilhermeMedeiros** [comment]
haha, no worries. I'm being too short.
So the idea is to configure your fields via javascript, right? That's beautifully being done already. However, we loose flexibility because we cannot decide where each field is going to be placed.

Having a configuration of each field like we have today, is perfect. Even if you want to add any class to the wrapper of the field or add any extra configuration to a specific field is ok. The problem is when you want to place those fields in different places.

Keeping a simple API is very important. You can create a basic form without being aware you can place fields in different areas. That's the current implementation.

If you want to create multi-step forms for instance, or two columns layout, you need to group the fields somehow. So instead of rendering your fields inside of the `formly-form` directive you would do inside of the `formly-area`. With this is already possible to do a lot of things in terms of layout.

But let's say you don't want to create groups, you want define exactly where you want to "render" your field instead. So you need to have a directive which tells what is the name of the field (unique) and replace it with the actual field. This directive shouldn't have any parameters other than an identifier (name).

Using this approach, you are keeping you current api, and you can add this "layout" feature as a separated module. This module will introduce two directives `formly-area` and `formly-field`. Of course you will have to expose the fields somehow to this module, rather then render all the fields straight away.

I hope that was clear, I'm finishing a project by thursday but maybe after that I can help you building this part of the bridge. btw nice talk on NG-NL.

**Comment by kentcdodds** [comment]
Thanks @GuilhermeMedeiros! I would really appreciate any help you can give on implementing this functionality. Reach out to me when you think you've got time!

**Comment by stefanzweifel** [comment]
Guys. Thank you! Great to see that a simple idea takes shape so quickly.

@ShMcK's [approach](https://github.com/formly-js/angular-formly/issues/173#issuecomment-74660431) worked well for me. I just didn't now I can nest multiple `formly-form` directives.

I also like the idea to split this "grid-function" into a separate module. Maybe we should consider to tie those functions to the template system? After all `formly-area` and `formly-field` should be placed in your templates, right?

**Comment by kentcdodds** [comment]
@stefanzweifel, perhaps. The thing is that there are a few "right" ways to do this I think which makes it difficult to decide which is the real "right" way.

**Comment by kentcdodds** [comment]
So, looking for feedback. I'm guessing that the vote right now is to create a separate repository/module for this. There are actual several directives in the angular-formly module that could go into this category I think. Do you think that we should create a new repo called `angular-formly-template-utils` and use that for all of these utility directives? I'm also thinking that it may just be easier to stick in the `formly-area` directive into formly proper. I'm sort of torn and not certain of the best approach for this.

**Comment by kentcdodds** [comment]
I've created an example of how to accomplish this on [the website](http://formly-js.github.io/angular-formly/#/example/other/advanced-layout). I think that will have to be sufficient for now.

**Comment by ShMcK** [comment]
:+1: Fantastic!

**Comment by stefanzweifel** [comment]
Looks great. Thank you! :sparkles:

**Comment by aubricus** [comment]
Looking for a solution to this but example link is broken. Can someone restore it? Thanks!

**Comment by kentcdodds** [comment]
Here's the bootstrap version:
http://angular-formly.com/#/example/bootstrap-specific/advanced-layout
Here's the flex version:
http://angular-formly.com/#/example/other/advanced-layout-flex

**Comment by aubricus** [comment]
:+1: Thanks @kentcdodds for the fast response!

**Comment by Luddinus** [comment]
I vote for the idea of "formly-area", I think that the code in the template look much more clean and easy.

The current way seems too hackish for me.

**Comment by JBusch** [comment]
I'm having problems with this solution. If i am wrapping a fieldGroup inside a fieldGroup, the inner fieldGroup has no access to the model of the outer fieldGroup. Is this may be a bug, or am i just too stupid?

`
 formlyConfig.setWrapper({
            name: 'fields-wrapper',
            template: '<div class="fields-wrapper"><formly-transclude></formly-transclude></div>'
        });
`

` function ($translate, $FrontendComponentsPicklists) {
            function getConfig() {
                return [
                    {
                        key: 'mykey',
                        wrapper: 'fields-wrapper',
                        className: 'fields-wrapper-form',
                        fieldGroup: [
                            {
                                key: 'name',
                                type: 'input',
                                templateOptions: {
                                    type: 'text',
                                    label: $translate.instant('labelxyz')
                                }
                            }, {
                                key: 'dateCombo',
                                wrapper: 'fields-wrapper',
                                className: 'fields-wrapper-form-datecombo',
                                fieldGroup: [
                                    {
                                        key: 'fromDate',
                                        type: 'input',
                                        templateOptions: {
                                            type: 'date',
                                            label: $translate.instant('labelxyz')
                                        }
                                    },
                                    {
                                        key: 'toDate',
                                        type: 'input',
                                        templateOptions: {
                                            type: 'date',
                                            label: $translate.instant('labelxyz')
                                        }
                                    }
                                ]
                            },
                            {
                                key: 'currentEmployer',
                                type: 'hr-checkbox',
                                templateOptions: {
                                    label: $translate.instant('hrFormApplication.labelCurrentEmployer')
                                }
                            }
                        ]
                    },`
