### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#175]
We need a logo for the org, site, and the documentation. Would really love some help with this!

**Comment by ShMcK** [comment]
Any specs on the logo?
- Is it for Angular-Formly in particular or Formly-JS entirely?

**Comment by kentcdodds** [comment]
formly-js first. If you want to make an angular specific spin on that later
then that's cool to, but the original logo should appeal to regular
JavaScript I think.

I'm thinking something very simple. Like a few lines in a box or something.
I dunno... I'm no designer...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Closed, thanks to @raibutera!
