### ISSUE TITLE
Requires Angular 1.2?

### ISSUE THREAD

**Issue by Ledragon** [formly-js/angular-formly#176]
Hi,
I just tried to install angualr-formly using bower, after installing angular 1.3.13, and I got a conflict version for angular, as formly is trying to install 1.2. Is this normal? ::sad::

**Comment by kentcdodds** [comment]
No, you're fine. angular-formly depends on at LEAST Angular 1.2.x, but if you have a newer version that's terrific! You just need to specify a resolution. With npm, I can specify angular 1.2.x as a peer dependency and you don't get this, but with bower, this is the best we can do. Let me know if you need help getting this to work, but you should be able to simply follow the bower cli to specify a resolution for the conflict.

**Comment by Ledragon** [comment]
Thanks for the prompt reply. I will test this as soon as I can and will let you know. I managed to install it, but did not build an example yet. I will let you know as soon as I have something up and running!

**Comment by kentcdodds** [comment]
I know that it's possible because I've done it. So if you have any trouble, don't hesitate to come back and ask for help :D

**Comment by Ledragon** [comment]
Well, I saw your demo at NG-NL so I know it should work, but I wanna make sure :-)

**Comment by kentcdodds** [comment]
What I mean is I've gotten angular-formly to work with angular 1.3.x using bower :-)

**Comment by Ledragon** [comment]
Okay, I managed to get a formy error message, as I did not set up my model yet. Thanks for your help!

**Comment by kentcdodds** [comment]
Woot! Let me know if you need any help or if additional [examples](http://formly-js.github.io/angular-formly/#/) would be helpful to you. As always, contributions are welcome (especially examples!)

**Comment by Ledragon** [comment]
I will try to come out with something that can be useful :-)

**Comment by Ledragon** [comment]
TOTALLY working. It's just freaking awesome!

**Comment by Ledragon** [comment]
TOTALLY working. It's just freaking awesome!

**Comment by kentcdodds** [comment]
:smile: :+1:
