### ISSUE TITLE
Performance of initial display of fields

### ISSUE THREAD

**Issue by gboersma** [formly-js/angular-formly#177]
When displaying a page with a formly form for the first time, the form takes about 1/2s to display. Initially, I thought it was due to server lag, but after looking at it, the client already has all of the data from the server.

To narrow it down, I added some test code to print out the value of the data before displaying the form (using an AngularJS ng-repeat directive). The data is displayed immediately, the form follows about 1/2s later- but only on the initial display of the page.

It seems to me that formly is the most likely culprit here. Any suggestions as to how to improve performance? I notice that in the vanilla templates, each template is cached. Could this make a big difference?

**Comment by kentcdodds** [comment]
Yes, you'll want to use the template cache. I'll give a more complete
example later (on mobile now). But look into plugins for build systems to
automatically add your templates to the template cache.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by gboersma** [comment]
I think I got it. I created a run method for my module and passed in $http and $templateCache. I then load each of the templates into the cache:

$http.get('path/to/template.html', {cache:$templateCache});

I guess I could also have each template loaded directly from a string (i.e. from a build system plugin, I'm guessing) and completely avoid the server round-trip, but this is good enough for me.

**Comment by kentcdodds** [comment]
Great! I definitely recommend using a build system, but either way works I
guess. If this solves your issue, please closer this issue. Thanks! Let me
know if I can be of any more help! :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by gboersma** [comment]
Thanks for the pointer. Excellent suggestion. Grunt looks excellent.
