### ISSUE TITLE
Couldn't set the formControl after {time}ms

### ISSUE THREAD

**Issue by maryampashmi** [formly-js/angular-formly#179]
Hi,

I follow exactly "example " in "https://github.com/formly-js/angular-formly" , i have downloaded these version of formly  "angular-formly": "~1.0.0",
                            "angular-formly-templates-bootstrap": "~0.0.2",
                             "angular-formly-templates-vanilla": "~0.0.2"
Why i should have this error? what is wrong here when i follow the same code line as example came in this link. It seems somethings strange..How i should solve this error, do you mean instead of  model i should use ng-model?

**Comment by kentcdodds** [comment]
What are the actual versions that are downloaded with those definitions? The example in the readme is for the latest version which is version 3.1.6. Please update to the latest version and let me know if that fixes things for you.

**Comment by maryampashmi** [comment]
this problem is solved . thx. I still have a problem , i want to see this form in my view which is not possible to see , here you can see my controller "https://github.com/maryampashmi/Data-Procurement-Repository/blob/master/controllers/formController.js" and here is my partial "https://github.com/maryampashmi/Data-Procurement-Repository/blob/master/partials/poll.legal.html" .

I also add related script in my index. What is a problem?

Thank you.

**Comment by kentcdodds** [comment]
I'm not certain I understand the problem you're describing. Could you make an example by cloning this [jsbin template](http://jsbin.com/biqesi/edit)

**Comment by maryampashmi** [comment]
Thank you for your following.
Please check this example : http://jsbin.com/nowaju/1/edit?html,js,output
I have 2 app.js in my program which in one i entered dependencies : 
var myApp= angular.module('myApp', ['ui.router','formly', 'formlyVanilla']);
Also i have index.html which i called all these 3 java script with versions you have mentioned. I want to show my form in page while i can see only button in my page.
this is a link of my project : https://github.com/maryampashmi/Data-Procurement-Repository

**Comment by kentcdodds** [comment]
The example you provided doesn't work because it doesn't actually create an angular module. You also weren't bootstrapping the module and weren't specifying the controller. Here's a [fixed example](http://jsbin.com/xuboxu/1/edit).

I realize that this is only a small example, but I think the problem in your actual repository is that you're not actually specifying a controller in your state definition. You should add a `controller: 'formController'` to [this line](https://github.com/maryampashmi/Data-Procurement-Repository/blob/master/app.js#L82).

**Comment by maryampashmi** [comment]
I don't know what is going on with my code ;) somethings that i can not guess happened. I have applied all changes as you have mentioned in my repository. this appear new problem beside old one.My ui-router part is not working now ;) moreover i can not see any form in my html..... In addition i don't get any error in inspected element so i can not realize nothing..

**Comment by kentcdodds** [comment]
It sounds like you're having problems with UI router. I'm not certain how to help you. Let me know if you have specific questions. Good luck!

**Comment by maryampashmi** [comment]
I have tried a lot , This is all last commit you can see in my repository. There is not any way to run angular formly with ui route.  I really decided to use normal form in angular as i couldn't find any way to solve it.  Please see this command "https://github.com/maryampashmi/Data-Procurement-Repository/commits/master"

We will be really thank you if you can give us any help. It is not possible to shoe any form in html.

**Comment by maryampashmi** [comment]
Thank you so much Kent  for time you have spent ...
