### ISSUE TITLE
'Couldn't set form control' warning on non-input types

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#180]
I use two types that don't include form inputs: `lx-flex` for flexbox and `lx-title` to add section titles.

Both of these are now resulting in `angular.js:11607 Formly Warning: Couldn't set the formControl after 2000ms`. Any thoughts about how to supress the warning or fix the templates?

**Comment by kentcdodds** [comment]
That warning should link you to [this](https://github.com/formly-js/angular-formly/wiki/Errors-and-Warnings#couldnt-set-the-formcontrol-after-timems). If it doesn't, that's a bug and should be fixed. Does it not send you to that link?

**Comment by kentcdodds** [comment]
Regardless, the way you fix it is that for those you specify `noFormControl: true` as property and that will fix it. You could specify it as `defaultOptions` if it's registered for types.

**Comment by ShMcK** [comment]
Somehow I hadn't noticed the link, the error/warning docs are great. Issue should be resolved!

**Comment by kentcdodds** [comment]
Great! :D

**Comment by ShMcK** [comment]
However, if I set `noFormControl` to true on `lx-flex`, it will remove the needed `formControl` on all inner elements. May need some kind of `grid` based fix.

**Comment by kentcdodds** [comment]
Oh, ok. Do you need to reopen this issue then?

**Comment by ShMcK** [comment]
I would consider it a `grid` issue. The solution worked for titles.
