### ISSUE TITLE
Test things out with Angular 2.0

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#182]
One goal of this library should be that the API doesn't change at all between Angular 1.x and 2.x making a migration as simple as updating the custom templates to use 2.x syntax. Investigate what it would take to make angular-formly either span either version or at the very least create another project that uses the same API that supports 2.0.

**Comment by jameswyse** [comment]
Seen this @kentcdodds? Looks like Angular 2.x will have a new Form API: http://angularjs.blogspot.nl/2015/03/forms-in-angular-2.html

**Comment by kentcdodds** [comment]
Thanks @jameswyse, I actually video chatted with Victor a little bit to talk about the formly api and I would like to think that had some sway on the decision to include a more imperative approach. Hoping that angular-formly will be rendered useless by Angular 2. However, my plan is to make the port anyway so people can upgrade to Angular 2 without the need to change their form configurations. Then they can migrate from angular-formly to Angular 2's built-in stuff.

**Comment by jameswyse** [comment]
That's awesome! :)

**Comment by kentcdodds** [comment]
Created the [formly-js/angular2-formly](http://github.com/formly-js/angular2-formly) repo. It's pretty rough, but I'm closing this issue in favor of that.
