### ISSUE TITLE
Allow types to validate options

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#183]
It would be really useful if types could validate options and throw errors when there are options provided that are not valid for the type. This should be simply in the form of a function that accepts the `options` and the type author throws an error or warns in the console themselves. It should run in the `formly-field` controller function before (almost) anything else.

**Comment by kentcdodds** [comment]
Would love your input @ShMcK and @mhartington

**Comment by ShMcK** [comment]
I like the idea. Lately, I've been playing with React and enjoy their implementation of type validation. It follows as properties on a validation object that can follow a hierarchical order. An (http://developer.fortnox.se/blog/proptypes-in-react-js/)[http://developer.fortnox.se/blog/proptypes-in-react-js/].

```javascript
templateOptions: {
   required: Formly.optionsType.boolean,
   maxlength: Formly.optionsType.number.range(4, 8),
   type: Formly.optionsType.oneOf('text', 'number', 'url', 'email', 'password').default('text').isRequired
}
```

It could also be written as an object, as in the [react-prop-schema library](https://github.com/killercup/react-prop-schema). Now that I look at it, this method is much more in order with what angular-formly is doing already.

```javascript 
{
  "required": {"type": "boolean"},
  "maxlength": {"type": "number", 
                       "min": 4, "max": 8},
  "type": {"oneOf": ["text", "number", "url", "email", "password"], 
               "required": true, 
               "default": "text" }
}
```

**Comment by ShMcK** [comment]
These could be added in the `setType` stage when creating a template. It would be easy to add:

```javascript
formlyConfigProvider.setType({
    name: name,
    templateUrl: templateUrl,
    optionTypes: optionTypes  /** optionSchema? */
})
```

**Comment by kentcdodds** [comment]
I actually created apiCheck.js for this purpose:
https://github.com/kentcdodds/apiCheck.js

I've been planning on bringing apiCheck into formly as a dependency and may
expose that to types via the API you described. Just need to work on the
error messaging a little better...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
I should keep a better eye on your prolific Github work. There are definitely a lot of great ideas that can be exchanged between React & Angular, great work with apiCheck.js!

**Comment by kentcdodds** [comment]
:blush: thanks :-) It's written in vanillajs and works on in node too :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
After reading the intro docs, I'm quite happy with apicheck.js. Let me know when it's ready and I'll give it a beta run.

**Comment by kentcdodds** [comment]
I think it's good for beta now. It's just the error messaging that I want
to improve. But everything else works quite well.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
Is there an option available for using `apiCheck` with `formlyConfigProvider.setType` ?

**Comment by kentcdodds** [comment]
Not currently. I could pretty easily add an api like this:

```javascript
formlyConfig.setType({
  name: 'input',
  validateOptions: function(options) {
    // validate your stuff here, throw your own errors or log your own warnings
  }
});
```

With that, you could do something like this:

```javascript
formlyConfig.setType({
  name: 'input',
  validateOptions: function(options) {
    var templateOptionsCheck = apiCheck.shape({
      label: apiCheck.string,
      placeholder: apiCheck
    });
    templateOptionsCheck.strict = true; // must have all and no more than specified stuff

    apiCheck.throw(apiCheck.shape({
      templateOptions: templateOptionsCheck,
      data: apiCheck.shape({
        someProperty: apiCheck.any
      })
    }, arguments);
  }
});
```

Or you could roll your own api check stuff. What do you think?

**Comment by ShMcK** [comment]
I think the API could be further simplified, but the functionality is great and necessary.
Ideas: 

* Smart defaults: like `templateOptionsCheck.strict` set to `true`.
* I think the validation should try to resemble the current json-like style api as much as possible.
* Will errors be thrown or logged as warnings? I have a personal preference for warnings.

A few questions about the example:
In the example, `validateOptions` takes a function with `options` but doesn't use the parameter.
I'm also not sure what the `placeholder: apicheck` does.

**Comment by kentcdodds** [comment]
So, in this scenario, formly doesn't actually care what you do. It simply passes you `options` and allows you to `throw` or `warn` or `alert` or whatever the heck you want. In my example, I'm using `apiCheck.throw` which will throw an error if the checks fail. I'm passing `arguments` because that's the api to `apiCheck` (the first argument is your check function and the second argument expects you to pass `arguments`) so it actually is using `options` though not explicitly as a variable.

I suppose that formly could take a more opinionated approach, but I fear this would reduce flexibility.

**Comment by ShMcK** [comment]
I have to say, it sounds great. If you can post a few good working examples, I'll set it up with LumX and give it a try.

**Comment by kentcdodds** [comment]
Ok, the api should be pretty simple to setup. I think I'm going to make apiCheck a dependency of formly, and when that happens, you'll be able to use apiCheck by default because you depend on formly, so you'll get apiCheck. I'll make apiCheck injectable as well so you'll be able to simply inject it and not worry about where it came from :-)

**Comment by ShMcK** [comment]
:)

**Comment by kentcdodds** [comment]
Oh, by the way, this is supported as of [3.3.0](https://github.com/formly-js/angular-formly/blob/master/CHANGELOG.md#330) :-)
