### ISSUE TITLE
Forced apiCheck requirement for templates

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#184]
I'm currently setting up apiCheck with `angular-formly-templates-lumx`, however I noticed a problem.

My build already fails when upgrading to `angular-formly@3.3.0` with the error: `Error: angular-formly: formlyConfig.setType apiCheck failed! `

I think this is unintended, as `apiCheck` should be an optional enhancement.

**Comment by kentcdodds** [comment]
formly uses `apiCheck` internally to validate its own apis (like `setType`). So if you're seeing that it's because you're calling `setType` wrong or there's a problem with the `apiCheck` config for that function. I actually have a bunch of stuff locally around that stuff. If you can hold off for a day or so, I'll get it in and then you can play with it :-)

**Comment by ShMcK** [comment]
I figured a way around it. Before I handled `setType` in the config stage, but with 3.3 it results in an error.

I changed it to handle wrappers in `config` and types in `run`, then no problem.

**Comment by ShMcK** [comment]
I map over the templates to create them. 
```javascript
For example: FIELDS = [{ 
    name: 'templateName', 
    template: 'htmlStuffHere'
}]
```

Will it be possible to map over the apiCheck validation rules with the new 3.3 API?

Example:

```javascript
 FIELDS.map(function (field) {
        formlyConfig.setType({
          name: _prefixer(field.name),
          templateUrl: _fieldTemplateUrl(field.name),
          validateOptions: function (options) {
            apiCheck.throw(field.validateOptions || apiCheck.object, arguments);  // <--- validateOptions key
          }
        });
      });
```

I imagine field.validateOptions would be a function or object... But not sure how to set this up. Perhaps some more advanced examples?

**Comment by kentcdodds** [comment]
I think it'd be more like this:

```javascript
```

**Comment by ShMcK** [comment]
So far I'm still not quite sure how to use validateOptions as an object in a loop.

```javascript
"validateOptions": function (options, apiCheck) {
      apiCheck.warn([
        apiCheck.shape({
         templateOptions: {
                   label: apiCheck.string
                }
          })
      ], arguments);
    }
}
```

Of course, this doesn't work. 

Would it be possible to pass in an object that automatically used apiCheck.shape on templateOptions with easy defaults?

```javascript
"validateOptions": {
    label: apiCheck.string
}
```

**Comment by ShMcK** [comment]
Actually, ideally it would great if apiCheck could be used with angular-formly in a more succinct manner:

setType:
`validateOptions: apiCheck(field.validateOptions)`

Fields object:
```javascript
validateOptions: {
      label: 'string',
      required: 'boolean'
}
```

Forgive me! This is me dreaming of an impractical perfect world after my own failure at applying apiCheck!

**Comment by kentcdodds** [comment]
I can see where what you're suggesting would be beneficial. Maybe that can be a feature added a little later down the line. Right now, you're responsible for throwing your own error or logging your own warnings.

**Comment by ShMcK** [comment]
Could we get a more advanced example of using `apiCheck` with `angular-formly`? I think that would help. 

```
// formlyConfig.setType
validateOptions: function (options) {
            apiCheck.warn([
              apiCheck.shape({
                label: apiCheck.string
              })], arguments);
          }
```

Results in an error: 
angular-formly: apiCheck failed! You passed: `{"key":"String","type":"String","templateOptions":"{\"type\":\"String\",\"label\":\"String\"}","data":"{}","validation":"{}"}` and should have passed: `shape({"label":"String"})``

I've struggled and failed at getting a basic example to work.

**Comment by kentcdodds** [comment]
There's an example for this now: http://formly-js.github.io/angular-formly/#/example/custom-types/validate-options

**Comment by ShMcK** [comment]
Thanks, I'll give it a try!

**Comment by kentcdodds** [comment]
Does this still need to be open?
