### ISSUE TITLE
validation trigger

### ISSUE THREAD

**Issue by adasq** [formly-js/angular-formly#185]
field1 validation should be forced when field2 has changed. How could be this done with formly field description object?

greetings

**Comment by kentcdodds** [comment]
You can add an `expressionProperty` for `validation.show` that returns true when you want it to show and null otherwise.https://github.com/formly-js/angular-formly/blob/master/README.md#validation-object

**Comment by adasq** [comment]
Hey, thanks for answer.  ```validation.show``` function as an ```expressionsPropery``` did not want to call my custom valdiation function, so I did this:

*the concept*:
- two fields: ```name```, and ```nameAgain```,
- ```nameAgain``` has a validator, which check if ```name === nameAgain```,
- when we change ```name```, the ```nameAgain``` validator function should be called

*code*:

```javascript 
vm.model = {};
vm.fields = [{
    key: 'name',
    type: 'input',
    watcher: {
      expression: 'model.name',
      listener: function(field, _new) {
        var nameAgainField = vm.fields[1]; //that's pretty weak...
        var nameAgainFormControl = nameAgainField.formControl;
        nameAgainFormControl && nameAgainFormControl.$validate();
      }
    },
    templateOptions: {
      label: 'Enter your name',
      required: true
    },
  }, {
    key: 'nameAgain',
    type: 'input',
    validators: {
      nameAgain: {
        expression: function(viewValue, modelValue) {
          return (viewValue || modelValue) === vm.model.name;
        },
        message: '$viewValue + " is not equal to your name!"'
      }
    },
    templateOptions: {
      label: 'Enter your name again',
      required: true
    }
  }

**Comment by kentcdodds** [comment]
I do this at work. I'll create an example for you and put it on the website
:-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Here's the example. Let me know if you need any more direction :-) http://formly-js.github.io/angular-formly/#/example/other/matching-two-fields

**Comment by adasq** [comment]
The example you've provide is really interesting - I appreciate your work. Thanks.

**Comment by kentcdodds** [comment]
That's very nice of you to say. Thanks! Please let me know if there's more
I can do to help. Otherwise, please close this issue

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by adasq** [comment]
It seems to be closed already :)

**Comment by fated-x** [comment]
The link Kent added on **Feb 28, 2015** no longer shows the example. The currently working link can be found here: http://angular-formly.com/#!/example/other/matching-two-fields.
