### ISSUE TITLE
apiCheck failed on validation.messages

### ISSUE THREAD

**Issue by jameswyse** [formly-js/angular-formly#188]
> Error: angular-formly: formly-field directive apiCheck failed! `messages` at `validation` must be `Function`

I'm getting the above error without ever specifying a `validation` key. It's present in the "You passed" log output, and is set to an empty object.

Looks like that's happening here:
https://github.com/formly-js/angular-formly/blob/733c7cc103dde3a509ae14efb20d67ce35bb4476/src/directives/formly-custom-validation.js#L15

**Comment by kentcdodds** [comment]
My most sincere apologies @jameswyse. I just added apiCheck, so I wonder if you could give me feedback on it. How difficult was it to work with before you realized that you needed to make a bug? The whole purpose of apiCheck is to help you learn how to use the api. Unfortunately, the way I defined the api for this piece was wrong and that's where the bug comes from (I said it was a function, but it is actually an object of functions).

Anyway, I'd love feedback on that. Thanks!

**Comment by kentcdodds** [comment]
Oh, also, `npm|bower install 3.3.2` :-)

**Comment by jameswyse** [comment]
hehe that's what I figured. My first thought was actually "Oh, he's changed the api again!". (not a bad thing - this project is rapidly evolving and i'm really happy about that!) and ApiCheck is already proving to be useful.

I guess I still don't fully understand how to simply change the standard validation messages, (e.g. "This field is required") as I was trying to do that with the `validation` object on some other forms. Should the function simply return the message?

Thanks for all your hard work!

**Comment by kentcdodds** [comment]
Thanks @jameswyse. That's very... for lack of a better word... validating :-)

So, I just updated the [Custom Validators example](http://formly-js.github.io/angular-formly/#/example/advanced/validators) on the website to show an example of how to alter the default message using `validation.messages`. It actually heavily depends on how you implement `ng-messages` in your templates. If you do it like the example demonstrates, then you're invoking the messages.

Also note, that the example has also been updated to demonstrate the use of the [`formlyValidationMessages`](https://github.com/formly-js/angular-formly#formlyvalidationmessages) factory which may be of use to you as well :-) Let me know if you need any more help.

**Comment by jameswyse** [comment]
That's awesome, thanks a lot!
