### ISSUE TITLE
TypeError with getType

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#189]
When using apiCheck with angular-formly, I've come across this error. I'm not sure why type returns undefined. I traced the issue down to:

formlyConfig.js line 170 in `getType`

`var type = typeMap[name]; `, type becomes `undefined`

`name` has the type name, for example 'lx-input'.
`typeMap` has the array of types, including 'lx-input: Object'

**Comment by kentcdodds** [comment]
Very interesting. How are you creating your type? Here's the entire `setType` function:

```javascript
function setType(options) {
      if (angular.isArray(options)) {
        angular.forEach(options, setType);
      } else if (angular.isObject(options)) {
        checkType(options); // <-- at this point, the options you pass are validated using apiCheck, so the name is definitely defined and a string here.
        if (options.extends) {
          extendTypeOptions(options); // <-- if you're extending then options runs through this function, but nothing happens to the `name` property
        }
        typeMap[options.name] = options; // <-- we're putting the `options.name` here.
      } else {
        throw getError(`You must provide an object or array for setType. You provided: ${JSON.stringify(arguments)}`);
      }
    }
```

That function should be using apiCheck before long, but anyway, I think you get the idea. My first place to check (and step through the code) would be in the `setType` function.

**Comment by kentcdodds** [comment]
Are you still experiencing this issue?

**Comment by ShMcK** [comment]
No longer an issue, closed!

**Comment by kentcdodds** [comment]
Fantastic! :D
