### ISSUE TITLE
Add JSDoc comment above directives as a workaround for a WebStorm bug

### ISSUE THREAD

**Issue by rborman** [formly-js/angular-formly#191]
This is not really a Formly issue, but imho would benefit Formly. Let me explain...

WebStorm has a bug (https://youtrack.jetbrains.com/issue/WEB-14092) which prevents it from recognizing html tags that are backed by an Angular directive, written acccording the 'John Papa style guide' (named functions instead of anonymous functions as a callback). Besides a confusing warning ('unknown html tag') this also short-circuits navigation in WebStorm.

A fix will be available only in the next major WebStorm release. There is a workaround, however. You can add a JSDoc comment above the named function (see the WebStorm issue, Markdown mangles it) and the tag is recognized. Of course I could do that myself every time there is a new Formly release, but the pace is quite fast ;-)

**Comment by kentcdodds** [comment]
Sounds great. Could you submit a PR? I use WebStorm as well. Thanks.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by rborman** [comment]
As this was my first encounter with Formly, I'm new to it and I want to be sure before I submit the PR.

According to the documentation there are four directives:
- formlyCustomValidation (an attribute directive although the restrict property is not specified so in theory it depends on the Angular version being used: A for 1.2, AE for 1.3+);
- formlyField (can be both an element and attribute directive as specified by the restrict property);
- formlyFocus (an attribute directive that also has no explicit restrict property, but it uses the inline callback notation so is not affected by the bug anyway);
- formlyForm (an element directive as specified by the restrict property).

For now I think only formlyField and formlyForm should have the comment.

BTW maybe all directives should have an explicit restrict property and formlyFocus should be transformed into a named callback - I'm not sure about any side effects though.

Regards, Ronald

**Comment by kentcdodds** [comment]
I'm not sure how I overlooked not restricting these directives. In your PR, feel free to restrict them each. The `formlyCustomValidation` and `formlyFocus` directives must be restricted by `A`. The `formlyField` can be `AE` and the `formlyForm` is an `E`. Let's leave the `formlyFocus` directive as an object so we can specify it's restriction as an attribute. Thanks a lot for your help!

**Comment by rborman** [comment]
I just submitted the PR. As this is my very first PR, I hope I did everything right. Feel free to suggest changes.

**Comment by kentcdodds** [comment]
Resolved by #205 Thanks!

**Comment by kentcdodds** [comment]
This has been published as 4.0.10 :-) Thanks!
