### ISSUE TITLE
Adding an AngularUI popup date controller

### ISSUE THREAD

**Issue by andyfensham** [formly-js/angular-formly#195]
Hi,  I am trying to add an AngularUI popup date controller using formlyConfig.setType

formlyConfig.setType([
        {
            name: 'date',
            templateUrl: '/app/templates/date.html'
        }
    ]);

I copied  from the Popup date onwards, and added the relevant scope variables in my controller.  These scope variables are not being picked up.  Please help.  PS : I am quite inexperienced in Angular.

**Comment by kentcdodds** [comment]
It looks like you're creating the type properly. Could you paste your template?

**Comment by kentcdodds** [comment]
Also, you don't happen to be here at ng-conf right now are you? If so we could meet up and I could help you in person.

**Comment by andyfensham** [comment]
No..unfortunately not.  The template is : 

<h4>Popup</h4>
    <div class="row">
        <div class="col-md-6">
            <p class="input-group">
              <input type="text" class="form-control" datepicker-popup="{{format}}" ng-model="dt" is-open="opened" min-date="minDate" max-date="'2015-06-22'" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" />
              <span class="input-group-btn">
                <button type="button" class="btn btn-default" ng-click="open($event)"><i class="glyphicon glyphicon-calendar"></i></button>
              </span>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label>Format:</label> <select class="form-control" ng-model="format" ng-options="f for f in formats"><option></option></select>
        </div>
    </div>

    <hr />
    <button type="button" class="btn btn-sm btn-info" ng-click="today()">Today</button>
    <button type="button" class="btn btn-sm btn-default" ng-click="dt = '2009-08-24'">2009-08-24</button>
    <button type="button" class="btn btn-sm btn-danger" ng-click="clear()">Clear</button>
    <button type="button" class="btn btn-sm btn-default" ng-click="toggleMin()" tooltip="After today restriction">Min date</button>

In my controller I set :

$scope.today = function () {
        $scope.dt = new Date();
    };
    $scope.today();

    $scope.clear = function () {
        $scope.dt = null;
    };

    // Disable weekend selection
    $scope.disabled = function (date, mode) {
        return (mode === 'day' && (date.getDay() === 0 || date.getDay() === 6));
    };

    $scope.toggleMin = function () {
        $scope.minDate = $scope.minDate ? null : new Date();
    };
    $scope.toggleMin();

    $scope.open = function ($event) {
        $event.preventDefault();
        $event.stopPropagation();

        $scope.opened = true;
    };

    $scope.dateOptions = {
        formatYear: 'yy',
        startingDay: 1
    };

    $scope.formats = ['dd-MMMM-yyyy', 'yyyy/MM/dd', 'dd.MM.yyyy', 'shortDate'];
    $scope.format = $scope.formats[0];

So everything is there inside the controller that points to my <formly-form>

**Comment by kentcdodds** [comment]
So, with angular-formly, the template has access to some specific things. The scope of your template is not the same as the scope in your controller. So, anything you want your template to have access to needs to be in your field configuration under `templateOptions`. So you'd want to do something like this:

```javascript
$scope.fields = [
  {
    type: 'date', // <-- the name of the type you created for the date-picker
    key: 'selectedDate', // <-- the property on the model to bind to the value of the date-picker
    templateOptions: {
      dateOptions: {}, // <-- your date options
      formate: '', // <-- your format
      ... // <-- the other things you want to have access to in your template
    }
  }
];
```

Then you need to reference the `options` object in your template. Most of your stuff will be on `options.templateOptions`, but because this is a lot to type, formly gives you a shortcut called `to`.

```html
<input type="text" class="form-control" datepicker-popup="{{to.format}}" ng-model="model[options.key]" is-open="opened" min-date="to.minDate" max-date="to.maxDate'" datepicker-options="to.dateOptions" date-disabled="to.disabled(date, mode)" close-text="{{to.closeText || 'Close'}}" />
```

Note: You don't need to specify ng-required because angular formly will add that for you automatically if you specify `required` as one of your template options.

If you need more help, take a look at [this example](http://formly-js.github.io/angular-formly/#/example/custom-types/custom-templates) and [this talk](http://youtu.be/o90TMDL3OYc)

**Comment by andyfensham** [comment]
Thanks so much for your quick reply. Will try it..

**Comment by abodacs** [comment]
@kentcdodds  Thanks for your talk very helpful

**Comment by kentcdodds** [comment]
You're welcome @abodacs :-)

**Comment by nrice** [comment]
Reference from above:  `<input type="text" class="form-control" datepicker-popup="{{to.format}}" ng-model="model[options.key]" is-open="opened" min-date="to.minDate" max-date="to.maxDate'" datepicker-options="to.dateOptions" date-disabled="to.disabled(date, mode)" close-text="{{to.closeText || 'Close'}}" />   `  

`date-disabled="to.disabled(date, mode)" ` causes the entire datepicker to be disabled.  I changed to 

`date-disabled="to.datedisabled(date, mode)"`

In the controller, example to disable weekends

`{
                    className: 'col-md-3',
                    key: 'startDate',
                    type: 'datepicker',
                    templateOptions: {
                        label: 'Start Date',
                        required: true,
                        type: 'text',
                        datepickerPopup: 'dd-MMMM-yyyy',
                        datedisabled: function (date, mode) {
                            return (mode === 'day' && (date.getDay() === 0 || date.getDay() === 6));
                        }
                    }
                }`
