### ISSUE TITLE
How to handle lookup fields? [Question]

### ISSUE THREAD

**Issue by paulvanbladel** [formly-js/angular-formly#197]
Formly looks great and I might need to explore the documentation once more, but I'm wondering how to handle lookup fields.
Simple examples: 
* dropdown or autocomplete with countries
* an order screen where I want to select a customer, so the customer field (eventually showing the name of the customer) needs a [...] button next on the right with an ng-click triggering a custom action (in this case a new window for selecting the customer)

**Comment by kentcdodds** [comment]
Hi @paulvanbladel,
Both of these would require a custom `type`. There's an example of how to do this on [the website](http://formly-js.github.io/angular-formly/#/example/custom-types/custom-templates). For the custom action, your type could specify a `controller` which would add the custom action to the `$scope` (here's [an example](http://formly-js.github.io/angular-formly/#/example/advanced/custom-controller-and-link) of that).

**Comment by paulvanbladel** [comment]
Thanks Kent, I'll look into that.

**Comment by kentcdodds** [comment]
Hi @paulvanbladel! Did you get this working? Does this need to remain open?

**Comment by kentcdodds** [comment]
I take it you got this working? Great! :D Let me know if there's anything more I can do!

**Comment by abodacs** [comment]
@kentcdodds can you make an example of autocomplete ??

**Comment by kentcdodds** [comment]
@abodacs, an autocomplete component is pretty complex. There are libraries that allow you to do it pretty easily. Is there a particular library you'd like to see an example of integration with formly?

**Comment by abodacs** [comment]
@kentcdodds i accept any library :) and it would be great if it was in edit mode.

**Comment by kentcdodds** [comment]
> and it would be great if it was in edit mode.

I'm not sure what you mean by this...

**Comment by kentcdodds** [comment]
Here you go: http://angular-formly.com/#/example/other/ui-bootstrap-typeahead

**Comment by abodacs** [comment]
my use case i have form has autocomplete populated from api . i mean by "edit mode" how can i populated the autocomplete field again when user want to edit it.

**Comment by CodeLiftSleep** [comment]
Can we have an example of how to handle dynamically loaded data into typeahead instead of data that is included?

**Comment by abodacs** [comment]
@CodeLiftSleep 
https://gist.github.com/eyston/5851760 may help

**Comment by CodeLiftSleep** [comment]
I actually created my own example...I basically merged the example for Async Select and UI-Bootstrap and got it working...

Here is a much better typeahead example with UI BootStrap using dynamic data: [](http://plnkr.co/IjuJ0HPGCKfZAOrK0u3z?p=preview)
