### ISSUE TITLE
How to tune the layout?

### ISSUE THREAD

**Issue by paulvanbladel** [formly-js/angular-formly#198]
Simple case: I have 8 input fields and want to display them in 2 columns.
I know that without formly, I would just use layout system of twitter bootstrap to do this, but can this be done also with formly in the definition in the controller?

**Comment by kentcdodds** [comment]
This is possible. Give me a little time to get back to my computer to
create an example

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
I made an example. Check this example: http://formly-js.github.io/angular-formly/#/example/other/advanced-layout

I'm going to close this, but if you have trouble, feel free to reopen or just comment.

**Comment by paulvanbladel** [comment]
Thanks a lot.

**Comment by josmora** [comment]
Thanks, 
only update the links of that example. :+1: 
http://angular-formly.com/#/example/bootstrap-specific/advanced-layout

**Comment by kentcdodds** [comment]
Updated. Thanks! :+1:
