### ISSUE TITLE
bootsrap select method returns array instead of objects

### ISSUE THREAD

**Issue by gowram** [formly-js/angular-formly#200]
I tried to use formly with bootstrap select methods, the result i am getting as array instead of objects such as...
```javascript
[Resource, $promise: Promise, $resolved: true, organisationId: "2", name: "clarie"]
```
is this normal behavior?

these are my fields.

```javascript

vm.formFields = [
        {
          key: 'name',
          type: 'input',
          templateOptions: {
            type:'text',
            label: 'Name',
            required: true
          }
        },
       {
        key:'organisationId',
        type:'select',
        templateOptions: {
          label: 'Choose orgainsation',
          required:true,
          options:$scope.organisations
        }
       }
      ];
```

**Comment by kentcdodds** [comment]
It has everything to do with what you're setting your `options` to. So your `$scope.organizations` is what formlyBootstrap will use for the options. I don't know how to help you. You just need to make sure that you're setting `options` to the right thing...

**Comment by gowram** [comment]
my options is as below...
```javascript
$scope.organisations = [
    {name: 'org1', value: '1'},
	{name: 'org2', value: '2'},
	{name: 'org3', value: '3'},
	{name: 'org4', value: '4'},
	{name: 'org5', value: '5'}	
  ];
```
when i choose any one of the i have to get object like 

```javascript
 {'name': 'person1', 'organisationId': '3'}
```
my output is not in object, i am actually getting as array as above mentioned...

**Comment by kentcdodds** [comment]
So, currently formlyBootstrap's select type doesn't support selecting the entire object as the model value. Feel free to submit a PR to support this or simply create your own select type (it's very easy to do).

As far as that array, I have no idea where that's coming from. If you look at the examples, that's not what is happening. Could you [create a jsbin](http://jsbin.com/biqesi/edit) that reproduces the issue?

**Comment by gowram** [comment]
The problem is that angular promises, nothing to do with formly, thanks for your valuable responses.
