### ISSUE TITLE
How to handle dynamic options in 'select' type

### ISSUE THREAD

**Issue by billfranklin** [formly-js/angular-formly#202]
Am I going to have to write a custom type to get the options to dynamically load into the select field?

If I place the array of objects into the options attribute of the field, formly populates the select perfectly, however, if I try to set the options to a promise variable, it doesn't populate the select at all.

I didn't see an example of this.  You may have covered this in the workshop, but I can't recall, and don't have my laptop with me to see the examples.

```javascript
	vm.locations = [];
	
	$http.get('./assets/locations.json').success(function(data){
            vm.locations = data;
	});
	vm.formFields = [
	{
		key: 'startingLocation',
		type: 'select',
		templateOptions:{
			label: 'Starting Location',
			options: vm.locations,
			valueProp: 'stationID',
			labelProp: 'name',
			required: true,
			focus:true,
			placeholder: 'Select Starting Location from List'
		}
	}
	];

DOM

<ng-form class="formly ng-pristine ng-isolate-scope ng-invalid ng-invalid-required" role="form" name="form" fields="vm.formFields" model="vm.model">
<div class="formly-field formly-field-select" index="$index" form-state="options.formState" form-id="formId" form="form" fields="fields" model="field.model || model" options="field" ng-if="!field.hide" ng-repeat="field in fields track by $index" formly-field="">
<div class="form-group ng-scope has-error" ng-class="{'has-error': showError}">
<div>
<label class="control-label ng-binding" for="formly_1_select_startingLocation_0"> Starting Location * </label>
<select id="formly_1_select_startingLocation_0" class="form-control ng-pristine ng-invalid ng-invalid-required ng-touched" ng-options="option[to.valueProp || 'value'] as option[to.labelProp || 'name'] group by option[to.groupProp || 'group'] for option in to.options" ng-model="model[options.key]" name="formly_1_select_startingLocation_0" formly-focus="true" required="required" placeholder="Select Starting Location from List" tabindex="0" aria-required="true" aria-invalid="true">
<option value="?" selected="selected" label=""></option>
</select>
</div>
</div>
</div>
<div ng-transclude="">
</ng-form>

**Comment by billfranklin** [comment]
DOM

`<ng-form class="formly ng-pristine ng-isolate-scope ng-invalid ng-invalid-required" role="form" name="form" fields="vm.formFields" model="vm.model">`
`<div class="formly-field formly-field-select" index="$index" form-state="options.formState" form-id="formId" form="form" fields="fields" model="field.model || model" options="field" ng-if="!field.hide" ng-repeat="field in fields track by $index" formly-field="">`
`<div class="form-group ng-scope has-error" ng-class="{'has-error': showError}">`
`<div>`
`<label class="control-label ng-binding" for="formly_1_select_startingLocation_0"> Starting Location * </label>`
`<select id="formly_1_select_startingLocation_0" class="form-control ng-pristine ng-invalid ng-invalid-required ng-touched" ng-options="option[to.valueProp || 'value'] as option[to.labelProp || 'name'] group by option[to.groupProp || 'group'] for option in to.options" ng-model="model[options.key]" name="formly_1_select_startingLocation_0" formly-focus="true" required="required" placeholder="Select Starting Location from List" tabindex="0" aria-required="true" aria-invalid="true">`
`<option value="?" selected="selected" label=""></option>`
`</select>`
`</div>`
`</div>`
`</div>`
`<div ng-transclude="">`
`</ng-form>`

**Comment by kentcdodds** [comment]
What is the value of `vm.locations` after the request finishes? Also, it's best practice to not use `$http` in your controller. You should either use `resolve` in your route definition and/or use a service. If you resolve your dependencies into your controller, then this issue goes away intirely.

**Comment by billfranklin** [comment]
vm.locations is fully populated, I actually output it in a `<pre>{{vm.locations|json}}</pre>` to verify that it is populated.

**Comment by kentcdodds** [comment]
Hmmm... Could you reproduce this issue in a jsbin?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by billfranklin** [comment]
http://jsbin.com/yomowa/7/edit?html,js,console,output

**Comment by kentcdodds** [comment]
Ummm... That appears to be an empty bin:

![screen shot 2015-03-11 at 9 49 28 pm](https://cloud.githubusercontent.com/assets/1500684/6611921/938dc230-c838-11e4-9753-5d49f3740aeb.png)

**Comment by billfranklin** [comment]
not sure why...it is full for me...saved it a couple of times, let's see if it works now..


http://jsbin.com/yomowa/9/edit?html,js,output

**Comment by kentcdodds** [comment]
Weird... Still totally empty for me.... I don't think this matters, but do you have an account? Maybe you have to sign up for an account to have it persist...

**Comment by billfranklin** [comment]
Yes, I do

![untitled](https://cloud.githubusercontent.com/assets/6142870/6611944/6a824b78-c841-11e4-8751-8b3f5746cbf1.png)

**Comment by kentcdodds** [comment]
Very odd... @remy, do you know why this might be happening?

**Comment by billfranklin** [comment]
what's even odder, if I open it in a new browser, that's not logged in to jsbin, I can see the contents from that link.

**Comment by kentcdodds** [comment]
If I go to the output only view, I see this:

![screen shot 2015-03-11 at 9 57 16 pm](https://cloud.githubusercontent.com/assets/1500684/6611985/a5dc15f8-c839-11e4-9464-e44a2efa7a25.png)

**Comment by kentcdodds** [comment]
Tried in an incognito window and in Firefox / Safari. No dice. I'm thinking that jsbin is experiencing issues right now...

**Comment by billfranklin** [comment]
having someone else try the link

**Comment by billfranklin** [comment]
maybe it is you, because other people are trying it and see it

**Comment by kentcdodds** [comment]
This wouldn't be the first time I personally had trouble with jsbin :-( Maybe I use it too much? Could you maybe clone it and send me the cloned URL...

**Comment by billfranklin** [comment]
http://jsbin.com/deqeta/1/edit?js,output

**Comment by kentcdodds** [comment]
Wow, this is really sad... Maybe you could switch to codepen :-( I'm super sorry about that.

**Comment by billfranklin** [comment]
http://codepen.io/billfranklin/pen/vEVJPW

**Comment by kentcdodds** [comment]
Ah hah! I know what the problem is! The issue is that you're not reassigning the template's `options` to what comes back from the server, you're actually reassigning your `vm.jsonData` to what comes back from the server which is entirely different. I've made an update to your example that works:

http://jsbin.com/qawawe/edit?html,js,output (hopefully jsbin will work for you, I'm not a huge fan of codepen)

**Comment by billfranklin** [comment]
aha, that worked, thanks!!!  Was driving me crazy....

**Comment by kentcdodds** [comment]
Great! Is there anything I could do to make the API easier to understand so that would have been easier for you to figure out? I want this to be dead simple

**Comment by billfranklin** [comment]
You could actually make this an example.

**Comment by kentcdodds** [comment]
Doing that right now :-) Thanks for the help!

**Comment by kentcdodds** [comment]
And it's live! http://formly-js.github.io/angular-formly/#/example/other/async-select-options-with-controller

**Comment by remy** [comment]
Sorry, missed this coming in. A bug landed in jsbin that's been fixed but
still affecting some users. If I can get usernames I can correct those
affected.

**Comment by kentcdodds** [comment]
My username is: kentcdodds
Still totally love jsbin. Thanks @remy!

**Comment by jesperronn** [comment]
@kentcdodds the URL you pasted for example no longer exists. It has changed to http://angular-formly.com/#/example/other/async-select-options-with-controller 

(`formly-js.github.io/angular-formly` to `formly.com`)

**Comment by kentcdodds** [comment]
Thanks for the update @jesperronn :-) I've updated my comment.

**Comment by uglow** [comment]
Hi @kentcdodds, great example at http://angular-formly.com/#/example/other/async-select-options-with-controller 

My question is, if model.englishMonarchs has an initial value of 'Cnut', how do I get the list to show that as the selected value once the data is returned?

**Comment by NamPNQ** [comment]
@kentcdodds How to use it for case options dependency by parent controller value

```
parent.$watch('abc', function(){
  // I want change options in here
})
```

**Comment by NamPNQ** [comment]
I had solve this case, i set parent = $scope in parent controller, and put watch in field controller

**Comment by suny5** [comment]
Hi,
i'm using this link "http://angular-formly.com/#!/example/other/filter-select" to make a cascading drop-down in ng formly and it bindat first time but when i change value in first drop-down than value of second drop-down is not changing as it changing in link example. can you help me with this or provide me a sample json for Cascaded Select, Thanks.

**Comment by ashwini1081** [comment]
how do I add ability to filter the options? i.e. option 2 gets filtered based on values from option1?
http://jsbin.com/nacazuseka/edit?js,output
