### ISSUE TITLE
templateOptions orderBy and disabled options

### ISSUE THREAD

**Issue by billfranklin** [formly-js/angular-formly#203]
One more multi-part question tonight :)

How can you pass in an orderBy for the select options?  For instance, I want an orderBy:'name' for the options list....I tried adding orderBy on the templateOptions...

Also, is it possible to disable an option in the list?

**Comment by billfranklin** [comment]
a use case for disabling an option is selecting your first and second favorite English Monarch in two different selects....the second select would have the same options but the one selected in the first one would be disabled.

**Comment by kentcdodds** [comment]
Definitely useful. `formlyBootstrap` doesn't support this currently. I definitely recommend that you create your own type for `select` because you obviously have some extra use cases that it's not supporting now. I recommend that everyone create their own types anyway. I've done this and I'll put that below. Maybe it will be instructive (note, it's written in ES6)

```javascript
export default ngModule => {
  const template =
    `<select ng-model="model[options.key]" class="form-control">
      <option ng-if="!to.notNull" value=""></option>
    </select>`;
  ngModule.run((formlyConfig) => {
    formlyConfig.setType({
      name: 'select',
      extends: 'azBase',
      template,
      defaultOptions(options) {
        const forWithFilter = `for item in to.options | azDynamicFilter:to.filter:to.orderBy`;
        let ngOptions = `item[to.valueProp] as item[to.displayProp || 'name'] ${forWithFilter}`;
        const {valueProp, displayProp, options: items} = options.templateOptions;
        if (items && typeof items[0] === 'string') {
          ngOptions = `item for item in to.options | azDynamicFilter:to.filter:'toString()'`;
        } else if (valueProp === null && displayProp) {
          ngOptions = `item as item[to.displayProp] ${forWithFilter}`;
        }
        return {
          ngModelAttrs: {
            [ngOptions]: {
              value: 'ng-options'
            }
          },
          templateOptions: {
            filter: 'orderBy',
            orderBy: 'name',
            displayProp: 'name',
            valueProp: 'value'
          }
        };
      }
    });
  });
};
```

**Comment by kentcdodds** [comment]
If you want to add support for this in `formlyBootstrap`, please feel free to do so! I'm closing this issue though because this is not the formlyBootstrap repo.
