### ISSUE TITLE
Disable a button if formly form not valid

### ISSUE THREAD

**Issue by gboersma** [formly-js/angular-formly#204]
I want to disable a button if the formly field is not valid, as in this example: http://stackoverflow.com/questions/15300067/disable-submit-button-when-form-invalid-with-angularjs

Formly names the form "form", so I try the following in the HTML:

    <formly-form novalidate model="newUserForm" fields="newUserFields">
       <button type="button" ng-disabled="form.$invalid" class="btn btn-default" ng-click="confirmNewUser()">Confirm New User</button>
    </formly-form>

However, this is not working for me. Is this a formly issue?

**Comment by kentcdodds** [comment]
Here's an example of how to do that :-)

http://formly-js.github.io/angular-formly/#/example/other/disable-submit-button

Let me know if you have any other questions :-)

**Comment by gboersma** [comment]
Works perfectly. Thanks so much!

**Comment by zorzysty** [comment]
link update: http://angular-formly.com/#/example/other/disable-submit-button

**Comment by jacobsenanaizabel** [comment]
Thamks for the link update zorzysty ! :')
