### ISSUE TITLE
requires the library apiCheck.js

### ISSUE THREAD

**Issue by maryampashmi** [formly-js/angular-formly#208]
Hi,

I am getting this error recently :
Uncaught Error: angular-formly requires the library apiCheck.js! Please include it

I added following staff in order to solve this issue but it is not possible:
1)bower i -S api-check
2)<script src="bower_components/angular-formly/dist/formly.min.js"></script>
    <script src="bower_components/api-check/dist/apiCheck.min.js"></script>

I am not sure if i should add inside my module or now? and if 'yes', what is the name which i should add it. I would like to say that my angular version is "AngularJS v1.3.13".

Thank you in advance for your response.

**Comment by kentcdodds** [comment]
Hi @maryampashmi! You simply need to include the apiCheck script on the page. If you're using script tags, make sure to add the one for apiCheck:

```html
<script src="bower_components/api-check/dist/apiCheck.min.js"></script>
```

**Comment by maryampashmi** [comment]
I have added  before. i forgot to write it.
 <script src="bower_components/angular-formly/dist/formly.min.js"></script>
    <script src="bower_components/api-check/dist/apiCheck.min.js"></script>

But i got this problem.

**Comment by kentcdodds** [comment]
Make sure that this script tag is BEFORE angular-formly.

**Comment by maryampashmi** [comment]
yes. ;) that was a problem.

Thank you.

**Comment by kentcdodds** [comment]
You're very welcome! Let me know if you have any other questions.
