### ISSUE TITLE
Non-webpacked version for Bower

### ISSUE THREAD

**Issue by dgsmith2** [formly-js/angular-formly#210]
Is there any way you can provided a version of angular-formly that has not been webpacked and it be the version that is distributed via bower?

**Comment by kentcdodds** [comment]
angular-formly is built entirely with webpack in mind. It would be significant effort to remove the webpack dependency. I'm curious to know why you have a problem how it's built...

**Comment by dgsmith2** [comment]
We were attempting to incorporate angular-formly into our produce.  Currently, we do not use a module-based approach for our dependencies.  Instead we use Bower to install them and our build process concatenates the file indicated to be the distributed. Trying to use angular-formly in that same flow does not work.  Admittedly, I had not done due diligence to debug but instead quickly posted a question based upon an assumption/opinion.

In my consumption of other tooling I have seen them laid out to support either AMD or CommonJS, but none to be coded up specifically to webpack (which I have no experience with and for which this may be the norm).  I believed that the use of webpack should be left up to the individual developer.  Case in point in terms of Browserify, I've seen the tooling distributed so that it can simply be referenced in a <script> but supplemental JS/config provided should a developer want to use Browserify.

I very well could be missing something and welcome explanation.  Thanks!

**Comment by kentcdodds** [comment]
I see what you mean. However, I think you've misunderstood. Even though angular-formly is built with Webpack, it's distributed using UMD, which supports AMD, CommonJS, and globals. For example, all the examples on the website are using basic script tags, so angular-formly will expose itself as a global in that case.

Please do some additional research to let me know why it didn't just work for you and I'll see what I can do to help.

**Comment by kentcdodds** [comment]
I'm going to go ahead and just close this. Let me know if you still have issues with this.
