### ISSUE TITLE
scope.showError and options.validation.errorExistsAndShouldBeVisible never get set for "read only" forms

### ISSUE THREAD

**Issue by rbfinch** [formly-js/angular-formly#216]
In forms that can be toggled between read only and editable like this [example](http://jsbin.com/tinoxo/3/edit?html,js), `scope.showError` and `options.validation.errorExistsAndShouldBeVisible` never get set because noFormControl is true when `setFormControl()` is called in formly-field.js so the watcher is never set.

**Comment by kentcdodds** [comment]
Good point... So there are two options here. You can either setup the watcher yourself, which may not be a bad idea, or you could use `ng-hide` instead of `ng-if`. That comes with its own set of issues. What do you think?

**Comment by rbfinch** [comment]
I can see that setting up the watchers myself would be the most efficient solution, but it feels like I'm duplicating Formly code behind the API's back.  I think for the example, changing the `ng-if`s to `ng-show` and `ng-hide` might be best.  I'm assuming that the issue you're referring to is that you'll have the overhead of the ng-models even when the form is in read only mode.

For my application, I think i'll take a different approach.  I have read only and editable versions of a form in two different ui router states, so my forms never change between read only and editable on the fly.  I now have a service that extends field objects by adding `noFormControl: true` when its in a read only state.

**Comment by kentcdodds** [comment]
@rbfinch, do you think this is acceptable or should we work on researching a better solution.

**Comment by kentcdodds** [comment]
@rbfinch, good news! I totally forgot that I did this, but I changed the way that the `formControl` gets added to the `options` based on this use case. It now uses a `$watch` and will add the `formControl` after the fact. The example has been updated to use the latest version and shows that this works :-) http://jsbin.com/tinoxo/edit

Please re-open this issue if you still have problems.

**Comment by rbfinch** [comment]
Nice, looks great!
