### ISSUE TITLE
Make more egghead.io lessons

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#219]
Feel free to thumbs up/+1 this issue if you want to bug me about it :+1: 

Also, feel free to recommend specific topics you'd like lessons on :-)

**Comment by piernik** [comment]
+1

**Comment by rmacteague** [comment]
+1

**Comment by abodacs** [comment]
+1

**Comment by frijswijk** [comment]
+1

**Comment by mtakac** [comment]
:+1:

**Comment by adyba** [comment]
+5

**Comment by kentcdodds** [comment]
Just recorded 4 lessons. Should be up on egghead.io soon! :D

**Comment by akarelas** [comment]
:+1:

**Comment by asadsahi** [comment]
A full course on pluralsight will do? :) :+1:

**Comment by kentcdodds** [comment]
You'll see one of the new egghead.io lessons has been published :-) You'll find all (2) of the lessons on the [documentation website](http://docs.angular-formly.com/v6.1.0/docs/learn-angular-formly) enjoy!

**Comment by kentcdodds** [comment]
P.S. More to come :-)

**Comment by kentcdodds** [comment]
Another lesson is up! http://docs.angular-formly.com/v6.1.0/docs/learn-angular-formly

**Comment by rafaell-lycan** [comment]
+1

**Comment by kentcdodds** [comment]
Hey everyone! There are now 8 lessons on [the egghead.io playlist](https://egghead.io/playlists/7) and the [Learn angular-formly](http://docs.angular-formly.com/v6.3.2/docs/learn-angular-formly) page. Please let me know if there are specific topics you want to know about. Right now I'm using analytics to know which lessons to record next, but it's starting to get pretty even now. Squeaky wheel gets the grease!

**Comment by benoror** [comment]
+1 more on custom templates, templateManipulators, wrappers

**Comment by Olgagr** [comment]
:+1:

**Comment by geoervin** [comment]
+1 more on custom templates, templateManipulators, wrappers

**Comment by timur** [comment]
+1

**Comment by kentcdodds** [comment]
Going to go ahead and close this, but feel free to keep asking for lessons on specific subjects. I'm still listening :-)

**Comment by shorstki** [comment]
I've watched videos and read expressionProperties doc, also checked ngModelElAttrs but still I'm wondering how to change field value after other field changes without watchers in page controller - which looks dirty.
I thought that hideExpression will do the job, but it only hides the field and it's value is still in model. It should be removed then (at least in my case). Is there easy way to do that?

So +1 to any non-trivial (real life) examples

**Comment by DeveBj** [comment]
hey, if you could put a lesson on validating the JSON's in angular formly by angularjs directives mostly a single directive used for checking the 2 fields will be better from my side

**Comment by m-esm** [comment]
+1

**Comment by kentcdodds** [comment]
Hi @DevanB, I'm no longer doing anything with angular-formly, so it's very unlikely that I'll make any more egghead.io lessons about it. Good luck.

**Comment by DevanB** [comment]
Oops wrong user ;) 

@DeveBj - check out @kentcdodds comment above :)
