### ISSUE TITLE
Update ngmodules.org

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#220]
@astrism, the README has changed significantly, could you please update [it](http://ngmodules.org/modules/angular-formly)? Thanks!

**Comment by astrism** [comment]
Updated the readme, ngmodules can't handle the youtube link or relative links but I fixed those. I also looked for a way to transfer/share ownership, doesn't seem to be one, but I think I can handle it for now. Alternatively I can delete the module so you can recreate it.

**Comment by astrism** [comment]
Also the repo is looking great :clap:

**Comment by kentcdodds** [comment]
Thanks! :D
