### ISSUE TITLE
form attribute of formly-form doesn't seem to be set

### ISSUE THREAD

**Issue by ValentinH** [formly-js/angular-formly#222]
I just started using this nice library but I have a problem using the form attr of formly-form.
I want to use it to call the $setPristine() method on it. However, the variable I linked on it is always undefined...

I have noticed it seems to be the same on several examples so it might be a bug. Indeed on [this](http://formly-js.github.io/angular-formly/#/example/field-options/watchers), [this](http://formly-js.github.io/angular-formly/#/example/custom-types/default-options) and [this](http://formly-js.github.io/angular-formly/#/example/custom-types/extending-types) examples, the form area is always empty...

**Comment by kentcdodds** [comment]
Yeah, just barely noticed this too! I broke this in 5.0.0. Fixing now!

**Comment by kentcdodds** [comment]
Thanks for creating the issue. I was just about to create one so I could reference it in my commit. Should be about 10 minutes or so before I have the fix released. Thanks for your patience!

**Comment by ValentinH** [comment]
Awesome! :)

**Comment by kentcdodds** [comment]
Released! Thanks!

**Comment by kentcdodds** [comment]
It's 5.0.1

**Comment by ValentinH** [comment]
Thanks but I don't understand:
- the doc states that form is `The variable to bind the NgFormController to.` but now  it is only the name of the form. Is it normal?

**Comment by kentcdodds** [comment]
Uh oh... Yeah, totally still broken

**Comment by kentcdodds** [comment]
Give me a second... My test wasn't correct.

**Comment by kentcdodds** [comment]
@ValentinH, thank you for your patience! This was pretty irresponsible of me. I promise this is not normal :-)

**Comment by kentcdodds** [comment]
Ok, it's fixed for real in 5.0.2. Once rawgit's cache is updated, all the examples should be fixed. You can `npm install angular-formly` or `bower install angular-formly` (you may need to clear your cache)

**Comment by ValentinH** [comment]
Indeed it works! Thanks for your reactiveness ;)

**Comment by kentcdodds** [comment]
Thank you for YOUR reactiveness in reporting the issue :-) Great! Please let me know if you need any help!
