### ISSUE TITLE
"Place a form attribute on the formly-form element" doesn't work

### ISSUE THREAD

**Issue by joezhouOxford** [formly-js/angular-formly#223]
"Place a form attribute on the formly-form element" doesn't work for "Disable submit button" sample http://formly-js.github.io/angular-formly/#/example/other/disable-submit-button. Tested in IE10, 11, Chrome 41.0.2272.101. 

"Place a name attribute on the form element that encloses the formly-form" method works, however I can't use "form" element in the target platform (SharePoint) which disallow it in content editor web part.

**Comment by kentcdodds** [comment]
Thanks for letting me know. I'm working on a fix. Duplicate of #222.

**Comment by kentcdodds** [comment]
FYI, this is fixed as of 5.0.2. Thanks for your patience!

**Comment by joezhouOxford** [comment]
It is working now. Thank you for the quick response! Great work

**Comment by kentcdodds** [comment]
Thanks! Let me know if you need any additional help!
