### ISSUE TITLE
validation.show is undefined error when resetting the fields

### ISSUE THREAD

**Issue by ValentinH** [formly-js/angular-formly#224]
In order to be able to show the same form for different object, I want to reset the fields to clean them all.
However when doing this, I get the following error after resetting it and trying to fill the fields:
```js
"TypeError: Cannot read property 'show' of undefined
    at Object.scope.$watch.options.validation.errorExistsAndShouldBeVisible (http://rawgit.com/formly-js/angular-formly/master/dist/formly.js:457:49)
```

[Here's the example](http://jsbin.com/fikovekumo/2/edit)

**Comment by kentcdodds** [comment]
Don't have time to explain, but angular-formly doesn't do well when you swap out the `fields` after it has rendered the form. I think that's what you're doing...

**Comment by ValentinH** [comment]
Yes that's what I was doing...

**Comment by kentcdodds** [comment]
I'm thinking that #225 is what you're actually interested in doing, so I'm going to close this one.
