### ISSUE TITLE
Resetting the model doesn't if validation is used and field is invalid

### ISSUE THREAD

**Issue by ValentinH** [formly-js/angular-formly#225]
In another try to reset a form, I do `formData = {}' to clean it.
However, I have noticed that this doesn't work for invalid fields using validation (email for instance)

[Here's an example](http://jsbin.com/tamegatonu/1/edit).
Try to set an invalid value on Email and click "Reset".

**Comment by kentcdodds** [comment]
Yeah, because it's invalid, it technically doesn't have a value, so angular wont update the `$viewValue`. This is an angular problem. You may just have to update the `$viewValue` yourself :-(

**Comment by ValentinH** [comment]
OK I understand. What is the best way to reset a form then?

**Comment by kentcdodds** [comment]
Great question... #168 is wondering about supporting this in the core... I think it may be nice. Basically it would require making a copy of the `model` on first render, then exposing some kind of function (probably on `options`) that could be called to reset the model to its original state. Would have to handle the `model` property of `field`s as well... Do you think that angular-formly is the right place to do that?

**Comment by kentcdodds** [comment]
Alright, I think I've got this fixed. If you could please try this out, that would be great. I've made a beta release that has this feature. Please let me know if this fixes the issue for you. `npm install angular-formly@5.2.0-beta.1`

**Comment by kentcdodds** [comment]
Sorry, should have given an example or docs. Here you go!
http://angular-formly.com/#/example/form-options/reset-model

**Comment by ValentinH** [comment]
I think they are 2 cool options! ;) 

However, with this beta, my code broke! :D But it was because I was using the forms inside a popup toggled with ng-show, and my model was null at the beginning (I was using the null value to show/hide the popup). So I had the idea to use ng-if instead, and miraculously, my previous problem of models not being reset was gone even without using resetModel()! ^^

Then I am wondering if the resetModel method wouldn't be a good place to reset the validation.show flags if they were set after the form initialization. What do you think?

**Comment by kentcdodds** [comment]
Ok, that's good to know. It shouldn't break if your model is null. I'll fix that. `resetModel` shouldn't impact the actual field itself. That wouldn't make sense in the api. And I was thinking about adding a `resetFields` method, but I don't think that would really make sense either...

Let me fix the null problem and then I think we're good to release this officially. What do you think?

**Comment by ValentinH** [comment]
Yeap it is OK for me.

**Comment by kentcdodds** [comment]
There you go. Officially in 5.2.0!

**Comment by kentcdodds** [comment]
Update, use 5.2.1 instead...

**Comment by SagiMedina** [comment]
Hi @kentcdodds, any news about resetFields method? 
I really need the option to swap my fields... 
Think about it, that would be amazing! we could have 20 dynamics forms and only html line.
The formFields will be update via controller...

**Comment by kentcdodds** [comment]
@SagiMedina, this is being tracked in #246. Unfortunately it's not as easy as you might think...

**Comment by SagiMedina** [comment]
Thanks a lot for your fast response! 
I'll check...
btw thank you for this amazing module!!
