### ISSUE TITLE
Wizard Directive would be very helpful

### ISSUE THREAD

**Issue by frijswijk** [formly-js/angular-formly#226]
Love Formly but I need also Wizard Forms and it would be awesome if a sample or even better an extension to allow Angular-Formly to create Wizards.

The wizard should have 
- validation per step, i.o. disable next button / showing message if fields are not completed.
- hiding/showing steps based on conditions with previous filled in fields (model values)
- skipping steps (hided steps should be skipped anyway)
- optional finish button on last step
- wizard in wizard (on a step showing another wizard)
- Different layouts (tab, steps, pills, progress bar, collapsable sections, etc.
- JSON configurable

there most likely more options to add.

**Comment by kentcdodds** [comment]
I think that you could very easily combine angular-formly with [angular-wizard](https://github.com/mgonto/angular-wizard). Let me see if I can make an example sometime. Or, if you want to, feel free to [try making one yourself](http://jsbin.com/panovu/edit?html,js,output)

**Comment by kentcdodds** [comment]
Added an example of integrating this with [angular-wizard](https://github.com/mgonto/angular-wizard) by @mgonto: http://angular-formly.com/#/example/other/angular-wizard

I think that's the best we can do right now.

**Comment by txa1562** [comment]
When you were creating your example, did you run into the issue where the contents of your step arrays was getting wiped out?  When mine loads, the arrays are empty, but when I take the formly-form outside the wizard directive, it loads just fine.  Also, when I hard code form fields into the wizard, it works fine.  It's just when I use formly and wizard in conjunction that it gets wiped clean.
