### ISSUE TITLE
Add angular-formly to devdocs

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#229]
[DevDocs](http://devdocs.io/) is totally awesome and allows for offline documentation (as requested by @mikeerickson). We have [approval](https://github.com/Thibaut/devdocs/issues/190) to make a PR to the repo. Anyone is welcome to do this (and I'd really appreciate it!), especially someone with Ruby experience!

[Here's how](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs)

Let me know if you're going to do this. Would be awesome!

**Comment by mikeerickson** [comment]
@kentcdodds I am in ;-)  Seeing as I had the request, seems it would benefit me so may as well contribute eh!

**Comment by kentcdodds** [comment]
:+1:

**Comment by kentcdodds** [comment]
ping @mikeerickson :-) weekend project? ;-)

**Comment by mikeerickson** [comment]
@kentcdodds In fact I was gonna get going on this tomorrow!  just cleaned a bunch off my plate this past couple weeks so have some time for measly OSS projects ;-)

**Comment by mikeerickson** [comment]
pong!  @kentcdodds thx for the ping though ;-)

**Comment by kentcdodds** [comment]
ping? :-)

**Comment by mikeerickson** [comment]
@kentcdodds Sorry for delay mate, always seem to get bombarded on day I plan to get started on this.   So, I will allocate some good time on Sunday to making this happen :-)

But you need to quit adding features so fast!

**Comment by kentcdodds** [comment]
:P, I'll stop bugging you about it. I appreciate all that you can do!

**Comment by mikeerickson** [comment]
@kentcdodds No, keep bugging me, it keeps the pressure on to get this done.  I will get it done! ;-)

**Comment by mikeerickson** [comment]
@kentcdodds I will be doing the side-by-side comparison as well in a separate blog post

**Comment by kentcdodds** [comment]
:+1:

**Comment by mikeerickson** [comment]
@kentcdodds still alive, just wrapping up some client work and then I will move my efforts to formly

**Comment by kentcdodds** [comment]
:+1:

-Kent C. Dodds

**Comment by kentcdodds** [comment]
@mikeerickson maybe this weekend? :-)

**Comment by mikeerickson** [comment]
@kentcdodds perhaps, seeing as I will be working on a project which is using formly a lot - I will need fresh docs ;)

**Comment by kentcdodds** [comment]
:+1: would love to get offline docs working. That'd be an awesome addition to the library.

**Comment by kentcdodds** [comment]
Maybe this weekend @mikeerickson? :-)

**Comment by benoror** [comment]
+1 (also for the sake of ping'ing @mikeerickson & trying: https://chrome.google.com/webstore/detail/github-%2B1s/lddfkkebajnpiicnpfamebilmhamkeme :smile: )

**Comment by kentcdodds** [comment]
I'm cleaning up issues and it doesn't look like this one's going to happen. Feel free to prove me wrong!

**Comment by benoror** [comment]
https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs

**Comment by brutalcrozt** [comment]
@benoror  i had no ruby experience dude, but i maybe i have to learn it?
@kentcdodds the left pane on angular-formly.com feel confusing for me, really.
what if change the formly doc like angular documentation?
