### ISSUE TITLE
Angular's ngMessages

### ISSUE THREAD

**Issue by delaman** [formly-js/angular-formly#23]
Any chance ngMessages could be worked into this wonderful library?

https://docs.angularjs.org/api/ngMessages/directive/ngMessages

Thanks

**Comment by kentcdodds** [comment]
This is definitely a template-specific item. If you want support for `ngMessages` you'll need to implement templates that make use of them (using the `options.formControl` that formly adds to your template's scope) or submit a PR to the template library that you're using.
