### ISSUE TITLE
$scope.showError doesn't work with angular 1.2

### ISSUE THREAD

**Issue by koenweyn** [formly-js/angular-formly#231]
When working with angular 1.2, `$scope.showError` does never get set to true (except when `validation.show` is used).
Formly uses `$touched` which is absent in angular 1.2.

I propose to change the logic for showError to:
```
return scope.fc.$invalid && (scope.fc.$touched || scope.fc.$dirty);
```
or (code more convoluted, but no change at all for angular 1.3)
```
return scope.fc.$invalid && (scope.fc.$touched || (angular.isUndefined(scope.fc.$touched) && scope.fc.$dirty));
```
I can send a PR your way if you agree.

**Comment by kentcdodds** [comment]
I didn't realize that 1.2 didn't support `$touched`. Nice catch. Thanks! I like the second recommendation. Would love the PR :-)
