### ISSUE TITLE
Browser supported?

### ISSUE THREAD

**Issue by monkeymonk** [formly-js/angular-formly#234]
Could you please list somewhere the browsers that `angular-formly` support ?

**Comment by stefanzweifel** [comment]
Formly supports the latest browsers (even IE8). You find more information in the [documentation](http://docs.angular-formly.com/v5.1.1/docs/support-ie-8).

**Comment by monkeymonk** [comment]
I hadn't seen that part in the documentation... my bad! Σ(°Д° )

Thank you @stefanzweifel ! ;-)

**Comment by rjacquemin** [comment]
Hi all, 

I have some troubles with IE8, IE9.
Moreover  doc is not available 

http://docs.angular-formly.com/v6.3.2/docs/support-ie-8
http://docs.angular-formly.com/

**Comment by kentcdodds** [comment]
The docs are available for me...

![screen shot 2015-06-09 at 3 28 27 pm](https://cloud.githubusercontent.com/assets/1500684/8070098/334ee9e2-0ebc-11e5-84b1-4320eafe4ec5.png)
