### ISSUE TITLE
Make Angular a regular dependency instead of a peerDependency

### ISSUE THREAD

**Issue by pmowrer** [formly-js/angular-formly#235]
Having declared Angular `1.4.0-beta.x` as a dependency of our project, installing `angular-formly` via NPM is impossible due to its peerDependency on Angular `1.x`. We're living on the edge and using the latest Angular beta, and while we understand `angular-formly` isn't explicitly compatible, we're OK taking that risk. However, peerDependencies doesn't allow us to make that choice. It's a great concept, but it's currently often more harmful than helpful, as `npm` has itself acknowledged:

https://github.com/npm/npm/issues/6565#issuecomment-74971689

Until peerDependencies throw warnings instead of installation-preventing errors (as proposed for `npm 3`), you may want to reconsider whether they're helpful to include in `angular-formly`.

**Comment by kentcdodds** [comment]
@pmowrer, thanks for the issue. I had intended on fixing this because I was upgrading my own app to the beta versions, but I forgot. I'll have this fixed shortly.

**Comment by kentcdodds** [comment]
Just ran:

```
~/Desktop
😄  $ npm i api-check
api-check@6.0.11 node_modules/api-check
~/Desktop
😄  $ npm install angular@1.4.0-beta.6
angular@1.4.0-beta.6 node_modules/angular
~/Desktop
😄  $ npm install angular-formly
angular-formly@5.1.2 node_modules/angular-formly
~/Desktop
😄  $ 
```

Let me know if you have problems.

**Comment by pmowrer** [comment]
Wow, thanks for the extremely quick fix @kentcdodds! Verified it works on our end as well.

**Comment by kentcdodds** [comment]
Glad it works! Let me know if you have any questions!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
