### ISSUE TITLE
Broken examples due to new apiCheck.js release

### ISSUE THREAD

**Issue by tourist** [formly-js/angular-formly#237]
Hi,

I'm new to angular-formly and was looking into some examples today on [angular-formly.com site](http://angular-formly.com) and wanted to let you know that [examples](http://angular-formly.com/#/example/intro/introduction) are broken since some hours probably due to [new release](https://github.com/kentcdodds/apiCheck.js/commit/f5d2baa1d8e38af6008beed07a0350c05bcd34d0) of apiCheck probably as ```dist``` files name changed - at least that's what it complaining first.

**Comment by kentcdodds** [comment]
Thanks for letting me know. apiCheck just had a breaking change and I forgot that all the examples run off of master. I'll go fix those now!

**Comment by kentcdodds** [comment]
Fixed. Thanks again! I really need to develop a better way to keep all of the examples dependencies in one place. It may be nice to have them all run on the latest *stable* version somehow...

**Comment by tourist** [comment]
Thanks to you for ultra quick response and maintaining this nice looking library and all your other Angular activities as well... time for some squats! ;)

**Comment by kentcdodds** [comment]
:smiley: haha! which talk did you see?

**Comment by tourist** [comment]
"JSON Powered Forms" from NG-NL 2015 - not live sadly (via YT) but squats are done ;)

**Comment by kentcdodds** [comment]
Haha! The exercise lives on! Thanks for using angular-formly. Please let me know if you have any other needs!
