### ISSUE TITLE
How setup a default validation for a field type?

### ISSUE THREAD

**Issue by bygiro** [formly-js/angular-formly#240]
is It possible to setup a default custom validation at the field TYPE level?
I saw I can setup it at the FIELD level, but I don't see how to do it at the TYPE level, am I missing something?

The main idea would be to just create custom validations at the field TYPE level, so it would be possible to use the FIELD level to just add few validation parameters in the "templateOptions" obj, then manipulated by the default custom validation functions in the specific field type.
thanks in advance for the collaboration.

**Comment by kentcdodds** [comment]
Yes, this is totally possible! And I recommend doing things this way too! :-) Personally, I use the `data` property for the parameters, but you can do it however you like. You'll use [`defaultOptions`](http://docs.angular-formly.com/v5.2.1/docs/custom-templates#formlyconfig-settype-options) which can be an object or function. Here's [an example](http://angular-formly.com/#/example/custom-types/default-options).

Please reopen this issue if you need more help.

**Comment by bygiro** [comment]
THANK YOU a lot!, I don't know why I didn't pay attention to "defaultOptions", it seems so obivous! :-)
You are doing a very good job with FORMLY. It's very flexible to any customizations!
Data property would probably be the right place. thanks again!
