### ISSUE TITLE
The example site does not load

### ISSUE THREAD

**Issue by amitmawkin** [formly-js/angular-formly#241]

**Comment by kentcdodds** [comment]
It's loading fine for me. But you're not the first one to mention issues today. I wonder if iwantmyname.com is experiencing issues... Can you look at the network tab and see if there are DNS issues?

**Comment by amitmawkin** [comment]
The error message I am getting is

The server unexpectedly closed the connection. Looks like it fails at the URL below when seen in Chrome

https://jsbin.com/kunaho/embed?output

Thanks,
Amit

**Comment by kentcdodds** [comment]
Wait, just to confirm. For you, the site is actually working, but the embedded examples are failing, is that right?

**Comment by amitmawkin** [comment]
That’s correct.

**Comment by kentcdodds** [comment]
Ok, then it sounds like your computer is having difficulty with jsbin... This could be the result of a few issues. Perhaps your IP address has been blacklisted (that's happened to me before). ping @remy

**Comment by amitmawkin** [comment]
got it, I think the corp proxy blocked jsbin. You can close the issue as I can see the examples on my personal mac.
