### ISSUE TITLE
multi input field model is null

### ISSUE THREAD

**Issue by ddesign84** [formly-js/angular-formly#248]
jsbin:
http://jsbin.com/jifeco/1/edit?html,css,js,output

default: 
```
model:
{
  "urls": [
    "url1",
    "url2"
  ]
}
```

modify value:
```
model:
{
  "urls": [
    null,
    null
  ]
}
```

**Comment by kentcdodds** [comment]
I'm guessing that you figured out the issue because you closed it correct?

**Comment by ddesign84** [comment]
yes, Think you!
