### ISSUE TITLE
Expose extends property to template manipulators

### ISSUE THREAD

**Issue by ckniffen** [formly-js/angular-formly#251]
Currently the options object that is passed into a template manipulator does not specify which type(s) that field extends.  This makes it difficult to have an abstract type which needs to have template manipulation occur.

I have been trying to decide how to go about doing this an submitting a pull request.  One option is that a field stores on it an array of the types it extends and then the template manipulator can call indexOf on that array.

**Comment by kentcdodds** [comment]
Hmmm... Sounds interesting. Do you think that you could provide an example use case for me so I understand what you're trying to accomplish.

**Comment by kentcdodds** [comment]
By the way, I'm thrilled that you're using this feature. I'm pretty sure it's one of the coolest features of angular-formly that few people understand/know how to use. It's pretty dang powerful.

**Comment by ckniffen** [comment]
I work on a team that develops tools used by a number of different apps and I have a abstract select type that other teams extend that internally leverages ui-select.  An example of this is we have `user` and `userGroup` types which extend `selectResource`.  All types that extend selectResource need to run through a templateManipulator.  I will work on creating a plnkr of this to better demonstrate the use case.

**Comment by kentcdodds** [comment]
Ah, I see what you're saying... One second...

**Comment by kentcdodds** [comment]
Check it out :-) http://jsbin.com/xeguxi/edit

**Comment by ckniffen** [comment]
That will work perfect.  I forgot about the getType method on formlyConfig.  Thank you.

**Comment by kentcdodds** [comment]
Note! For the love of everything good in the world. Don't go deeper than 3 levels of extends :-)
