### ISSUE TITLE
FormId is not unique when inside of an ng-repeat

### ISSUE THREAD

**Issue by ckniffen** [formly-js/angular-formly#252]
I have been unable to find a fix for this problem.  It seems the root cause is that the template function for the formly-form directive is only called once per ng-repeat directive instance.

I created the following failing unit test.

```
    it(`should not allow sibling forms in an ng-repeat to override each other on a parent form`, () => {
      compileAndDigest(`
        <form name="parent">
          <div ng-repeat="forms in [1, 2] track by $index">
            <formly-form></formly-form>
          </div>
        </form>
      `);
      expect(scope.parent).to.have.property('formly_1');
      expect(scope.parent).to.have.property('formly_2');
    });
```

**Comment by kentcdodds** [comment]
Dude, you're awesome. Thanks! This will be in the next beta release of 6.0.0. Thanks!

**Comment by kentcdodds** [comment]
This is a tough one... What version of angular are you running?

**Comment by kentcdodds** [comment]
Ok, this is the best I can do. And it only works in angular 1.3 ... Will that work for you?

```javascript
it(`should allow the user to specify their own name for the form`, () => {
  compileAndDigest(`
    <form name="parent">
      <div ng-repeat="forms in [1, 2] track by $index">
        <formly-form model="model" fields="fields" bind-name="$parent.$index"></formly-form>
      </div>
    </form>
  `);

  expect(scope.parent).to.have.property('formly_0');
  expect(scope.parent).to.have.property('formly_1');
});
```

**Comment by kentcdodds** [comment]
Doing this would be possible with angular 1.2, but it would involve completely recompiling the entire template once the correct ID was generated. This would be enough of a performance hit that it wouldn't make it worth it I think. I'm just hoping that you're using 1.3 right now... :-)

**Comment by kentcdodds** [comment]
Note, the way it works is it sets the `name` attribute of the `ng-form` to `{{::'formly_' + ${attrs.bindName}}}`. The reason this only works in >= 1.3 is in 1.2, the `name` attribute can't be dynamic. :-(

**Comment by kentcdodds** [comment]
Here's the implementation: https://github.com/formly-js/angular-formly/commit/94f82860310c5ae0d3ec17ea0c4427b0d252d6b4

Let me know what you think, or if you think there's another way to accomplish this...

**Comment by ckniffen** [comment]
I am currently using angular 1.3 and we have not encountered this causing issues just yet.  I noticed it while debugging something unrelated and had remembered that during a previous version there was a fix for this and realized this was an uncovered edge case.  Your solution is fine.

**Comment by kentcdodds** [comment]
Ok great. I'll merge it in then. Thanks for providing a failing test. That was awesome.

**Comment by kentcdodds** [comment]
This is now part of 6.0.0-beta.10. Hoping to get out of beta soon. Still working out a few kinks.

**Comment by kentcdodds** [comment]
This is closed as illustrated in the test! Let me know if you have trouble!

**Comment by theotherp** [comment]
I still have this problem.

It even occurs in your example here: http://angular-formly.com/#/example/advanced/repeating-section
![Screenshot](http://i.imgur.com/uJQ98vS.png)
