### ISSUE TITLE
New Example:

### ISSUE THREAD

**Issue by gowram** [formly-js/angular-formly#256]
I would like have an example that demonstrates: 

1.  dynamically add remove items in a form, kind of todo model. 

2. hierarchical forms for one to many models.

```
 {
    "products":[
        "item1":["price1","price2","price3"],
        "item2":["price1","price2","price3"],
        "item3":["price1","price2","price3"],
        ]
 }

```

**Comment by kentcdodds** [comment]
how's this? http://angular-formly.com/#/example/advanced/repeating-section

-Kent C. Dodds

**Comment by gowram** [comment]
there is an issue with this example, 
 http://angular-formly.com/#/example/advanced/repeating-section

if I enter 1st set of investment details, it's value repeated in 2nd set as well.
basically, it's using same "key" name.

It's not possible to enter multiple investment plan.

**Comment by kentcdodds** [comment]
Thanks. The example has been updated. Let me know if it is not sufficient.

**Comment by abodacs** [comment]
why 'investments' key must be defined in vm.model to show the form ?

**Comment by kentcdodds** [comment]
@abodacs That key is specific to that example. But it's because the key for the field, that's why it needs to be on the model.

**Comment by abodacs** [comment]
@kentcdodds try to change it to vm.model = {};??

**Comment by kentcdodds** [comment]
This is a bit of a poor example. But part of the repeatSection type depends on their being a value initially because it copies the previous section to make the next one. It fails when there's not an existing previous value. You could easily alter the type so this doesn't happen.

**Comment by kentcdodds** [comment]
I updated the example. Go ahead and play around with it. Should work now.
