### ISSUE TITLE
New Example:Validation Messages

### ISSUE THREAD

**Issue by asadsahi** [formly-js/angular-formly#260]
I would like an example that demostrates: how to simply show validation messages for input fileds if required, minlength etc by formly. Can't find a simple example where when set required in the formly controller config, the messages will appear. As mentioned in docs that it is based on ngMessages, I can't see a simple example on the formly site, which shows ngMessages for any form.

**Comment by kentcdodds** [comment]
Let me know if this one's not enough :-) http://angular-formly.com/#/example/intro/introduction2

**Comment by wfsm** [comment]
@kentcdodds This example is no longer exist. Any example for different validation, like required, not match min/max length, two field are not match?

**Comment by kentcdodds** [comment]
@wfsm, sorry, I renamed it: http://angular-formly.com/#/example/intro/codementor

**Comment by kentcdodds** [comment]
oh, and here's an example of two fields not matching: http://angular-formly.com/#/example/other/matching-two-fields

For min/max length, you'd simply use:

```javascript
{
  type: 'input',
  key: 'whatever',
  templateOptions: {
    minlength: 4,
    maxlength: 10
  }
}
```

**Comment by jayasrinagrale** [comment]
All these links are redirecting back to http://angular-formly.com/#!/

**Comment by joer33304** [comment]
Most links found on the web for formly do work if one simply replaces /#/ by /#!/
