### ISSUE TITLE
allow choice of 'if' / 'hide' / 'show 

### ISSUE THREAD

**Issue by gmsewell6** [formly-js/angular-formly#262]
It'd be really great to be able to specify which visibility directive to use for showing/hiding a form field. The 'hide' property always corresponding to ng-if can cause popping in the UI

**Comment by kentcdodds** [comment]
Was actually thinking of doing this already. Will be in 6.1.0 :-) in a few moments. Thanks for the issue!

**Comment by kentcdodds** [comment]
This is now released! `npm install 6.1.0` See the docs:

http://docs.angular-formly.com/v6.1.0/docs/formlyconfig#extras
http://docs.angular-formly.com/v6.1.0/docs/formly-form#attributes

Thanks again :+1:

**Comment by gmsewell6** [comment]
awesome! looking forward to trying it out. thanks for the quick response!

**Comment by kentcdodds** [comment]
@gmsewell6, please let me know what you think when you've tried it out. Thanks!
