### ISSUE TITLE
Error messages with angular-formly

### ISSUE THREAD

**Issue by jonricaurte** [formly-js/angular-formly#263]
I noticed for errors you have to have something like this:

{
    "key": "picky",
    "type": "customInput",
    "templateOptions": {
      "label": "Picky field...",
      "placeholder": "This is required and has a maxlength of 5 and minlength of 3",
      "required": true,
      "maxlength": 5,
      "minlength": 3
    }

What happens if I had another one that had a different maxlength and minlength, would I be able to reuse the object above? Also, what if I want a required error message to show without the min and max length like how you can do it using ng-messages?

**Comment by kentcdodds** [comment]
so, the placeholder can be whatever. That part isn't dynamic. But you can make it dynamic if you want to. And yes, you could reuse the object above. angular-formly is all about keeping your code DRY, so you could create a custom `type` that defaults the maxlength and minlength values as well. It's extremely powerful. Come at me with a specific use case and I can explain or show how you'd accomplish it with ease :-)

**Comment by kentcdodds** [comment]
Going to go ahead and close this due to lack of activity. Please feel free to open it again if you have further questions/concerns/need help.
