### ISSUE TITLE
Error: There is no type by the name of "input"

### ISSUE THREAD

**Issue by jaymorgan** [formly-js/angular-formly#264]
I'm just getting into this and I'm getting this error.

```javascript
Error: Formly Error: There is no type by the name of "input": {"key":"firstName","type":"input","templateOptions":{"required":true,"label":"First Name","foo":"hi"},"data":{},"validation":{"messages":{}}}.
```

I'm following the setup and examples as best I can and I'm still not getting off the line. Is this a typical thing? Am I missing something?

**Comment by kentcdodds** [comment]
Make sure that you either include a template library or create your own type.

http://docs.angular-formly.com/v6.1.0/docs/custom-templates


On mobile otherwise I'd be more helpful. Let me know if you need more help and I'll help when I get on later.

**Comment by jaymorgan** [comment]
Great, thanks man. That worked. I would suggest adding that to the "Getting Started" explanation.

**Comment by kentcdodds** [comment]
I'll reopen this to remind me. Thanks!

**Comment by kentcdodds** [comment]
Added. Thanks again!
