### ISSUE TITLE
JSBin template broken. Unable to follow contribution guidelines.

### ISSUE THREAD

**Issue by swifthand** [formly-js/angular-formly#265]
Trying to be a good open source citizen and use the [contribution guidelines](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md), but [the requested JS Bin template](http://jsbin.com/biqesi/edit?html,css,js,output) seems to be broken?

It is worth noting that all other JS Bin examples on the angular-formly site work for me, so it is (probably) not an issue with my browser environment (i.e. version of Chrome or what-have-you).

Did my best to modify it for the better part of 40 minutes, but never could get JS Bin to do anything except say `"error"` and `"Script error. (line 0)".`, nor did angular ever start interacting with the DOM. The screenshot below is me re-opening the JS Bin to an unmodified state (i.e. without my various, futile attempts to fix).

![jsbin_script_error_line_0](https://cloud.githubusercontent.com/assets/948048/7355149/addb50ea-ece5-11e4-9689-c167fcdf8aff.png)

It is worth noting that I am not very versed in the myriad ways that JavaScript can break, never mind Angular. There might be a one-line fix somewhere that I overlooked, but as it stands I cannot use the JS Bin to follow the [contribution guidelines](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md) and submit an issue.

**Comment by swifthand** [comment]
As for the issue I want to submit in the first place, I will still attempt to reproduce it via JS Bin by stripping out and replacing content from one of the working examples over at [the examples page](http://angular-formly.com/#/).

**Comment by kentcdodds** [comment]
I fixed the template. Could you try it again? Thanks for your patience!

**Comment by kentcdodds** [comment]
Please close this issue if the template works for you :-)

**Comment by swifthand** [comment]
It does work now. Thanks!

**Comment by kentcdodds** [comment]
Thank *you* for letting me know it was broken :-)
