### ISSUE TITLE
Cannot use both name attributes and validations in custom templates.

### ISSUE THREAD

**Issue by swifthand** [formly-js/angular-formly#266]
**Alternative Title: Validation behavior for custom templates is opposite of documentation.**

**[Demonstration JS Bin](http://jsbin.com/gelamahiru/1/edit?html,js,output)**

I have been using angular-formly for about a week to make some truly beautiful forms for our company's first ever attempt at a unified form style with a modern UX. I'm very grateful for this project and very excited to be using it!

However, I have been unable to submit form data properly, because use of the name attribute in a custom template functions in the exact opposite way that the documentation seems to suggest. Instead of enabling validations and the `formControl` property, it breaks them!

Specifically [on this page about validation](http://docs.angular-formly.com/v6.1.0/docs/validation), regarding custom templates:
>Make sure to specify a name on any ng-model in your custom templates to ensure that the formControl is added to the options.

This is speculation on my part, but formly seems to set not only the id of its fields to things like `formly_1_my-custom-template_field_key_0` but also the names, by default. I figure that the majority of people are submitting via the `$http` service, and so do not see this or are not affected by it?

I have searched for through previous issues for anything involving "name" and "name attribute" but nothing seemed to address this. Am I mis-interpreting the documentation somehow?

**Motivating Use Case**
We are not using Angular for a single page application, and need to perform a normal HTML form submission with full page reload. Thus I need to be able to control a field's name attribute.

**Comment by kentcdodds** [comment]
I haven't read through everything yet, but can I just say, this is a terrific bug report. Thank you!

**Comment by kentcdodds** [comment]
Ah! You're right! The docs are out-dated. I'll update that as soon as possible...

So, angular-formly now comes equipt with a sweet new feature called the [`ngModelAttrsTemplateManipulator`](http://docs.angular-formly.com/v6.1.0/docs/ngmodelattrstemplatemanipulator) which will automagically add a bunch of attributes based on the config for the field. What's cool about this is it makes creating custom templates a breeze and saves on the amount of watchers necessary for a particular field.

One thing to note about this manipulator is that (with a few exceptions) it will not overwrite attributes that already exist in the template. So, if you specify your own name (for example) then it should not override your own name. I haven't looked at your example yet, but if this behavior is not what you're seeing then that is definitely a bug :-)

I'll look at your example, but let me know if this clears anything up for you.

**Comment by kentcdodds** [comment]
Alright! You found a real bug! I need to do some work to get it fixed. May be a day or two. But here's [a workaround](http://jsbin.com/cejoru/edit) for now :-) Thanks for using angular-formly! I'll let you know when the bug is fixed.

**Comment by swifthand** [comment]
Thanks so much! I am in the process of trying to work my way through the docs on `ngModelAttrsTemplateManipulator` but will try to apply the workaround first.

**Comment by kentcdodds** [comment]
The actual solution will be a fix in `formly-field`, not in the template manipulator. The issue is that the `formly-field` is watching the field `id` rather than respecting the possibility that a user could specify a custom name.

**Comment by kentcdodds** [comment]
Alright, updated the docs! Now to fix the bug!

**Comment by kentcdodds** [comment]
I think I've got it! Master has been updated and your bug reproduction is working as expected now. Let me know if I've missed anything. Once I get the ok from you, I'll cut a release! Thanks!

**Comment by swifthand** [comment]
Installed from master and removed the workarounds. Specifying names now works for all of my custom templates and the input types that I found issues with before (so I've tested pretty much everything besides radio buttons).
