### ISSUE TITLE
Creating a grid based form in Formly

### ISSUE THREAD

**Issue by rborman** [formly-js/angular-formly#267]
Most form examples have a label above the field, but I'm trying to create a grid based form where labels are placed left of the input and are right justified.

I have played with Zurb Foundation for Apps (only used the css part for now) and created a rudimentary example with flexbox, where labels and inputs are placed in separate grid blocks and rows are wrapped and can have 'line breaks' (essentially filling the remaining space by giving the last input a large right margin - this is not included in Foundation so I added custom 'medium-after-x' css classes). See http://plnkr.co/edit/89HIP7 for an AngularJS (but not Formly) example. Maybe there are better solutions, although I have not found one that used flexbox (which I prefer for other reasons).

When I try to translate this to Formly, there seems to be a problem. A Label and corresponding input are in separate blocks and these blocks must be continuous without using a parent div. I used the ng-repeat-start en ng-repeat-end directives to loop through a fields array and creating two divs per field. Most examples in Formly use a parent div per field for scoping and repeating (through the formly-form directive).

I've looked at issue 173 and the 'Advanced Layout' example but afaics there is still a parent element per field.

Can my solution (with continuous divs) be translated to Formly or does anybody know a better flexbox solution that can be translated to Formly?

**Comment by kentcdodds** [comment]
There is no solution that I have found in the open source world. But I can tell you that in my app, we actually don't use the pre-built templates and have custom templates. We use bootstrap for our columns and simply have a specified column width for all of our labels and our fields. And labels are a part of the fields via a wrapper. This is the result.

![screen shot 2015-04-27 at 3 13 43 pm](https://cloud.githubusercontent.com/assets/1500684/7358028/0afcedba-ecf0-11e4-89e6-1a5050aed636.png)

I'll make an example for this when I have time. It should be trivial to accomplish using any css grid system (including flexbox).

**Comment by rborman** [comment]
Hi Kent! Thanks for the (extremely) quick reply. The way you run Formly is quite impressive.

**Comment by kentcdodds** [comment]
You're very welcome! And thanks! I want formly to be as helpful as possible and it's rewarding to me when I see it being helpful to other developers.

I take it that you don't need the example right away based on you closing this issue?

**Comment by rborman** [comment]
Actually, I could use the example but did not want to pollute issue tracking so I closed the issue and wait for the example to appear on the site. Should this issue remain open?

**Comment by kentcdodds** [comment]
Actually could you move it to the [angular-formly-website](https://github.com/formly-js/angular-formly-website) repo? Thanks!
