### ISSUE TITLE
hide issue

### ISSUE THREAD

**Issue by pedrocatre** [formly-js/angular-formly#271]
If I specify the hide property in the field then the expression will not be able to override this afterwards.

Example:

```javascript
{
        key: 'text2',
        type: 'input',
        hide: true,
        templateOptions: {
          label: 'Hey!',
          placeholder: 'This one is disabled if there is no text in the other input'
        },
        expressionProperties: {
          hide: '!model.text',
          'templateOptions.disabled': '!model.text'
        }
      }
```

I have hide: true and then an expression property that sets hide if the model has text. But the field will not appear.

You can check it out here: http://jsbin.com/yumasegefi/1/edit?html,css,js,output

if you remove the hide: true from the example then when you put data on the input box the second one will show up.

The reason I need to do something like this is that I have a huge multistep form that is slow to initialize on steps that have many fields, and in one part I have 3 possible headings and only one will remain. The current behaviour is that the 3 headings appear and then 2 of them disappear. I would rather have them all hidden by default and show only one when angular and angular formly finish doing their thing.

Thanks! Great library! it is saving me a lot of work and it has an amazing API. Were it not for angular performance issues this would be perfect.

**Comment by kentcdodds** [comment]
I'll answer better later when I get a second, but the problem is with the
ng-if that formly uses on the fields. Look at changing that to ng-show
using the hide-directive attribute.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by pedrocatre** [comment]
Can't :( I really need to use ng-if because there are many dependencies and many fields hidden in the same step of the form. If I use ng-show all their binding will be active if though they are not being displayed.

I already have some performance issues (specially with older browsers and weaker machines) so I really can't afford to use ng-show.

**Comment by kentcdodds** [comment]
That's fine. Switch from expression properties to watcher.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Note, obviously, you've got some serious performance considerations, so you may need to take things at a bit of a different approach. If you have a bunch of fields with their own hide conditions, instead of paying for a watcher for each of those, create your own watcher and respond to model changes yourself (by setting `hide` on the appropriate fields).

It's not as clean and neat, but that's the reality of the performance situation. :-(

**Comment by kentcdodds** [comment]
So I've now had time to actually read through your issue. For the headings, you might consider not using angular-formly and just coding that up yourself in the HTML. This would allow you to using `ng-if` without a problem.

**Comment by pedrocatre** [comment]
These headers can appear in the middle of the form fields, that is one of the reasons I don't hardcode them. The second reason is that it is very appealing to have the entire form described in one JSON. Also because I intend to reuse as much as I can for future forms that are very different but have similar requirements, and I want to be able to build those forms very fast.

But is this hide thing a bug?


Also regarding what you said "Note, obviously, you've got some serious performance considerations, so you may need to take things at a bit of a different approach. If you have a bunch of fields with their own hide conditions, instead of paying for a watcher for each of those, create your own watcher and respond to model changes yourself (by setting hide on the appropriate fields)." You mean creating watchers outside of the JSON form configuration right?

**Comment by kentcdodds** [comment]
@pedrocatre, yes, I do mean creating watchers outside of the JSON. This is because there's a watcher created for every time you have a `watcher`. And they all watch the same thing. It's just some extra overhead that may not be necessary.

The hide thing is not a bug. Basically, when the field is hidden behind the ng-if, it never compiles which means the `expressionProperties` never get set up and cannot run.

I may be able to add a `hideExpression` attribute which could make life a little bit easier for you. It would not be a normal formlyExpression though. It could be a function or a string, but it would be evaluated on the `formly-form` not the `formly-field` so you wouldn't have access to the same stuff... But it should be enough for what you want (it'll have the model for example).

**Comment by pedrocatre** [comment]
hideExpression attribute would be nice thanks! I'm still going to think how I could do this with the existing mechanisms. One thing that comes to mind would be to have only one header instead of 3 and just change its text. It is less easy to configure and see, but it would probably work and I would have less watchers.

Regarding what you said about the watcher instead of expressionProperties it would not help in my case because I'm not using the expressionProperties per field. For the step that can have more than 100 fields I put them inside groups and I only have the expressionProperties per group of fields (8 groups in total each group has many fields inside) not in every field. It is strange that I have performance issues and so many watchers (I used your awesome ng-stats lib to see this!) because I one time bind most things inside the fields. Also I ng-if the groups until they are necessary. Still on that step in the best case scenario I have 513 watchers (before the user starts interacting with the form and causing more fields to show up). Worst case I have more than 3000 watchers. I will have to find time to take a closer look.

**Comment by kentcdodds** [comment]
In the latest beta, I added a hideExpression property. Give that a shot.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
@pedrocatre, have you tried `hideExpression` yet? Here's [an example](http://angular-formly.com/#/example/field-options/hide-fields). I think this will do what you need. Only available in `6.4.0-beta.4` though... Please provide feedback :-)

**Comment by kentcdodds** [comment]
ping @pedrocatre. I would really like to make sure that this solves your use case before I cut an official release. Let me know as soon as you are able please :-)

**Comment by pedrocatre** [comment]
Yes, sorry it took my a while to answer. I only had the opportunity to test this today. It solves my use case :) thanks!

**Comment by kentcdodds** [comment]
Supported in 6.4.0 :-)
