### ISSUE TITLE
formlyApiCheck.disable()

### ISSUE THREAD

**Issue by pedrocatre** [formly-js/angular-formly#272]
In the documentation http://docs.angular-formly.com/v6.1.0/docs/tips you have this tip:

```javascript
angular.module('yourModule').config(
  function(formlyConfigProvider, formlyApiCheck, onProd) {
    if (onProd) {
      formlyApiCheck.disable();
      formlyConfigProvider.disableWarnings = true;
    }
  }
);
```

When I was running version 5 formlyApiCheck.disable() would work. I upgraded to the latest 6.3.2 and now I get TypeError: formlyApiCheck.disable is not a function.

**Comment by kentcdodds** [comment]
Thanks for letting me know. Docs can be hard to keep updated! :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
This has been updated. Thank you!

**Comment by antoinepairet** [comment]
For anyone encountering the issue, the link to the doc is: http://docs.angular-formly.com/docs/tips 

````js
apiCheck.globalConfig.disabled = true;
````
