### ISSUE TITLE
Improved grouped layout

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#273]
Two thoughts that could really really help this:

1. Add the ability to specify a class that would go on the `formly-field`
2. Add the ability to group fields in the field array. Can be an array of fields or an array of arrays of fields.

**Comment by abodacs** [comment]
:+1:

**Comment by kentcdodds** [comment]
@abodacs, this has been done in `6.4.0-beta.1`. If you could try it out, that would be awesome. See [this example](http://angular-formly.com/#/example/other/advanced-layout-flex)

**Comment by abodacs** [comment]
i already saw it. normaly i check your awesome formly every day. i work with  autocomplete i choose angucomplete-alt hope i got it work

**Comment by kentcdodds** [comment]
@abodacs, have you tried out the new advanced layout stuff? I want to make sure that everything's working before I cut an official release. (By the way, the latest version is `6.4.0-beta.3`

**Comment by gowram** [comment]
is this alternative to multifield? or still we can use multifield.

**Comment by kentcdodds** [comment]
@gowram, you mean like the [Multi-input](http://angular-formly.com/#/example/other/multi-input) example? You may be able to use a `fieldGroup` for that. Haven't tried it out, but it may be an easier API. I don't have time to write docs right now, but here's the apiCheck checker for `fieldGroup`: https://github.com/formly-js/angular-formly/blob/master/src/providers/formlyApiCheck.js#L148

You can now specify a `fieldGroup` or a `field` for the `fields` of a `<formly-form>`.

**Comment by abodacs** [comment]
yes i tried it and use it with repeatedsection it works have a nice vacation :\

**Comment by kentcdodds** [comment]
:+1:

**Comment by kentcdodds** [comment]
Supported is 6.4.0
