### ISSUE TITLE
Support for Angular 1.3/1.4

### ISSUE THREAD

**Issue by jaxon** [formly-js/angular-formly#274]
What versions of Angular does angular-formly support and/or have issues with?

I'm currently migrating from Angular 1.2. to 1.3.

**Comment by kentcdodds** [comment]
If you look at the package.json, there's a very loose peerDependency for angular. Angular-formly strives to support 1.2+ so you should be good. It is noteable that angular-formly does version checking to know what features it can use from 1.3

**Comment by jaxon** [comment]
Graceful degradation based on version capability. Nice. ;)
