### ISSUE TITLE
formly-field: custom child-el for template

### ISSUE THREAD

**Issue by whjvenyl** [formly-js/angular-formly#276]
Currently there is a hardcoded template for the formly-field which uses a 'div' tag

    <div formly-field ng-repeat="field in fields ...

I'd like to be able to overwrite the tag used for the ng-repeat operation, in my case a 'li' element.

**Comment by kentcdodds** [comment]
Good request. I can add this to 6.4.0-beta.5. Give me a few minutes :-)

**Comment by kentcdodds** [comment]
```
$ npm install angular-formly@6.4.0-beta.5
```

or

```
$ bower install angular-formly@6.4.0-beta.5
```

Thanks!

**Comment by whjvenyl** [comment]
Woww.. that was fast! Thanks
