### ISSUE TITLE
Improve Website Homepage

### ISSUE THREAD

**Issue by SoundLogic** [formly-js/angular-formly#277]
This looks like a great library! BUT there is a multiverse of libraries out there and I can't read the details about all of them. I think the website would really benefit from having a "Why Angular-Formly?" section that's up front and center. IMHO this is more useful than summarizing what the library does - at least for me, I am more interested in the problems a library solves before I want to know how it works.

**Comment by kentcdodds** [comment]
Good suggestion. I'll look into it.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Migrating this to the website: https://github.com/formly-js/angular-formly-website/issues/20
