### ISSUE TITLE
Reset on formly and form makes dirty

### ISSUE THREAD

**Issue by cboden** [formly-js/angular-formly#278]
In resetting a form validation is run, fields are $dirty and marked as invalid if they're required. 

http://output.jsbin.com/pifericawe

**Comment by kentcdodds** [comment]
Good point. The reset feature should not only reset the model value, but
the NgModelController as well. I'll get this fixed as soon as I am able.
Thanks.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Note, if you need a workaround immediately, all fields have the controller
attached to them called formControl. You could reset the dirty and touched
state yourself until I can get this fixed (or submit a PR. Should be fairly
simple...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by cboden** [comment]
Ah, thanks @kentcdodds! I was only calling `$setPristine()`. I didn't think of calling `$setUntouched()`.

**Comment by cboden** [comment]
Awesome, thanks @kentcdodds!
