### ISSUE TITLE
Overriding messages on validation errors

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#280]
I'm looking at https://docs.angularjs.org/api/ngMessages and http://angular-formly.com/#/example/advanced/validators and see the template wrapper being configured in the `formlyConfigProvider` which defines the validation.html ng-message include.  My question would be how would we go about overriding the default error messages.

Is it as simple as specifying the `message` field on the `validators` object?  As such:
```
{
  key: 'ip',
  type: 'input',
  validators: {
    ipAddress: {
      expression: function(viewValue, modelValue) {
        var value = modelValue || viewValue;
        return /(\d{1,3}\.){3}\d{1,3}/.test(value);
      },
    message: '$viewValue + " is not a valid IP Address"'
  }
}
```

**Comment by kentcdodds** [comment]
Exactly

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Did this answer your question? If so, please close this issue :-)

**Comment by icfantv** [comment]
Sorry, was out of pocket all weekend:  Mother's day....kids....you know the drill.  It did answer my question and will put it to good use this morning.  Thanks.
