### ISSUE TITLE
Incomplete (and confusing) error message

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#281]
I suspect this is due to a lack of HTML escaping but I created a wrapper that allegedly didn't include `<formly-transclude></formly-transclude>` in a template and got the following (confusing) error message:

```
Failed to instantiate module foo due to:
Error: Formly Error: Template wrapper templates must use "" somewhere in them. This one does not have "" in it: static/views/required-label.html
Additional information: {"name":"bootstrapLabel","template":"static/views/required-label.html","apiCheck":{},"types":[]}.
...
```
Looking at the source (line 414 in version 5.2.1), it looks like it's supposed to inject the string "\<formly-transclude>\</formly-transclude>" into the error message, but that's not happening.

The cause of this is that I'm trying to override the built-in `bootstrapLabel` wrapper to make the required * character red and the template (which is a near copy of formly's `label.html` file) DOES have the requisite formly-transclude element.  Debugging formly.js reveals that the template field is not getting de-referenced, that is, the template is coming into the `checkWrapperTemplate(...)` function as the string "static/views/required-label.html" and not the actual contents of the template.

Here's the relevant portion of my `.config(...)`:

```
.config([
  'formlyConfigProvider',
  'formlyBootstrapApiCheck',
  function(formlyConfigProvider,
           formlyBootstrapApiCheck) {
					 
    /* snip */
		
    formlyConfigProvider.setWrapper({
      name: 'bootstrapLabel',
      template: 'static/views/required-label.html',
      apiCheck: {
        templateOptions: formlyBootstrapApiCheck.shape({
          label: formlyBootstrapApiCheck.string,
          required: formlyBootstrapApiCheck.bool.optional
        })
      },
      apiCheckInstance: formlyBootstrapApiCheck
    },
    { name: 'bootstrapHasError',
      template: 'static/views/has-error.html'
    });

    /* snip */
}
```
Thoughts?

**Comment by kentcdodds** [comment]
Use templateUrl instead of template

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by icfantv** [comment]
Well, that was embarrassing.  Thanks.

**Comment by kentcdodds** [comment]
No worries :-)
