### ISSUE TITLE
Remote Radio Button Values: Best Practices

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#284]
I've got radio button values that come from a service call (REST) and was wondering what the "right" way was to tell formly about them.

I can think of two options off the top of my head:

* don't set the `fields` attribute value in the controller until after the data is loaded.
* append to the `fields` array after loading (it appears formly watches both the fields array and each field item in the array)

Maybe there's more?  Thoughts?

**Comment by kentcdodds** [comment]
Hmmm.... It really depends on the experience that you want to give your user... I wouldn't say that either of those is necessarily the "right" way to tell formly about them...

**Comment by icfantv** [comment]
I'm open to your suggestions/thoughts on this.

Right now I have it making a service call (the second option) when the controller function is loaded and just pushing a new item into the `fields` array.  I suspect I'll have to wait until we deploy to production to test the full on latency/UX ramifications of this because on my machine and on our QA servers it's loading fine w/ almost no noticeable delay - even using the mobile network throttling feature of the Chrome debuggger - I took it down to 2G and it was still fine.  It's only 848 bytes of uncompressed data and we have compression turned on.

**Comment by kentcdodds** [comment]
So, what I would recommend is using a router `resolve` feature which allows you to make requests before a controller is loaded and inject the results into the controller. That way you keep your controllers as synchronous as possible. This is just good practice in general in my opinion.

**Comment by icfantv** [comment]
I'm already doing that for our $modals.  Never occurred to me to do that for remote data.  I like it, thanks.
