### ISSUE TITLE
falsy issue on template and templateUrl

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#285]
[this line](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L337) should check for defined, not falsy.

**Comment by ckniffen** [comment]
What is the use case for having falsy templateUrl or template?

**Comment by kentcdodds** [comment]
Good question, should have specified. For some advanced layout stuff, I want to have a "field" in place just to have a node there with a specific class. So something like:

```
{template: '', className: 'my-class-name'}
```

**Comment by kentcdodds** [comment]
Right now, I have to do:

```
{template: 'nbsp;', className: 'my-class-name'}
```

Less fun...

**Comment by ckniffen** [comment]
What are the use cases for 0, false and null?
