### ISSUE TITLE
Minor bug in formly template parsing

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#286]
The `checkWrapperTemplate(...)` function only looks for the string `<formly-transclude></formly-transclude>` and thus, breaks when using `<data-formly-transclude></data-formly-transclude>` which is valid directive syntax.

The work-around is easy, just remove the `data-` but just wanted to put this on your radar.

**Comment by kentcdodds** [comment]
It's actually not a directive, and it's never actually rendered. Do there's
no need to prefix it with data.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by icfantv** [comment]
Oh, ok.  Cool.  Thanks.
