### ISSUE TITLE
Allow configuring `errorExistsAndShouldBeVisible` expression

### ISSUE THREAD

**Issue by pmowrer** [formly-js/angular-formly#287]
Per the [docs](http://docs.angular-formly.com/v6.4.0/docs/field-configuration-object#validation-errorexistsandshouldbevisible), `errorExistsAndShouldBeVisible` is set according to a hardcoded expression. Though it looks like it can be modified on a per-field basis, It would be great to be able to alter this expression globally.

For example, rather than disabling the form button until the form is valid, we like to allow the user to click the submit button at any point. If they form is invalid, we prevent submit and show errors. Allowing us to append `|| scope.fc.$submitted` to the `errorExistsAndShouldBeVisible` expression would facilitate this behavior.

**Comment by kentcdodds** [comment]
This is a good idea. I'll implement it when I get the chance in the next week or so. PRs welcome :-)

**Comment by kentcdodds** [comment]
This has been added as an [`formlyConfig.extra`](http://docs.angular-formly.com/v6.4.0/docs/formlyconfig#extras) in 6.5.0 :-)

**Comment by pmowrer** [comment]
Beat me to it! Works perfectly for our purposes. Thanks!

**Comment by Quji** [comment]
I read #317 and looks like scope.fc.$submitted is not visible inside errorExistsAndShouldBeVisible. Its true?

**Comment by kentcdodds** [comment]
You have to make sure that the `FormController` that's getting submitted is the one that you pass to angular-formly. As of a few minutes ago, you should be able to do this:

```html
<form name="vm.theForm" ng-submit="vm.submit()">
  <formly-form mode="vm.model" fields="vm.fields" form="vm.theForm"></formly-form>
</form>
```

And that should work if you're using angular-formly@6.11.2

**Comment by Quji** [comment]
Now I am really confused. I read your comment https://github.com/formly-js/angular-formly/issues/317#issuecomment-105304114 where you said that name="vm.theForm" and form="vm.theForm" should be different.

I have no idea how to make errorExistsAndShouldBeVisible work with "$submitted". Can you help me? I created http://jsbin.com/qurejigoni/1/edit?html,js,output from example just with one new line: formlyConfig.extras.errorExistsAndShouldBeVisibleExpression = 'options.formControl.$submitted'; and its not working. And 'options.formControl.$dirty' works fine.

**Comment by kentcdodds** [comment]
Sorry @Quji, at the time, you would have problems giving them the same name. Now you don't. Or, at least you wont as soon as I fix the bug you just found :-) I'll let you know and have an example for you when I have it fixed!

**Comment by kentcdodds** [comment]
Alrighty, here's a cloned and fixed version of your jsbin: http://jsbin.com/cekepo/1/edit

Had to change two things:

1. You now need to specify the `name` attribute on your `<form>` that has the `ng-submit` and then pass that same value to the `form` attribute of the `<formly-form>`.
2. Your `formlyConfig.extras.errorExistsAndShouldBeVisibleExpression` expression was wrong, it's supposed to be `form.$submitted`.

It's working now with 6.11.4. Enjoy!

**Comment by Quji** [comment]
@kentcdodds Thank you for so quick response and fix!
You are awesome ; )
