### ISSUE TITLE
Error: opts is undefined (formly.js:768:1)

### ISSUE THREAD

**Issue by bygiro** [formly-js/angular-formly#290]
I got this error using a custom directive, which perfectly works without formly.js, I need to investigate more, if the error is caused by formly or the directive.
By the way, adding this to line 768 solve the error:

if(!opts) return;

I'll prepare a jsbin.

**Comment by kentcdodds** [comment]
My guess is that the field configuration for one of your fields is undefined... But I'll look forward to the jsbin :-)

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this due to lack of activity. Please re-open it if you need further help.
