### ISSUE TITLE
ngModelAttrs support multiple of the same value

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#293]
The current implementation will not allow me to get something that results in this:

original template:

```html
<input ng-model="model[options.key]" />
```

desired result after ngModelAttrsTemplateManipulator:

```html
<input ng-model="model[options.key]" foo="true" bar="true" />
```

Because the way to have a `value` type of `ngModelAttrs` is where the key is the actual value, and the value of `value` is the attribute to be applied. It's an extremely tough API, but I couldn't think of how to make it work as well/flexible AND simpler...

If I were to try to accomplish the above `foo` attribute above, this is the `ngModelAttrs` config for it:

```javascript
ngModelAttrs: {
  'true': {
    value: 'foo'
  }
}
```

So, what we need is somehow, the ability to handle an array as part of the `value`:

```javascript
ngModelAttrs: {
  'true': {
    value: ['foo', 'bar']
  }
}
```

But this isn't supported currently. Wondering if perhaps we should support it for the `attribute`, `bound`, and `expression` as well.

Docs: http://docs.angular-formly.com/v6.4.0/docs/ngmodelattrs

**Comment by kentcdodds** [comment]
@ckniffen, if you're looking for a challenge ;-)

**Comment by ckniffen** [comment]
I may be missunderstanding the issue but I thought the following would work.

```
{
  ngModelAttrs: {
    foo: {
      attribute: 'foo'
    },
    bar: {
      attribute: 'bar'
    }
  },
  templateOptions: {
    foo: true,
    bar: true
  }
}
```

**Comment by kentcdodds** [comment]
Give that a shot in a jsbin and you'll see why that will unfortunately not
work.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Actually....... Maybe it will... I'll have to give it a look later.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ckniffen** [comment]
I have a feeling that the use case of an interpolated expression for the value of the dynamically added attribute the issue will still be there but for you example I don't see a problem.

**Comment by kentcdodds** [comment]
[You're right](http://jsbin.com/hulidu/1/edit?html,js,output) it works just fine. Thanks!

**Comment by ckniffen** [comment]
I still think it is a valid issue because you cant have the same expression write to two different attributes just much more of an edge case now.

**Comment by kentcdodds** [comment]
You're right.

**Comment by kentcdodds** [comment]
I think that this feature will be even less needed once #378 exists. Closing.
