### ISSUE TITLE
Is there a way to disable a validator?

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#296]
I'm wondering if there's a way to disable a validator?  I didn't see anything in the docs, but I was looking for something like:
```javascript
{
  key: 'foo',
  type: 'input',
  validators:  {
    validateFoo: {
      expression:  vm.someFunc,
      message: '\'some message'\'
    }
  },
  templateOptions: {
    /* snip */
  },
  expressionProperties: {
    'templateOptions.disabled': 'formly expression',
    'validators.validateFoo.disabled':  'formly expression'  // <-- this is not valid
  }
}
```
Formly yells at me, makes me sad, and hurts my feelings...in a jslint kind of way.

I have a workaround in that I can adapt `vm.someFunc` to either return a resolved promise or wrap it in an `if` block, but that's not really the same thing.

If there's not a way to do this via properties, would this be a good enhancement?

**Comment by kentcdodds** [comment]
Hey @icfantv. Sorry if `api-check` is hurting your feelings. But it's for the best. Much better than going down a road for a few hours before realizing that you're using angular-formly wrong.

As for your question. First off, your config is wrong. I'm guessing this was just a copy/paste error or something, but you have `templateOptions` and `expressionProperties` inside the `validators` property... They should all be sibling properties at the root of the config object.

Secondly, angular-formly doesn't support disabling validators. This is the first time I've heard of this use case... Perhaps you could describe what your use-case is and I can give you the right way to do it or we can figure out how angular-formly can cover your use-case better.

**Comment by icfantv** [comment]
That was more a tongue-in-cheek comment.  I'm a firm believer in fail early, fail fast.  So keep on api-checkin'.

I fixed the config.  I free typed it in and the default text editor in github is rubbish - I should have typed it a proper text editor (like Notepad) and then pasted it.

Here's the use case:  This is a user admin page and the validator is on the username field.  One of the validators on the username field checks to see if the username is already taken.  This all works great for creating new users.  When I go to edit an existing user, the username field is populated, but disabled (via `expressionProperties['templateOptions.disabled']`) and this `uniqueUsername` validator is still triggered **even if the field is disabled**.  Thus, my `Save` button remains disabled because the form is still being reported as invalid - and indeed if one looks at the `$errors` object on the form, the `uniqueUsername` is present.

So, I'm thinking either we need a way to disable the validators, or perhaps more appropriately, the validators should not be triggered when a field is disabled - but this could get tricky as it starts to depend on the order in which formly evaluates the formly expressions.

As I mentioned, I have a temporary workaround in that I've added a conditional to my `vm.someFunc` expression - but I sure would like to do this the correct way.

**Comment by kentcdodds** [comment]
Yeah, a better way would be to not use `expressionProperties` and actually just set the value based on the state (create/edit). So when you create the field, before you add the validator, check to see if you're in `edit` mode. If you are, don't add the validator. Also, instead of using `expressionProperties` for disabled, just say something like: `disabled: isEditMode` or something like that. That's what I do. It's better for several reasons. Would that work?

**Comment by icfantv** [comment]
I follow the last bit on `isEditMode` but I don't follow how to NOT add a validator based on that boolean.

**Comment by kentcdodds** [comment]
something like:

```javascript
{
  key: 'foo',
  type: 'input',
  validators:  {
    validateFoo: isEditMode ? undefined : {
      expression:  vm.someFunc,
      message: '\'some message'\'
    }
  },
  templateOptions: {
    disabled: isEditMode
  }
}
```

**Comment by kentcdodds** [comment]
I do stuff like that all the time

**Comment by icfantv** [comment]
Ah, got it.  That will work nicely.  Thanks.

**Comment by kentcdodds** [comment]
Note, for people who are persisting their config to a database and need it to just work with JSON, then another solution would be to make checking the mode part of the validator.

**Comment by kentcdodds** [comment]
Glad that'll work for you :+1:

**Comment by icfantv** [comment]
So api-check doesn't like `undefined` as a value for the validator.  If `isEditMode` is `false`, it's fine, but if not, it yells and says:
```javascript
Error: angular-formly: formly-field directive apiCheck failed! `validators` at `Argument 1/value` must be `objectOf[oneOfType[oneOfType[String, Function], strict shape]]`  formly-field-directive-validation-failed

/* snip */

"validators": {
  "__apiCheckData": {
    "optional": true,
    "type": "objectOf",
    "error": "THIS IS THE PROBLEM: `validators` must be `objectOf[oneOfType[oneOfType[String, Function], strict shape]]`"
  },
/* snip */
```
Thoughts?

**Comment by kentcdodds** [comment]
In all honesty, I haven't done that for validators before. I'm not certain why that is causing you issues, but one thing that you could do is something like this:

```javascript
var myField = {
  key: 'foo',
  type: 'input',
  validators:  {},
  templateOptions: {
    disabled: isEditMode
  }
};

if (!isEditMode) {
  myField.validators.fooValidator = {
    /* snip */
  };
}
```

**Comment by icfantv** [comment]
That would work.  It does change the "implied paradigm" (and I use that phrase quite loosely) of defining all the fields in the same array.  But it does only conditionally add the validator - meaning it's simply not at all there if in edit mode.

Here's what I wound up doing:  I was hoping that `angular.noop` would work instead of `undefined` but angular installs an `$inject` property on everything, including `angular.noop`, so that doesn't work because api-check checks for extraneous properties.  And it turns out it wouldn't work anyway because the validator function needs to return either a resolved or rejected $promise, so what I did was create a utility service that had a `noopResolve` function and that works like a charm.

Although, it could be argued that at this point, why not just add the conditional to the `vm.someFunc` to make it just return a resolved promise and honestly, I don't have good answer here.

**Comment by kentcdodds** [comment]
Actually, you know what would be even better:

```
{
  key: 'foo',
  type: 'input',
  validators:  {
    validateFoo: isEditMode ? 'true' : {
      expression:  vm.someFunc,
      message: '\'some message'\'
    }
  },
  templateOptions: {
    disabled: isEditMode
  }
}
```

**Comment by icfantv** [comment]
It totally would be better....if it worked.  :-(  api-check still complains about the argument/value needing to be `objectOf[oneOfType[oneOfType[String, Function], strict shape]]`

**Comment by kentcdodds** [comment]
Hmmm... That's crazy.... That should totally work... (the `undefined` solution should have worked as well)... Try this:

```javascript
{
  key: 'foo',
  type: 'input',
  validators:  {
    validateFoo: isEditMode ? {expression: 'true'} : {
      expression:  vm.someFunc,
      message: '\'some message'\'
    }
  },
  templateOptions: {
    disabled: isEditMode
  }
}
```

**Comment by icfantv** [comment]
I wrote too soon.  Sorry. One sec.

**Comment by kentcdodds** [comment]
http://jsbin.com/foramu/1/edit?html,js,output :-)

**Comment by icfantv** [comment]
Gaaaaaaah.  When am I going to learn that formly expressions need to be quoted.....?  Both `'undefined'` and `'true'` work.

**Comment by kentcdodds** [comment]
Haha, that's actually a common pitfall. But it's literally an angular expression, so there's really no way to get around it :-( Glad you got it working! :dancer:

**Comment by icfantv** [comment]
I'm sure it is.  It's so easy to do and whether you add them or not, it's valid J/S.  The only difference is when it gets evaluated.

I was thinking about if there was a way to pre-parse it to see if there was potentially an error, but as you said, there's not.

Thanks again. :smiley:
