### ISSUE TITLE
Add user to angular-formly site: New User: Panax.io

### ISSUE THREAD

**Issue by benoror** [formly-js/angular-formly#297]
# Add Panax.io to users

Project/Company Name: Panax.io

Link: http://panax.io/

Logo:

![logo for Panax.io](https://raw.githubusercontent.com/panaxit/panax/master/wiki_resources/panax_roboto_condensed_bold.png)

Short Description:

Panax is a stack of technologies to generate applications automatically based on a relational data model. Customization and extensibility is done via configuration, nevertheless Panax aim is to generate an usable app with less possible interaction from the developer (based on heuristics, assumptions, etc).

One of the most important UI for an application are forms, therefore we heavily rely on angular-formly to ease it's generation.

---

We will release our Beta soon. If you want to keep updated with the news please subscribe to our newsletter at http://panax.io/#subscribe

**Comment by kentcdodds** [comment]
:+1:
