### ISSUE TITLE
Minified 6.5.3 throws error

### ISSUE THREAD

**Issue by jasonrichardsmith** [formly-js/angular-formly#298]
Using 6.5.3 the minified js throws the following angular error
Angular 1.3.15

https://docs.angularjs.org/error/$parse/syntax?p0=%7B&p1=invalid%20key&p2=2&p3=%7B%7B::%27formly_%27%20%2B%20$parent.$index%20%2B%20%27_in_my_ng_repeat%27%7D%7D&p4=%7B::%27formly_%27%20%2B%20$parent.$index%20%2B%20%27_in_my_ng_repeat%27%7D%7D

Unminified does not have the error.

**Comment by kentcdodds** [comment]
I couldn't reproduce this... Am I doing something wrong? http://jsbin.com/sekepu/edit?html,js,console,output

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this for inactivity. Please re-open if you have more information.
