### ISSUE TITLE
List of default / built in validations?

### ISSUE THREAD

**Issue by facultymatt** [formly-js/angular-formly#301]
I'm having trouble finding a clear list of the validation types built into formly. 

The [documentation page](http://docs.angular-formly.com/v6.4.0/docs/validation) is sparse.

The best I could reason is that Angulars standard html5 validations are supported, along with custom expressions your write yourself, ala [this page](http://docs.angular-formly.com/v6.4.0/docs/formly-expressions). 

Is there anything more robust I should reference?

**Comment by kentcdodds** [comment]
You've got it. Technically, angular-formly doesn't ship with any validators
at all and only leverages a few of angular built in ones.

I was going to link you to a validation library that you could use, but all
the ones I found are too big in scope. If anyone knows of a validation
library that just ships functions that would work great with formly.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
I should also point out that angular-formly will never ship with custom
validators. That is outside the scope of the project. It is concerned about
making an easy api for you to add your own business-specific validators.

On another note, if I can't find a validation library that's just a bunch
of functions, then I'm going to make one. I can't believe something like
that doesn't already exist though...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by facultymatt** [comment]
https://github.com/chriso/validator.js is a great validator that should work for this use case.

**Comment by benoror** [comment]
This is a validation library for JSON-Schema: https://github.com/geraintluff/tv4

**Comment by kentcdodds** [comment]
I found a terrific validation library that works great with angular-formly :-)
is.js: http://is.js.org/
example: http://angular-formly.com/#/example/integrations/is-js

**Comment by benoror** [comment]
Wow never heard of that on, looks pretty impressive!

**Comment by kentcdodds** [comment]
I improved the docs for [validation](http://docs.angular-formly.com/v6.10.1/docs/validation)
