### ISSUE TITLE
Watcher in JSON

### ISSUE THREAD

**Issue by ASardar** [formly-js/angular-formly#302]
Hi,

I am using formly that loads a JSON file from the server, but how can i use the watcher functionality?
Tried this:

                {
                    "key": "FirstName",
                    "type": "horizontalInput",
                    "templateOptions": {
                        "label": "First name",
                        "required": true
                    },
                    "watcher": {
                        "listener": "function(field, newValue, oldValue, scope, stopWatching) { if(newValue) { console.log('String Expression: '+ newValue); } }"
                    }
                }

but that didn't work. How can i get this to work?

**Comment by kentcdodds** [comment]
Yeah, so if you're loading it from a server then you'll have to use the string version for your [watcher and other expressions](http://docs.angular-formly.com/v6.4.0/docs/formly-expressions). In-lining functions as strings will not work (and would be a very bad idea). Here's an example that may be helpful to you: http://angular-formly.com/#/example/other/json-powered

P.S. I recommend avoiding using `watcher` if you can. It's better to try to use `expressionProperties`. Mostly from a performance standpoint.

**Comment by kentcdodds** [comment]
Let me know if that is enough to get you going.

**Comment by ASardar** [comment]
Thank you Kent. Can i use expressionProperties to filter a dropdown depending on what the user types in the FirstName?

**Comment by kentcdodds** [comment]
Absolutely. Depending on the dropdown's `templateOptions`, you might do something like this: http://angular-formly.com/#/example/other/filter-select

**Comment by ASardar** [comment]
Perfect, thank you very much.
