### ISSUE TITLE
Can't use nested fieldGroups for advanced layout

### ISSUE THREAD

**Issue by DrDanRyan** [formly-js/angular-formly#304]
I am using angular-material to layout a form and have been experimenting with different layout possibilities. I can get things to work with a single level of fieldGroup, but I can't make it work when nesting one fieldGroup inside of another. One example where this would be useful is putting a column layout inside of a row layout to produce something like:

![screen shot 2015-05-21 at 11 51 27 am](https://cloud.githubusercontent.com/assets/2340323/7752863/e6be718a-ffaf-11e4-9c2d-166029694dcf.png)

The template that produces the image above is:

```html
<div layout="row" style="height:200px">
  <div flex="75" style="background-color:blue"></div>
  <div flex="25" layout="column" style="height:200px">
    <div flex="60" style="background-color:red"></div>
    <div flex="40" style="background-color:green"></div>
  </div>
</div>
```

Trying to port this over to formly-fields would look like:
```javascript
vm.myFields = [
    {
      elementAttributes: {
        layout: 'row',
        style: 'height:200px'
      },
      fieldGroup: [
        {
          template: '<div></div>',
          elementAttributes: {
            flex: '75',
            style: 'background-color:blue'
          }
        },
        {
          elementAttributes: {
            flex: '25',
            layout: 'column',
            style: 'height:200px'
          },
          fieldGroup: [
            {
              template: '<div></div>',
              elementAttributes: {
                flex: '60',
                style: 'background-color:red'
              }
            },
            {
              template: '<div></div>',
              elementAttributes: {
                flex: '40',
                style: 'background-color:green'
              }
            }
          ]
        }
      ]
    }
];
```

Unfortunately this doesn't work because the `flex: '25'` attribute on the column `<div>` gets applied to the inner `ng-form` element created by the `fieldGroup` instead of the outer `formly-field` element that contains the second `fieldGroup`. This breaks the flexbox design as the second element in the flex `row` has no flex attribute and gets assigned a 0 width. As far as I can tell there is no way to assign attributes to this second `formly-field` in the row in this example (it is created by `formly` behind the scenes).

**Comment by kentcdodds** [comment]
This is definitely something that I want to make work. Give me some time to look into it later.

**Comment by kentcdodds** [comment]
I created a jsbin for it to demonstrate the issue: http://jsbin.com/goduno/edit

**Comment by kentcdodds** [comment]
Boy, you've really got me stumped... I don't know how to accomplish that design based on how angular-formly works. Could you describe the UI you're trying to actually build? Maybe I can help you figure out a work-around.

**Comment by DrDanRyan** [comment]
Honestly, I was just trying to grok how to fully use angular-material's flex layout with formly and was trying some things out. I ended up just setting things up without nesting flex layouts and it all looks nice and works great.

One thing I thought of to make this nesting work is if there was a property on the field configuration object like `containerAttributes` that only applied when a fieldGroup property was also provided. Then the `containerAttributes` are applied to the outer `formly-field` element that wraps the inner `ng-form` created by the fieldGroup. Then, moving the `flex: 25` into `containerAttributes` instead of `elementAttributes` in the second fieldGroup would fix the issue.

**Comment by kentcdodds** [comment]
That shouldn't be too difficult to add I think... If you think that it would work and you need that functionality, then I may take the time to add it.

**Comment by DrDanRyan** [comment]
I think I have figured out a nice way to do this, but there might be a drawback that I am not seeing, please point it out for me if you see one.

Instead of forcing the layout into the javascript, do the flex layout in the html and use multiple `formly-form` elements that share the same model. For example the html `<body>`:
```html
  <form>
    <div layout="row" style="height:500px">
      <formly-form flex="75" style="background-color:blue" model="vm.myModel" fields="vm.blueFields"></formly-form>
      <div flex="25" layout="column" style="height:500px">
        <formly-form flex="60" style="background-color:red" model="vm.myModel" fields="vm.redFields"></formly-form>
        <formly-form flex="40" style="background-color:green" model="vm.myModel" fields="vm.greenFields"></formly-form>
      </div>
    </div>
  </form>
```

and the javascript:
```javascript
ngModule.controller('testController', function() {
  var vm = this;
  vm.myModel = {};

  vm.blueFields = [
    {
      type: 'input',
      key: 'blueInput',
      templateOptions: {
        label: 'Blue Input'
      }
    }
  ];

  vm.redFields = [
    {
      type: 'radio',
      key: 'redRadio',
      templateOptions: {
        label: 'Red Radio',
        options: [
          {
            label: 'Option 1',
            value: 1
          },
          {
            label: 'Option 2',
            value: 2
          }
        ]
      }
    }
  ];

  vm.greenFields = [
    {
      type: 'radio',
      key: 'greenRadio',
      templateOptions: {
        label: 'Green Radio',
        options: [
          {
            label: 'Option 1',
            value: 1
          },
          {
            label: 'Option 2',
            value: 2
          }
        ]
      }
    }
  ];
});
```

Yields:
![screen shot 2015-05-27 at 11 56 02 am](https://cloud.githubusercontent.com/assets/2340323/7840899/6287c562-0467-11e5-94fc-3c63834b4b28.png)

What drawbacks are there to having my fields split among separate `formly-form` elements?

**Comment by kentcdodds** [comment]
I don't think any drawbacks of having multiple `formly-form`s would be noticeable. If you wanted to make sure that `formState` was shared between all of the fields (in the different forms) then you'd have to make sure it was initialized prior to the forms rendering. Another thing you'd need to be aware of is that the `fields` property for each of the forms would be different. Not normally a real issue though. I think you've found a good solution. Do you mind [creating an example](https://github.com/formly-js/angular-formly-website/blob/master/CONTRIBUTING.md) for the website?

**Comment by DrDanRyan** [comment]
Sure, I can do that. Also, would there be a point in making the `formly-forms` use the same `form` attribute? I am not entirely clear what impact that would have.

**Comment by kentcdodds** [comment]
Ah, good catch. I didn't notice that. Basically, the last `formly-form` would overwrite the other ones. So you don't want to do that. Instead, wrap all of them in a single `ng-form` or `form` and specify a `name` on that and don't worry about specifying a `form` attribute on any of the `formly-form`s (unless you're interested in that specific form controller for some reason).

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this issue. An example for the website would be welcome. Thanks @DrDanRyan!

**Comment by GianlucaBobbio** [comment]
This isn't a good solution if I'm working with multiple possible advanced layouts. I need no HTML layout configuration. (sorry for bad english)

**Comment by kentcdodds** [comment]
I'm not sure I understand the problem you're having. Could you follow the instructions here so we can help you better? http://help.angular-formly.com
