### ISSUE TITLE
docs urls for "latest" release

### ISSUE THREAD

**Issue by maku** [formly-js/angular-formly#306]
It would be a good idea to be able to reference the documentation also for the "latest" version. 
e.g. http://docs.angular-formly.com/v6.4.0/docs/ngmodelattrs -> also via http://docs.angular-formly.com/latest/docs/ngmodelattrs

Reason.: I write a simple form builder for internal use and would like to reference the docu, but I don't want change the URL's

**Comment by kentcdodds** [comment]
Actually this is possible. Simply remove the version altogether and it will add the latest version! For example: http://docs.angular-formly.com/docs/ngmodelattrs NEAT!

However, you'll notice that the latest version of angular-formly is 6.6.0 but the latest docs version is 6.4.0. Perhaps @gkoberger or someone he knows can explain why [this regression](https://twitter.com/kentcdodds/status/600275240887799808) has still not been fixed after 4 days...
