### ISSUE TITLE
Need a mechanism for setting/getting an index for repeating forms.

### ISSUE THREAD

**Issue by jlowery457** [formly-js/angular-formly#308]
I am creating a custom template in the same vein as the Repeating Section example.  I want to keep the custom template as generic as possible.  This means having the repeated forms and fields driven from an array in the model and fields defined in the implementors controller.  The challenge comes when I want to delete a particular "row" from the form.  I tried setting an index in the formState object and then retrieve that index when creating my delete button and store it in the data field of the delete button and retrieve it in the onClick function so I can remove that index from the array in the model.  However, the value that is stored for each repeated form is the last index value.  IOW the index value in the data object is the same, whatever the highest index value.

Here is a link to a jsBin that shows what I'm trying to do.  the number in the delete button is the index stored for that button.  I would expect the numbers to be 0, 1, 2, etc.  but they are all the same.  When you add a row you will see the value on all buttons increment by one each time the add button is pressed.

I suspect this has something to do with the formState object.  The docs say that object is shared by all fields in a form, but since each "row" in my form is a form, I wouldn't expect the formState object to be shared by all forms.  I'm sure I'm missing something but need a little guidance.

http://jsbin.com/dajode/3/edit?html,js,output

**Comment by ckniffen** [comment]
I don't know if this is related to the issue, but what I am most concerned about is that the `name` attribute of the fields in the repeat section are not unique.  I spent about an hour trying to figure out the issue is with that but to no avail.  I will revisit it tonight.

**Comment by cdoe0108** [comment]
I am facing the same problem. Can u please help me in case u already found the solutions to this @jlowery457
