### ISSUE TITLE
feature: Allow templateManipulators and wrappers to be assigned on a per form basis

### ISSUE THREAD

**Issue by ckniffen** [formly-js/angular-formly#309]
Use case: Rendering the same field in a table might be different than rendering it in the horizontal bootstrap form.  This would allow people to define their own directives which define on the fly the wrappers and manipulators ex. formlyAsTable or formlyAsAccordion.  Also if the form being rendered in a form builder you may want different manipulators to run.

I do not have an immediate need just thought this would be a cool feature.

**Comment by kentcdodds** [comment]
Maybe this should be an additional issue, but I think that while we're at it, we should make it work on a per-field/per-type basis as well.

**Comment by ckniffen** [comment]
+1

**Comment by kentcdodds** [comment]
Officially released in 6.11.0!

**Comment by kentcdodds** [comment]
The test for it is a little crazy: https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.test.js#L975-L1083 :-)
