### ISSUE TITLE
Allow string in `model`property from field configuration object

### ISSUE THREAD

**Issue by benoror** [formly-js/angular-formly#311]
Since all my configurations come from a JSON backend, I would like to use a string in `model` property from field configuration object.

Originally I wanted it for  [field-groups](http://docs.angular-formly.com/v6.4.0/docs/field-groups), in order to support **nested forms**, but I guess it can be extended for any kind of field.

** *Note: this is currently supported when specifing model as formState (https://github.com/formly-js/angular-formly/issues/299)*

JSBin: http://jsbin.com/bitoli/1/

**Comment by benoror** [comment]
Would `key` property make more sense:

JSBin: http://jsbin.com/tusubo/1/

**Comment by benoror** [comment]
Added both: https://github.com/formly-js/angular-formly/pull/314

**Comment by kentcdodds** [comment]
Supported in 6.9.0
