### ISSUE TITLE
Allow controllerAs on custom fields.

### ISSUE THREAD

**Issue by Mattnmoore** [formly-js/angular-formly#318]

**Comment by kentcdodds** [comment]
What is your reasoning for wanting this? I'm a big fan of controller as, but I don't see a reason for it here.

**Comment by ckniffen** [comment]
My solution for this is to define the custom field's controller using the angular module controller method and then in the type definition do:

```javascript
{
  controller: 'CustomTypeController as typeCtrl'
}
```

**Comment by kentcdodds** [comment]
I don't think that there's a way that we could do any better than that. And, as much as I love controller as, I don't see the benefits in this scenario. Closing this unless someone can convince me otherwise.

**Comment by ckniffen** [comment]
The only small benefit I could see and that would be if someone wanted the controller definition to be "private" but still use controllerAs.  I don't think the benefit warrants a code change though unless there is a huge demand for it.

**Comment by kentcdodds** [comment]
I can see the benefit of making it private (in fact, in my app, I never actually register any of my controllers with angular). But I definitely firmly believe that the benefits of controllerAs cannot be seen in a type's controller. And we're also supporting angular 1.2 still, so we can't switch to use it in our own internal directives.

**Comment by ckniffen** [comment]
I personally expose most of mine so that they can be enhanced via delegate.  I always forget about angular 1.2 support :)

**Comment by kentcdodds** [comment]
Wish I had metrics on what version of angular people are using with
formly...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
