### ISSUE TITLE
Not working anymore in strict dependency injection mode

### ISSUE THREAD

**Issue by prismsoundzero** [formly-js/angular-formly#319]
Since version 6.9.0 I get this error :
```javascript
Error: [$injector:strictdi] FormlyFormController is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.3.15/$injector/strictdi?p0=FormlyFormController
```

I'm using angular 1.3.15 with strict-di mode enabled (see https://docs.angularjs.org/guide/di#using-strict-dependency-injection)

**Comment by kentcdodds** [comment]
Ah! Thanks for letting me know! I haven't upgraded my app yet, otherwise I would have caught this earlier. #refactorbug

**Comment by kentcdodds** [comment]
Released as 6.10.1. Thanks for the heads up!

**Comment by kentcdodds** [comment]
Also, previous versions with this bug have been deprecated on npm.

**Comment by prismsoundzero** [comment]
Great, thanks !
