### ISSUE TITLE
jspm support

### ISSUE THREAD

**Issue by maku** [formly-js/angular-formly#321]
By and large jspm usage of formly works. But I get the message "WARNING: Tried to load angular more than once" which is triggered by formly

**Comment by kentcdodds** [comment]
Sounds like a problem with jspm. Angular-formly is using UMD. jspm should
support that. If you have any suggestions for how to fix it for jspm, I'm
all ears.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by maku** [comment]
Of course the best solution would be to provide angular-formly via  jspm registry :-) to be able to "jspm install angular-formly" 

To find the reason why the warning occurrs ("Tried to load angular more than once") is not that easy. Maybe it is a problem with jspm (as you mentioned)

**Comment by kentcdodds** [comment]
Looks like it actually is already available in the jspm registry, but I'm thinking that jspm doesn't deal with peerDependencies correctly. Here's a PR that might fix the problem: https://github.com/jspm/registry/pull/396
