### ISSUE TITLE
disabled with function does not work correctly

### ISSUE THREAD

**Issue by maku** [formly-js/angular-formly#322]
When I try to use a function influencing the **disabled** state I get an incorrect behaviour: e.g.

```
expressionProperties: {
        'templateOptions.disabled' = function($viewValue, $modelValue, scope)  {
             console.log('disabled',$viewValue, $modelValue, scope);
       }
}
```
The $viewValue is always undefined....

A little example http://output.jsbin.com/joroci/3 which demonstrates the behaviour (console output of function parameters of first textfield)

**Comment by kentcdodds** [comment]
Deprecated 6.10.1 and created 6.10.2 with this bugfix. Thanks.

**Comment by maku** [comment]
Great, thank you
