### ISSUE TITLE
Support for the ability to set a key's value based on another

### ISSUE THREAD

**Issue by siddharthkchatterjee** [formly-js/angular-formly#326]
So, in my form currently (snippet below) the value of the `link` key is supposed to be the result of the `Slug .slugify` function called on the value of the `name` key. I could of course do this with a `$scope.$watch` on the value of `model.name` but I'm wondering if there's a better way. I can't find anything in the documentation. Any ideas?

	vm.fields = [{
		key: 'name',
		type: 'input',
		templateOptions: {
			label: 'Name',
			placeholder: "John Doe's Party",
			required: true
		}
	}, {
		key: 'link',
		type: 'input',
		// value: Slug.slugify(vm.model.name),
		templateOptions: {
			label: 'Link',
			placeholder: "john-does-birthday-party",
			required: true
		}
	}, {
		key: 'city',
		type: 'input',
		templateOptions: {
			label: 'City',
			placeholder: 'Las Vegas',
			required: true
		}
	}];

**Comment by kentcdodds** [comment]
Nope, I think a normal $scope.$watch in your controller is the best way to
do that. You could also look into the watch property on the field, but I'd
probably just do a normal watch.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Closing this for now. Feel free to reopen it if you need.

**Comment by siddharthkchatterjee** [comment]
Ah, alright. That's fine. Thank you for the quick reply, Kent!

**Comment by casoetan** [comment]
Okay, but how do I implement a scenario where a select box depends on another. For instance, I have a select box for countries, when a user selects his country how can i auto populate a second select box with states from that country. 
Note, country and states will be fed from an external api.

Thanks

**Comment by siddharthkchatterjee** [comment]
You can use use a `$scope.$watch` on the model value of the country and when it changes, get the appropriate states from the API and mutate the options in the states field (within `vm.fields`) in particular.

**Comment by casoetan** [comment]
Thanks for the quick response, do you have any sample code for this?

**Comment by benoror** [comment]
There are a lot of examples in the webpage, you can use a formly watcher:

http://angular-formly.com/#/example/field-options/watchers

Or as @siddharthkchatterjee said, you can use `$scope.$watch` in the controller

There are many alternatives since angular-formly is quite flexible, use the one that suits your needs. :smile:

**Comment by casoetan** [comment]
Okay, tried $scope.$watch on my model, doesn't get called when I change select options, only does for text fields.

**Comment by benoror** [comment]
The best way to get help is to get a failing example in jsbin/jsfiddle/... and ask in [gitter.im/formly-js/angular-formly](https://gitter.im/formly-js/angular-formly)

Also take a look at [Questions/Help](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#questionshelp) section and the [corresponding video](https://www.youtube.com/watch?v=Kw9fVgc3Tzk&index=6&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH)

**Comment by benoror** [comment]
For anyone wondering here's an example: http://jsbin.com/jinaca/1/edit?js,output
