### ISSUE TITLE
Bug with multicheckbox and required

### ISSUE THREAD

**Issue by PhilFlash** [formly-js/angular-formly#330]
Hi,
Error is incorrect when you use a multicheckbox and option required.
See example:
http://plnkr.co/edit/IleV3U8AVY0Va3lbmUve?p=info

Steps to reproduce:
- step 1 : check Travel and uncheck Travel (last checkbox) => there is an error : Type is required : field is in red : all is ok
- step 2 : check Research => the field Type is in error : BUG

Only the last checkbox is used to check 'Required'

**Comment by ckniffen** [comment]
@kentcdodds do you want me to take point on this?  It is a recurring problem.  I think this issue should be moved to https://github.com/formly-js/angular-formly-templates-bootstrap.

**Comment by kentcdodds** [comment]
Thanks @ckniffen, I was actually just about to say that the solution is either fix the bootstrap template so it handles this scenario or make an example of a custom validator that does require like people expect it should. What approach do you think?

Either way, I'm moving this to the bootstrap templates.

**Comment by kentcdodds** [comment]
Moved: https://github.com/formly-js/angular-formly-templates-bootstrap/issues/26
