### ISSUE TITLE
Please, use $interpolate's start and end symbols instead hardcoded values

### ISSUE THREAD

**Issue by yushkovskiy** [formly-js/angular-formly#331]
I've to use custom configuration for interpolation brackets in markup:
```javascript
  module.config(function ($interpolateProvider) {
    $interpolateProvider.startSymbol('{[{');
    $interpolateProvider.endSymbol('}]}');
  });
```
In this way generated templates does not work

**Comment by kentcdodds** [comment]
Working on it now. Should be fixed soon. Note, I don't think that I'm going to do this for any of the template libraries. It would be far too much effort.

**Comment by kentcdodds** [comment]
You should be able to get this in `6.11.5` and/or `6.12.0-beta.1`. Enjoy!

**Comment by yushkovskiy** [comment]
Great! Thanks!
