### ISSUE TITLE
require: '^form'

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#332]
In the next breaking version change, let's remove the `form` attribute and require the user to have a `formController` as a parent. This would seriously alleviate confusion (though make a bit more boilerplate in the simple case).

Here's what you might do now:

``` javascript
<formly-form model="vm.model" fields="vm.fields" form="vm.form">
  <button ng-disabled="vm.form.$invalid" ng-click="vm.submit()">Submit</button>
</formly-form>
```

With this change, the above example would throw an error. This is what you would need to do:

``` javascript
<form name="vm.form" ng-submit="vm.submit()">
  <formly-form model="vm.model" fields="vm.fields">
    <button ng-disabled="vm.form.$invalid">Submit</button>
  </formly-form>
</form>
```

Would love feedback on this.

**Comment by benoror** [comment]
Agree, this was something I personally faced when learning angular-formly, while having used formController before.

**Comment by kentcdodds** [comment]
I would like some feedback on this one from people please!

**Comment by dwolt** [comment]
I'm using the "after" version, but why have a breaking change if you don't have to? It is very tempting to tidy things up, but it is a better habit to go out of the way not to have breaking changes. The examples could all look like the "after" and I see no problem keeping the "before" out of the documentation or indicating the user should consider it deprecated, unless there is a significant cost to keeping the "before" option around, why break existing code with the upgrade?

**Comment by kentcdodds** [comment]
@dwolt, thanks for your perspective! The challenge is that there's [some crazy code](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L276-L313) to make things work the way that people expect it should anyway. It also has been the source of several questions from people who've spent a few hours with issues related to this... Though, thinking about it now, some of those questions and issues would not be solved by this change anyway, so maybe I should keep the old code around...

**Comment by kentcdodds** [comment]
This is significant a change. I'm about to release a few minor breaking changes in 7.0.0. I'm going to push this off to a different breaking release so people can benefit from the 7.0.0 release without having to pay the price for this change.

**Comment by softEngJason** [comment]
I like the potential new change. It immediately makes things more clear for me.

**Comment by koraybalci** [comment]
How about keeping the old one and introducing a brand new formly directive instead? This looks more readable to me with the added benefit of not braking existing code:

```
<form name="vm.form" ng-submit="vm.submit()">
  <formly model="vm.model" fields="vm.fields">
    <button ng-disabled="vm.form.$invalid">Submit</button>
  </formly>
</form>
```

**Comment by homerjam** [comment]
Seems like a pretty trivial thing to fix on upgrading. Simplifying the code would help people contribute too.

**Comment by kentcdodds** [comment]
I like your suggestion @koraybalci. We could add a console warning to the `formly-form` directive and then remove it later in a major version. The problem is upgrading all of those examples would be incredibly painful. lol. It's funny that the thing that protects users the most from breaking changes is the effort it takes to upgrade documentation!

What if instead we made the form controller optional to start?

**Comment by SteveShaffer** [comment]
I'm not against requiring `form`.  I already write it that way and I think it would at least be important to make sure people know that's probably the best way to do it.

I might not fully understand here, but if you didn't require the form controller, isn't formly just a templating library at that point?  I'm not sure there's that many strong use cases that don't require a form controller (though I'm probably wrong on that).

I also like @koraybalci's suggestion for a good strong `<formly>` directive and would be happy to help update docs if that's the blocker (note the word **_help_** though).

One other thought: if `^form` is required and the main directive no longer *is* the form, then is there any point to having the transclusion for things like buttons?  With a `<form>` wrapper, it's the same as just including it after the `<formly-form>`, right?  All my stuff already looks like this just for clarity and I believe it works exactly the same as including the buttons as transcluded content:
```
<form name="vm.form" ng-submit="vm.submit()">
    <formly-form fields="vm.fields" model="vm.model"></formly-form>
    <button type="submit>Submit</button>
</form>
```

**Comment by egucciar** [comment]
>I might not fully understand here, but if you didn't require the form controller, isn't formly just a templating library at that point? I'm not sure there's that many strong use cases that don't require a form controller (though I'm probably wrong on that).

it's actually a fairly common use-case to inter-mix forms and interactive, templated components. 

Can I ask what issues came about which caused this? I know it's been a long time since the last update and everyone has moved on from formly, but I am just getting started.
