### ISSUE TITLE
var vm = this; doesn't work...have to use $scope..why is that?

### ISSUE THREAD

**Issue by sharpmachine** [formly-js/angular-formly#333]
So I was attempting to set up formly in my project using the examples in the documentation.  Everywhere you use 'vm' I did as well.  And nothing worked.  It's only when I used $scope.whatever rather than vm.whatever did it work.

Why is that?

No workie:

```javascript
  var vm = this;

 vm.user = {
    email: 'jesse@jkad.com'
  };

vm.userFields = [
    {
      key: 'email',
      type: 'input',
      templateOptions: {
        type: 'email',
        label: 'Email address',
        placeholder: 'Enter email'
      }
    },
    {
      key: 'password',
      type: 'input',
      templateOptions: {
        type: 'password',
        label: 'Password',
        placeholder: 'Password'
      }
    },
    {
      key: 'file',
      type: 'file',
      templateOptions: {
        label: 'File input',
        description: 'Example block-level help text here',
        url: 'https://example.com/upload'
      }
    },
    {
      key: 'checked',
      type: 'checkbox',
      templateOptions: {
        label: 'Check me out'
      }
    }
  ];
```

```html
<formly-form model="vm.user" fields="vm.userFields">
  <button type="submit" class="btn btn-default" ng-click="vm.submit(vm.user)">Submit</button>
</formly-form>
```

This works:

```javascript
  $scope.user = {
    email: 'jesse@jkad.com'
  };

  $scope.userFields = [
    {
      key: 'email',
      type: 'input',
      templateOptions: {
        type: 'email',
        label: 'Email address',
        placeholder: 'Enter email'
      }
    },
    {
      key: 'password',
      type: 'input',
      templateOptions: {
        type: 'password',
        label: 'Password',
        placeholder: 'Password'
      }
    },
    {
      key: 'file',
      type: 'file',
      templateOptions: {
        label: 'File input',
        description: 'Example block-level help text here',
        url: 'https://example.com/upload'
      }
    },
    {
      key: 'checked',
      type: 'checkbox',
      templateOptions: {
        label: 'Check me out'
      }
    }
  ];
```

```html
<formly-form model="user" fields="userFields">
  <button type="submit" class="btn btn-default" ng-click="submit(user)">Submit</button>
</formly-form>
```

**Comment by ckniffen** [comment]
Are you using controllerAs syntax?  If you are not that could cause the issue you are seeing.

**Comment by sharpmachine** [comment]
No I'm not.  But everything is working as expected so is it an issue?  Am I meant to be using controllerAs syntax?  Or am I good?

**Comment by ckniffen** [comment]
You don't have to use controllerAs to work with formly.  The examples are just typically written that way.

**Comment by sharpmachine** [comment]
Okay, just checking.  I'm new to Angular.  Thanks for your help.

**Comment by kentcdodds** [comment]
I highly recommend you use controller as syntax. :-) good luck!

**Comment by sharpmachine** [comment]
Thanks @kentcdodds!  Can you explain why controller as syntax is better or point me to a good article that does?  I'd appreciate it.

**Comment by kentcdodds** [comment]
This article by @pascalprecht talks about bindToController but it references some benefits of controllerAs as well: http://blog.thoughtram.io/angularjs/2015/01/02/exploring-angular-1.3-bindToController.html

**Comment by sharpmachine** [comment]
Thanks @kentcdodds.  Much appreciated.  Loving Formly too...great stuff.

**Comment by kentcdodds** [comment]
:+1: glad to hear it!

**Comment by PascalPrecht** [comment]
@sharpmachine `controllerAs` is considered best practice in Angular. It solves basically your `vm = this` problem, since that has been always a work-around.

Thanks @kentcdodds for mentioning our article :)

**Comment by mweels** [comment]
I seem to be having the same problem, I have setup my controller as.  Anything else that would cause fields not to show up?  My controller is wired up fine.  I am not using routes (not sure if that is a required).

**Comment by kentcdodds** [comment]
Could you provide an example of what you're doing? It's easier to help
identify what's going wrong when I can see what you're doing.

http://help.angular-formly.com

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by austinstudio** [comment]
This was huge for me.  Not sure why I should have to do this but I had to do the following in my app where I was using routes.

	$routeProvider
		.when('/home', {
			templateUrl: 'views/main.html',
			controllerAs: 'ctrl',
			controller: 'homeCtrl'
		})

And then on my page I had to use the following:

    <form ng-submit="ctrl.onSubmit()" novalidate>
        <formly-form model="ctrl.user" fields="ctrl.userFields" form="ctrl.userForm">
            <button class="btn btn-primary" type="submit" ng-disabled="ctrl.userForm.$invalid">Submit</button>
        </formly-form>
    </form>

Notice the "ctrl" stuff I had to add to make my form show up.  Is this the only way to do this?  I tried to follow other examples where people used "vm.userFields" directly without the extra controllerAs and extra . syntax.  At least this thread helped me figure this out.  I guess the tutorial I was following was just outdated.

**Comment by benoror** [comment]
You might want to take a look at:

* https://github.com/johnpapa/angular-styleguide#controllers
* https://github.com/toddmotto/angularjs-styleguide#controllers
