### ISSUE TITLE
UI-select breaks in angular 1.4.0

### ISSUE THREAD

**Issue by dev229** [formly-js/angular-formly#335]
Hi,

First of all, thank you for your work. Saves ton of time, and makes code so much more maintainable! :)

I just came across an issue, that seems to be specific to angular 1.4.

    "Error: [$compile:ctreq] http://errors.angularjs.org/1.4.0/$compile/ctreq?p0=select&p1=ngOptions

Here's a jsbin (using the UI-select  example from angular-formly.com, with just one change -- changed angularjs to version 1.4)
http://jsbin.com/dikoribeku/1/edit?html,console,output

Thanks!

**Comment by benoror** [comment]
Hi! I'm a collaborator from [angular-formly](http://angular-formly.com/#/) and author of the [original example](angular-formly.com/#/example/integrations/ui-select).

Thanks for spotting the issue, could you isolate it without involving angular-formly at all?

**Comment by kentcdodds** [comment]
Closing this issue. If you want to keep it tracked, please put it on the formly-js/angular-formly-website repo :-)

P.S. Thanks for your help @benoror!
