### ISSUE TITLE
Model in nested fieldGroup

### ISSUE THREAD

**Issue by Quji** [formly-js/angular-formly#336]
Hello,

As far as I see, there is no way to access whole model from inner fieldGroup when it has a "key". And its very important when you make conditional field groups.

I made jsbin as example: http://jsbin.com/reditagidi/1/edit?js,output
Deleting 'key' makes everything work as expected

**Comment by kentcdodds** [comment]
You'll have to pass it in somehow so it can be referenced. Here's one way you could accomplish that: http://jsbin.com/wehiro/edit

**Comment by kentcdodds** [comment]
However, this is not the place to ask questions, if you have further questions, I suggest that you checkout http://chat.angular-formly.com, http://mailing-list.angular-formly.com, or post on stackoverflow with the `angular-formly` tag. (Watch [this screencast](https://www.youtube.com/watch?v=NXqFiSeBE-M&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH&index=2) for more info)
