### ISSUE TITLE
dependent dropdown ?

### ISSUE THREAD

**Issue by Revln9** [formly-js/angular-formly#345]
hi, first of all thank you  this is awesome ! i would like to know how i can achieve  dependent dropdown properly in formly  like one category dropdown that populate a second dropdown of sub categories ? it would be great if you can make an example out  of this ! thanks again & keep it up ^^

**Comment by benoror** [comment]
http://jsbin.com/jinaca/1/edit?js,output

On Tue, Jun 9, 2015, 20:03 Revln9 <notifications@github.com> wrote:

> hi, first of all thank you this is awesome ! i would like to know how i
> can achieve dependent dropdown properly in formly like one category
> dropdown that populate a second dropdown of sub categories ? it would be
> great if you can make an example out of this ! thanks again & keep it up ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/345>.
>
-- 

Sent from my phone
Benjamin Orozco - benoror.com

**Comment by Revln9** [comment]
awesome ! thanks for the quick reply ! you should put this on top of the examples list  ! a very good one

**Comment by benoror** [comment]
I just happened to answer that issue a few days ago: https://github.com/formly-js/angular-formly/issues/326#issuecomment-109312896

This has been asked before few times (including me), @kentcdodds shall we add this example to the webpage?

**Comment by kentcdodds** [comment]
Would be a good example I think! Thanks!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by benoror** [comment]
http://angular-formly.com/#/example/other/cascaded-select

**Comment by ObaidUrRehman** [comment]
It seems to be adding empty items to the State drop down every time I select a different state. Here is how to reproduce it:

1. Select United States from the country drop down.
2. Select any state from the state drop down.
3. Select any other option from the country except United States.
4. Select United States again from the country drown down.

Notice how the state drop down list now has 2 empty options. It goes away if you select an option. Any idea why this is happening?

**Comment by benoror** [comment]
Corrected, I had an empty object appended at the end of the dummy DataService. Anyway, it wouldn't matter for a real ajax service.

**Comment by ObaidUrRehman** [comment]
Thanks @benoror. Much appreciated.

**Comment by kentcdodds** [comment]
Agreed! Much appreciated @benoror :-)

-Kent C. Dodds

**Comment by benoror** [comment]
No problemo :smile:

**Comment by een54** [comment]
Can you fix the example? It's complaining about you using https while embedding.

I can access it by going to http://jsbin.com/jinaca but there's no explanation or source.

**Comment by benoror** [comment]
Actually many other JSBin examples are throwing the same error

On Wed, Aug 19, 2015, 06:14 Ian Hitchcox <notifications@github.com> wrote:

> Can you fix the example? It's complaining about you using https while
> embedding.
>
> I can access it by going to http://jsbin.com/jinaca but there's no
> explanation or source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/345#issuecomment-132550230>
> .
>
-- 

Sent from my phone (sorry for possible typos)
Benjamin Orozco - benoror.com

**Comment by een54** [comment]
Isnt it fixed by changing it to http?

**Comment by kentcdodds** [comment]
@een54, the problem is that by default we embed the jsbins using SSL, however that requires a pro account. I should probably just remove the SSL default...

**Comment by kentcdodds** [comment]
I'm pushing out an update that will make all of the examples not use SSL. Maybe one day we'll bring that back...
