### ISSUE TITLE
Changing form fields programmatically

### ISSUE THREAD

**Issue by ejchet** [formly-js/angular-formly#352]
I would like to change the form fields in the controller on the fly;

Example:

var data =  {
        key: 'id',
        type: 'input',
        templateOptions: {
            label: 'Id'
    }
};

vm.clicked = function() {
    vm.fields.push(data);
    alert(JSON.stringify(vm.fields), null, 2);
};

I currently don't see how to tell formly to render the page now that the fields have been updated.

Thanks,

Eric

**Comment by kentcdodds** [comment]
Hmmm... I think that what you're suggesting is actually not what I thought you were asking. Could you please provide [an example](http://jsbin.com/biqesi/edit) of the problem you're seeing? You should be able to add/remove fields from a formly-form. Though, I've never done it myself, I think it should work (I seem to remember seeing others do it).

**Comment by ejchet** [comment]
Well I guess you can close this, it worked when I put it in jsbin looks like I had a local issue.

http://jsbin.com/yepisa/edit?output

**Comment by kentcdodds** [comment]
Good luck!

**Comment by hamidpp** [comment]
hi: i want add dynamically field to form 👍 

<formly-form model="model" fields="userFields" options="options" form="form" track-by="$index">
     <button type="submit" class="md-btn md-btn-success md-btn-wave-light waves-effect waves-button waves-light">Submit</button>
  </formly-form>

$scope.userFields = [
{
                  // the key to be used in the model values
                  // so this will be bound to vm.user.username
                  key: 'username',
                  type: 'input',
                  templateOptions: {
                      label: 'نام کاربری',
                      placeholder: 'user name',
                      required: true,
                      description: 'Descriptive text'
                  }
              },
]

$scope.addField = function(){

$scope.userFields.push({
                    key: 'submit',
                    type: 'button',
                    templateOptions: {
                        label: 'label-text'
                    }
                })

}
