### ISSUE TITLE
Ability to use 'wrapper' property with 'fieldGroup's

### ISSUE THREAD

**Issue by jpuzzo** [formly-js/angular-formly#354]
The way my form is set up, this would be a huge help, as I plan on wrapping bootstrap accordions around the 'fieldGroup's I have.

**Comment by benoror** [comment]
Can you provide a JSBin example (as explained in [CONTRIBUTING.md](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#reporting-bugs--requesting-features)) while using [template-wrappers](http://angular-formly.com/#/example/advanced/template-wrappers) along with [fieldGroups](http://docs.angular-formly.com/v6.4.0/docs/field-groups)?

**Comment by ckniffen** [comment]
@jpuzzo You can achieve the same effect by having a type that has a template that contains a formly-form.  This example shows how to achieve something similar http://angular-formly.com/#/example/advanced/repeating-section.

**Comment by jpuzzo** [comment]
Here's an example of what I'm trying to accomplish:
http://jsbin.com/gumodedito/1/edit?html,js,output

I apologize for not initially creating one, as jsbin is blocked on my company's network.

@ckniffen After seeing the jsbin above, does making an additional formly-form still make sense?  I am already needing to create several of them for other purposes as it is...so the simpler the better.  If it's the only way to do it at this point, if you could shoot me a quick example of how I'd use accordions per new type (wrapping fields within the type with accordian-group), that would be helpful.

Thank you,
Jeff

**Comment by ckniffen** [comment]
At this moment the feature doesn't exist.  There have been several requests for but it has been put off due to the custom type method working in the interim.  I will try to coming up with something.  Essentially fieldGroup is an api that sits outside of the lifecycle of a field and as such does not have many of the features you would find in the field api.

https://github.com/formly-js/angular-formly/blob/0e400b65b86f02840ba045efbe5c21162c6b4c33/src/directives/formly-field.js#L36-L39

**Comment by jpuzzo** [comment]
So this is essentially what I was trying to accomplish:
http://jsbin.com/butotacabi/1/edit?html,js,output

Thanks @ckniffen for the reference to the 'repeating section' example which allowed me to work backwards to reach the conclusion linked above.  I'm not sure if there was an easier way to apply a unique header title per section, but it's all that came to mind at the time.

**Comment by ckniffen** [comment]
@jpuzzo Looks great.
