### ISSUE TITLE
maxlength isn't being applied on input field even  formlyConfig.extras.ngModelAttrsManipulatorPreferBound = true 

### ISSUE THREAD

**Issue by asadsahi** [formly-js/angular-formly#355]
As discussion on gitter below, I am raising this issue:
would you reckon, <input type="text" ng-model="model[options.key]" maxlength="{{options.templateOptions.maxlength}}"> to be the solution or should I use another approach?
yes, I saw minlength attribute applying correctly though.
ckniffen 15:33
could you open up a ticket about it?
If you were to do that it wouldnt work
there can be issues with maxlength being an interpolation
https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.js#L135
I found this in the changelog "Because the attribute html maxlength prevents the user from inputing anything longer than the specified length, formlyNgModelAttrsManipulator allows you to specify that you want to use the bound version only (i.e. ng-maxlength). This adds a watcher, but is a better user experience. Set formlyConfig.extras.ngModelAttrsManipulatorPreferBound = true to enable this."

**Comment by kentcdodds** [comment]
Thanks for the bug report. Could you please [provide an example](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#reporting-bugs--requesting-features) of the bug?

**Comment by ckniffen** [comment]
@asadsahi did you try adding formlyConfig.extras.ngModelAttrsManipulatorPreferBound = false?

**Comment by asadsahi** [comment]
@kentcdodds first field in this example.....http://jsbin.com/vozucodoba/edit?js,output

@ckniffin yes, tried with both true and false


Man i am lovin formly as much as support from community :).. thanks

**Comment by ckniffen** [comment]
This seems to be a case of incorrect documentation.  The property should be `formlyConfig.extras.ngModelAttrsManipulatorPreferUnbound = true`.

**Comment by kentcdodds** [comment]
Whoops! Sorry about that! I'll fix the docs now.

**Comment by ckniffen** [comment]
I just submitted a change request on the docs.

**Comment by kentcdodds** [comment]
I changed some of the wording. Thanks! I think I'm going to remove that in a breaking release... No reason you should want that. Does this solve your problem @asadsahi?

**Comment by ckniffen** [comment]
Still has a typo ...

Also I think it should still remain as a feature.

**Comment by kentcdodds** [comment]
Thanks for the tip! :disappointed_relieved:

**Comment by asadsahi** [comment]
Hi Kent & @ckniffen Yes, using 
`formlyConfig.extras.ngModelAttrsManipulatorPreferUnbound = true`
.. has resolved it. Should I keep on using this global setting or keep an eye on breaking change?

**Comment by kentcdodds** [comment]
No, I think we'll keep it around :-) Looks like you're using it.

**Comment by asadsahi** [comment]
Thanks :)
