### ISSUE TITLE
Add option for templateManipulator to ignore specific ng-model

### ISSUE THREAD

**Issue by mikejpeters** [formly-js/angular-formly#358]
Sometimes custom templates may involve multiple directives referring to the same `ng-model`.  For example:

```html
<div class="dropdown">
    <input ng-model="model[options.key]">
    <a data-toggle="dropdown">Click here to show calendar</a>
    <ul class="dropdown-menu">
        <datetimepicker ng-model="model[options.key]"></datetimepicker>
    </ul>
</div>
```

In this situation, formly adds the same attributes to both the `input` and `datetimepicker`.

We can tell the manipulator to skip ALL attributes using `skipNgModelAttrsManipulator`, but what we really want is to just ignore the one on `datetimepicker`.

It would be great to be able to add an attribute to the actual element so it is ignored:

```html
<datetimepicker ng-model="model[options.key]" formly-skip-ng-model-attrs-manipulator>
```

**Comment by kentcdodds** [comment]
Very good. I like the suggestion. I'd be happy to pull this concept in. I'll try to get to it as soon as I am able. If you want to try your hand at a PR, see CONTRIBUTING.md and the changes will likely be around here: https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.js#L17

**Comment by kentcdodds** [comment]
Like with #343, I've created tests for this feature and I'm going to give someone a shot at contributing to open source for the first time :-)

Instructions:

- [ ] Watch [this video](https://www.youtube.com/watch?v=QOchwBm9W-g&index=5&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) to learn what you need to do to get things setup
- [ ] Go to [these tests](https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.test.js#L30-L57) and change `it.skip` to `it.only`
- [ ] Run `$ npm test`
- [ ] Notice that all the tests are failing
- [ ] Update the [formlyNgModelAttrsManipulator](https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.js) to make the tests pass.
- [ ] Once they're passing, change the `it.only`s to `it`s so all the tests run.
- [ ] Commit your changes to the `src/` directory mentioning issue #343 (notice it runs all the tests... twice)
- [ ] Push your changes to your fork, create a PR, get merged, celebrate 🎉

I'm happy to hold your hand through this if you need help. [Catch me on gitter](https://gitter.im/kentcdodds).

**Comment by kentcdodds** [comment]
P.S. I've already developed the solution locally so I know it's possible :-)

**Comment by kentcdodds** [comment]
@douglas-mason committed this! Thanks!

**Comment by kentcdodds** [comment]
This will be released as soon as I'm able

**Comment by kentcdodds** [comment]
This has been officially released in `6.16.0`. Docs have been [updated](http://docs.angular-formly.com/v6.16.0/docs/ngmodelattrstemplatemanipulator#disabling).

**Comment by koenweyn** [comment]
Hi @kentcdodds, the fix for this breaks IE8 compatibility.
`querySelectorAll(':not()')` is not supported, because it is a CSS3 selector: [Can I Use?](http://caniuse.com/#feat=queryselector).
I have implemented a fix that builds the nodelist in a different way when the current method throws an Exception.
Would you be interested in that PR? Or are you tired of trying to support IE8? ;-)

**Comment by kentcdodds** [comment]
> Would you be interested in that PR? Or are you tired of trying to support IE8?

Both :-) Thanks!
