### ISSUE TITLE
Flexible setting of attributes for parent container

### ISSUE THREAD

**Issue by maku** [formly-js/angular-formly#359]
E.g. for using formly with angular material design I would need e.g. the following to achieve a responsive design. 

```
            <div layout-padding layout="row" layout-sm="column">
                <md-input-container>
                    <label>Title</label>
                    <input ng-model="user.title">
                </md-input-container>
                <md-input-container>
                    <label>Email</label>
                    <input ng-model="user.email" type="email">
                </md-input-container>
            </div>
```

It seems that it is necessary to set attributes on the parent container. How can I do this with angular-formly?

**Comment by kentcdodds** [comment]
I created an example that does this for you :-) http://angular-formly.com/#/example/integrations/angular-material

As always, help is welcome on the template library :D

**Comment by maku** [comment]
Wow, really cool, thank you....
