### ISSUE TITLE
multiCheckbox does not populate values when checkbox values are async

### ISSUE THREAD

**Issue by m0t0r** [formly-js/angular-formly#365]
Working with `multiCheckbox` I found an issue. As demonstrated in this [jsbin](http://jsbin.com/janeha/edit?html,js,output). In the first case, I predefine checkbox values in options array, and then I simulate async population of the values and in the UI we can see checked checkbox. In the second case I simulate async loading of the checkbox values and when I populate values, the checkbox is not checked.

**Comment by kentcdodds** [comment]
I think this is an issue with the template library, not angular-formly.
Could you move this issue to the template library please?
https://github.com/formly-js/angular-formly-templates-bootstrap

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by m0t0r** [comment]
Sure, thank you

**Comment by m0t0r** [comment]
This issue is [moved](https://github.com/formly-js/angular-formly-templates-bootstrap/issues/32) to angular-formly-templates-bootstrap repo.
