### ISSUE TITLE
Move all ng-model element attributes to a new property

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#376]
This is kind of a crazy idea and it would definitely take some time for people to migrate so don't worry, I'm thinking about all of these things...

But at the same time, I want to make angular-formly more straightforward in the v7.0.0 release if I can. So here's what I'm thinking:

**Before**:

```javascript
vm.fields = [
  {
    type: 'input',
    key: 'emailAddress',
    templateOptions: {
      type: 'email',
      required: true,
      label: 'Email Address',
      description: 'Please input your email address so we can spam you',
      onClick: function() {
        alert('I know! How mean is that!?');
      }
    }
  }
];
```

**After**:

```javascript
vm.fields = [
  {
    type: 'input',
    key: 'emailAddress',
    templateOptions: {
      label: 'Email Address',
      description: 'Please input your email address so we can spam you'
    },
    ngModelAttrs: {
      type: 'email',
      required: true,
      onClick: function() {
        alert('I know! How mean is that!?');
      }
    }
  }
];
```

I realize that `ngModelAttrs` exists as a property already. But this is the name that makes most sense to me. Think less about the naming and more about the concept. What do you think of the idea that anything you would normally place on the element with `ng-model` you would put in `ngModelAttrs` rather than sort of mixing it with `templateOptions`?

The fact that those things exist as `templateOptions` was kind of a mistake in design and sort of happened, because the `templateOptions` is supposed to be reserved for template authors (except for the few things that the `ngModelAttrsTemplateManipulator` and a few other directives do with it apparently)...

I personally think this is much more straightforward and easier to learn. Simply stated, anything you normally would place on the `ng-model` element has a counterpart in `ngModelAttrs`.

This would be a pretty significant change, but I believe that it would make the library more approachable. I'm anxious to hear what people have to say (even if it's just a :+1:, that's still helpful).

**Comment by kentcdodds** [comment]
Note, this wouldn't be without a migration path. Because of the `fieldTransform` functionality, I could provide a workable fieldTransform (with instructions/an example on how to use it) that you could copy to your project and slowly migrate the forms in your project over time. It wouldn't be perfect, but I think it would work well. So don't let that part scare you. I'm more concerned about the idea. Do you think this would make angular-formly more approachable/simple/maintainable/etc.?

**Comment by mhartington** [comment]
I'm all for it. Makes more sense that putting everything under templateOptions. So how would this effect custom templates? Either way, you get my :+1:

**Comment by kentcdodds** [comment]
Hopefully most templates will require very few changes. The idea of most of these attributes is that they would be dynamically added to the `ng-model` element(s) in the template so the templates don't have to concern themselves with them. But I know at least the bootstrap templates' [label](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/wrappers/label.html#L4) wrapper uses `required` and would require updating. But that would be trivial and I would likely make a shortcut for this new property (like the `to` shortcut for `options.templateOptions`, we'd probably have `ma` for `options.ngModelAttrs` or something like that).

**Comment by mhartington** [comment]
So safe to say that this change would be more internal?

**Comment by kentcdodds** [comment]
Not quite, but from a template author's perspective, you should hopefully have just a few places to update things. Unfortunately, from a user's perspective, many field properties that used to live in `templateOptions` would go to `ngModelAttrs` instead. As I said, I'd make a demonstration of a  `fieldTransform` that would allow you to make that transition over time, but eventually you'd want to rewrite all of your field configuration objects to resemble the new format.

**Comment by maku** [comment]
Principally, I find the approach good because it seems more logical to me.
Because of I write the JSON not manually (I hide JSON creation behind a formbuilder) - this should not have so much impact for me.

**Comment by beazergood** [comment]
Thumbs up

**Comment by redhead** [comment]
I agree with this change as it is more logical and straightforward. :+1: 
However, I really have a problem with the name ngModelAttrs :D Imagining it all over the place in my field configs, it seems ugly, long, and too complicated for me. Although I can't figure out any other name than `attrs` which isn't explaining it well.

**Comment by kentcdodds** [comment]
I agree @redhead, I don't like the name either (especially since it's already in use and it seems long and ugly to me too). I'd love suggestions on a better one... Perhaps we can consider something that would make sense in both an angular 1 and angular 2 context...

**Comment by mhartington** [comment]
What about just `modelAttrs` or `formAttrs`? I don't think it needs to have the `ng-` prefix.

**Comment by kentcdodds** [comment]
Hmmm... I'll have to think on that a little more. I'm trying to think what would be most obvious for a new comer... `ngModelAttrs` is the best name I can think of for someone new to angular-formly but used to angular forms...

**Comment by dwolt** [comment]
I'm curious why it would be better for the user (developer) to have to know
both the name of a "parameter" and the classification of it. Unless these
tuples (templateOptions, ngModelAttrs) have optional cardinality > 1, why
make the user group them? If there are namespace type issues or the
internals need to separate them into groups to pass them to different
processors, then a prefix should suffice. My suggestion would be to put
them all just one level deep (unless there are repeating groups). I will
grant that I am not giving a second of attention to the coding behind the
scenes -- I'm just speaking as a user.

--dawn

On Mon, Jun 29, 2015 at 9:30 PM, Kent C. Dodds <notifications@github.com>
wrote:

> Not quite, but from a template author's perspective, you should hopefully
> have just a few places to update things. Unfortunately, from a user's
> perspective, many field properties that used to live in templateOptions
> would go to ngModelAttrs instead. As I said, I'd make a demonstration of
> a fieldTransform that would allow you to make that transition over time,
> but eventually you'd want to rewrite all of your field configuration
> objects to resemble the new format.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/376#issuecomment-116916849>
> .
>



-- 
Dawn M. Wolthuis

Take and give some delight today

**Comment by kentcdodds** [comment]
@dwolt, your perspective as a user is exactly what I'm trying to get, so thanks for sharing!

Originally, angular-formly didn't have any kind of structure for its options. If you wanted to create a new template, you would just add your own property to the field config object and life was good. Until the angular-formly core library comes around and decides to use a property of the same name for some other purpose and now you're stuck.

For example, let's imagine that you decide you want to make a special input that allows you to react when when you type into the input. You would probably add an `onKeyup` property to the field config and use that:

```javascript
{
  type: 'datepicker',
  onKeyup: function(event) {
    if (event.which === 32) {
      console.log('space typed!!');
    }
  }
}
```

Then angular-formly comes along and decides to add this to all fields, but makes the function arguments different. Instead of passing the event, it passes the `$viewValue` or something. Or perhaps angular-formly processes your field differently because that field exists. This would prevent you from upgrading until you refactored all of your fields.

Hopefully that makes sense and builds a case for the separation as well as the use of api-check in this project. I force you to place your own stuff in either `data` or `templateOptions` and I let you have full reign over those objects. Except in the case of `templateOptions`, there are properties that angular-formly uses to do some of its magic. Which sort of reintroduces the original issue. Which is why I'm suggesting this change would be worth the migration.

Does that make sense? Any holes in my logic? Is it not worth it?

Asside from that, the `templateOptions` stuff is a little magical and is something that you must learn. It's not really intuitive. Something like `ngModelAttrs` makes a lot of sense. You just think to yourself: "What would I normally put alongside the `ng-model` element, there's probably a property for that."

**Comment by rmulder** [comment]
The only comment I have on this Kent - is that we are still working on migrating our code to be able to work on a version of formly beyond 6.13.1. The deprecation of support for 'hide' under expressionProperties and replacing it with hideExpression was *not* a straight-forward, one-to-one change as suggested (i.e., the function version) - and so has required us to refactor a bunch of code (we use server-side generated JSON), as we had depended heavily on that feature for hiding/showing certain elements based on certain user criteria.

My only concern with this change proposal is that there truly is a 'migration path' that works out of the box. Otherwise - developers may struggle to get their code updated while 'deadlines' are pressing on them, and therefore might be unable to take advantage of newer features for quite awhile. (Once bitten, twice shy)

This is truly an awesome library, but as an outsider recently pointed out to us - a library that is still very much 'under development'. While I cannot disagree in principle with the proposed change and the goal it seeks to achieve - I submit that the change itself would need to provide as *painless* an upgrade path as possible for those who are already heavily entrenched with previous versions of the library. You have 'sculptured' something that is truly a beautiful 'work of art' - and for that, as I'm sure my fellow developers would agree - we are truly grateful.

Therefore I would vote that yes, it's important to get the API 'nailed down' so that the functionality it provides 'makes sense' going forward - but I suggest that it's more important as these types of changes are made, to provide a solid migration path/clear upgrade instructions for those already heavily using older version(s).

**Comment by kentcdodds** [comment]
@rmulder, I cannot express how sorry I am that the change to `hideExpression` didn't work for you. I remember you mentioning having difficulties with it, but I didn't realize how wide sweeping a change that was for you. The reason it didn't result in a breaking change was the old way still works just as it did before, so you can stick with that. And I could add something that allows you to disable the warning formly now gives if you try to use `hide` in an expressionProperty if you want. I'm just so so sorry that this  has caused you grief :-(

I appreciate you voicing your opinion and I will make sure that this upgrade is as painless as possible. I'm confident that a `fieldTransform` could quite easily make this work out of the box (you'd just copy/paste the field transform and it should work for you).

One thing I wish to clarify is that this library is not "under development." This library works really really well and I could stop working on it and people would benefit from it for as long as angular 1.x is around. It is, however, being developed and improved. I just want to reiterate that angular-formly is no more "under development" as angular is. It's solid and it honors semver. I expect this isn't what you meant @rmulder, but I want to make it clear that angular-formly is a production-ready library :+1: :-)

**Comment by dwolt** [comment]
Yes, that does make sense. If all of the delivered attributes were "at the
top" and custom attributes had their own embedded tuple, that would
accomplish things without the old-fashioned (but tried and true) use of
different prefixes, either for the delivered code ("ng" for example) or for
custom additions (I recall prefixes of "x" or "z").

If you further want us to grok that there are various types of attributes,
prefixes can be used for that too. Requiring "me" to find not only the name
of an attribute but the right classification to file it under seems
unnecessary. I'll give you the name and you can file it in the right spot
and process as needed.

key:
type:
toLabel:
toPlaceholder:
customAttrs: {
  myStuff:
  namedWhatever:
  toBecause:
}

Make the api easy for the developer and cling to backward compatibility and
developers will appreciate it.  --dawn

On Tue, Jun 30, 2015 at 10:32 AM, Kent C. Dodds <notifications@github.com>
wrote:

> @dwolt <https://github.com/dwolt>, your perspective as a user is exactly
> what I'm trying to get, so thanks for sharing!
>
> Originally, angular-formly didn't have any kind of structure for its
> options. If you wanted to create a new template, you would just add your
> own property to the field config object and life was good. Until the
> angular-formly core library comes around and decides to use a property of
> the same name for some other purpose and now you're stuck.
>
> For example, let's imagine that you decide you want to make a special
> input that allows you to react when when you type into the input. You would
> probably add an onKeyup property to the field config and use that:
>
> {
>   type: 'datepicker',
>   onKeyup: function(event) {
>     if (event.which === 32) {
>       console.log('space typed!!');
>     }
>   }
> }
>
> Then angular-formly comes along and decides to add this to all fields, but
> makes the function arguments different. Instead of passing the event, it
> passes the $viewValue or something. Or perhaps angular-formly processes
> your field differently because that field exists. This would prevent you
> from upgrading until you refactored all of your fields.
>
> Hopefully that makes sense and builds a case for the separation as well as
> the use of api-check in this project. I force you to place your own stuff
> in either data or templateOptions and I let you have full reign over
> those objects. Except in the case of templateOptions, there are
> properties that angular-formly uses to do some of its magic. Which sort of
> reintroduces the original issue. Which is why I'm suggesting this change
> would be worth the migration.
>
> Does that make sense? Any holes in my logic? Is it not worth it?
>
> Asside from that, the templateOptions stuff is a little magical and is
> something that you must learn. It's not really intuitive. Something like
> ngModelAttrs makes a lot of sense. You just think to yourself: "What
> would I normally put alongside the ng-model element, there's probably a
> property for that."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/376#issuecomment-117229970>
> .
>



-- 
Dawn M. Wolthuis

Take and give some delight today

**Comment by rmulder** [comment]
@kentcdodds No worries Kent. We just have data stored in rows that contain the 'field logic' for the application (i.e., a data-driven application). It just took time to track down all the locations we were using this hideExpression and convert them, as well as the server-side code doing the JSON generation, and then updating the client side/removing that dependency. I *think* it's pretty much been cleaned up by now, but just have to verify before doing the version upgrade.

I guess I should have used wording other than 'under development'. I only meant that the project has been very actively evolving/changing (i.e., witness all of the version changes made in just the past few months) - not in a bad way per se, but that was just the observation made by an outside party that made my boss a bit 'nervous'. 

As shown by the above rework required in our project, when an API is growing/changing like this, and you want to adopt the 'latest and greatest' - then there usually tends to be a little 'pain' involved in the upgrade process. That's all.

**Comment by MacKentoch** [comment]
I agree with the logic behind `ngModelAttrs`. 

To be honest, when I started using angular formly I did not understand why `required` was defined in `templateOptions` as it is more model orientated.

To be honest again (I'm very honest you know?! ^^), it will make a bit of change on my side but it is worth the pain so :+1: 


**By the way, it gives me the idea to store in database with the model which angular formly it is related.**

Example :

    {
      model : {**a data model here**},
      formlyRangeVersion: '<7.0.0'
    }
 
> like that even a hard change won't affect my old data, that I would render with a compatible version or give a message to user.

**Comment by redhead** [comment]
> ngModelAttrs is the best name I can think of for someone new to angular-formly but used to angular forms...

@kentcdodds What about `controlAttrs`. ngModel is an attribute that specifies the model for the control, but abstracted away it is represented by a "form control". FormController in angular also uses the name control in registration functions etc. It is not so obvious, but it still gives a hint that it is related to the control itself and not the wrappers or whatever.

**Comment by kentcdodds** [comment]
Good thoughts everyone. Thanks for providing feedback (keep it coming). I'm going to think on this for a bit and I'll get back to you with what I decide on.

**Comment by ckniffen** [comment]
I am against the change.  The reason being is that more implementation details now need to be known in order to know which object to place properties.  For example `placeholder` is an attribute normally placed on an element with a `ngModel` but doesn't have to be as is the case with ui-select.  Also you have said that required can be used for both `ngRequired` as well as in wrappers for styling.

The way my team uses it is we define types and the completely different teams build the forms.  So far the only issues we have run into has been around hide/hideExpression which make sense to be edge cases.

If this change goes through we will likely use the fieldTransform which is mentioned above.

**Comment by kentcdodds** [comment]
@ckniffen, you've convinced me with this line:

> The reason being is that more implementation details now need to be known in order to know which object to place properties.

I want to try really hard to not force people to know implementation details. For that reason, I'm closing this issue.

Big thanks to everyone who dropped their opinion in here. Note, I do intend to implement #378 which should make it easier to add custom attributes to the `ng-model` element. Feel free to read up on that and drop an opinion on there. That will *not* be a breaking change :-)

**Comment by kentcdodds** [comment]
Also, I intend to implement adding the `extras` property onto the field configuration object. This object would be apiChecked by formly (as opposed to the `templateOptions` and `data` properties) and would be used to configure stuff that's specific to angular-formly core (rather than a template library). (Though, having just written that, it sounds like implementation details, but I think this is one case that we can make an exception due to the fact that these are edge cases).
