### ISSUE TITLE
hideExpression not called when model property specified

### ISSUE THREAD

**Issue by redhead** [formly-js/angular-formly#380]
I am not sure if this is correct, but I think hideExpression is not called on model update when the model property in field config is specified (different from the form model).

if I use expressionProperties: hide, it works ok.

**Comment by kentcdodds** [comment]
This is indeed a bug. I'm on vacation, so I can't look at this now, but a
tested PR would be welcome.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by redhead** [comment]
Hi, I think I've got the bug sorted out, but I am not orienting myself in tests much here.

**Comment by kentcdodds** [comment]
The bug should probably be fixed in the `formly-form`, so the fix should go in `formly-form.test.js` in a new `describe('hideExpression')` block right above [this line](https://github.com/formly-js/angular-formly/blob/b07e49c0642894bad920bde350adfeb9bd16084c/src/directives/formly-form.test.js#L361).

**Comment by redhead** [comment]
Ok I will look at it, thanks.

**Comment by juanpujol** [comment]
A question, does this has anything to do with the fact that if I hide an input using hideExpression the model is not updated? If I remove the `name` input shouldn't that property be removed from the model too? I'm doing it manually using `delete scope.model.name` from hideExpression. But I'm sure must be a better way, right?

Thank you.

**Comment by kentcdodds** [comment]
This has been discussed before and angular-formly has decided to not alter the model based on whether a field is hidden. Modifying the model willy-nilly is too much magic and doesn't account for varying use-cases. So yes, you'll have to keep doing that manually if that's what you want.

**Comment by juanpujol** [comment]
ok, @kentcdodds thank you.

**Comment by kentcdodds** [comment]
Any progress on this @redhead?

**Comment by redhead** [comment]
Done it, had to send a new pull request for some reason.

**Comment by kentcdodds** [comment]
I've re-opened this so I don't forget to release it tomorrow.

**Comment by kentcdodds** [comment]
This has been released in `6.22.0`. Thanks again for the PR!

**Comment by redhead** [comment]
You're welcome.
