### ISSUE TITLE
Custom value (getter/setter) function in field config object is ignored

### ISSUE THREAD

**Issue by prokilogrammer** [formly-js/angular-formly#383]
If I implement the value function as specified [here](http://docs.angular-formly.com/v6.16.0/docs/field-configuration-object#value-gettersetter-function), it is never applied on the model. Example: http://jsbin.com/setesezuqi/1/edit?html,js,output. 

Looking under the hood, [`extendOptionsWithDefaults`](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L136) in formly-field.js overwrites my custom function with the default `valueGetterSetter()`. 

If this hasn't been fixed yet, I can submit a PR

**Comment by kentcdodds** [comment]
@prokilogrammer, I'm sorry, but this is actually how it's supposed to work. The docs aren't very clear, but if you look above the docs for `value`, there's a callout that says:

>  Added Properties
> The properties listed below are added to your field configuration.

Meaning that you shouldn't override them, but they are actually added. It's purpose is to be used internally to get the current value as well as when you specify `modelOptions` as specified in the docs:

Under `value`

> Useful when using getterSetter: true in the modelOptions

Under `modelOptions`

> Note, if you use the getter/setter option, formly's templateManipulator will change the value of ng-model to options.value which is a getterSetter that formly adds to field options

So I wont be accepting #383. I'm sorry :-/

Now, I think what you're wanting to do (based on your example) is use either parsers of formatters which is on the roadmap in #368.

**Comment by prokilogrammer** [comment]
Interesting. Yes, the callout isn't very clear. It might be useful to format documentation of internal properties differently to show the distinction.

**Comment by kentcdodds** [comment]
Yeah, without pushing every property down another heading level, I can't do that unfortunately... I'll see if there's a sensible obvious way to do that. Really sorry you took the time to write a PR and everything. I hope it was at least a good learning experience!

**Comment by ckniffen** [comment]
@prokilogrammer I override the  `$scope.options.value` in my controller or link if I want to define my own getterSetter.

**Comment by kentcdodds** [comment]
Curious about what the use case for a custom getterSetter is...

**Comment by ckniffen** [comment]
I have an internal and an external representation of the input.  For example I have ui-select type.  ui-select requires an array of objects but the value that gets stored on the formly model is the object's id or an array of ids.  The getterSetter handles that mapping for the type.

**Comment by kentcdodds** [comment]
Ah, that makes sense. Perhaps I'll accept the pull request after all! :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by prokilogrammer** [comment]
Cool, submitted a pull request https://github.com/formly-js/angular-formly/pull/385

**Comment by gentledepp** [comment]
Hi! I require the same functionality as I have a datepicker which stores the selected value in the same format as it was displayed. I, however,  need to convert the datetime string to an ISO date.
I could not find any documentation or samples on this. :-/
Value conversion is a huge benefit!

**Comment by kentcdodds** [comment]
Look at `defaultOptions`

**Comment by gentledepp** [comment]
Thanks for the reply.
I am using defaultOptions all the time, but where do I get the scope from?
I have:
<pre>
 formlyConfig.setType({
            name: 'kendo-datetimepicker',
            templateUrl: '/App/Core/formly-fields/kendo/formly-datetimepicker.cshtml',
            wrapper: ['bootstrapLabel', 'bootstrapHasError'],
            defaultOptions: {
                templateOptions: {
                    datepickerOptions: {
                        parseFormats: [
                            "yyyy-MM-ddTHH:mm:ss", // this is the format sent back from JSON.NET enabled web api rest service.
                            "yyyy-MM-ddTHH:mm:ss.fffZ",
                            "yyyy-MM-ddTHH:mm:ss.fffzzz",
                            "yyyy-MM-ddTHH:mm:sszzz",
                            "yyyy-MM-ddTHH:mmzzz",
                            "yyyy-MM-ddTHH:mmzz",
                            "yyyy-MM-dd"
                        ]
                    }
                },
                // the following was copied from formly-source
                // here I need
                // to get a reference to model or $scope
                // to get a reference to templateOptions as it contais the format string that I can use to parse the date string
                modelOptions: { getterSetter: true },
                value: function valueGetterSetter(newVal) {
                    if (!$scope.model || !$scope.options.key) {
                        return undefined;
                    }
                    if (angular.isDefined(newVal)) {
                        parseSet($scope.options.key, $scope.model, newVal)
                    }
                    return parseGet($scope.options.key, $scope.model)
                },
            }
        });
</pre>

**Comment by kentcdodds** [comment]
Yeah, you're not given the `$scope` in that function (and we can't give it to you either because angular calls it, not us). Do you think that you could use `parsers` and `formatters` instead?

**Comment by gentledepp** [comment]
hmmm... I am not that good in angular, so I do not know how to use parsers and/or formatters.
I solved it by introducing another directive which encapsulates the kendo-ui datetimepicker widget that causes this issue, because it stores the selected date in the display format (what did they think when programming this....)

However, I believe this is a very important aspect of binding. 
So if there was a way in angular-formly to specify a gettersetter function which gets the current $scope as parameter, that would be a HUGE benefit. ;-)

Thanks anyways
