### ISSUE TITLE
Is it possible to specify field name? 

### ISSUE THREAD

**Issue by facultymatt** [formly-js/angular-formly#386]
By default angular formly auto names your inputs, for example: 

```
formly_1_input_password_3
```

Is is possible to give this a custom name, such as:

```
password
```

**Comment by kentcdodds** [comment]
You can specify your own `id` and the name will match that. You can also keep the random `id` and instead specify a custom `name`. https://github.com/formly-js/angular-formly/blob/master/src/providers/formlyApiCheck.js#L92-L93

**Comment by kentcdodds** [comment]
Note: The github issues in this project are not for questions but rather bugs reports or feature requests. Please follow the instructions here instead: http://help.angular-formly.com

Thanks for using angular-formly :D

**Comment by facultymatt** [comment]
Thanks for the quick response! In the future I will post questions to the
designated channels, and save github for bugs and features.

On Fri, Jul 10, 2015 at 11:26 AM, Kent C. Dodds <notifications@github.com>
wrote:

> Note: The github issues in this project are not for questions but rather
> bugs reports or feature requests. Please follow the instructions here
> instead: http://help.angular-formly.com
>
> Thanks for using angular-formly :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/386#issuecomment-120436084>
> .
>



-- 
Matt Miller


Web Master
609-335-4417
matt@superpedestrian.com
https://www.superpedestrian.com/
<https://www.google.com/url?q=https%3A%2F%2Fwww.superpedestrian.com%2F&sa=D&sntz=1&usg=AFQjCNHLEDFaMLgggeXL8rh4gGlNfN0WSA>
________________
Superpedestrian Inc.
84 Hamilton St.
Cambridge, MA 02139

*This message is intended only for the addressee named above.  If you are
not the intended recipient of this message, you are hereby notified that
you must not use, disseminate, or copy it in any form or take any action in
reliance upon it.  If you have received this message in error, please
delete it and any copies of it from your email system and reply immediately
to the sender at the address shown above.  This message may contain
confidential and/or proprietary information.  Neither confidentiality, nor
any proprietary rights are intended to be waived or lost by any error in
transmission.*

**Comment by kentcdodds** [comment]
Thanks! :+1:
