### ISSUE TITLE
How to handle dynamic number of form fields with validation?

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#388]
I have a model structure like the following whereby each object can have a different number properties:
```
[
  {
    prop1: boolean,
    prop2: String,
    ...
    properties: [
      {
        key: String,
        value: String,
        description: String
      },
      ...
    ]
  },
  ...
]
```
It should be pretty straight forward to pass the array of objects to a formly type template and have formly iterate over each object's properties array (right?).  I think the tricky part would be wanting to validate each item in the properties array - with _separate_ validators.

Any thoughts on how I might do that?  The keys are well-defined so I could, in theory, create some angular service that maps a key to a `validators` object but i'm not clear how to tell formly about it.

**Comment by kentcdodds** [comment]
This is a perfect candidate for http;//help.angular-formly.com

Please keep the issues reserved for bugs and feature requests. There are many other resources for questions and help. Thanks!

**Comment by icfantv** [comment]
Sorry.  Not intended.  Where would you like me to post the follow up (and future help requests)?  I'm working on the JS Bin.  Thanks.

**Comment by kentcdodds** [comment]
No worries. http://help.angular-formly.com explains the best ways to get
help. :-)

-Kent C. Dodds

**Comment by icfantv** [comment]
Oy.  Sorry, i should have read the instructions before just starting work on the example.  Thanks for being so patient.
