### ISSUE TITLE
Validate the size of an input file

### ISSUE THREAD

**Issue by LTroya** [formly-js/angular-formly#389]
Can I validate a file input? I didn't find anything about in the docs. For example, if it is an image, I want to validate its height and width, its size, and so on. Or if video or audio its size too.

**Comment by kentcdodds** [comment]
You'll find that it's easier to first try to accomplish something without angular-formly. Then take that solution and accomplish it with angular-formly. Once you have the first solution, if you can't figure out how to integrate it with angular-formly, then create an example and ask for help on the appropriate channels (not in the github issues which are for bugs/feature requests).

Here's something to get you started and point you in the right direction to get help: http://help.angular-formly.com
