### ISSUE TITLE
Semantic UI support?

### ISSUE THREAD

**Issue by funkytaco** [formly-js/angular-formly#394]
Does this package work with Semantic UI? I see Bootstrap mentioned. 

http://semantic-ui.com/kitchen-sink.html

Thanks.

**Comment by kentcdodds** [comment]
Should work just fine. You'd have to define your own templates. See
http://learn.angular-formly.com to find out how to define custom
templates/types

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
If you're interested in creating [a template library](http://docs.angular-formly.com/docs/custom-templates#prebuilt-templates) let me know and I'll create a shell repo in the formly-js organization for you to build the library with. Let me know if you need any help :-)

**Comment by funkytaco** [comment]
Yeah sure. I'm definitely using Semantic UI since this project is underway.

**Comment by jmls** [comment]
oh! oh! +1 ;) How's it going ? /me wants semantic-ui badly ...

**Comment by funkytaco** [comment]
I decided not to use formly for now, so somebody else would need to take this on.

**Comment by jmls** [comment]
@funkytaco : why did you choose not to use formly ?

anyone else: anyone worked on semantic-ui templates ? There's a great feature-set for angular-semantic at https://github.com/ClickerMonkey/Semantic-UI-Angular
