### ISSUE TITLE
Support `data` prop for a Field Group (nested form)

### ISSUE THREAD

**Issue by benoror** [formly-js/angular-formly#395]
Our application make extensive use of custom metadata for each form field (via `data` prop mostly).

We allow nested forms via [field-groups](http://docs.angular-formly.com/docs/field-groups), therefore we would like to be able to use the [data object](http://docs.angular-formly.com/docs/field-configuration-object#data-object) for it as well.

_\* Note_: I have no need for [templateOptions](http://docs.angular-formly.com/docs/field-configuration-object#templateoptions-object) atm, but would it make sense to support it too?

**Comment by kentcdodds** [comment]
I believe this is currently supported... http://changelog.angular-formly.com#6150 am I missing something?

**Comment by benoror** [comment]
You're not @kentcdodds, I was deceived by an outdated version of formly and [incomplete documentation](http://docs.angular-formly.com/docs/field-groups).

Sorry for the false negative (mondays.. (-, - )…zzzZZZ), you can close the issue now.

BTW, Still looking forward for [that blog post](https://twitter.com/kentcdodds/status/621691930527707136) regarding `npm config set save-exact=true`, `next-update`, etc ( ͡~ ͜ʖ ͡°)

**Comment by kentcdodds** [comment]
So much to do, so little time to do it... :-) [For example](https://github.com/alianza-dev/az-dynamic-filter)
