### ISSUE TITLE
Simplifying

### ISSUE THREAD

**Issue by a-laughlin** [formly-js/angular-formly#396]
There is a balance between making the API more powerful and preserving its simplicity. I've seen that tension come up in multiple tickets.  Building my first few forms with that tension in mind, I noticed a potential way to increase Formly's utility for me while decreasing API complexity.  Sharing it here for discussion.

The main problem that I set out to solve was the inability to mix in behaviors from multiple places in the code, like autosave, validation, etc.  I also wanted to keep my controllers light and intuitive.  The process of defining fields, defining types, extending types with other types, and figuring out which properties went on types/fields/type.defaultOptions, led to many apiCheck errors.  While apicheck's errors are useful, getting them made me wonder.  What value do Types and defaultOptions add?  To me they add complexity without an appreciable benefit.  Inheriting straight from other fields would be simpler and more flexible.

So I implemented simple multiple inheritance for fields.  It uses two functions: `defineFields()` which is equivalent to `setType()` but creates fields instead of types (no defaultOptions because any field can be defaults for any other), and `getFields()`, which takes field names and returns an array of fields ready for inserting into $scope.fields.  Both work with the existing API and have made using Formly simpler and more flexible for me.  Below is an example.:

**Define base field types**

```js
factory('BaseFields',function(FormlyExtensions){
  FormlyExtensions.defineFields({
    'base.text':{
      template: '<input class="form-control" ng-model="model[options.key]">',
      templateOptions:{type:'text'}
    },
    'base.number':{
      templateOptions:{type:'number'} // defines a number type
      defaults: ['base.text'], // and inherits the template from base.text
    }
  });
})
```

**Define validators**

```js
factory('ValidatorFields',function(FormlyExtensions){
  FormlyExtensions.defineFields({
    'validators.alphaNumeric':{
      validators:{
        alphaNumeric:{
          expression:function(viewValue){return /^[a-zA-Z0-9]+$/.test(viewValue);}
        }
      }
    }
  });
})
```

**define model-specific fields**
```js
factory('FishModel',function(FormlyExtensions){
  FormlyExtensions.defineFields({
    'fish.defaults':{
      mixins:['validators.alphaNumeric']
    },
   'fish.name':{
      mixins:['base.text','fish.defaults'],
      validators:{
        alphaNumeric:{message:"Fish name must contain letters or numbers"}
      }
    },
   'fish.age':{
      mixins:['base.number','fish.defaults'],
      validators:{
        alphaNumeric:{message:"Fish age must be a number"}
      }
    }
  });
})
```

**Populate the controller**

```js
.controller('FishtankControl',function($scope,FormlyExtensions){
  $scope.model={
    fish:{}
  };

  $scope.fields = FormlyExtensions.getFields(
    'fish.name',
    'fish.age'
  );

  // ^^ this is the whole controller
```

**$scope.fields becomes:**

```js
    /*
    [{
      model:'model.fish',
      key:'name',
      template: '<input class="form-control" ng-model="model[options.key]">',
      templateOptions:{type:'text'},
      validators:{
        alphaNumeric:{
          expression:function(viewValue){return /^[a-zA-Z0-9]+$/.test(viewValue);},
          message:"Fish name must contain letters or numbers"
        }
      }
    },
    {
      model:'model.fish',
      key:'age',
      template: '<input class="form-control" ng-model="model[options.key]">',
      templateOptions:{type:'number'},
      validators:{
        alphaNumeric:{
          expression:function(viewValue){return /^[a-zA-Z0-9]+$/.test(viewValue);},
          message:"Fish age must contain letters or numbers"
        }
      }
    }]
    */
```

The functionality is similar to [extendTypeOptions](https://github.com/formly-js/angular-formly/blob/d43ed72fbc73b4a06c2c687e52f25d42800be76b/src/providers/formlyConfig.js#L65).  I actually implemented both defaults and mixins since the functionality was nearly identical.  And only required a couple extra lines.  One extends without overwriting, and the other overwrites (the equivalent to lodash's `_.defaultsDeep()` and `_.merge()` methods.

Anyway.  More flexible inheritance.  Simpler API.  Works with existing code.  Food for thought.

Adam

**Comment by kentcdodds** [comment]
I like what you're talking about. I still need to consider the api you've suggested further, but at first glance I like it. I think it is simpler. Do you think this is something that could be implemented as a separate library? They should work fine together...

**Comment by a-laughlin** [comment]
Sure.  I'm already using it as a separate factory.  It's only 60 lines or so, but depends on lodash.  If formly exposed its functions to merge fields/templates/wrappers, etc., that could cut its size significantly and remove the lodash dependency.

**Comment by a-laughlin** [comment]
Exposing methods not critical though.  Easy to just copy the necessary code.

**Comment by kentcdodds** [comment]
I have no problem exposing the methods... I can do that. Would you be
willing to contribute to a new formly-js repo I make for this plugin?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by a-laughlin** [comment]
I think that should work.  Let me talk with my team about it and get back with you.

**Comment by a-laughlin** [comment]
Hey Kent.  Sure.  Go ahead and create the repo and I'll put in some initial code.  We can discuss/improve from there.

Also, formlyUtils already exposes reverseDeepMerge.  That'll help eliminate the lodash dependency.

**Comment by kentcdodds** [comment]
[The repo](https://github.com/formly-js/angular-formly-simplified) has been created and you've been invited to the team that collaborates on it. Please let me know if there's anything else that you'd like me to expose from angular-formly to make this easier. I'm eager to see how this library turns out.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this issue in favor of [this one](https://github.com/formly-js/angular-formly-simplified/issues/1). Perhaps some of the ideas developed there can be incorporated into the core.
