### ISSUE TITLE
custom field class

### ISSUE THREAD

**Issue by Evanion** [formly-js/angular-formly#398]
I'm working on a [uikit](http://getuikit.com) module for angular-formly, but I have 2 issues:

* The field repeat class is hard coded, I would like a way to add a custom class to the 'formly-field' directive.
* Similarly I would like a way to add a custom class to the ngTransclude that wraps the transcluded content from the page template.

This is somewhat related to #276.

**Comment by kentcdodds** [comment]
You can add a class to the `formly-field` element via the `className` property. I could add the ability to have a custom class to the `ngTransclude` element. That would be quite simple to implement actually if you're interested in making a PR. You'd basically do the same thing [here](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L53) as is done in several other places (like [here](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L38)). The test would look similar to [this one](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.test.js#L32-L38). Should be pretty simple.

**Comment by kentcdodds** [comment]
Also, if you like, I can create a shell repo under the `fromly-js` organization for you to fill out with the library. Or you can just develop it under your own account. Whatever you like :-)

**Comment by Evanion** [comment]
Right now I'm working on this repo: https://github.com/Evanion/angular-formly-templates-uikit
Once I get it to a beta phase we can migrate it to an official repo.
I will take a look at making a PR.

**Comment by kentcdodds** [comment]
@Evanion, do you mind holding off on that PR? I'd like to reserve this one for a new-comer as I've done in the past #343 #358.

**Comment by kentcdodds** [comment]
Like with #343 and #358, I've created tests for this feature and I'm going to give someone a shot at contributing to open source for the first time :-) So I will only accept a PR from someone who's never contributed to open source before.

Instructions:

- [ ] Watch [this video](https://www.youtube.com/watch?v=QOchwBm9W-g&index=5&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) to learn what you need to do to get things setup
- [ ] Go to [these tests](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.test.js#L152-L168) and change `describe.skip` to `describe.only`
- [ ] Run `$ npm test`
- [ ] Notice that some of the tests are failing
- [ ] Update the [formlyFormGetTemplate](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L28-L101) function to add the class if it's specified on the `attrs`. I recommend doing pretty much the same thing that's done for [the form name](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L38) except your function should look more [like this](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L57-L59).
- [ ] Once the tests are  passing, change the `describe.only`s to `describe` so all the tests run.
- [ ] Commit your changes to the `src/` directory mentioning issue #343 (note it may take a second... it runs all the tests...)
- [ ] Push your changes to your fork, create a PR, get merged, celebrate 🎉

I'm happy to hold your hand through this if you need help. [Catch me on gitter](https://gitter.im/kentcdodds).

**Comment by kentcdodds** [comment]
This has been released in the official `6.21.0` release.
