### ISSUE TITLE
Angular 1.2 validation does not prevent downstream actions

### ISSUE THREAD

**Issue by a-laughlin** [formly-js/angular-formly#399]
I've spent a couple days worth of time trying to follow examples and learn how formly works, only to find that it's supposed to be easier to use then it has been for me in 1.2.x.  Bleh.

Here's a jsbin(http://jsbin.com/wunigi/edit?html,js,console,output).  Type anything in the input, then change the angular version in html pane from 1.3.0 to 1.2.28. Validation failing prevents downstream actions in 1.3.x & 1.4.x. Validation failing has no effect in 1.2.x.

This is a critical bug for folks on 1.2.x since it makes documentation and many other examples differ from actual behavior in 1.2.x.

Question on validation and execution order on SO [here](http://stackoverflow.com/questions/31640450/how-is-validation-supposed-to-work-in-angular-formly).

**Comment by kentcdodds** [comment]
I think I understand the issue. What's the behavior with the model without Angular-formly?

**Comment by a-laughlin** [comment]
In [this code](https://github.com/angular/angular.js/blob/v1.2.28/src/ng/directive/input.js#L1216) it looks like viewChangeListeners (including ngChange) will not fire if the model value === the parsers' pipeline output.  I need to head out, but can run tests tomorrow.

**Comment by a-laughlin** [comment]
And thanks for the quick response.  Definitely was feeling a bit frustrated earlier.  All good.  Also, trying to get a handle on how formy works internally.  Would I be correct in thinking that this behavior is the result of parser functions always returning the viewValue [here](https://github.com/formly-js/angular-formly/blob/d2bce4bbb6b3f7cd3f220c702ebcd21e592bd199/src/directives/formly-custom-validation.js#L102)?  If so, a fix that supports asynchronous validation seems like it would require setupWithParsers to return different values for sync and async.  If synchronous, return the view value.  If async, return the model value, then force a digest after the promise returns.

**Comment by kentcdodds** [comment]
Yes, I believe what you're suggesting is the correct fix to the bug. Thanks for spending the time digging into this. I think you have a good idea for the fix. Do you fancy creating some tests for the bug and fixing the issue? Would probably go somewhere [in here](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-custom-validation.test.js#L19-L23). (Notice that even though the tests are run with angular 1.4, you can force `formly-custom-validation` to use parsers anyway with `use-parsers`).

**Comment by a-laughlin** [comment]
Howdy Kent,

Normally, sure.  Since I'm behind on some deliverables due to spending time figuring that bug out, I think a better place to start with tests will be the simplified repo.  I still need to implement the fix for our code though, so I'm happy to implement a patch and post the code for it.

Any conflicts you anticipate with the new parsers/formatters code?

**Comment by kentcdodds** [comment]
No, that code lives in master so you shouldn't have any merge conflicts. And it was additive so I wouldn't expect any issues with it.

**Comment by a-laughlin** [comment]
After struggling to get setupWithParsers correctly triggering downstream actions this morning, and then spending a while trying to get some of the examples working after changing the script to angular 1.2 in the html, I decided to bite the bullet and go through migrating our codebase to 1.3.17.

Never did get the downstream async actions running correctly.  Unless you know an easy solution for getting 1.2 async working with dependent downstream events, it might be worth re-opening the discussion about dropping 1.2 support.

Anyway, here's the setupWithParsers function working correctly with synchronous validation:
```js
function setupWithParsers(validator, name, isAsync) {
	var inFlightValidator = undefined;
	ctrl.$parsers.unshift(function evalValidityOfParser(viewValue) {
		var isValid = formlyUtil.formlyEval(scope, validator, ctrl.$modelValue, viewValue);
		// In the next breaking change, rather than checking for isPromiseLike, it should just check for isAsync.
		if (isAsync || isPromiseLike(isValid)) {
			if (!isAsync) {
				logAsyncValidatorsDeprecationNotice(validator, opts);
			}
			ctrl.$pending = ctrl.$pending || {};
			ctrl.$pending[name] = true;
			inFlightValidator = isValid;
			isValid.then(function () {
				if (inFlightValidator === isValid) {
					ctrl.$modelValue = viewValue;
					ctrl.$setValidity(name, true);
				}
			})['catch'](function () {
				if (inFlightValidator === isValid) {
					ctrl.$setValidity(name, false);
				}
			})['finally'](function () {
				if (Object.keys(ctrl.$pending).length === 1) {
					delete ctrl.$pending;
				} else {
					delete ctrl.$pending[name];
				}
			});
			return ctrl.$modelValue;
		}

		if(isValid){
			ctrl.$setValidity(name, true);
			return viewValue;
		}
		ctrl.$setValidity(name, false);
		return ctrl.$modelValue;
	});
}
```

**Comment by kentcdodds** [comment]
Sorry about that, but congrats on the upgrade! There are a lot of really cool features in 1.3 (here are [some](https://egghead.io/search?q=new+in+angular+1.3)) :-)

Thanks for the code. I think I may just implement this as a bugfix. Unless you (or anyone watching) can think of a reason it shouldn't be...

**Comment by a-laughlin** [comment]
Hey Kent.  I deleted the SO question.  I think learning Formly would be faster for me if I understood early where/how Formly intersects forms interaction.  A diagram would be ideal, though I'm debating whether it's worth the effort to create.  Something along the lines of: http://image.slidesharecdn.com/formsinangularjs-130512173919-phpapp01/95/forms-in-angularjs-16-638.jpg?cb=1422097771, or a sequence diagram.

**Comment by kentcdodds** [comment]
Good point. A diagram would probably be helpful. I'll give it some thought.

**Comment by kentcdodds** [comment]
I'm going to consider this one a breaking change. Even though it may be easy to think of it as a bugfix, it definitely changes behavior and so I'll include it in the 7.0.0 milestone. I'm hoping to give that milestone an entire day to work on it. I may develop this functionality as a `formlyConfig.extras` property which you can enable and then remove the original functionality when 7.0.0 hits...

**Comment by kentcdodds** [comment]
I'm not 100% certain that this is correct... After looking at it, I think there's a problem. Particularly with this line:

```javascript
ctrl.$modelValue = viewValue;
```

and this line:

```javascript
return ctrl.$modelValue;
```

I found that the later prevented other async validators from starting which I don't believe is the correct behavior, and the former doesn't take `parsers` into account. I'm going to go ahead and close this because you've moved on to Angular 1.3, nobody else has complained, and I'm dropping 1.2 support in the next major release (not the one I'm doing in a few minutes, but the one after that).

For anyone else, feel free to resurrect this if need be.
