### ISSUE TITLE
angular directives not working

### ISSUE THREAD

**Issue by siripimamatha** [formly-js/angular-formly#400]
like kendo-drop-down-list,ng-show,ng-if ,this type of directives not working on angular formly how to solve this issues

**Comment by benoror** [comment]
Supposing I succeeded figuring out your cryptic message, I guess what you're looking for is **custom templates**: http://docs.angular-formly.com/docs/custom-templates

**Comment by siripimamatha** [comment]
please send me on example using this directive( kendo-drop-down-list)

**Comment by siripimamatha** [comment]
please send me one example using this directive( kendo-drop-down-list)

**Comment by kentcdodds** [comment]
Thanks for trying @benoror. @siripimamatha, the github issues are reserved for bug reports and feature requests. If you need help, please follow the instructions here: http://help.angular-formly.com This is the most effective way for us to help you and for you to receive help.
