### ISSUE TITLE
Tag library (e.g. jstag) integration?

### ISSUE THREAD

**Issue by estaub** [formly-js/angular-formly#402]
"Tag" here is used in the StackOverflow sense - an editable collection of keywords.

Is anyone aware of an easy way to integrate tag support into formly?  I was looking at [jstag](http://eranhirs.github.io/jsTag/), but any would help.  

jstag, in particular, is an Angular plugin, so the formly template would need to nest a <jstag> directive in it.  Does this kind of nested directive invocation work well with formly?  I've run into problems doing this kind of thing myself (outside of formly or jstag), but it's probably because I don't know how to write a good outer directive.

**Comment by kentcdodds** [comment]
Hi @estaub. Thanks for your interest in angular-formly. The best way to get help is to follow the instructions here: http://help.angular-formly.com
The github issues are reserved for bug reports and feature requests, so I'm going to go ahead and close this issue.

**Comment by estaub** [comment]
@kentcdodds ,
The question isn't of a kind allowed on StackOverflow, and clearly is not of a form suitable for JSBin!  I thought the answer, if any exists, might be of value to others, so I thought it should be Google-searchable (not Gitter).  I've of course searched and found nothing - but "tag" is not the easiest thing to search for; I may have missed something.  I'm inferring from your response that there is no such integration, in which case consider it a feature request.  I'll spend some time trying to do it myself and will share if successful, but frankly expect to fail and fall back to a no formly where tags are needed.  
Thanks -Ed

**Comment by kentcdodds** [comment]
The core of angular-formly has nothing to do with the templates/types that are used to create the form. For example, angular-formly itself knows nothing about an `input` element. This has been delegated to the end developer to tell formly about the different types that you'll be using in your application. To learn about how to do this, see the "Custom Templates" video [here](http://docs.angular-formly.com/docs/learn-angular-formly).

This, however is out of the scope of the angular-formly core library and therefore cannot be a feature request for this repository. You could however [request an example](https://www.youtube.com/watch?v=lu-c5C1t4Sk&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH&index=4) for the website.

Good luck! :+1:

**Comment by benoror** [comment]
@estaub angular-formly is **agnostic regarding template/controls/widgets rendering**. You could implement multiselect/tagging by yourself, or **easily adapt an existing solution using custom templates**, as explained in the documentation.

For multiselect I've seen that [ui-select](https://github.com/angular-ui/ui-select) supports it, and I will implement it eventually for my project (which should be rather easy considering an existing example [like this](http://angular-formly.com/#/example/integrations/ui-select)), but there should be plenty of different alternatives, in the end JavaScript

**Comment by estaub** [comment]
@benoror - Thanks!  The "agnostic" bit is reassuring - I'll push it harder.  FWIW, I need tags, though, not just multiselect.

**Comment by estaub** [comment]
@kentcdodds - Sorry, I wasn't clear - I meant to request an example.  Let me see what I can do - I'll be back in a few days.

**Comment by benoror** [comment]
@estaub don't worry, a quick search threw me around 3k results:
https://github.com/search?l=JavaScript&q=tagging&ref=searchresults&type=Repositories&utf8=%E2%9C%93

BTW, let me know whenever you've found a good candidate and implemented a custom template!

Good luck!
