### ISSUE TITLE
FeatureRequest: add field validation on model change to the extras property

### ISSUE THREAD

**Issue by TheMcMurder** [formly-js/angular-formly#404]
In [issue 390](https://github.com/formly-js/angular-formly/issues/390) you discussed adding an `extras` property to the formly field configuration, I think that whole form validation would be a great use case for the `extras` property. 

**Example Use case**: I want to invalidate the form if the password and confirm password fields do not match.

Currently if you want to perform the validation mentioned above you need to add a watcher or during one of the expression properties you need to evaluate the fields and manually invoke fc.$validate();

What I'm proposing would have an API similar to this:

```javascript
vm.fields = [
  {
    key: 'password',
    type: 'input',
    templateOptions: {
      label: 'Password'
    }
  },
  {
    key: 'confirmPassword',
    type: 'input',
    extras: {validateOnModelChange: true},
    templateOptions: {
      label: 'Password'
    },
    validators: {
      samePassword: 'model.password === model.confirmPassword'
    }
  }
];
```

Now I don't need to add an additional watcher or implement a workaround via the expression properties

**Comment by kentcdodds** [comment]
Love this. Would love some feedback from people on this one.

**Comment by kentcdodds** [comment]
You might have to re-open this one... I can't seem to find it... 😜 #seewhatididthere?

**Comment by SchizoDuckie** [comment]
I'm not quite certain yet, but I think this would be super handy for me. 
I'm doing some revalidation operations directly on the model right now because I have the need to trigger specific revalidations when (loosely) linked properties change. Currently i'm doing that like this. 

```javascript
revalidateRowSelectors = function() {
    self.fields.map(function(field) {
        if(someConditionThatMatches50PercentOfMyForm) {
            field.fieldGroup[0].formControl.$validate();
        }
    });
};
```
Maybe we can have some sort of revalidation expression on top of this?

**Comment by a-laughlin** [comment]
+1.

I did something similar by copying the field's scope to data.fieldScope called the formlyUtils function to evaluate it, passing data.fieldScope in.  A common way to call validateAllFields() would be handy.

Is it possible to manage the field validation using angular's existing validation states/classes?  I'd like to avoid adding additional formly-specific states to maintain simplicity.  Personally, I use css to manage my error styling by using extras.errorExistsAndShouldBeVisibleExpression of `!$valid && ($touched || $dirty)` so I can use angular's existing validation classes of `ng-invalid.ng-touched,.ng-invalid.ng-dirty` to highlight errors (that expression gets select elements before the first blur, when they register as dirty but not touched).

**Comment by kentcdodds** [comment]
"Is it possible to manage the field validation using angular's existing
validation states/classes"

Not sure I understand what you mean by this. More simplicity is good though.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by a-laughlin** [comment]
And.... that was a great example of why not to read and respond when sleepy.  Not sure what I was thinking last night either.  Removed my comment.  Carry on!

**Comment by kentcdodds** [comment]
Alright, I think there's enough support for this issue that I've added the `intent to implement` and `up-for-grabs` labels :+1:

**Comment by kentcdodds** [comment]
This has been released in `6.22.0`! Thanks for the suggestion @TheMcMurder :-)

**Comment by gentledepp** [comment]
in what way has this been released? I cannot find any documentation? Do I have to read the source code? :-|

**Comment by benoror** [comment]
@gentledepp https://github.com/formly-js/angular-formly/commit/2cb7d2e8758a78fd083e257d57ea9dddd588a1ae#diff-4830f282e0aa2d5c786eb691f55beb43R2095

**Comment by alxvallejo** [comment]
I'm confused, does this mean you need to set a optionsTypes, like from the example? That's a lot of code for a simple comparison validator.
http://angular-formly.com/#/example/other/matching-two-fields

**Comment by kentcdodds** [comment]
@alxvallejo, agreed. Perhaps someone (you) would like to write a plugin to keep all that common code :-)

**Comment by mota57** [comment]
thank you soo much guys it helps me a lot.
