### ISSUE TITLE
placeholder two-way-binding issue

### ISSUE THREAD

**Issue by Astray-git** [formly-js/angular-formly#405]
Hello, I just found that if I change label in to, it get updated in the rendered form, but this doesn't work for placeholder
jsbin: http://jsbin.com/fugofohasu/edit?html,js,output

**Comment by kentcdodds** [comment]
Hi @Astray-git, thanks for using angular-formly. This is actually not a bug, but a performance optimization that angular-formly makes for you. To indicate to angular-formly that you wish to change the property, you need to use [`expressionProperties`](http://docs.angular-formly.com/docs/field-configuration-object#expressionproperties-object). Here's a working example of your issue: https://jsbin.com/qijuwe/edit?html,js,output

Good luck!
