### ISSUE TITLE
Swap $timeout for setTimeout or nothing at all

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#406]
I think this could be a significant perf gain if we could get rid of running `runExpressions` in a `$timeout`... https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L61

**Comment by kentcdodds** [comment]
This may require a breaking change...

**Comment by kentcdodds** [comment]
Just for context... `runExpressions` is a function that's added to all of your fields which is in charge of running all of your `expressionProperties`. You can invoke it yourself, but most of the time it's just invoked by the parent `formlyForm` ([here](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L123)).

Because `expressionProperties` require the `$viewValue` and the `$modelValue`, I remember having trouble with getting those values at the time I was developing it. Wrapping the function in a `$timeout` seemed to fix the problem. However, things have changed and it may not be necessary to do this anymore. I'm crossing my fingers.

If it is still necessary to execute `expressionProperties` on the "next tick" of the event loop, the next best thing I could do is replace `$timeout` with `setTimeout`. Right now, every one of your `expressionProperties` causes a `$digest` to fire because it's using `$timeout`. This is a major performance drag. However, if I switch to `setTimeout` then I fear that we may have a situation where things don't get updated as you would expect and you'd have to invoke `$digest` yourself (I don't want to force you to do this). This is why I would release this in a beta and ask that a lot of people please upgrade to try it out in your apps.

Feedback is appreciated.

**Comment by sparty02** [comment]
May want to check out [evalAsync/applyAsync](http://www.bennadel.com/blog/2751-scope-applyasync-vs-scope-evalasync-in-angularjs-1-3.htm)

**Comment by kentcdodds** [comment]
Oh! Yeah! Why didn't I think of that earlier. Thanks for the tip. That's probably exactly what I need.
