### ISSUE TITLE
Optionally choose validation behavior?

### ISSUE THREAD

**Issue by a-laughlin** [formly-js/angular-formly#407]
Last June, angular implemented a [breaking change](https://github.com/angular/angular.js/commit/f3cb2741161353f387d02725637ce4ba062a9bc0) to validators that essentially wipes out the model value if validation fails.  That is counterintuitive to me.  I expected the model to remain unchanged if I return `false` from a validator, not to become `undefined`.

Yet that isn't angular's behavior anymore.  Is there a workaround to prevent angular from wiping out model properties when validation fails?  If not, what do you think about a property that will instruct Formly to preserve model values if field invalid?

Also, onChange handlers fire on the first validation with a select option, then don't fire on subsequent validations.  They shouldn't fire on the first either.  That may be related to the angular issue of selects becoming dirty but not touched before they first blur.

**Comment by kentcdodds** [comment]
Sorry, somehow this slipped through the cracks for me. I want to avoid doing too much different from the angular implementation of how to treat the model. Fewer surprises, more consistency. As a side, I actually disagree with you and I believe that the clearing of the model is appropriate.

On the subject of `select` `onChange`, I haven't seen what you're experiencing. Could you create an example and file a bug if you feel there is one?
