### ISSUE TITLE
shrinkwrap is forcing unavailable registry for deps

### ISSUE THREAD

**Issue by sparty02** [formly-js/angular-formly#408]
With the change to leveraging shrinkwrap in formly 6.21.0, our builds started failing because shrinkwrap is forcing our npm client to try and resolve formly's dependencies from https://registry.npmjs.org (based on the ```resolved``` field).  This may seem ok on the surface, but it completely breaks users who leverage a private npm repo (e.g. we're using Artifactory as our NPM repo).

Digging around a bit, I found some interesting issues filed on npm related to this:
https://github.com/npm/npm/issues/6444
https://github.com/npm/npm/issues/3581

Based on the comments in these threads, it sounds like:
a) shrinkwrap isn't really bulletproof
b) is probably not appropriate for libraries (at least in its current form).

**Comment by kentcdodds** [comment]
Yeah, it didn't really work out well for me either. I'll release a bugfix version with the removed file.

**Comment by kentcdodds** [comment]
The file has been removed in `6.21.1`. Thanks for letting me know.

**Comment by sparty02** [comment]
Thanks for the lightning fast change!
