### ISSUE TITLE
default to ng-repeat track by id?

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#413]
All formly fields are given an id (or one can be specified). Because of this, I don't think that there would be any problem to have a default trackBy for the `formly-form` `ng-repeat` over the `formly-fields`. This could potentially give us a perf boost and make it so we don't have the `$$hashKey` attached to our objects.

Thoughts?

**Comment by jpuzzo** [comment]
I would appreciate this enhancement. :+1:

**Comment by kentcdodds** [comment]
Turns out this is only possible if you specify an ID for all the fields. Most people aren't doing this. If you are doing this, then I recommend that you specify `track-by` as an attribute.
