### ISSUE TITLE
TypeError: scope.theFormly Form.$remove Control is not a function

### ISSUE THREAD

**Issue by SupriyaVenkatesh** [formly-js/angular-formly#414]
hi @kentcdodds ,

Am facing i=this problem when i load my app using angular fomrly (TypeError: scope.theFormly Form.$remove Control is not a function). is der any solution for this.

**Comment by kentcdodds** [comment]
Hi @SupriyaVenkatesh, please follow the instructions here: http://help.angular-formly.com

Because the github issues are for bug reports and feature requests, I'm going to go ahead and close this issue. See you in chat!

**Comment by andreystehno** [comment]
But this is bug.

**Comment by david-dlc-cerezo** [comment]
https://github.com/formly-js/angular-formly/issues/741
