### ISSUE TITLE
Accesing the wrapper formly-field from a fieldGroup.

### ISSUE THREAD

**Issue by nomack84** [formly-js/angular-formly#417]
Is there a way to access the formly-field wrapper  of fieldGroups? `className` works with the `ngForm` that contains the fieldGroups' fields, but I need to go one more step up in the hierarchy. Why? Because I need to add a class to that element, Bootstrap's `row` class. That way I'll be able to lay out perfectly my forms fields, and I won't need to use CSS 'hacks' in order to fix it. 
Perhaps I should make a custom type? Any tips would be of paramount help. 
By the way, really nice library. Thanks a lot for it

**Comment by benoror** [comment]
Hi @nomack84, warm welcome from Cuba! I recently had the same requirement, but un fortunately `fieldGroups` doesn't support telplate wrappers.

But I achieved the same result making use of the `data` property inside a custom template called `nested`, take a look: http://jsbin.com/zaqeke

Also @kentcdodds came with a slightly different approach, by using two different `fields` objects, look: http://jsbin.com/setupi/edit?html,css,js,output

@kentcdodds shall I submit it as an example for the website?

**Comment by kentcdodds** [comment]
Seems good to me. Thanks @benoror. I hope this helps @nomack84. I'm going to go ahead and close this issue because issues are reserved for feature requests and bugs. If you need help, follow the instructions here: http://help.angular-formly.com

**Comment by nomack84** [comment]
@benoror @kentcdodds Thanks for your help. I've found that what I needed is to add display block the the `ng-form`. Now is working fine.

**Comment by netowp** [comment]
@benoror Ben, where is this `panel.html` file?

```
	formlyConfigProvider.setWrapper({
      name: 'panel',
      templateUrl: 'panel.html'
    });
```

**Comment by benoror** [comment]
@netowp in the JSBin it's included inside an script tag, since JSBin doesn't support multiple files afaik:

```
<script type="text/ng-template" id="panel.html">
...
</script>
```

In your project you'll likely have it in a **separate file**, or if you'd like yo might use ES6 multi-line strings, like this:

```
    formlyConfigProvider.setWrapper({
      name: 'panel',
      template: `
          ...
      `
    });
```

**Comment by netowp** [comment]
Thanks, @benoror! I was so confused about that, since JSBin doesn't support multiple files. :)
