### ISSUE TITLE
model object used by formly does not change when I reassign the object

### ISSUE THREAD

**Issue by Stijnkool** [formly-js/angular-formly#418]
I use formly to edit some objects I get from a server. When I'm done editing I hit save. When the server responds with the newly saved object, I reassign this new object to my model object that formly uses. But this new object won't be used by formly for some reason. Because when I then tried to edit & save the object again. The old object is being used by formly instead of the new one I assigned to my model object.

I have a [jsbin](http://jsbin.com/quqaduhuzo/1/edit?js,console,output) that demonstrates this. I mocked the server responding with a different object by just having 2 different objects. When I submit my changes, I assign a different object to my model object. I expect the data to change to the new model when i submit.

When I only use the key property on my fields, it works fine. But when I use the model property, assigning a new object to the model doesn't work. The new model is not shown in formly.

**Comment by kentcdodds** [comment]
I think the issue you're seeing isn't an issue with formly, but with the part that displays the model. See [here](https://jsbin.com/liveca/edit?html,js,output).

**Comment by kentcdodds** [comment]
Did this resolve your issue? Please close if so.
