### ISSUE TITLE
Remain access to original model after replacing model on a field

### ISSUE THREAD

**Issue by kwypchlo** [formly-js/angular-formly#419]
```
{
  ...
}, {
  key: 'routingNumber',
  type: 'input',
  model: {routingNumber: ''},
  templateOptions: {
  label: gettext('Routing number'),
    onChange: function(value, options, scope) {
      fetchBank(scope.model, value);
    }
  }
}, {
  ...
}
```
This is just one field, a part of bigger form.

I'm storing routingNumber field outside the model because this is just a search field so I needed to create isolated model for that field. However function `fetchBank` expects the original model as a first parameter because it wants to modify it (it searches for a bank and inserts it to the original model). 
As of current formly version, `model` object on the field's `scope` is overriden with what is passed to `model` attribute and I lose access to the original model. I couldn't find any way to access the original `model` through the given params in `onChange` callback. Maybe there could be a reference to original model next to the current model that could be accessed like `scope.originalModel` or something like that?

If this doesn't make sense, I will try to find an easier example however this is real use case :)

If what I propose is acceptable solution, I could prepare PR as I imagine it is not very complicated issue but needs some documentation work too.

Cheers!

**Comment by kentcdodds** [comment]
Here's what I'd recommend: https://jsbin.com/wibado/edit?html,js,console,output
Will that do it for you?

Either way, this could be helpful. If you want to make a PR, we can take a look at the amount of complexity it adds to angular-formly. I'm fairly confident I'd accept a PR for this though. Thanks!

**Comment by kwypchlo** [comment]
Thanks @kentcdodds for the idea however I cannot use `data: {originalModel: vm.model}` because I have my formly directive inside `ng-repeat` so my `vm.model` is array of models, not the exact model that I want.

I will try to compose PR this week, however if you have other workaround I will gladly check if it could work for my case :)

**Comment by kentcdodds** [comment]
Here's a good workaround: https://jsbin.com/wibado/edit?html,js,console,output

**Comment by kwypchlo** [comment]
This looks good and legit workaround :) It will definately work in my case. I will try to come up with PR anyway as keeping original model reference might be a good feature anyway.

**Comment by kentcdodds** [comment]
:+1:

**Comment by kentcdodds** [comment]
:+1:

**Comment by kentcdodds** [comment]
This actually would probably be a good first-timers-only issue. Maybe I'll work on adding some tests sometime. Until then, feel free to submit a PR if you want. Should be pretty simple.
