### ISSUE TITLE
How to bind or insert data in other model with formly  

### ISSUE THREAD

**Issue by marcoriesco** [formly-js/angular-formly#420]
I am a problem, which in my view, is very complicated. I wanted to see other thoughts about.

Created fields with the angular formly, these same fields are generated by a policy to be dealt with, the problem to record this data, I would need two repeats or not, still have not found a way out for not using 2 repeats, my code below is one more try unsuccessfully:

http://jsbin.com/faquhizupo/1/edit?html,js,console,output

This was one of the attempts, which brought me another problem.
If you managed to give me a light, it would be great!

http://stackoverflow.com/questions/31862176/angular-update-resource-without-overwriting

**Comment by kentcdodds** [comment]
Hi @marcoriesco, thanks for using angular-formly. I'm not certain that I understand the problem you're having. If you could be a little more clear that would be helpful. Some reproduction steps in the jsbin you created would be helpful.

Either way, the github issues are reserved for bug reports and feature requests, so I'm going to go ahead and close this issue.
