### ISSUE TITLE
Added formatters do not format the initial model value

### ISSUE THREAD

**Issue by koenweyn** [formly-js/angular-formly#423]
As can be seen in this [sample](http://jsbin.com/tiwuha/edit?js,console,output), a formatter is not executed for the initial model value.
Probably because the formatters are added to the NgModelCtrl after the model value has already been set.

I will submit a PR containing a failing test for this scenario.

**Comment by koenweyn** [comment]
This code below demonstrates a possible workaround (if you can get hold of the NgModelCtrl)

```javascript
let value = ctrl.$modelValue;
ctrl.$formatters.forEach((formatter) => {
  value = formatter(value);
});

ctrl.$setViewValue(value);
ctrl.$render();
```

**Comment by kentcdodds** [comment]
Thanks for setting this up @koenweyn!

Here's another [`first-timers-only`](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue! I will only accept a PR from someone who's never contributed to an open source project before!

I'll hold your hand through this so you can get your first PR into a real open source project! Your goal is to make [this test](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.test.js#L1018-L1029) pass. Here are some steps:

- [ ] Watch [this video](https://www.youtube.com/watch?v=QOchwBm9W-g&index=5&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) to learn what you need to do to get things setup
- [ ] Go to [this test](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.test.js#L1018-L1029) and change `it.skip` to `it.only`
- [ ] Run `$ npm test`
- [ ] Notice that it's failing
- [ ] Go to [this function](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L360-L362). This is where angular-formly applies the `formatters` from the field options to the `$formatters` of the [NgModelController](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$formatters). Look at the code sample that @koenweyn suggests in the comment above. You'll do something similar. You'll get `ctrl` from `scope.fc`.
- [ ] Once the test is passing, change the `it.only` to `it` so all the tests run.
- [ ] Make sure that all the tests pass
- [ ] Commit your changes to the `src/` directory mentioning issue #423 (this issue) in your commit message (note it may take a second... it runs all the tests...)
- [ ] Push your changes to your fork, create a PR with the description mentioning issue #423 (this issue), get merged, celebrate 🎉

Catch me on [gitter](https://gitter.com/kentcdodds) if you need help!

**Comment by TheMcMurder** [comment]
I actually need this functionality now, I'm not a first-timer, can I still work on this bug?

**Comment by kentcdodds** [comment]
Yeah, that's totally fine. There's been plenty of time for a first timer to grab this if they wanted to. There will other opportunities.

**Comment by redhead** [comment]
Close?

**Comment by kentcdodds** [comment]
Ah! Yes, thank you @redhead, this is indeed implemented.
