### ISSUE TITLE
writing field attributes in json rather than controllers

### ISSUE THREAD

**Issue by codewreaker** [formly-js/angular-formly#425]
Angular formly is an awesome tool and makes DRY more DRY when used in combination with jade. A little issue I am facing with using formly is the JSON limitation. I tried to place all code in a json file and fetch with a service to inject in my controller. I want to do this to prevent my controller from becoming bulky with formly code. Unfortunately formly attributes are not read as json and thus is throwing error.

I saw a git tool trying to be implemented to solve this issue in March but unfortunately looks like it hasn't been continued.

Any help

**Comment by kentcdodds** [comment]
This is definitely possible and many people do it. Here's an example: http://angular-formly.com/#/example/other/json-powered

I'm going to go ahead and close this issue. The github issues are reserved for feature requests and bug reports. If you need help, follow the instructions here: http://help.angular-formly.com
