### ISSUE TITLE
Enhancement: Support for nested model attribute

### ISSUE THREAD

**Issue by redhead** [formly-js/angular-formly#426]
I was thinking while making a PR with refactoring of model watchers that I could use a nested attribute in a model numerous times (as I already did). It can be done now by specifying model attribute in field config, however this is treated as a completely new model object, having its own watcher.

I've come up with an idea of a "dot syntax" for model attribute:

    key: 'street',
    model: '.address'
    ...
    key: 'city',
    model: '.address'

This would take a "parent" model (being it the formly form model or a model specified on field group) and "add" the model "path" with dot syntax to form a model for the field. This way however it would not create a new watcher on the nested attribute (since the "parent" model is already watched).

This would be equivalent to:

    key: 'street',
    model: 'model.address'
    ...
    key: 'city',
    model: 'model.address'

in current implementation, however WITHOUT adding a watcher to the attribute.

What do you think? I could create a PR if you like it.

**Comment by kentcdodds** [comment]
Thanks for looking into this. My first impression is that this would add quite a bit of complexity to the codebase. That's fine, but I want to make sure that the complexity is worth it. Do you think you could produce an example that demonstrates the perf bottleneck?

Maybe I'm mistaken and this wont actually make things more complex...

**Comment by redhead** [comment]
Well, from programming in angular I know that perf bottleneck comes with each deep watcher created. But since I used the use case multiple times already I though this could be addressed and also simplify the model assignment if it is just a nested attribute of a model.

I don't think that the footprint of this would be big. I my eyes (correct me if I am wrong) it would make changes to https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L199, where we would check if the model attribute has a dot as the first character. In that case, we would prefix it with `'model'` (making it `model.nestedAttrName`) since we want the nested attribute of "parent" model, and the code would continue in the same way as it is now. On top of that, the `initModel` would return `true` if the model is "new", otherwise `false`, to the caller function (`setupModels()`), where it would decide to create a watcher based on the return value (true - create a model watcher, false - do not).

In sense:

    function setupModels() {
      // a set of field models that are already watched (the $scope.model will have its own watcher)
      const watchedModels = [$scope.model];

      angular.forEach($scope.fields, (field) => {
        var isNewModel = initModel(field);

        if (field.model && watchedModels.indexOf(field.model) === -1 && isNewModel) {
          $scope.$watch(() => field.model, onModelOrFormStateChange, true);
          watchedModels.push(field.model);
        }
      });
    }

    function initModel(field) {
      if (angular.isString(field.model)) {
        var isNewModel = true;
        if (field.model[0] === '.') {
          field.model = 'model' + field.model;
          isNewModel = false;
        }
        const expression = field.model;
        const index = $scope.fields.indexOf(field);
        field.model = evalCloseToFormlyExpression(expression, undefined, field, index);
        if (!field.model) {
          throw formlyUsability.getFieldError(
            'field-model-must-be-initialized',
            'Field model must be initialized. When specifying a model as a string for a field, the result of the' +
            ' expression must have been initialized ahead of time.',
            field);
        }
        return isNewModel;
      }
      return true;
    }

Is there something I don't see, that would make it bigger issue?

**Comment by redhead** [comment]
What do you think?

**Comment by kentcdodds** [comment]
I'm still not 100% sure this is good from a simplicity standpoint. Feel free to create a PR. That might help me visualize exactly what the API and the code changes involved would look like. But just know that I'm not certain whether I'd accept it.

I really appreciate your contributions! Thank you for your work!

**Comment by redhead** [comment]
Maybe you could elaborate a bit more on what troubles you in the suggested idea. But nevertheless, I might do the PR for you to consider.

Anyway, I just came up a with an idea, not to set a watcher if the model attribute starts with `model.` (and is a string). In that case we already watch the (parent) model and we don't have to add a new watcher for the nested attribute. This way the API would not change at all, at the code impact would be minimal.

**Comment by kentcdodds** [comment]
I think that would be better. The thing I don't like about what you were originally suggesting is that we're creating our own magic DSL by having '.something' have special meaning. I would prefer it if there were a little less angular-formly-specific magic going on, and it was easier to understand what's happening. By doing what you've just suggested, I think that would be much better.

**Comment by redhead** [comment]
I've read your comment too late, so the pull request I've sent includes both (dot syntax as well as starting with `model.`). Will reworked it tomorrow hopefully.

**Comment by voodoorider** [comment]
Is there any way to access the parent model now in an expression? I have a field that has a model overwritten and I would like to disable it based on a property from the original model.

**Comment by redhead** [comment]
Do you mean that you had a nested model on a field like this?
  
    model: 'model.nestedModel'

and you wanted to access the parent `model`? 

I think this wasn't possible before either in a string expression. Because `model` expression for this field will resolve to `model.nestedModel` object (I believe). You can do it using function instead, where you would access the parent model using `vm.model` or whatever variable you store the parent model in. Correct me, if I am wrong, @kentcdodds. :)

Anyway, we concluded that the API is not going to change in this issue. In the PR #434 I merely optimized watchers not to be applied on nested properties of an existing model.

**Comment by voodoorider** [comment]
Yep, exactly that was my case. Ok, I'll work on the variable outside the formly config then.

**Comment by ankitprahladsoni** [comment]
Hi,

I have used fieldGroup to make nested forms, and I want to display inner field based on the value of an outer field. Going through this issue, I guess this is not possible for now in angular-formly.
Please let me know if there's any workaround for this issue.
I can go with a flat structure and provide a full key to each field(for example `'person.name'`, `'person.address.city'`, `'person.address.state'`), but I want to avoid such as I have a lot of nested fields. 

Example of my issue: http://jsbin.com/jikajomike/edit?js,output

**Comment by kentcdodds** [comment]
Here's a solution using `formState`: https://jsbin.com/gokonaq/edit?js,output
