### ISSUE TITLE
how to disable previous dates in UI- datepicker[Question]???

### ISSUE THREAD

**Issue by SupriyaVenkatesh** [formly-js/angular-formly#431]
hi @kentcdodds ,

I have a small question in UI date-picker how do we disable previous dates i.e i have two date fields start and end date once i select an start date, in end date the previous dates of start date should be disabled..

here is an jsbin example http://jsbin.com/suzekuseso/1/edit?html,js,output

**Comment by kentcdodds** [comment]
Hi @SupriyaVenkatesh. Your question is related to how to work with ui date-picker, not angular-formly. I recommend you direct your question to [them](https://github.com/angular-ui/bootstrap/). Also, as I believe you are aware, the github issues are reserved for bug reports and feature requests. If you need help, please follow the instructions here: http://help.angular-formly.com
