### ISSUE TITLE
Inititializing formatters sets dirty flag

### ISSUE THREAD

**Issue by redhead** [formly-js/angular-formly#432]
On initialization of a field, `addFormatters` function is called, where the view value is set to the ngModel, and thus triggering $setDirty() on ngModel as well. This caused as issue with dirty checker confirmation dialog on navigation leaving the form even though the form was not touched (i.e. should not be dirty).

Bug was caused by fixing this issue #423 in PR https://github.com/formly-js/angular-formly/commit/f93bf1427578875ab2d1e9acfb7b6f6532f42b69

**Comment by kentcdodds** [comment]
Thanks for letting me know! @TheMcMurder's fix is in release `6.23.5`

**Comment by kentcdodds** [comment]
Turns out that there's still an issue with setting the `form` to `$dirty`. @TheMcMurder is working on a fix now.
