### ISSUE TITLE
Fields from JSON

### ISSUE THREAD

**Issue by irhabi** [formly-js/angular-formly#435]
How can I provide data for example label text for fields defined in JSON file?
Lets say JSON fields looks like this:
// formlyData.json
`{
  "fields": [
    {
     "key": "car",
      "type": "input",
      "templateOptions": {
        "label": "vm.car.label"
      }
   }
 ]
}`

MyController() {
  var vm = this;
  vm.car.label = "Type the car brand";
  vm.model = {};
  vm.fields = formlyData.json;
}

If it wasn't JSON file than (label: vm.car.label) would work...

**Comment by kentcdodds** [comment]
Hi @irhabi. Please see [this example](http://angular-formly.com/#/example/other/json-powered). Also, from [README](https://github.com/formly-js/angular-formly#getting-help):

> Please don't file an issue unless you feel like you've found a bug or have a feature request. Instead, go to [help.angular-formly.com](http://help.angular-formly.com) and follow the instructions.

So I'm going to close this issue.
