### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by pzartech** [formly-js/angular-formly#436]
Hi,
I'm trying to enter Unicode characters in the placeholder field: 
        vm.orderFields = [
            {
                key: 'full_name',
                type: 'input',
                templateOptions: {
                    type: 'text',
                    placeholder: 'שם מלא',
                    required: true
                }
            },

But unfortunately it renders as this "×©× ×ž×œ×" in the HTML.

Any idea how could I espace the Unicode in the HTML rendered form? 
Thanks a lot!

**Comment by kentcdodds** [comment]
This appears to work just fine for me: http://jsbin.com/fowufo/edit?html,js,output
