### ISSUE TITLE
expressionProperties issue

### ISSUE THREAD

**Issue by SpinoWeb** [formly-js/angular-formly#438]
I specified in the expressionProperties for the first field the "templateOptions.onChange" event. However, the onChange is triggered not only when the user changes the first field, but also when the user changes another field of the form. I'd want that the function in "templateOptions.onChange" is run only when the first field is changed. Is it possible?

Example:
        
    vm.formFields = [ // fields
            {
                key: 'cls',
                type: 'select',
                defaultValue: vm.input.cls,
                templateOptions: {
                    label: 'Cls',
                    placeholder: 'Cls',
                    options: vm.getOptions(), //[],
                    valueProp: 'value',
                    labelProp: 'value',
                    required: true       
                },
                expressionProperties: { 'templateOptions.onChange': function($viewValue, $modelValue){
                        //console.log('viewValue: ' + $viewValue);
                        //console.log('modelValue: ' + $modelValue);
                        onSelect();
                    }
                },
            },
            {
                key: 'fc0',
                type: 'input',
                defaultValue: vm.input.fc0,
                templateOptions: {
                    label: 'fc0 (MPa)',
                    placeholder: 'fc0 (MPa)',                    
                    type: 'number',
                    required: true,
                    min : 0.
                }
            }]

**Comment by kentcdodds** [comment]
Instead of putting `templateOptions.onChange` in `expressionProperties`, put `onChange` in `templateOptions`. It's similar to [this example](http://angular-formly.com/#/example/field-options/on-keypress)

Note, from [the README](https://github.com/formly-js/angular-formly#getting-help):

> Please don't file an issue unless you feel like you've found a bug or have a feature request. Instead, go to help.angular-formly.com and follow the instructions.

So I'm going to go ahead and close this. Thanks.
