### ISSUE TITLE
Chrome autocomplete="off"

### ISSUE THREAD

**Issue by mavrick** [formly-js/angular-formly#440]
Hey dude,

I'm just trying to wrap my head around this one. I've read https://code.google.com/p/chromium/issues/detail?id=468153#c14

I've set ``formlyConfig.extras.removeChromeAutoComplete`` to true so we hit the following code:

```javascript
// ლ(ಠ益ಠლ)   (╯°□°)╯︵ ┻━┻    (◞‸◟；)
function fixChromeAutocomplete() {
  var global = formlyConfig.extras.removeChromeAutoComplete === true;
  var offInstance = scope.options && scope.options.removeChromeAutoComplete === false;
  var onInstance = scope.options && scope.options.removeChromeAutoComplete === true;
  if (global && !offInstance || onInstance) {
    var input = document.createElement('input');
    input.setAttribute('autocomplete', 'address-level4');
    input.setAttribute('hidden', 'true');
    el[0].appendChild(input);
  }
}
```

Looking at comment 41: https://code.google.com/p/chromium/issues/detail?id=468153#c41

>Once I did this, all of my "autocomplete=off" elements were respected by Chrome.

Which brings me to my question. How can I set the autocomplete flag on an input element using angular-formly?

Should I be overriding the base template for an ``input`` or is there a ``templateOption`` I can specify to set the autocomplete flag?

Cheers

**Comment by kentcdodds** [comment]
Yes, look into ngModelOptions. Sorry, I have a spotty internet connection,
otherwise I'd link you to it in the docs.

-Kent C. Dodds

**Comment by mavrick** [comment]
Thanks for the reply mate, will check it out.

Cheers
