### ISSUE TITLE
UI-Select enhanced example

### ISSUE THREAD

**Issue by drmikecrowe** [formly-js/angular-formly#441]
I could not implement multiple-select using the docs, and it took me all day to figure out the secret sauce.

Here's a revised jsbin illustrating multi-select with UI-select and select2:

http://jsbin.com/nihiza/3/edit?js,output

**Comment by kentcdodds** [comment]
Neat! Thanks for doing this! Could you follow the steps [here](https://github.com/formly-js/angular-formly-website/blob/master/CONTRIBUTING.md#creating-an-example) to get this added to the website? Thanks again :+1:

**Comment by drmikecrowe** [comment]
Kent, will.

BTW, Contributing needs to be on the main page under Get Help on the left.  I looked everywhere on the website (probably not exhaustively) for the process, but it wasn't immediately obvious for new users of formly.  Would you like me to submit a PR for that too?

**Comment by kentcdodds** [comment]
Sure thing! Thanks!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by rosscdh** [comment]
Hey guys, there appears to be something broken with the example since angular 1.4.

http://jsbin.com/nihiza/3/edit?html,output <-- broken

Im getting the following in my codebase..
```
 Error: [$compile:ctreq] Controller 'select', required by directive 'ngOptions', can't be found!
```

Any thoughts would be appreciated.

**Comment by kentcdodds** [comment]
That jsbin is out dated so the scripts aren't being loaded properly. Here's the updated version:

https://jsbin.com/xuyogoy/edit?html,console,output

I'm also seeing that error. I'm not sure what the problem is. Anyone else?

**Comment by rosscdh** [comment]
Legendary thank you :)

**Comment by rosscdh** [comment]
PS. found the issue was I was using angular#1.4.9 but the example only works ~= 1.4.7

**Comment by rosscdh** [comment]
So just to confirm.. formly is still using the now depreciated
angular-select2 lib? and not https://github.com/angular-ui/ui-select

**Comment by kentcdodds** [comment]
Formly only depends on angular and api-check (see [package.json](https://github.com/formly-js/angular-formly/blob/master/package.json#L53-L56)). You can see the dependencies of that example in the `head` tag:

```

    <!-- Twitter bootstrap -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">

    <!-- apiCheck is used by formly to validate its api -->
    <script src="//npmcdn.com/api-check"></script>
    <!-- This is the latest version of angular (at the time this template was created) -->
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js"></script>

    <!-- This is the latest version of formly core. -->
    <script src="//npmcdn.com/angular-formly"></script>
    <!-- This is the latest version of formly bootstrap templates -->
    <script src="//npmcdn.com/angular-formly-templates-bootstrap"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.0/ui-bootstrap-tpls.min.js"></script>

    <!-- ui-select files -->
    <script src="https://rawgit.com/angular-ui/ui-select/master/dist/select.js"></script>
    <link rel="stylesheet" href="https://rawgit.com/angular-ui/ui-select/master/dist/select.css">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.js"></script>

    <!-- Select2 theme -->
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.css">

    <!--
Selectize theme
Less versions are available at https://github.com/brianreavis/selectize.js/tree/master/dist/less
-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.8.5/css/selectize.default.css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.8.5/css/selectize.bootstrap2.css"> -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.8.5/css/selectize.bootstrap3.css"> -->
```

**Comment by blowsie** [comment]
Latest versions of angular select throw an error.
`Error: [ui.select:iexp] Expected expression in form of '_item_ in _collection_[ track by _id_]' but got '{{to.ngOptions}}'.` trying to figure out how to resolve this, does anyone else already have a solution?
