### ISSUE TITLE
Drop bower support

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#445]
In an effort to make things more simple to release and maintain, I'm considering dropping bower support. 

If you have any tooling whatsoever (`grunt`, `gulp`, `jshint`, `eslint`, etc), you're probably already using `npm` to get your devDependencies to build your project. If you're not doing this, install node and npm and run `npm init` in your project.

If you are currently using bower, you would simply need to install angular-formly via npm. All you would have to do is:

1. Remove angular-formly from bower.json
2. run `npm install --save angular-formly`
3. Change where you're referencing angular-formly: `bower_components/angular-formly/dist/formly.js` now becomes `node_modules/angular-formly/dist/formly.js`.

And that's it. Obviously, if you're doing anything creative you may have a few different or other steps. But you should probably just switch to `npm` entirely anyway ([Why We should Stop Using Bower--And How to Do It](http://gofore.com/ohjelmistokehitys/stop-using-bower/)).

Please comment on this issue with reasons this wouldn't work for you.

**Comment by kentcdodds** [comment]
Also, this: http://beletsky.net/2015/04/npm-for-everything.html

**Comment by ckniffen** [comment]
Please do not we currently use bower pretty heavily.

**Comment by jpuzzo** [comment]
I'm currently using bower to update formly but I also have npm so I can switch things up if need be.

**Comment by kentcdodds** [comment]
@ckniffen, how does the work-around not work for you?

**Comment by drmikecrowe** [comment]
node_modules is outside our static routes.  I'd have to redo my build scripts (we use grunt), and change how components are integrated.  

Right now, grunt reads bower.json and integrated the appropriate css/js into our html template automatically.

I understand the simplification desire.  However, how difficult is maintaining both?  From my viewpoint, dropping npm would work great for me :-)

**Comment by kentcdodds** [comment]
I'm wanting to automate releases using semantic-release. Currently, semantic-release doesn't push the built changes to the git repo (https://github.com/semantic-release/semantic-release/issues/75). I bet I could finagle something to get it to work, but it's just extra complexity and time spent that I'd like to avoid if I can.

The process of a release before adding semantic-release was to do this basically:

1. Make and commit the changes
2. Manually update the changelog (which I've made mistakes on several times)
3. Decide whether this is a breaking change, new feature, or a bugfix and bump the version accordingly
4. Run the build, commit changes, tag the commit with the version, push to github, npm publish

Luckily, I was able to make the third item be a single command, but what semantic-release gives me is it removes the last three steps and does all of those automatically. This saves me time and reduces human error.

That's why I want to use semantic-release. I want to drop bower because semantic-release doesn't work well with bower currently and I also would prefer if we all (as a frontend community) just use `npm` instead.

**Comment by kentcdodds** [comment]
I should mention, I'm just testing the waters. I was at a 30% likelihood of actually going through with this when I filed the feedback issue.

**Comment by ckniffen** [comment]
@kentcdodds we use wiredeps which leverages bower.json for our modules to inject the paths into several of our files.

**Comment by kentcdodds** [comment]
This doesn't have to happen! I got it working :-)
