### ISSUE TITLE
Is there any API to clear all validations and to mark all form fields and the form itself as valid (when using Angular 1.2)?

### ISSUE THREAD

**Issue by janjonas** [formly-js/angular-formly#448]
The resetModel() function seems to be something that could help (http://angular-formly.com/#/example/form-options/reset-model)? 
But unfortunately the function seems not to be compatible to Angular 1.2., we get the error:
```TypeError: formControl.$setUntouched is not a function```

Is resetModel() supported in Angular 1.2?

**Comment by kentcdodds** [comment]
This is definitely a bug. I may make this a [first-timers-only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue. If someone else would like to write skipped tests to reproduce this issue, that would be awesome :-)
