### ISSUE TITLE
Use directive with attribute ?

### ISSUE THREAD

**Issue by kavi87** [formly-js/angular-formly#450]
I would like to use the directive formlyForm as an attribute instead of a custom element because we use this way accross all of our directives. Currently it is restricted to element only.

**Comment by kentcdodds** [comment]
Why can't you just use it as an element?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kavi87** [comment]
We use an html validator and all of our directives are written with an attribute. So it is mainly for consistency. Our users are used to attribute instead of custom element. Btw nice work for this lib.

**Comment by kentcdodds** [comment]
Understood. Personally I don't like it, but I would be happy to accept a PR that updates [this](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L14) and [this](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L8) to make that possible :-) Make sure to check [this](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#development) to know how to contribute :+1:

**Comment by kentcdodds** [comment]
Note: Commit this one as a `feat` not a `fix`.

**Comment by kentcdodds** [comment]
[As before](https://github.com/formly-js/angular-formly/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afirst-timers-only+) this one is for [First Timers Only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455). That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Watch [this video](https://www.youtube.com/watch?v=QOchwBm9W-g&index=5&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) to learn what you need to do to get things setup.
- [ ] Go to [this test](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.test.js#L24-L30) and change `it.skip` to `it.only`
- [ ] Run `$ npm test`
- [ ] Notice that it's failing
- [ ] Go to [this line](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L14) and make it look like [this line](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L17). Then make sure to update [the comment](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L8) as well.
- [ ] Once the test is passing, change the `describe.only` to `describe` so all the tests run.
- [ ] Make sure that all the tests pass
- [ ] Run `git add src/`
- [ ] Run `npm run commit` and follow the prompt (In the last question where it asks about referencing issues closed, put `closes #450`).
- [ ] Push your changes to your fork, create a PR, get merged, celebrate 🎉

I'm happy to hold your hand through this if you need help. [Catch me on gitter](https://gitter.im/kentcdodds).

**Comment by geraldchecka** [comment]
Hello Kent! I've never submitted to any open source projects. Can i do this?

**Comment by kentcdodds** [comment]
Please do!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by CrockAgile** [comment]
How do you define the "scope of this change"? Would it be $compile or should it be more specific like the formly-form directive?

**Comment by kentcdodds** [comment]
Good question! I'd probably say it's `formly-form`.
