### ISSUE TITLE
ngModelAttrs boolean config option fails apicheck

### ISSUE THREAD

**Issue by ckniffen** [formly-js/angular-formly#451]
Creating the following type errors in api-check when trying to set ngModelAttrs with a boolean configuration.

```
return {
  name: 'ipaddressMixin',
  defaultOptions: {
    templateOptions: {
      ipaddressType: 'any',
      ipaddressAllowAny: false
    },
    ngModelAttrs: {
      ipaddressType: {
        attribute: 'ip-valid'
      },
      ipaddressAllowAny: {
        boolean: 'ip-valid-allow-any'
      }
    }
  }
}
```
Will craft a PR.

**Comment by ckniffen** [comment]
@kentcdodds Where would you like the unit test placed?

The two places that make sense are formlyApiCheck.test.js  and formlyNgModelAttrsManipulator.test.js

**Comment by kentcdodds** [comment]
Probably in the `formlyApiCheck.test.js`
