### ISSUE TITLE
Support dot notation in keys

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#452]
I think that I've actually figured out a good way to do this...

from gitter:

> right now, if you specify a getterSetter then we find the ng-modeland change it to be ng-model="options.value"...
> what if, instead...
> if we see that the key has a property accessor (like a . or []), then we just change it to be the key?
> I'm going to investigate that idea more
> it'd perform better and it would work Angular 1.2

**Comment by pdemilly** [comment]
Or give the value function a scope we can work with other that manipulate the value. I do like your new dot notation using a fieldTransform. Dont know the impact on performance. Just an idea maybe if you see a key with a dot notation then you set a getter and setter function using $parse serviceonce in the field definition and use those functions if they are present? so you don't need to reparse everytime you access the model

**Comment by kentcdodds** [comment]
The current example isn't re-parsing at all. If you look, it's only parsed once.

**Comment by kentcdodds** [comment]
But what I'm thinking of wouldn't even require the parse service or a getter setter at all

**Comment by pdemilly** [comment]
I created a little jsbin that you could hopefully use to test your changes http://jsbin.com/jeqaha/edit?js,output

basically It shows the use of firebase as a backend with straight ng-model. You can see changes from the backend or the frontend syncing in real time.

now the goal would be that a form defined with formly does the same. I put a checkbox to turn on or off using firebase model as the model of the formly-form. As you can see with your dot-notation changes when the model is an object it works. But as soon as the model is a $firebaseObject bind to the scope, it fails.

The goal at least for me would be to have the same behavior.

**Comment by kentcdodds** [comment]
This is now supported in the core. Feel free to test as you will! :-) Version `7.0.0`
