### ISSUE TITLE
Insert break into long form.

### ISSUE THREAD

**Issue by xgvargas** [formly-js/angular-formly#456]
Hello, first I should say thank you for this amazing library!

I'm looking for a practical way to insert breaks inside a long form. My Idea is to have a few fields then a `next` button on first page. `previous` and `next` in intermediaries and `previous` and `submit` on last page.

I already have it working but is not practical and demands code for every page instead of a `break` type inside my fields object, which would be really nice... but I can't figure out how to create such type. Any north to achieve this?

**Comment by Werick** [comment]
Hi xgvargas ,
Not sure if this may be helpful, we have similar long forms and we are using angular bootstrap tabs here is the link to an example http://angular-formly.com/#/example/integrations/ui-bootstrap-tabs.

Thanks

**Comment by kentcdodds** [comment]
Hi @xgvargas! Thanks for your interest in angular-formly! I think what you're looking for is something like [this](http://angular-formly.com/#/example/integrations/angular-wizard).

Issues on GitHub are reserved for bug reports and feature requests. So I'm going to close this issue. If you need help, please follow the instructions here: http://help.angular-formly.com
