### ISSUE TITLE
Refresh form

### ISSUE THREAD

**Issue by laurent-thai** [formly-js/angular-formly#457]
Hello,

Maybe it's not the good place for that request.
I am working on a multi step form .
For each step , I have a submit button that save the current form and load the next form.
That works fine but I have also a second button Prev to cancel the current form and load the previous form.
In that case, even the fields are properly loaded from the database the form is not refreshed.
Can you give me an advice ?
Thanks.

**Comment by kentcdodds** [comment]
You're looking for `resetModel`. I'm going to go ahead and close this issue. The github issues are reserved for bug reports and feature requests. If you need help, please follow the instructions here: http://help.angular-formly.com Good luck!

**Comment by laurent-thai** [comment]
Hello Thank you so much for your reply and for the advice about the correct usage of github.

Have a nice day.

Laurent.

 

 

De : Kent C. Dodds [mailto:notifications@github.com] 
Envoyé : mercredi 9 septembre 2015 11:08
À : formly-js/angular-formly
Cc : laurent-thai
Objet : Re: [angular-formly] Refresh form (#457)

 

You're looking for resetModel. I'm going to go ahead and close this issue. The github issues are reserved for bug reports and feature requests. If you need help, please follow the instructions here: http://help.angular-formly.com Good luck!

—
Reply to this email directly or view it on GitHub <https://github.com/formly-js/angular-formly/issues/457#issuecomment-138774740> .  <https://github.com/notifications/beacon/AFn3uD8hhbKD1GuWLDdXKl6nFOMs7uUmks5ov6gvgaJpZM4F5_mX.gif> 

Aucun virus trouvé dans ce message.
Analyse effectuée par AVG - www.avg.fr
Version: 2015.0.6125 / Base de données virale: 4409/10603 - Date: 09/09/2015

**Comment by kentcdodds** [comment]
Note, not all projects work the same way. Generally you're fine to use
issues for questions. But this project gets so many questions I couldn't
keep up with them. Generally, check if the project has a CONTRIBUTING.md
file. That'll have instructions :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
