### ISSUE TITLE
Make fieldTransform an array.

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#458]
This would make it possible to have multiple `fieldTransforms`.

This could be implemented as a non-breaking change by making this capable of handling a function or an array of functions: https://github.com/formly-js/angular-formly/blob/55cbe3c1288daae1ea0a0f18c99834271ecced96/src/directives/formly-form.js#L138-L143

We'd want to log a deprecation warning, add error/warning docs, and test that (like we've done before, [implementation](https://github.com/formly-js/angular-formly/blob/v6.26.1/src/providers/formlyConfig.js#L271-L278) | [warning docs](https://github.com/formly-js/angular-formly/blob/v6.26.1/other/ERRORS_AND_WARNINGS.md#apicheck-as-an-object-deprecated) | [test](https://github.com/formly-js/angular-formly/blob/v6.26.1/src/providers/formlyConfig.test.js#L610-L621)).

Then in a breaking release we could remove that logic and require it to be an array.

This one's up for grabs (whether you've contributed to open source before or not!)

**Comment by BarryThePenguin** [comment]
Looks interesting, happy to have a go

**Comment by kentcdodds** [comment]
Awesome!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
