### ISSUE TITLE
How to invoke field validators before submit

### ISSUE THREAD

**Issue by Werick** [formly-js/angular-formly#462]
We would like to fire/trigger the field validators when the user clicks the submit button so that we can review if the dependent fields are filled/completed correctly. Is this something that can easily be done using formly?

**Comment by kentcdodds** [comment]
[here you go](http://angular-formly.com/#/example/advanced/validation-on-form-submit)

**Comment by kentcdodds** [comment]
The github issues are reserved for Bug Reports and Feature Requests. If you have a question in the future, please follow the instructions here: http://help.angular-formly.com thanks!
