### ISSUE TITLE
Use options.key as default name instead of id

### ISSUE THREAD

**Issue by tb** [formly-js/angular-formly#463]
As person who writes integration tests for angular formly
Given `key="countries"`
I would like to have `name="countries"` instead of `name="formly_7_uiSelect_countries_0"`

Since we already have `id="formly_7_uiSelect_countries_0"`, can we have  `name="countries"`?

This would require small change in:

    function setFieldIdAndName() {
      // ...
      $scope.options.id = $scope.id;
      $scope.name = $scope.options.name || $scope.options.id;
      $scope.options.name = $scope.name;
    }

Would you accept PR for this?

**Comment by kentcdodds** [comment]
I'm not sure I understand what you're asking. You should be able to do this already... http://angular-formly.com/#/example/advanced/custom-ids-and-names

**Comment by tb** [comment]
I will use `extras.getFieldId`:

    formlyConfigProvider.extras.getFieldId = function(options, model, scope) {
      if (options.id) {
        return options.id;
      }

      return options.key;
    };

Thank you!

**Comment by kentcdodds** [comment]
Ah, I misunderstood your question. My apologies. That's exactly what I do as well. Thanks for your patience.

**Comment by kentcdodds** [comment]
Note, that's not 100% what I do because I have situations where there are two of the same form for two different models in the same page at the same time. So that implementation would result in duplicate ids. So, instead, I simply use the model id as part of the field id.

**Comment by tb** [comment]
The main issue is that when router opens component a couple of times (like you navigate our of page and navigate back), fields get different `formId`. For now I dont see any problem with the `return options.key` in our app. I also tried to pass id to formly-form, but it did not work (I considered using model id as part of form id)

**Comment by kentcdodds** [comment]
Here's what mine looks like:

```javascript
function azGetFieldId(options, model, scope) {
  if (options.id) {
    return options.id;
  }
  const index = getIndexOfIdInFields(options, scope);
  return ['az-formly', getModelIdentifier(model), options.key, index].join('_');
}

function getModelIdentifier(model) {
  let identifier = 'no-id';
  if (model) {
    const objectType = (model.constructor && model.constructor.name) || 'Object';
    identifier = `${objectType}_${model.id || 'no-id'}`;
  }
  return identifier;
}

// sometimes you have two fields that use the same key. This ensures they don't have the same ID
function getIndexOfIdInFields(options, scope) {
  const fieldsWithTheSameKey = _.filter(scope.fields, field => field.key === options.key);
  return _.indexOf(fieldsWithTheSameKey, options);
}
```

Results in something like:

```
az-formly_${objectType}_${id}_${propertyName}_${index}
```

Examples:

```
az-formly_User_123453523_username_0  // existing User
az-formly_User_no-id_username_0      // new User
az-formly_Object_no-id_someProp_0    // new Object
```
