### ISSUE TITLE
How to Improve form rendering speed for large forms

### ISSUE THREAD

**Issue by Werick** [formly-js/angular-formly#467]
Hi, we have a very large form that has several questions and is layered using tabs and several nested forms. Is it possible to load this form asynchronously so that the for is rendered faster in about five seconds or less? Right now it's taking about 45 - 50 seconds to render the form. We would like to improve the rendering time irrespective of how the form having so many questions. Kindly advice. Thanks
Erick

**Comment by kentcdodds** [comment]
Woah, 45-50 seconds is outrageous. Please make sure that you're following the [tips](http://docs.angular-formly.com/docs/tips) (disable api-check when deploying to production). This will speed things up considerably. How many fields do you have?
