### ISSUE TITLE
Default value doesn't work as expected with nested keys

### ISSUE THREAD

**Issue by BarryThePenguin** [formly-js/angular-formly#468]
http://output.jsbin.com/zejuhe

**Comment by kentcdodds** [comment]
This is a bug. Thanks for pointing it out. The code that needs to be fixed is [here](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L111-L115). Basically, we should be using the `$parse` service to set the value instead. This could be a pretty good `first-timer-only` issue. Are you up to setting up the tests like @koenweyn did for #423? If you want, you could even do the step-by-step :+1: this would be a huge help for a new comer!

**Comment by BarryThePenguin** [comment]
[]  Go to [this](https://github.com/formly-js/angular-formly/blob/af99394d519e6330d40b4f615211f069dac81ce7/src/directives/formly-field.test.js#L506-L512) test and change `it.skip` to `it.only`
[] Run $ npm test
[] Notice that it's failing
[] Go to [this](https://github.com/formly-js/angular-formly/blob/3c45ae558fa37e0b5640aef0f55d8cb5c6226163/src/directives/formly-field.js#L111-L115) function, like Kent mentions above we should be using the $parse service to set the value.
[] Once the test is passing, change the it.only to it so all the tests run.
[] Make sure that all the tests pass
[] Commit your changes to the src/ directory mentioning issue #468 (this issue) in your commit message (note it may take a second... it runs all the tests...)
[] Push your changes to your fork, create a PR with the description mentioning issue #468 (this issue), get merged, celebrate :tada:

**Comment by kentcdodds** [comment]
Awesome! Thanks for the help @BarryThePenguin. Tweeting now!

**Comment by BarryThePenguin** [comment]
TIL `it.skip` and `it.only`

**Comment by dfromero** [comment]
would like to contribute but not sure what  `it.skip` and `it.only` mean

**Comment by gjcarrow** [comment]
@dfromero your confusion might be because the links in the checklist that @BarryThePenguin made are just reversed. The list item "Go to this function..." is actually the link to the formly-field.test.js file. If you go to line 506 of that file, you will see the it.only method. Changing it from that to it.skip will skip that test when you run npm test. At that point all the tests should pass. When you fix the function in the formly-field.js file at line 111, you can go back and change the test back to it.only. Then run the npm test command again. If your fix worked, then all the tests will pass. I was going to take a shot at this for my first pull request, but I saw that you wanted to contribute first, so have at it. Good luck. Hope this helped.

**Comment by BarryThePenguin** [comment]
Sorry! I've corrected that...

**Comment by dfromero** [comment]
Not sure, but $parse lexxer keeps throwing an error for the emoji test key.

**Comment by kentcdodds** [comment]
My apologies @dfromero... I think there was some miscommunication and I didn't check @BarryThePenguin's work. Let me fix it really quick. Thanks.

**Comment by kentcdodds** [comment]
@dfromero, you should be good to go now. Go ahead and pull the latest changes. I apologize for that. Looking forward to your implementation (I've already done it so I know it's possible now!).

Good luck!

**Comment by dfromero** [comment]
@kentcdodds I'm trying to commit using npm run commit , but at the end i get ✗ Commit failed. Did you forget to 'git add' your files?, even though I already added src/ (note there are some other files not commited, ie. .idea folder). PS: I'm using windows.

**Comment by kentcdodds** [comment]
That's coming from commitizen. Unfortunately if there's a failure, it's not printing out the logs (cc @jimthedev). To see what the problem could be, run `npm run code-checks && npm run test && npm run check-coverage`. If you don't see any problems, then you'll have to craft your commit message by hand (following [the conventions](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md)) and use `git commit --no-verify`. Let me know.

**Comment by kentcdodds** [comment]
This was fixed by @dfromero. Thank you so much! The new version is being built and automatically released now and should be available soon. Thanks again @dfromero on your first ever PR :-)

**Comment by kentcdodds** [comment]
And that @BarryThePenguin for helping get this set up.

**Comment by dfromero** [comment]
cheers, thanks for the help

**Comment by BarryThePenguin** [comment]
The plunker works now! Looks great @dfromero 

Proof: http://output.jsbin.com/zejuhe
