### ISSUE TITLE
Setting flex class to Fieldgroup inside a Fieldgroup

### ISSUE THREAD

**Issue by GianlucaBobbio** [formly-js/angular-formly#470]
FIRST OF ALL, SORRY FOR BAD ENGLISH

I had to create a dinamyc layout with fieldgroups inside of fieldgroups but I had no way to set a flex in a fieldgroup.

I was trying that, inside a row (wich is a fieldgroup), I could have:

|--------------object (flex 75)------------|---column (flex 25)---|

I was trying with the following json

`"elementAttributes": {
                "layout": "column",
                "className": "flex flex-25"
 },`

But that flex (or class) is being applied to the ng-form that is being crated, and not the "formly-field-group" container

I made a fix. Inside the "elementAttributes" i added "formlyFieldGroupClass" so now I have

`"elementAttributes": {
                "layout": "column",
                "formlyFieldGroupClass": "flex flex-25"
            },`

and in the library I added (line 1476):

`if(scope.options.elementAttributes.formlyFieldGroupClass){
	      		el.addClass(scope.options.elementAttributes.formlyFieldGroupClass);
	      	}`

and now everything is working fine :)

**Comment by kentcdodds** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. Thanks!

**Comment by GianlucaBobbio** [comment]
Ok, I will leave here an example:

http://jsbin.com/gonozubahu/1/edit?html,js,output

You can see that the second column is a fieldgroup with two checkbox in a column

So I have 2 problems here. 

First: The checkboxs aren't in a column, so I had to add to my CSS:

`.layout-column-row{
    -ms-flex-direction: column;
    flex-direction: column;
    -webkit-flex-direction: column;
}`

I really don't care about this one because I fixed that really easy.

But...
Second one: My second column (the fieldgroup with 2 checkboxes) doesn't use "flex-25", no matter where I put the "className" because its being applied to the inner element of the fieldgroup. Here is an img:
http://pasteboard.co/JzbVoiy.png

So, to fix that, I had to create a new param, I called it: "formlyFieldGroupClass". And in the src I added (line 1476):

`if(scope.options.elementAttributes.formlyFieldGroupClass){ el.addClass(scope.options.elementAttributes.formlyFieldGroupClass); }`

Now, it's working :)

http://jsbin.com/dukibefehu/1/edit?html,js,output

Snatpshot of debugger + result:

http://pasteboard.co/JAbE3f1.png

**Comment by GianlucaBobbio** [comment]
I think this thread is related:

https://github.com/formly-js/angular-formly/issues/304

I just didn't want to make it work with HTML like that user did, because I'm working with dinamyc possibles HTML layouts

**Comment by kentcdodds** [comment]
Sorry, life's crazy busy for me right now (new baby in the house). I don't
have time to help you right now. Could you please follow the instructions
here to get help? http://help.angular-formly.com

Good luck!

**Comment by GianlucaBobbio** [comment]
I did, and I put the jbins in my comment as an example. Congrats for the baby!

**Comment by kentcdodds** [comment]
What I meant was where you get help. Not in the GitHub issues. ☺
