### ISSUE TITLE
Firebase compatibilty

### ISSUE THREAD

**Issue by dfromero** [formly-js/angular-formly#471]
I'm trying to save all the fields configuration objects array in firebase, while trying to get it using $firebaseArray, it retrives a pseudo array with special methods attached to it, this extra properties are breaking the directive, related to api check. Is there any workaround this issue or should i just use vanilla firebase without 3-way binding?

**Comment by kentcdodds** [comment]
Hmmm... My first question would be, you don't need the realtime for your field configurations right? Meaning, you're fine if the fields just load and they're not bound to firebase. If that's the case, then I recommend simply getting a snapshot of the data.

Should only be a few lines of code, but once you do that, if you wouldn't mind [creating an example](https://www.youtube.com/watch?v=4dsXXTPET4A) (<-- video) for the website, I'd really appreciate it!

Even better, create [a plugin](http://docs.angular-formly.com/page/plugins). Good luck! Thanks!

**Comment by dfromero** [comment]
yea, it's just sort of a custom form builder, where i push config objects, it would have been awesome to have it sync'ing automatically, but its not that critical.
