### ISSUE TITLE
set "ShowError" true from controller after form submit?

### ISSUE THREAD

**Issue by Luddinus** [formly-js/angular-formly#473]
Hi. I'm barely new using angular-formly, but I see great potential.

I have an array of fields, and I submit the form.

The server response is something like this:

```
{
   errors: {
      title: 'the title is required!'
   }
}
```

I need an easy way to show the error in each field and set "showError" true in order to activate the 'has-error' class of the form-group (bootstrap).

Any help appreciate, thx.

**Comment by Luddinus** [comment]
I need something similar to this: http://angular-formly.com/#/example/advanced/validation-on-form-submit

Maybe I'm misunderstanding something but in my case it is the server who returns the error messages.

**Comment by kentcdodds** [comment]
Sorry, life's crazy busy for me right now (new baby in the house). I don't
have time to help you right now. Could you please follow the instructions
here to get help? http://help.angular-formly.com

Good luck!

**Comment by Luddinus** [comment]
Ok @kentcdodds I'll figure out, congrats for the baby!
