### ISSUE TITLE
Using Objects in Multi-input

### ISSUE THREAD

**Issue by tarkanlar** [formly-js/angular-formly#474]
How can i use
```js 
[{type:'Fred',link:'google.com'},
        {type:'Ethel',link:'google.com'},
         {type:'Rick',link:'google.com'},
         {type:'Lucy',link:'google.com'}]
```

instead of  
```js
[Ethel,Rick,Lucy]
```
the orginal 
http://jsbin.com/yuyawo/6/edit?html,js,output

the one i tried 

http://jsbin.com/qiyiku/3/edit?html,js,output

So now i see [object Object] in the url input but i want to see the url there.

i tried kids.url and kids.$.url but didnt worked

**Comment by kentcdodds** [comment]
Hi @tarkanlar, I'm sorry that I don't have time to help you right this minute (new baby in the house). But if you follow the instructions here you'll get the most help from others: http://help.angular-formly.com (you've already done most of that).

The github issues are reserved for feature requests and reporting bugs. So I'm going to go ahead and close this.

**Comment by kentcdodds** [comment]
good luck!

**Comment by tarkanlar** [comment]
Thanks @kentcdodds Congratulations on your new bundle of joy! Say "Hi" to the new member of the family! :+1:
