### ISSUE TITLE
is.js validation of none required field

### ISSUE THREAD

**Issue by TheBekker** [formly-js/angular-formly#476]
Hi

Not sure if this is a bug, or if its me doing somthing wrong.
I run into an issue when i use is.js for simple email validation, on a field that has `required: false` set.

The form is not valid, even though the field is empty and is not required.

Here is a jsbin (just used the is.js integration example and changed)
http://jsbin.com/giledaxoji/edit?html,js,output

Some way to fix this?

**Comment by kentcdodds** [comment]
I think we should update the example. You should first check if it's empty.
If it is, then don't do the validation check for email.

On Mon, Sep 21, 2015, 8:05 AM TheBekker <notifications@github.com> wrote:

> Hi
>
> Not sure if this is a bug, or if its me doing somthing wrong.
> I run into an issue when i use is.js for simple email validation, on a
> field that has required: false set.
>
> The form is not valid, even though the field is empty and is not required.
>
> Here is a jsbin (just used the is.js integration example and changed)
> http://jsbin.com/giledaxoji/edit?html,js,output
>
> Some way to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/476>.
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by TheBekker** [comment]
That makes sense, but not sure how i would accomplish this?

**Comment by kentcdodds** [comment]
Like this: http://jsbin.com/kebucas/edit?html,js,output :-)

On Mon, Sep 21, 2015 at 8:10 AM TheBekker <notifications@github.com> wrote:

> That makes sense, but not sure how i would accomplish this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/476#issuecomment-141994072>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by TheBekker** [comment]
Ahh didnt know that was possible, thanks!
