### ISSUE TITLE
Error in Ui-select integration with formly

### ISSUE THREAD

**Issue by Bedo81** [formly-js/angular-formly#478]
Hello, there is an error in ui-select integration with formly. You have that error in a console shown in your example as well.

http://angular-formly.com/#/example/integrations/ui-select

Error: [$compile:ctreq] http://errors.angularjs.org/1.4.4/$compile/ctreq?p0=select&p1=ngOptions

Thanks & Regards

Martin

**Comment by kentcdodds** [comment]
Looks like ui-select isn't ready for angular 1.4.x yet. I've downgraded that example's angular to 1.3.19 and it's working great. Thanks for letting me know!

**Comment by ckniffen** [comment]
@kentcdodds @Bedo81 This is actually a problem with the example.  ui-select works with angular-1.4 and I currently use it with my project running 1.4.0.  The issue with the example is that the `ui-select` formly type is defined as extending the formly-bootstrap-templates `select` type which defines a mapping for `ngOptions` in `ngModelAttrs`.  `ngOptions` is not a valid directive as of 1.4 on anything other than a `<select>` element.  ui-select does not need that attribute so I just made it not extend `select`.  Only draw back is that it doesn't inherit the apiCheck.

Ex. http://jsbin.com/kohowax/2/edit?html,js,output

**Comment by Knoxvillekm** [comment]
Example code don't work with angular 1.4.8, replace 
```js
app.run(function (formlyConfig) {
    formlyConfig.extras.removeChromeAutoComplete = true;
    formlyConfig.setType({
        name: 'ui-select',
        extends: 'select',
        template: ''
    });
});
```
with
```js
app.config(['formlyConfigProvider', function (formlyConfigProvider) {
    formlyConfigProvider.extras.removeChromeAutoComplete = true;
    formlyConfigProvider.setType({
        name: 'ui-select',
        extends: 'select',
        template: ''
    });
}]);
```
