### ISSUE TITLE
Crippling performance issues on large forms

### ISSUE THREAD

**Issue by cfv1984** [formly-js/angular-formly#479]
Hi! 
  We're building *large-ish* (140 to 500 fields) forms with formly, and are seeing **crippling**  performance issues, to the point we get "Firefox stopped responding" when tabbing from a field to another. Chrome also randomly appears to choke, but less often.

Templates have been optimized to the largest possible degree, to the point of using one-time bindings for any nonessential things in templates. ExpressionProperties are flat out unused. Validations are made to run outside formly and run sparingly due to being heavily optimized for our use case. 

What can we probably be missing? What can we do to pinpoint and avoid whatever is killing our experience with Formly?

**Comment by kentcdodds** [comment]
140-500 fields is not *large-ish*. That's plain **gigantic**. I don't know what kind of user experience you're looking for, but I don't think that formly (or angular for that matter) can help you with the performance in that scenario. Out of curiosity, what version of angular and angular-formly are you using?

**Comment by cfv1984** [comment]
```
    "angular-formly": "6.12.0",
    "angular": "1.3.14",
```

Would splitting the forms into smaller chunks work? What's the largest amount of inputs we could effectively use on screen?  

One thing we thought about  was throttling any keydowns blurs or watches on the inputs, since that's when the issues appear the most. 

Is that something we can even do?

**Comment by kentcdodds** [comment]
The problem is that you need all of those event listeners and watchers for your form to work properly.

I would recommend:

1. Upgrading to the latest angular-formly (there have been some significant performance optimizations made recently)
2. Upgrading to the latest version of angular (though this can be more difficult if other dependencies you have aren't ready for it).
3. Make sure you disable `api-check` in production as described in the [tips](http://docs.angular-formly.com/docs/tips)
4. Try showing only pieces of the form at a time, hide the rest of it behind an `ng-if` which will cause the form to not render until it's shown.

I hope these tips help!

**Comment by Werick** [comment]
We are also experiencing this issue and we have decided load and display
tab when the user clicks/selects the tab. The the forms loads the first tab
and the other tabs are loaded when the clicks on a given tab. This trick
improves the speed. We have also noticed that we need to reduce the number
of questions on each tab.

Hope this is helpful.

Erick

**Comment by joshtoo** [comment]
@cfv1984 - I have to agree with @kentcdodds here. From a UX perspective, nobody wants to try and absorb hundreds of fields on a form at once much less edit them.

Even if you used something besides Angular for this, you are still going to have some degree of degraded performance.

IMHO - You really need to reassess your requirements and design, this isn't a performance issue with formly. Personally I would probably go with something workflow driven and then break the fields up into stages but that solution is making assumptions on your requirements.

**Comment by cfv1984** [comment]
Hi @kentcdodds! in the end it was decided we'd split the form in a wizard-like fashion, by fieldgroups, and  only render a fieldgroup at a time. 

@Werick Did you do something similar to this? 

@joshtoo It's client work. I don't get to decide, just juggle the requirements and the capabilities we have.

**Comment by kentcdodds** [comment]
Good luck! Sorry the tech doesn't quite do what you were looking for in the first place :-/

**Comment by Werick** [comment]
No, we opted for tabs that load/render lazily. Only the first tab is
rendered. All others are rendered when the user clicks on the tab.
