### ISSUE TITLE
Can't dynamically add fields to a fieldGroup

### ISSUE THREAD

**Issue by holtjonathan** [formly-js/angular-formly#480]
Take a peek at this jsbin: http://jsbin.com/cexezaneni/edit?html,js,output

For whatever reason you don't see the error on jsbin but locally when this code executes the follow error is thrown: 
    
    Cannot assign to read only property 'data' of {key:"key3", type: "input"}

Unless I am trying to add to this fieldGroup in an incorrect way (totally possible) I don't see how I can add fields once the field has already been created.

**Comment by msc654** [comment]
@holtjonathan try this example based off of yours. http://jsbin.com/xecucenevu/3/edit?js,console,output

**Comment by kentcdodds** [comment]
Thanks @msc654! That is correct. That would be the proper way to do this. Because github issues on this project are reserved for bug reports and feature requests, I'm going to go ahead and close this one. If you need more help, please follow the instructions here: http://help.angular-formly.com
