### ISSUE TITLE
October FOSS Bash planning.

### ISSUE THREAD

**Issue by SomeKittens** [formly-js/angular-formly#483]
Angular Formly has been selected as the target of October's FOSS Bash!

This means that for one day in October, the denizens of Angular Buddies (the #1 Angular Slack group, [join here](http://angularbuddies.com)) will hack their way through Angular Formly.

This issue is for planning out the day.  On the docket are:

 - [x] When?  Ideally, @kentcdodds would be (mostly) available for the full day to answer questions, review PRs and hand out TODOs (same with @msc654 and @gkadillak ).
 - [x] Goal.  We've found these things work a lot better with goals.  Ideally, there'd be a list of ways newcomers can help out.
 - [ ] Issue prepping.  Kent's the #1 person at prepping issues for newcomers, so this isn't a big worry.
 - [ ] Promo.  I'd like to do more "get the word out" effort this time around.

Details of last month's bash: https://gist.github.com/SomeKittens/bf24e8bd854bf79ea055

**Comment by kentcdodds** [comment]
And don't forget @ckniffen and @benoror :-)

**Comment by benoror** [comment]
count with me :+1:

**Comment by kentcdodds** [comment]
How about October 14th? I could probably have some stuff prepared by then.

**Comment by SomeKittens** [comment]
14th's a Wednesday, I thought weekends might be best.

**Comment by kentcdodds** [comment]
Ah, of course, that makes much more sense... How about the 10th?

On Thu, Sep 24, 2015 at 3:47 PM Randall Koutnik <notifications@github.com>
wrote:

> 14th's a Wednesday, I thought weekends might be best.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/483#issuecomment-143059376>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by SomeKittens** [comment]
10th works for me if it works for you.

**Comment by SomeKittens** [comment]
10th it is, you're now featured on http://foss-hackday.github.io/

Let's talk goals.  There aren't very many open issues - perhaps you want to increase code coverage & hit 100%?  More examples?  Sky's the limit!

**Comment by kentcdodds** [comment]
Thanks @SomeKittens! That sounds fine. I can't promise that I'll be available *all* day, but should be able to help most of the day.

I'll get a few issues set up. At a high level, here are some things that I'd like:

- Investigate an Angular 2 version (for the more ambitious of contributors)
- Increase Test Coverage (both in the main repo and in the bootstrap templates)
- Identify performance bottlenecks and optimize for them <-- this one's really needed (and also for the more ambitious contributors)
- Resolve existing issues
- Record screencasts of features, write blogposts/tutorials, improve documentation, etc.
- Write plugins for common use-cases
  - ng-messages integration
  - Repeating sections
  - Angular Material
  - JSON Schema support
  - Additional types for bootstrap that integrates with angular-ui-bootstrap
  - Other ideas [here](http://docs.angular-formly.com/page/plugins)

**Comment by ckniffen** [comment]
@kentcdodds I thought there was ng-messages integration.

**Comment by kentcdodds** [comment]
Nothing official. Just stuff in the examples page.

**Comment by kentcdodds** [comment]
Hey, I had three family things come up for this weekend so I'm going to have to push this back two weeks. Is it alright if we move it to the 24th?

**Comment by SomeKittens** [comment]
Haven't done much promotion so at this stage I think it's ok.

**Comment by BobbieBarker** [comment]
Once you join our slack @  [angularBuddies](http://angularbuddies.com) type:
```
/join foss-hackday 
```
to join us in our channel!
