### ISSUE TITLE
Problem using directive + template

### ISSUE THREAD

**Issue by Rorkal** [formly-js/angular-formly#500]
Hello.

I am currently having problems on my project using directives and templates, error message never shows up !
I use a directive with formly wich use an input.I tried to make it simple in this example: http://jsbin.com/wajaqecano/1/edit?html,js,output
See the second input, there is no error message for 'required: true' when input is empty.

Am I doing something wrong?

**Comment by kentcdodds** [comment]
Hi @Rorkal,
I'm sorry that nobody's gotten to you until now. The github issues are reserved for bug reports and feature requests. If you're still having trouble with this, please follow the instructions here: http://help.angular-formly.com

**Comment by Rorkal** [comment]
Hi.
I wasn't sure if it was a bug or not. I will look into it. 
Thanks!
