### ISSUE TITLE
Custom option for addOns tabindex for formly bootstrap

### ISSUE THREAD

**Issue by Nishchit14** [formly-js/angular-formly#501]
Here i have to use two tab to go on next input field because of addons tabindex.

So if there is custom options for use tabindex for right/left addOns then it would so cool :)

And this is awesome :+1: 

![image](https://cloud.githubusercontent.com/assets/5078921/10276316/4b4e0f34-6b6c-11e5-808c-51f308c22114.png)

**Comment by kentcdodds** [comment]
Hi @Nishchit14! Thanks for using angular-formly :-) I've moved discussion for this issue to the bootstrap templates repo.
