### ISSUE TITLE
HideExpression in Nested form

### ISSUE THREAD

**Issue by altais** [formly-js/angular-formly#506]
Hi,

I have been working on this example (http://angular-formly.com/#/example/other/nested-formly-forms) to make a nested form.
It perfectly worked but when i'm in the field inside the nested form i can't access the global model : 
In the type "nested" i can access all the model but in data -> field i only have the model of the nested field.
I would like to hide the 2nd field of Address only if it's checked in the first nested form.
I wrote a jsbin to explain my problem : http://jsbin.com/lukuroxuni/1/edit?js,output

Can anyone help me?
Thx,
Cédric

**Comment by kentcdodds** [comment]
Could you use `formState`? http://kentcdodds.jsbin.com/vowuso/edit?html,js

Note, I changed the template for the `nested` type slightly and bound the checkbox to `formState` and updated the `hideExpression`. I think this is possibly what you're looking for.

Either way, the GitHub issues on this repository are reserved for bug reports or feature requests. If you have further questions, please follow the instructions here: http://chat.angular-formly.com
