### ISSUE TITLE
Remove property on hide, when hiding a fieldGroup

### ISSUE THREAD

**Issue by TheBekker** [formly-js/angular-formly#507]
Hi

I've been playing around with the "Remove property on hide" example, and seems to work fine. but i use alot of fieldGroups in my form, and also hide most of my input with a hideExpression outside the fieldGroup, so i can hide the whole fieldGroup with 1 hideExpression.

But the "Remove property on hide", doesnt seem to work on that.
Is it possible to extend the example code, to also clear all properties in a fieldGroup, if its hidden?

Se my example here:
http://jsbin.com/vugugonihi/edit?js,output

**Comment by benoror** [comment]
Hi @TheBekker! Thanks for your interest in angular-formly. I'm sure that angular-formly can do this for you. The best way to get help is by following the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Comment by ckniffen** [comment]
I feel like maybe this ticket should be moved to the formly website project.  As it is an enhancement request for an existing example.

**Comment by kentcdodds** [comment]
:+1:

On Sat, Oct 24, 2015, 5:43 PM Caleb Kniffen <notifications@github.com>
wrote:

> I feel like maybe this ticket should be moved to the formly website
> project. As it is an enhancement request for an existing example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/507#issuecomment-150872510>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by ckniffen** [comment]
I dont know if this fully applies but I wrote a utility to iterate over nested "fields".  I think it could be adapted to work with fieldGroups.

```
function iterateFields(fields, fn) {
      _.each(fields, function(field) {
        if(field.fields) {
          iterateFields(field.fields, fn);
          // return to prevent passing sections into fn
          return;
        }

        fn(field);
        if(field.templateOptions && field.templateOptions.fields) {
          iterateFields(field.templateOptions.fields, fn);
        }
      });
    }
```
