### ISSUE TITLE
ui-timepicker example is broken.

### ISSUE THREAD

**Issue by koraybalci** [formly-js/angular-formly#513]
Looks like http://angular-formly.com/#/example/integrations/ui-timepicker is broken. 

Checked in both chrome and ie if it matters.

**Comment by BarryThePenguin** [comment]
Need to update api-check from `master` to `latest`

`//rawgit.com/kentcdodds/apiCheck.js/latest/dist/api-check.min.js`

**Comment by benoror** [comment]
Done, thanks for letting me know!
