### ISSUE TITLE
Intercepting and overriding input[date] model data before binding

### ISSUE THREAD

**Issue by koraybalci** [formly-js/angular-formly#514]
I am trying to use input[date] as a simple formly field such as:
```
{
    "type": "input",
    "key": "birthday",    
    "templateOptions": {
      "type": "date",
      "label": "Date of Birth",
     }
}
```
However, angular input[date] binding does not automatically convert string to Date format and spits out an error like
> Error: [ngModel:datefmt] Expected 2010-05-13T00:00:00-04:00 to be a date

As discussed here: http://stackoverflow.com/questions/26853173/why-is-my-date-input-field-in-angularjs-throwing-type-error and here: http://stackoverflow.com/questions/26782917/model-is-not-a-date-object-on-input-in-angularjs

The easiest workaround is to convert string to new Date objects when payload is received, unfortunately this cannot be applied in my case (client side is not really aware of received object's properties, sort of a generic formly form is built).

I may use ui.datepicker or sth similar. However, I was wondering if I can intercept model binding somehow when a field's type is input[date] and create a proper Date object.

I tried traversing the whole payload and do the above fix in receiving end of my controller but things get messy when there are sub field groups etc.

Any ideas / suggestions? 

PS: Actually, fix suggested at the end of this issue https://github.com/formly-js/angular-formly-website/issues/15 by @yaronmiz is right on the spot, but I don't want to define a new formly type either, just fix the date model type.

I hope my question makes any sense :)

**Comment by dannycallaghan** [comment]
I don't really understand why you're against defining a new formly type. For me, that's one of the (many) fantastically powerful parts of formly. But...

Then why not add a controller to your existing 'input' type, then within that controller look for the existence of the templateOptions.type - if it's 'date' then perform the string to date conversion? That way, you're not adding a new formly type, and you're only affecting your existing input type if it's a date element.

**Comment by koraybalci** [comment]
I am not against new formly type at all, however, I suspect (gut feeling) that there is a better and simpler way. By the way, I already used ui datepicker example and defined a new type to overcome the problem.

On a side note, I also tried overriding actual input type and seek for date option set as you suggest but could not manage to work it out. I couldn't really figure out how to add a controller and do this one date fixing task alone.

I am pretty new to formly by the way.. It's great so far though..

**Comment by dannycallaghan** [comment]
Yeah, it is great isn't it? @kentcdodds has done / is doing an amazing job.

So I've not tested this, but adding a controller to the input type for your scenario would look something like this:

```javascript
formlyConfigProvider.setType({
	overwriteOk: true,
	name: 'input',
	template: require('YOUR_INPUT_TEMPLATE.html'),
	wrapper: ['label', 'bootstrapHasError'], // for example
	controller: ['$scope', function ($scope) {
		if ($scope.to.type && $scope.to.type === 'date') {
			/* 
			Do your stuff here, something like:
			
			var currentModelVal = $scope.model[$scope.options.key];
			if (typeof (currentModelVal) === 'string'){
				$scope.model[$scope.options.key] = new Date(currentModelVal);
			}
			*/
		}
	}]
});
```

**Comment by kentcdodds** [comment]
Thanks for your help and kind words @dannycallaghan :-)

Note, if all you want to do is override the template and add a controller you could define a new type that `extends` the `input` type, like so:

```javascript
formlyConfigProvider.setType({
    extends: 'input',
    name: 'myInput',
    template: require('YOUR_INPUT_TEMPLATE.html'),
    // don't need a wrapper because it will inherit that from the input type 
    controller: ['$scope', function ($scope) {
        if ($scope.to.type && $scope.to.type === 'date') {
            /* 
            Do your stuff here, something like:

            var currentModelVal = $scope.model[$scope.options.key];
            if (typeof (currentModelVal) === 'string'){
                $scope.model[$scope.options.key] = new Date(currentModelVal);
            }
            */
        }
    }]
});
```

**Comment by kentcdodds** [comment]
Also, I'm going to close this issue and direct you to the instructions at http://help.angular-formly.com

The github issues are reserved for feature requests and bug reports. We can help you better if you follow those instructions :-) cheers!
