### ISSUE TITLE
`npm start` isn't working (invalid config file)

### ISSUE THREAD

**Issue by atom-morgan** [formly-js/angular-formly#522]
I had a brief back and forth with @kentcdodds through Twitter about `npm run test` or `npm start` not working after a fresh clone and `npm install`. Here's what you initially asked for:

* System: Mac OSX Yosemite 
* npm: 3.3.5
* node: 0.10.40

As I mentioned on Twitter, this is happening when I run `npm run test` after `npm install`.

Here's the actual error I'm hitting:

```
⇒  npm run test

> angular-formly@0.0.0-semantically-released.0 test /Users/adammorgan/Desktop/angular-formly
> cross-env COVERAGE=true NODE_ENV=test karma start --single-run

-- recording coverage --

/Users/adammorgan/Desktop/angular-formly/node_modules/deindent/index.js:4
  let args = [].slice.call(arguments, 1);
  ^^^
16 10 2015 16:28:49.524:ERROR [config]: Invalid config file!
  SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adammorgan/Desktop/angular-formly/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/adammorgan/Desktop/angular-formly/other/webpack.config.es6.js:7:18)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/adammorgan/Desktop/angular-formly/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adammorgan/Desktop/angular-formly/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/adammorgan/Desktop/angular-formly/other/karma.conf.es6.js:12:23)
```
Please let me know if there's anything else I can provide to help. Thanks!

**Comment by kentcdodds** [comment]
From the look of that error, is failing because the version of node you
have is very very old and can't run even moderately modern JavaScript.
Could you update to the latest version of node (or even 0.12.x) and try
again? I recommend using nvm. Let me know! Thanks!

On Mon, Oct 19, 2015, 4:40 PM Adam Morgan <notifications@github.com> wrote:

> I had a brief back and forth with @kentcdodds
> <https://github.com/kentcdodds> through Twitter about npm run test or npm
> start not working after a fresh clone and npm install. Here's what you
> initially asked for:
>
>    - System: Mac OSX Yosemite
>    - npm: 3.3.5
>    - node: 0.10.40
>
> As I mentioned on Twitter, this is happening when I run npm run test
> after npm install.
>
> Here's the actual error I'm hitting:
>
> ⇒  npm run test
>
> > angular-formly@0.0.0-semantically-released.0 test /Users/adammorgan/Desktop/angular-formly
> > cross-env COVERAGE=true NODE_ENV=test karma start --single-run
>
> -- recording coverage --
>
> /Users/adammorgan/Desktop/angular-formly/node_modules/deindent/index.js:4
>   let args = [].slice.call(arguments, 1);
>   ^^^
> 16 10 2015 16:28:49.524:ERROR [config]: Invalid config file!
>   SyntaxError: Unexpected strict mode reserved word
>     at Module._compile (module.js:439:25)
>     at Module._extensions..js (module.js:474:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/Users/adammorgan/Desktop/angular-formly/node_modules/babel-core/lib/api/register/node.js:214:7)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/Users/adammorgan/Desktop/angular-formly/other/webpack.config.es6.js:7:18)
>     at Module._compile (module.js:456:26)
>     at normalLoader (/Users/adammorgan/Desktop/angular-formly/node_modules/babel-core/lib/api/register/node.js:199:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/Users/adammorgan/Desktop/angular-formly/node_modules/babel-core/lib/api/register/node.js:216:7)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/Users/adammorgan/Desktop/angular-formly/other/karma.conf.es6.js:12:23)
>
> Please let me know if there's anything else I can provide to help. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/522>.
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by atom-morgan** [comment]
Gotcha. That's the default on my system right now due to other work I'm doing. I updated to the latest version and it works. Thanks again for all of your help!

**Comment by brutalcrozt** [comment]
I am on windows running node 0.12.9.
any link will help, i will try solve it my own, since i know kent busy enough lately.

**Comment by benoror** [comment]
@brutalcrozt Try with a recent version of Node 4.* or even 5.* :smile:

**Comment by brutalcrozt** [comment]
@benoror he say or even 0.12.x . 4 or 5 ? how fast it's development. It's version confusing :confused: 
Downloading v.4.2.6 and i will report what happen soon
