### ISSUE TITLE
updateInitialValue doesn't work with complex keys

### ISSUE THREAD

**Issue by eliagentili** [formly-js/angular-formly#527]
I noticed that the updateInitialValue doesn't work if you define a complex key in your formly form.

This not work:
```
form: {
          options: {},
          model: this.model,
          fields: [
            {
              key: 'FieldParent.value',
              type: 'input',
              templateOptions: {
                label: 'FieldOne'
              }
            }
          ]
        }
      }
```

So, if the key is something like Field.value, or maybe more sub-index, it doesn't work.
Works only with simple key like "field".

This Work:
```
form: {
          options: {},
          model: this.model,
          fields: [
            {
              key: 'field',
              type: 'input',
              templateOptions: {
                label: 'FieldOne'
              }
            }
          ]
        }
      }
```

I think it's useful to handling sub-index in form keys, maybe editing:
src/directives/formly-field.js:182
can fix the problem.

**Comment by MCKRUZ** [comment]
I believe this is related to the same issue I'm having with model resetting.  Here is what I think is happening.
<code>
function resetModel() {
	      $scope.model[$scope.options.key] = $scope.options.initialValue;
	      if ($scope.options.formControl) {
	        if (_angularFix2['default'].isArray($scope.options.formControl)) {
	          _angularFix2['default'].forEach($scope.options.formControl, function (formControl) {
	            resetFormControl(formControl, true);
	          });
	        } else {
	          resetFormControl($scope.options.formControl);
	        }
	      }
	    }
</code>

Inside this code block we set $scope.model[$scope.options.key] like so.  Unfortunately if you have a key that is dot delimited it doesn't find the value.  We should be using some sort of recursive find like this one.

function _setNested(path, value, obj) {
            var schema = obj;  // a moving reference to internal objects within obj
            var pList = path.split('.');
            var len = pList.length;
            for (var i = 0; i < len - 1; i++) {
                var elem = pList[i];
                if (!schema[elem]) schema[elem] = {}
                schema = schema[elem];
            }

            schema[pList[len - 1]] = value;
        }

**Comment by kentcdodds** [comment]
No, the real solution is to set the value using the $parse service. We do
this for default values.

On Fri, Oct 30, 2015, 6:19 AM MCKRUZ <notifications@github.com> wrote:

> I believe this is related to the same issue I'm having with model
> resetting. Here is what I think is happening.
>
> function resetModel() {
> $scope.model[$scope.options.key] = $scope.options.initialValue;
> if ($scope.options.formControl) {
> if (_angularFix2['default'].isArray($scope.options.formControl)) {
> _angularFix2['default'].forEach($scope.options.formControl, function
> (formControl) {
> resetFormControl(formControl, true);
> });
> } else {
> resetFormControl($scope.options.formControl);
> }
> }
> }
>
> Inside this code block we set $scope.model[$scope.options.key] like so.
> Unfortunately if you have a key that is dot delimited it doesn't find the
> value. We should be using some sort of recursive find like this one.
>
> function _setNested(path, value, obj) {
> var schema = obj; // a moving reference to internal objects within obj
> var pList = path.split('.');
> var len = pList.length;
> for (var i = 0; i < len - 1; i++) {
> var elem = pList[i];
> if (!schema[elem]) schema[elem] = {}
> schema = schema[elem];
> }
>
>         schema[pList[len - 1]] = value;
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/527#issuecomment-152522247>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by MCKRUZ** [comment]
So something like

var setter = $parse($scope.options.key).assign;
	        setter($scope.model, $scope.options.initialValue);

**Comment by kentcdodds** [comment]
That would do the trick! Do you want to create a PR with a test and
implementation? :-) :+1:

On Fri, Oct 30, 2015, 6:52 AM MCKRUZ <notifications@github.com> wrote:

> So something like
>
> var setter = $parse($scope.options.key).assign;
> setter($scope.model, $scope.options.initialValue);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/527#issuecomment-152531451>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by kentcdodds** [comment]
If so, see the CONTRIBUTING.md file

On Fri, Oct 30, 2015, 6:53 AM Kent C. Dodds <kent@doddsfamily.us> wrote:

> That would do the trick! Do you want to create a PR with a test and
> implementation? :-) :+1:
>
> On Fri, Oct 30, 2015, 6:52 AM MCKRUZ <notifications@github.com> wrote:
>
>> So something like
>>
>> var setter = $parse($scope.options.key).assign;
>> setter($scope.model, $scope.options.initialValue);
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/formly-js/angular-formly/issues/527#issuecomment-152531451>
>> .
>>
> --
> - Kent C. Dodds <https://twitter.com/kentcdodds>
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by MCKRUZ** [comment]
Sure Give me a few

**Comment by MCKRUZ** [comment]
Kent, how do I debug through the unit test.  I tossed a debugger command inside but it doesn't break for me.

**Comment by kentcdodds** [comment]
Run `npm run test:debug` and it should open your tests in chrome. Then click the Debug button in that chrome window and it should open a new tab. Then open your developer tools in that tab and refresh the team. It should stop at your breakpoint.

**Comment by kentcdodds** [comment]
Whoops, miss-tapped

**Comment by MCKRUZ** [comment]
ok so $parse($scope.options.key)($scope.model)  does not work with $scope.options.key is a number.  

Any ideas?

**Comment by kentcdodds** [comment]
Maybe check if it's a number first and if it is, then don't use the parse service and do what it used to do.

**Comment by MCKRUZ** [comment]
ok I fixed it but now I'm getting this when trying to commit


git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/xq/b_llhsj1735gqlr3sh99cpbm0000gp/T/SourceTreeTemp.QHb7lk -a 
env: node: No such file or directory
Completed with errors, see above

**Comment by MCKRUZ** [comment]
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run eslint:test -s && npm run eslint:src -s

**Comment by MCKRUZ** [comment]
nm I got it.  Pushed

**Comment by MCKRUZ** [comment]
Kent, is this still a bug with my fix?

**Comment by kentcdodds** [comment]
Probably not! @eliagentili, could you verify this with the latest version of angular-formly?
