### ISSUE TITLE
fieldTransform apply only once

### ISSUE THREAD

**Issue by thefrontfactory** [formly-js/angular-formly#530]
Hi,
It seems that fieldTransform functions are only run once when setupFields is executed.
Because I am retrieving fields asynchronously, the transform are done when fields are not yet present.

Is there a way or a known workarround to allow transforms to be done when fields are updated?
Thanks for your help

**Comment by kentcdodds** [comment]
Yes, use ng-if to hide your formly-form until your fields are there.
Something like: ng-if="vm.fields.lenth" should do the trick.

On Fri, Oct 30, 2015, 8:57 AM thefrontfactory <notifications@github.com>
wrote:

> Hi,
> It seems that fieldTransform functions are only run once when setupFields
> is executed.
> Because I am retrieving fields asynchronously, the transform are done when
> fields are not yet present.
>
> Is there a way or a known workarround to allow transforms to be done when
> fields are updated?
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/530>.
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by thefrontfactory** [comment]
Hi,
I have an issue with the ng-if and fieldGroup, if I use an ng-if, groups are not displaying because somehow the ng-if is propagating.
My main form is going to be displayed, but then the subforms created by fieldGroup are not displayed because it fails the ng-if condition.
Thanks for your help

**Comment by kentcdodds** [comment]
I'm afraid that I don't know how to help you without more information. Please follow [these instructions](http://help.angular-formly.com) to get help.

Because the GitHub issues are reserved for bug reports and feature requests and this is more of a support issue, I'm going to close this one. Good luck! See you on chat!
