### ISSUE TITLE
Matching two fields example bugs.

### ISSUE THREAD

**Issue by yahyaKacem** [formly-js/angular-formly#533]
Hi, first thanks for your great effort on this and everyone who contributed, I'm trying to do a confirm password validation, like in [the matching two fields example](http://angular-formly.com/#/example/other/matching-two-fields), but I'm experiencing some weird behaviour.
I have this [screen capture](https://www.youtube.com/watch?v=IicyUoJQow8) on the errors I'm talking about on the example page it self I only added this small code(the second h2 and the pre under it) just to show the content of the confirm password and when it's valid:

    <h2>Model</h2>
    <pre>{{vm.model | json}}</pre>
    <h2>Confirmation Model</h2>
    <pre>{{vm.confirmationModel | json}}</pre>.

just to give a better description if the video is not clear when the password field is changed only when 2 characters are changed then the validation for the confirm password field is triggered, even if the second change is putting the same removed character back the confirm password field will still be invalid.

**Comment by dfromero** [comment]
@yahyaKacem btw your video is private, can't your capture.

**Comment by yahyaKacem** [comment]
@dfromero sorry, first video on Youtube, it's public now.

**Comment by yahyaKacem** [comment]
OK, I'v done some work on this, first I was going to take Google's approach on this and deleting the confirm password field whenever the password field changed, that was easy to implement but, it's annoying to have to retype the confirm password field from the start just because you added one character to the password field, so I did this:
 first have a data.fieldToMatch in both fields to have a reference in the password onChange method to what field I need to trigger the validation for, and to have another reference in the confirm password field to what field to match to, then whenever the password field changes select the field name to match from the scope.fields (I'm using lodash for this) and trigger it's validation, [example code](http://plnkr.co/edit/Y8Z07x?p=preview):

    Auth.formFields = [
      {
        type: "input",
        key:  "password",
        model: Auth.user,
        templateOptions: {
          type:        "password",
          label:       "Password",
          placeholder: "Password",
          onChange: function onChangeF(viewValue, modelValue, fieldScope) {
            var fieldToMatch = lodash.find(fieldScope.fields, {key: fieldScope.options.data.fieldToMatch}).name;
            fieldScope.form[fieldToMatch].$validate();
          }
        },
        data: {
          fieldToMatch: "confirm_password"
        }
      },
      {
        type:            "input",
        model:           Auth.user,
        key:             "confirm_password",
        templateOptions: {
          type:        "password",
          label:       "Confirm Password",
          placeholder: "Confirm Password"
        },
        validators: {
          fieldMatch: {
            expression: function fieldMatchExpression(viewValue, modelValue, fieldScope) {
              return (modelValue || viewValue) === Auth.user[fieldScope.options.data.fieldToMatch];
            }
          }
        },
        data: {
          fieldToMatch: "password"
        }
      }
    ];

this is just a simple example on how this could be approached maybe someone that have more knowledge of this plugin could enhance this solution.

**Comment by kentcdodds** [comment]
Hi @yahyaKacem. Sorry I never came to give you some feedback. You might look into [`extras.validateOnModelChange`](http://docs.angular-formly.com/v7.2.3/docs/field-configuration-object#extras-object) on the field you wish to validate rather than that `onChange` function on the field you're changing.

Other than that I think your solution looks pretty good. In the future when you need help, please follow the instructions here: http://help.angular-formly.com. The GitHub issues on this project are reserved for bug reports and feature requests. Have a nice day!
