### ISSUE TITLE
TypeError: (...) not a function

### ISSUE THREAD

**Issue by JiaJian** [formly-js/angular-formly#536]

**Comment by benoror** [comment]
>Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com
>
>This will make it easier for you to get help. Because the github issues are reserved for bug reports and feature requests, I'm going to go ahead and close this issue. See you on chat! Thanks!

**Comment by JiaJian** [comment]
Sorry! Accidentally hit some keys which submitted my issue while I haven't typed anything.

**Comment by benoror** [comment]
Don't worry :smile:
