### ISSUE TITLE
TypeError: (...) is not a function

### ISSUE THREAD

**Issue by JiaJian** [formly-js/angular-formly#537]
Hi! I got this error `Uncaught TypeError: (0 , _apiCheck2.default) is not a function`  when I included the latest version of formly into my Angular project. Anybody knows any fix for this?

**Comment by benoror** [comment]
Do you mind creating an example of what you're trying to accomplish? Please follow the instructions here: http://help.angular-formly.com

**Comment by JiaJian** [comment]
Ah got it, I missed out on api-check.js. Thanks!

**Comment by benoror** [comment]
:+1:

**Comment by cmwilhelm** [comment]
I had a follow up to this issue actually, having run into it today. Should formly's dependencies on the api-check module be affected by javascript inclusion order in the document?

I'm not using CommonJS or AMD for this application, and simply installed formly via bower. I received the same error as @JiaJian , and was only able to resolve it by doing a <script> tag for the api check file before the formly file. This was a bit surprising given Angular's ability to resolve dependencies?

**Comment by kentcdodds** [comment]
Yeah, but api-check isn't part of Angular at all. Think of it like jQuery or lodash. Order matters.
