### ISSUE TITLE
Watch does not work on deep properties

### ISSUE THREAD

**Issue by MCKRUZ** [formly-js/angular-formly#542]
http://jsbin.com/ginalo/1/edit?console,output

Try typing in the first field.  It no longer works.

As soon as you make the key a deep object like foo.text it will fail.

**Comment by kentcdodds** [comment]
Good find. Here's the line of code that causes the problem. What do you think we could/should do about it? https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-form.js#L293

**Comment by MCKRUZ** [comment]
Yes...but it's a touch hokey

change this
<code>var watchExpression = watcher.expression || '$parse(\'' + field.key + '\')(model)';</code>

to this
<code>var watchExpression = watcher.expression || '$parse(\'' + field.key.split('.').join('\'][\'') + '\')(model)';</code>

**Comment by kentcdodds** [comment]
I don't know if that would actually work... I don't think you can use `$parse` in a string expression like that.  Honestly, I think this is sort of an edge case and unless we can accomplish a solution that avoids the following two issues, I don't want to worry about it:

1. It adds complexity to the codebase
2. It reduces performance for the common case

I don't know if there's a satisfactory way to accomplish both of those for this case.

**Comment by MCKRUZ** [comment]
Hey Kent, sorry it looks like I posted the wrong code.

This is my fix.  I tried it and it works locally

var watchExpression = watcher.expression || 'model[\'' + field.key.split('.').join('\'][\'') + '\']';

**Comment by kentcdodds** [comment]
I think that's acceptable. Feel free to submit a PR :-)

On Mon, Nov 9, 2015, 6:28 AM MCKRUZ <notifications@github.com> wrote:

> Hey Kent, sorry it looks like I posted the wrong code.
>
> This is my fix. I tried it and it works locally
>
> var watchExpression = watcher.expression || 'model[\'' +
> field.key.split('.').join('\'][\'') + '\']';
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/issues/542#issuecomment-155061290>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by MCKRUZ** [comment]
Done and Done.

**Comment by blowsie** [comment]
I think this is a problem in other places, such as the documentation.
![image](https://cloud.githubusercontent.com/assets/308572/11066333/b130851a-87bf-11e5-890f-55139e97c291.png)

And all of the formly bootstrap templates.

How can we approach this?

**Comment by kentcdodds** [comment]
No, in the case of a nested key, angular-formly will actually change `ng-model="model[options.key]"` to `ng-model="model.your.nested.key"`. But only when you specify a nested key.

**Comment by blowsie** [comment]
Thanks for the information.
Indeed it does, very smart.

My problem was that I was using `formly-skip-ng-model-attrs-manipulator` along with `ng-model="model[options.key]" and it was of course breaking.

**Comment by blowsie** [comment]
I'm struggling to find how / where formly does this.

I keep finding lots of the examples, like the repeater which do not support `$scope,model[options.key]` when it is a nested key e.g. `key: 'user.name'`
http://angular-formly.com/#/example/advanced/repeating-section

Could you point me in the right direction as to how can I get this example to work?
I would be happy to update the examples If I could figure out how this works :)

**Comment by kentcdodds** [comment]
[Here's the function](https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.js#L46-L50) that does it and [here are the tests](https://github.com/formly-js/angular-formly/blob/master/src/run/formlyNgModelAttrsManipulator.test.js#L181-L193)

**Comment by MCKRUZ** [comment]
Kent, can you verify that this is the test you want.

    it(`should add watches on deep dive fields`, () => {
      const formWithOptions = '<formly-form model="model" fields="fields" options="options"></formly-form>'
      scope.model = {}
      scope.options = {}

      const deepLinkField = getNewField()
      deepLinkField.key = 'foo.bar'
      deepLinkField.watcher = {
        listener: sinon.spy(),
      }

      scope.fields = [deepLinkField]
      compileAndDigest(formWithOptions)
      expect(compileAndDigest).to.not.throw()
      expect(deepLinkField.watcher.listener).to.have.been.called
      scope.model[deepLinkField.key] = 'brown'
      scope.$digest()
      expect(compileAndDigest).to.not.throw()
      expect(deepLinkField.watcher.listener).to.have.been.called
    })

**Comment by kentcdodds** [comment]
Yes, I think that should work.

**Comment by MCKRUZ** [comment]
Kent, can you verify this is what you want?  I can't get to your other comment about this and I want to put this issue to b`    it(`should add watches on deep dive fields`, () => {
      const formWithOptions = '<formly-form model="model" fields="fields" options="options"></formly-form>'
      scope.model = {}
      scope.options = {}

      const deepLinkField = getNewField()
      deepLinkField.key = 'foo.bar'
      deepLinkField.watcher = {
        listener: sinon.spy(),
      }

      scope.fields = [deepLinkField]
      compileAndDigest(formWithOptions)
      expect(deepLinkField.watcher.listener).to.have.been.called
      scope.model.foo = {
        bar: 'brown',
      }
      scope.$digest()
      expect(deepLinkField.watcher.listener).to.have.been.called
    })`

**Comment by kentcdodds** [comment]
Yes, that should do it! I triple checked it this time. Thanks!

**Comment by MCKRUZ** [comment]
Ok hopefully this is good now

**Comment by kentcdodds** [comment]
Boom! This is fixed in `7.3.4`. Thanks @MCKRUZ!
