### ISSUE TITLE
showError variable not correct for control types with multiple inputs

### ISSUE THREAD

**Issue by bjspencer** [formly-js/angular-formly#548]
If a formly control type contains multiple input elements, then the showError variable always comes into the template as false.

**Comment by kentcdodds** [comment]
Could you produce an example with [issue.angular-formly.com](http://issue.angular-formly.com/). Thanks!

**Comment by kentcdodds** [comment]
Actually, this is a duplicate: https://github.com/formly-js/angular-formly/issues/510

**Comment by bjspencer** [comment]
Okay, I'll change my PR to reference the other issue

**Comment by kentcdodds** [comment]
Please check out the conversation over there. You'll need to adjust your implementation a bit.

**Comment by bjspencer** [comment]
Ah, looks like that other implementation is better anyway, so I'll hold off. Sorry for jumping the gun!

Date: Wed, 11 Nov 2015 11:05:52 -0800

**Comment by kentcdodds** [comment]
Nope, you're good. I think that @chrisheninger could use some help with that actually if you want to collaborate on #510 that'd be cool.
