### ISSUE TITLE
Fix focus with UI Bootstrap Modal

### ISSUE THREAD

**Issue by Knoxvillekm** [formly-js/angular-formly#562]
Field not focused and touched (show validation error)

http://jsbin.com/dibilesore/1/edit?html,js,output

**Comment by kentcdodds** [comment]
My guess is that this is an odd behavior with how ui-bootstrap deals with focus for modals. Here's a solution that uses `expressionProperties` which will set the focus value after the form is initially digested: https://jsbin.com/qanumi/1/edit?html,js,output

**Comment by juriw** [comment]
@kentcdodds I have the same problem with Angular Material v1.0.1

My problem is that only first time the modals first input is triggered. Next time it is not autofocused but the focus is kept on the main view behind the modal.

This is how I use autofocus in my modals; 
```
vm.fields = [
        {
            "elementAttributes": {
                layout: "row",
                "layout-sm": "column"
            },
            "fieldGroup": [
                {

                    key: 'name',
                    className: "flex-100 layout-column",
                    type: 'input',
                    templateOptions: {
                        type: 'text',
                        label: 'Kundenavn',
                        required: true,
                        focus: true
                    }
                },
................................................................................
```
