### ISSUE TITLE
Breaking change in @7.3.2? Key value?

### ISSUE THREAD

**Issue by dannycallaghan** [formly-js/angular-formly#566]
We've been using version 6.26.9 in production on our customer facing app (at tillr.io). We have an in-house tool that allows non-technical staff to build formly forms, using a GUI that generates the JSON. The tool generates a GUID for each form field, which is used as the form key - for example:

```javascript
{
  'key' : '0e327d36-e4c3-4080-947d-4b8c14d1d89d',
  'type': 'input'
}
```

Today I finally had time to upgrade our formly version, and every form is now broken. After some investigation, it seems that version 7.3.2 had a change that means that we can't use GUIDs as keys. More specifically, it seems that a key that contains a numeric character that proceeds an alpha character can cause errors. For example:

```javascript
// ...
'key' : 'A1', // no error
// ...
'key' : '1A', // ERROR
// ...
'key' : 'A1A', // no error
// ...
'key' : '1A1A', // ERROR
// ...
'key' : 'first-line-of-address', // no error
// ...
'key' : '1st-line-of-address', // ERROR
// ...
'key' : 'address-1st-line', // ERROR
```

You can see it here. Using 7.3.1, there are no errors:

http://jsbin.com/bumegi/edit?html,js,console,output

Using 7.3.2 (or any later version), and everything breaks:

http://jsbin.com/lejafu/edit?html,js,console,output

**Comment by dannycallaghan** [comment]
I can't pretend that I get what's going on with parseGet, but it seems that if it's changed to:

```javascript
function parseGet(key, model) {
  // If either of these are null/undefined then just return undefined
  if (!key || !model) {
    return undefined;
  }
  return model[key];
}
```

... then all of the following keys are valid:

```javascript
// ...
'key' : 100,
// ...
'key' : 'onehundred',
// ...
'key' : '1hundred',
```

Obviously, I suspect that parseGet is doing something that I'm missing. Can you shed any light?

**Comment by kentcdodds** [comment]
Yeah, `parseGet` is to allow for nested keys, like: `name.first`, so it's using the `$parse` service. My guess in the `$parse` service doesn't like a preceding number in a property getter or something. @MCKRUZ, do you think you could look into this?

**Comment by MCKRUZ** [comment]
Yeah, I think I have an easy fix solution

**Comment by MCKRUZ** [comment]
So this is actually more complex then it seems.

The test 'nested keys' is actually passing for the wrong reasons

When this gets called

`const secondField = {template: input, key: nestedArray, defaultValue}
        scope.fields.push(secondField)`

the nestedArray value is baz[0] which actually makes it so the model looks like this

scope.model.baz.0 = value

not like this

scope.model.baz[0] = value

So we need to figure out a way to dynamically set up a nested array.

**Comment by MCKRUZ** [comment]
Ok so I can fix the crash by putting this in

`if (/\d/.test(key) && key.indexOf('[') !== -1) {
        return model[key]
      } else {
        return $parse(key)(model)
      }` 

but it wont fix the array issue.

Kent is this sufficient?

**Comment by kentcdodds** [comment]
I think that if the model is already an array, then angular will treat it like an array. Otherwise (if it's an object or undefined) angular will make it an object and set the property there. @dannycallaghan can you try initializing your model to an object and seeing if that works?

**Comment by kentcdodds** [comment]
Actually... Yeah, that wont work... Nevermind...

@MCKRUZ, I think that your solution should work pretty well. Just make sure to write/run tests and check the code coverage report generated in the `coverage/lcov-report` folder to make sure you're covering what you think you are :-) Thanks!

**Comment by MCKRUZ** [comment]
Ok just checked in a fix.

**Comment by dannycallaghan** [comment]
Wow, incredible stuff. Thank you @MCKRUZ and @kentcdodds. 

Some open source projects are run badly, some are run really well, and then there is angular-formly. :)

**Comment by MCKRUZ** [comment]
Thanks!

And um...thanks to the second too, I think lol.

**Comment by kentcdodds** [comment]
All the thanks is to @MCKRUZ on this one. I just clicked the merge button.

**Comment by dannycallaghan** [comment]
Really sorry, but I don't think your tests covered all scenarios, in particular using GUIDs as keys. Using the test examples from my first post, most are now fixed, some are not:

```javascript
// ...
'key' : 'A1', // no error
// ...
'key' : '1A', // no error
// ...
'key' : 'A1A', // no error
// ...
'key' : '1A1A', // no error
// ...
'key' : 'first-line-of-address', // no error
// ...
'key' : '1st-line-of-address', // no error
// ...
'key' : 'address-1st-line', // ERROR
// ...
'key' : b141c66a-2857-4196-847b-b2096fa6170d', // ERROR
```
http://jsbin.com/sutuni/edit?html,js,console,output

Pretty certain that this bin is using the very latest.

**Comment by kentcdodds** [comment]
Yep, that's latest. @dannycallaghan, do you fancy making a pull request to add skipped test cases for your keys?

**Comment by MCKRUZ** [comment]
I have to admit I'm a little stumped on this one

If I do this..

`function shouldNotUseParseKey(key) {
      return angular.isNumber(key) || (/^\d/.test(key) && key.indexOf('[') === -1) || (key.indexOf('-') !== -1)
    }`

Then this works
address-1st-line
but this doesn't
b141c66a-2857-4196-847b-b2096fa6170d

Kent any ideas?

**Comment by MCKRUZ** [comment]
I don't think the second one ever worked.  Even with the original code

**Comment by kentcdodds** [comment]
What if we changed it to:

```javascript
function shouldNotUseParse(key) {
  return angular.isNumber(key) || !containsSelector(string)
}

// maybe we should put these in formlyUtils...
function containsSelector(string) {
  return contains(string, '.') || (contains(string, '[') && contains(string, ']'))
}

function contains(a, b) {
  if (!a || !a.indexOf) {
    return false
  }
  return a.indexOf(b) !== -1
}
```

What do you think?

**Comment by dannycallaghan** [comment]
By the second one, do you mean the GUID? It works in production now, on 6.26.9. We have clients using forms with those keys.

**Comment by MCKRUZ** [comment]
Danny sorry I stand corrected.  I pushed a change, that should fix it.

**Comment by dannycallaghan** [comment]
Thanks again @MCKRUZ, I really appreciate it.

**Comment by kentcdodds** [comment]
Guessing it's been resolved.

**Comment by dannycallaghan** [comment]
Apologies, @kentcdodds. Yes, it's perfect, thank you and @MCKRUZ.
