### ISSUE TITLE
resetModel() does not reset the $pristine and $dirty flag on the main form

### ISSUE THREAD

**Issue by abhisheksaraiya** [formly-js/angular-formly#574]
Calling resetModel() on the options resets the field $pristine and $untouched values on each field nicely but the $pristine on the main form is left unchanged. Is there a reason why these are left out in the resetModel call?

**Comment by kentcdodds** [comment]
`resetModel` should update those values. Could you please reproduce your issue using [issue.angular-formly.com](http://issue.angular-formly.com/)? It will help us determine what exactly the problem is that you're describing and how it could be fixed. Thanks!

**Comment by abhisheksaraiya** [comment]
Here are the steps to reproduce the issue:
http://jsbin.com/jonocawunu/edit?html,js,output

1) In the beginging when the page is loaded in jsbin, please note the values $pristine and $dirty for FORM with name : "vm.form". 
They would be 
Values for FORM:
	"$dirty": false,
 	"$pristine": true,
Values for input field:
	"$dirty": false,
 	"$pristine": true,
    
2) Now if you write anything in the input box in the form the values will change to 
Values for FORM:
  	"$dirty": true,
  	"$pristine": false,
Values for input field:
	"$dirty": true,
    "$pristine": false,

 This is OK!

3) Now when you click on reset button (thus calling resetModel()), the values change to:
Values for FORM:
 	 "$dirty": true,
 	 "$pristine": false,
Values for input field:
	"$dirty": false,
    "$pristine": true,

 The issue is that after resetModel is called, the values for the input field are reset as expected but for the form ($pristine,$dirty) are not reset!

**Comment by kentcdodds** [comment]
Looks like after we call `resetModel` on all the individual fields ([right here](https://github.com/formly-js/angular-formly/blob/917ec263ddcc4902fa2cb9dc167da0734f9d5ed6/src/directives/formly-form.js#L207-L215)) we need to set the form's `touched` and `pristine` state like we do with the individual fields ([here](https://github.com/formly-js/angular-formly/blob/8648c16c0a927ccbdf56861280a3680396041402/src/directives/formly-field.js#L202-L215)).

I'm open to a pull request for this! Anyone's welcome to try. Just follow [these instructions](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#pull-requests)

**Comment by tuckerjt07** [comment]
I am working on this issue but have ran into a problem. I took a fresh clone and I am getting a couple of errors when attempting to follow the steps you laid out. On the npm install 
>npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'semantic-release/last-release-npm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'semantic-release'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

>npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/jacobtucker/Toolbox/Workspace/angular-formly
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

And then on the npm start
>09 12 2015 23:30:29.667:ERROR [config]: Invalid config file!
  SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jacobtucker/Toolbox/Workspace/angular-formly/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jacobtucker/Toolbox/Workspace/angular-formly/other/webpack.config.es6.js:8:18)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/jacobtucker/Toolbox/Workspace/angular-formly/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jacobtucker/Toolbox/Workspace/angular-formly/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jacobtucker/Toolbox/Workspace/angular-formly/other/karma.conf.es6.js:13:23)

>npm ERR! angular-formly@0.0.0-semantically-released.0 test:watch: `karma start --set-env-COVERAGE=true --set-env-NODE_ENV=test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-formly@0.0.0-semantically-released.0 test:watch script.
npm ERR! This is most likely a problem with the angular-formly package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start --set-env-COVERAGE=true --set-env-NODE_ENV=test
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-formly
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "test:watch"
npm ERR! cwd /Users/jacobtucker/Toolbox/Workspace/angular-formly
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jacobtucker/Toolbox/Workspace/angular-formly/npm-debug.log
npm ERR! not ok code 0

>npm ERR! angular-formly@0.0.0-semantically-released.0 start: `npm run test:watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-formly@0.0.0-semantically-released.0 start script.
npm ERR! This is most likely a problem with the angular-formly package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test:watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-formly
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/jacobtucker/Toolbox/Workspace/angular-formly
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jacobtucker/Toolbox/Workspace/angular-formly/npm-debug.log
npm ERR! not ok code 0

Any ideas?

**Comment by thomasjosephgreco** [comment]
@kentcdodds is this issue still open? I checked it out the other day but i'm just seeing that I misread the comments :hear_no_evil:

**Comment by kentcdodds** [comment]
This issue should be closed I think. Let me know if you experience otherwise!

**Comment by janneman001** [comment]
I still see this in formly 7.2.3.  after resetModel  vm.form.$pristine equals false and vm.form.$dirty equals true. They should represent a propagated calculation from the fields $pristine and $dirty.

**Comment by kentcdodds** [comment]
@janneman001 could you provide an example of this behavior?

**Comment by janneman001** [comment]
I retested with latest 7.3.9. Same behaviour.
I have no experience with js bin. But i will try. I experienced the issue in a form with mysql backend code. I will try to make a smaller reproduction example if time permits.

**Comment by kentcdodds** [comment]
Here you can use [this](http://help.angular-formly.com) as a starter, then just post the link in here :+1:

**Comment by janneman001** [comment]
My bad. I was fighting with an incorrect datepicker type field.  I re-verified with 7.3.9 it is alright in 7.3.9.
