### ISSUE TITLE
ngModelAttrs customExpression fails

### ISSUE THREAD

**Issue by epnikolop** [formly-js/angular-formly#575]
Error: angular-formly: formly-field directive apiCheck failed! `ngModelAttrs` at `Argument 1/value` must be `objectOf[strict shape]`  formly-field-directive-validation-failed

http://jsbin.com/nebifu/edit?html,css,js,output

could be seen at formly examples official page

**Comment by kentcdodds** [comment]
In the last major version `expression` was changed to `statement`. Here's a working example:

https://jsbin.com/purobo/edit?js,console,output

**Comment by kentcdodds** [comment]
I've updated the example. Thanks!
