### ISSUE TITLE
Enter key on input will jump over validation, why? any solutions?

### ISSUE THREAD

**Issue by nextglory** [formly-js/angular-formly#588]
In the second step of demo:
http://angular-formly.com/#/example/integrations/angular-wizard

If you click the enter key, it will go to the next step, even when the fields are required.

Any solutions on this?

**Comment by nextglory** [comment]
I found that when enter key is fired, the form $valid state is true, this is whird.

**Comment by benoror** [comment]
This is not handled by angular-formly, but by the 3rd party wizard directive

In their docs the handle step validation: https://github.com/mgonto/angular-wizard#wizard-step-validation

Fixed example: http://jsbin.com/fexuji/1/edit?html,js,console,output

**Comment by nextglory** [comment]
benoror, awesome, I checked your code and amazingly cool.....

**Comment by benoror** [comment]
:smile:
