### ISSUE TITLE
Formly examples for UI Bootstrap are using deprecated code

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#590]
Hey guys, I pinged Kent on Slack but didn't hear back.

We're getting ready to release UI Bootstrap 1.0 and this release removes all the deprecated UIBS code currently being used in the Formly JSBin demos for UIBS Tabs, Modal, and Typeahead.  This means your demos will no longer work as they are using the old format.

It should be as simple as adding the `uib-` prefix to our directives, but take a quick look at the console to ensure the warning messages are gone.  This can be done w/ the current version of UIBS that you're using.

I'm happy to help you update this as it should only take a minute or two but I think the JSBins are owned by Kent.  Thanks.

**Comment by tuckerjt07** [comment]
Thanks for letting us know. You can copy Kent's JSBins and make the necessary changes then create a pull request on the examples.json file here: https://github.com/formly-js/angular-formly-website/

**Comment by icfantv** [comment]
Done.
