### ISSUE TITLE
Angular 2.0 and Latest Thoughts

### ISSUE THREAD

**Issue by rayhooker** [formly-js/angular-formly#593]
What are your current thoughts and plans on angular-formly and Angular 2.0.  I am about to go into full scale development of a dynamic forms solution with editor, etc.  From what I can tell Angular 2.0 does provide part of the functionality to describe a schema but not to have data driven form layout for truly dynamic forms.  So any thoughts or pointers?

Ray

**Comment by kentcdodds** [comment]
Hi @rayhooker. Thanks for the question. I actually just recently answered this on my [AMA](http://ama.kcd.im) [here](https://github.com/kentcdodds/ama/issues/66#issuecomment-169456411). Let me know if you have further questions :-)
