### ISSUE TITLE
Update invalid cdn on angular-formly example page

### ISSUE THREAD

**Issue by sandip-wane** [formly-js/angular-formly#609]
Hi, it seems some of the example on http://angular-formly.com/#/ are not working due to wrong cdn address, making preview of example non-usable. I found 'ui-bootstrap tabs' example working when changed cdn of ui-bootstrap. There are also other few example which have similar/other problem. Please update these update these examples.

**Comment by kentcdodds** [comment]
The examples seem to be working fine for me... Could you check them again?

**Comment by kamilkisiela** [comment]
As I wrote in formly-js/angular-formly-website#93

angular-ui-bootstrap v1.0.0 has a breaking change.

**Comment by kentcdodds** [comment]
Thanks @kamilkisiela! :D

**Comment by kamilkisiela** [comment]
@kentcdodds I fixed that in few others examples.

https://github.com/formly-js/angular-formly-website/compare/ebd26ff...c1c2577

So if any other example uses angular-ui-bootstrap it should be fixed immediately

**Comment by benoror** [comment]
@kamilkisiela super! :+1:

**Comment by sandip-wane** [comment]
Thanks for the fix and sorry for posting issue in wrong place :disappointed:
