### ISSUE TITLE
Add user to angular-formly site: GroupRaise

### ISSUE THREAD

**Issue by swifthand** [formly-js/angular-formly#611]
# Add GroupRaise to users

### Short Description:

GroupRaise helps restaurants host meals where groups of 20-200+ diners in exchange for donating a percentage of the sales to a charitable cause or organization. These meals are organized, found, and marketed online. The organization process, which could take weeks before or in some cases was not even possible, now takes a few clicks on GroupRaise.com.

GroupRaise improves all aspects of the fundraising experience, but a huge part of this is saving people time. Having clean, interactive, usable forms is critical to this, and (as of 2016) we are midway through transitioning all of our forms to angular-formly!

**Comment by kentcdodds** [comment]
Anyone from @formly-js/angular-formly-collaborators wanna take this one? https://github.com/formly-js/angular-formly-website/tree/master/app/states/root/children/users/components/data

**Comment by swifthand** [comment]
I'm going to try and throw together a pull request in a few minutes.

**Comment by kentcdodds** [comment]
:+1: even better! Thanks :D
