### ISSUE TITLE
need UI autogenerator

### ISSUE THREAD

**Issue by rameshpalipi** [formly-js/angular-formly#613]
Hi
We are looking for schema generator for angular-formly.
Can you suggest any?
are these GUI editors  targeting " angular-formly"? or it is totally separate?
easyFormGenerator
formly-builder

Thanks
Ram

**Comment by kentcdodds** [comment]
Here are the GUI builders I'm aware of. Built by others: http://docs.angular-formly.com/docs/gui-form-builders

**Comment by rameshpalipi** [comment]
so,can I use the schema generated by these tools in "angular-formly"?

**Comment by kentcdodds** [comment]
That's what they promise. If you have problems with them, contact their respective maintainers.

**Comment by rameshpalipi** [comment]
Kent,

I have following questions:
1. Is there any working example of angular-formly getting and setting data from database ?

2. In Fields definition, for a control like drop-down if we need to have the data be populated 
from database?
how to accomplish this?
{
    "key": "default-select-6347",
    "templateOptions": {
      "label": "Select",
      "placeholder": "placeholder",
      "options": [
        {
          "name": "value one",
          "value": "value one"
        },
        {
          "name": "value two",
          "value": "value two"
        }
      ]
    },

How to make the options values as database driven as we don't want to hard coded
as part of fields definition? 

3. What are the advantages and dis-advantages of using anular-formly ?
  Are there any limitations in terms of complexity , flexibility and learning?
4. Are there enterprise applications being built on top of this anular-formly ?


Thanks
Ram

**Comment by kentcdodds** [comment]
These are great questions for the chat: http://chat.angular-formly.com
