### ISSUE TITLE
hideExpression missing formOptions

### ISSUE THREAD

**Issue by chilversc** [formly-js/angular-formly#616]
When evaluating a `hideExpression` there is no `formOptions` variable.

This means there is no simple way to reference the `formOptions.data` field and leads to the odd scenario where to access the form options you use `this.options` but to access the field options you use just `options`.

I think the only change required would be to add `formOptions: $scope.options` to the [`getFormlyFieldLikeLocals`][1] function.

[1]: https://github.com/formly-js/angular-formly/blob/f8bc5479ce2dd66aafe2a513f68c2deb411d8d88/src/directives/formly-form.js#L366

**Comment by kentcdodds** [comment]
Technically [this](https://github.com/formly-js/angular-formly/blob/f8bc5479ce2dd66aafe2a513f68c2deb411d8d88/src/directives/formly-form.js#L369-L372) should have almost everything that [this](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L21-L29) has. I think the only thing that's missing is: `originalModel`, and `formOptions`. The other properties are actually properties on the `$scope` of the `formly-form` which is where the expression is evaluated and therefore you should have access to it in your expression.

I'd happily accept a (tested) PR to add these properties. If you're keen on it, that's great. If you need help, maybe someone from @formly-js/angular-formly-collaborators or @formly-js/angular-formly-collaborators-read could give you a little guidance. Thanks everyone!

**Comment by cynicaldevil** [comment]
I would like to create a PR for this bug. I am new to this project and have browsed through the formly docs a bit, and I have a basic understanding about this project now.

**Comment by kentcdodds** [comment]
Great, you might take a look at the CONTRIBUTING.md file as well :+1:

**Comment by cynicaldevil** [comment]
Ok, I dug into the docs and found that adding `formOptions: $scope.options` probably won't work because `hideExpression` is evaluated against the `form` scope instead of the `field` scope. I will have to try to find if the `field` scope has been initialized or not and then obtain it's scope via its index.( Or at least, this is how I think it should be :P ).
      As for the `originalModel` property, I am assuming that it will contain the field's model.

**Comment by kentcdodds** [comment]
Yeah, `originalModel` can simply be: `$scope.model` (the form's `$scope`). `formOptions` will need to be `$scope.options` (the form's `$scope`)...

**Comment by cynicaldevil** [comment]
Ok, got it. Will submit a PR soon.

**Comment by brutalcrozt** [comment]
since it merged, we should close this one?

**Comment by kentcdodds** [comment]
Yep! Feel free to close it. Thanks!

**Comment by brutalcrozt** [comment]
@kentcdodds maybe i don't get the right? or i missing something. even add label i can't do it. :smile:
