### ISSUE TITLE
Docs 404 

### ISSUE THREAD

**Issue by timelf123** [formly-js/angular-formly#618]
http://docs.angular-formly.com/ is down

**Comment by kentcdodds** [comment]
Seems to be up for me and isitup.org https://isitup.org/docs.angular-formly.com

**Comment by kentcdodds** [comment]
How's it looking for you now?

**Comment by kamilkisiela** [comment]
http://www.downforeveryoneorjustme.com/http://docs.angular-formly.com/

**Comment by benoror** [comment]
LGTM http://www.downforeveryoneorjustme.com/http://docs.angular-formly.com/

**Comment by timelf123** [comment]
Back up, thanks you speedy people
