### ISSUE TITLE
Disabling API check without require.js

### ISSUE THREAD

**Issue by theotherp** [formly-js/angular-formly#627]
All examples and instructions I can find on disabling API check require requireJS. How do I disable it without? Thanks.

**Comment by kentcdodds** [comment]
If you're simply using the global, then rather than requiring it, it's available as a global `apiCheck`. Then you disable it the same as in the docs.

**Comment by theotherp** [comment]
Uhm, I just realized I might've misunderstood something. I read the tips and they said to disable apiCheck.js in production. But I don't even use any custom API checks, so disabling it probably wouldn't do anything, right?

**Comment by kentcdodds** [comment]
No, angular-formly uses it heavily. You definitely want to disable it for production. There's an example on the website for production tips that uses globals.

I'm going to let you look at that and consider this issue closed. Check out the chat for more questions.

**Comment by gatspy** [comment]
api-check.js after loading is complete, use `apiCheck.globalConfig.disabled=true`.
formly version:8.4.0
