### ISSUE TITLE
Hotswapping template wrappers

### ISSUE THREAD

**Issue by synthecypher** [formly-js/angular-formly#631]
Is there anyway to configure template wrappers for a particular type.

Then switch these out relative to the `formly-form` they were used in.

**Comment by kentcdodds** [comment]
I'm not certain I understand what you mean by this. Could you give a more clear explanation of what you mean?

**Comment by kentcdodds** [comment]
Even better, maybe you could go to [the chat](http://chat.angular-formly.com) and describe what you're trying to do. Perhaps someone will be able to help you find another way.
