### ISSUE TITLE
defaultOptions specified as function not overriden in extending types

### ISSUE THREAD

**Issue by redhead** [formly-js/angular-formly#635]
With a chain of extending formly types, each having a function in `defaultOptions`, it does not override same-key options of the parent in more "concrete" types.

http://jsbin.com/wimifiyepo/1/edit?html,js,output

I don't know if that's intentional if using a function as `defaultOptions`, but I thought it should work regardless.

**Comment by kentcdodds** [comment]
This appears to be a bug. `defaultOptions` should work great as a function. But it appears to not work in this case. However, if we make the `abstractType` an object instead, it seems to work fine ([like so](https://jsbin.com/tureko/edit?html,js,output)).

I doubt that I'll have time to work on this I'm afraid. But feel free to [makeapullrequest.com](http://makeapullrequest.com) :-)
