### ISSUE TITLE
NEW MAINTAINER(S) NEEDED

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#638]
Hello everyone,

I don't think I have to say that I've been falling behind on issues and helping in the chat lately. I've really just lost my [open source stamina](https://medium.com/@kentcdodds/open-source-stamina-dafd063f9932) on this project. Please forgive me for that. I no longer use it at work or on side projects. I think that the best thing to do is for me to find someone who'd be willing to take this project to the next level of support and maintenance (and maybe build an Angular 2 version).

Please let me know if you'd like to take over the project by emailing me directly: [kent@doddsfamily.us](mailto:kent@doddsfamily.us). Please include the following information:
- Whether you're using the project regularly at work or otherwise
- Whether you have the time and interest to maintain the project and website

If we agree to bring you on as an owner, then I'll give you:
- Ownership status on all formly-js projects
- Access to @formly-bot 
- Publish rights on npm
- Access to docs.angular-formly.com

Thanks. It's been awesome to develop a project so widely used. I really do hope that my little contribution to the angular community has been valuable to some of you. Keep building awesome stuff!

-- Kent

**Comment by kentcdodds** [comment]
I should also mention that managing this project is primarily a matter of support at this point. There are definitely some bugs and a few tiny features, but for the most part, this project is done.

**Comment by ShashankaNataraj** [comment]
@kentcdodds I use this library at work. One suggestion, instead of handing this off to one person, why not create an angular-formly org and assign people to it?

**Comment by kentcdodds** [comment]
Thanks for the suggestion @ShashankaNataraj. That currently exists (and invitations are still open #481). I'm looking for someone to hand off account information, passwords, tokens, etc. to.

**Comment by kentcdodds** [comment]
If you're interested, I published a 3 minute podcast about this: https://www.briefs.fm/episodes/570

**Comment by benoror** [comment]
I want to publicly thank and congratulate @kentcdodds for his amazing work as angular-formly maintainer :clap: :tada: 

Good luck with your future projects and good luck with finding the right maintainer that angular-formly deserves :smile: 

Cheers mate!

**Comment by jorgemarcondes** [comment]
Hi, 
Im interested.
I am using the project and want to help to keep it updated.

**Comment by kentcdodds** [comment]
@jorgemarcondes fantastic. I'll add you to the collaborators on the org. Thanks!

**Comment by jorgemarcondes** [comment]
@kentcdodds awesome. Formly is a great tool! I will help as I can!

**Comment by barkoczi** [comment]
I would join as maintainer.

**Comment by kentcdodds** [comment]
Sweet @barkoczi, I'll add you to the collaborators.

**Comment by mohammedzamakhan** [comment]
I would love be join the team as maintainer

**Comment by agileurbanite** [comment]
I'd love to help contribute to this project as well.

**Comment by kentcdodds** [comment]
Thanks @agileurbanite! I'll add you to the collaborators as well.

For everyone on @formly-js/angular-formly-collaborators-read, you could really help out by investigating, reviewing, closing, and making PRs for [the issues](https://github.com/formly-js/angular-formly/issues). Also, make sure to watch the repo, and the various [formly-js](https://github.com/formly-js) repos as well.

If I see someone really taking initiative on the issues and things then I'll happily hand over write access and eventually publish access. Thanks!

**Comment by AjithJosephThomas** [comment]
@kentcdodds: I have not made much contributions in github. Angular-formly is a great directive and our team using it in a project. Please count me in, too.

**Comment by Stwissel** [comment]
I would be interested to help including an Angular2 TS port

**Comment by kentcdodds** [comment]
@Stwissel, talk with @mohammedzamakhan about how you can help with https://github.com/formly-js/ng2-formly :-)

**Comment by Doug-Shannon** [comment]
@kentcdodds do you have an update about the status of the maintainers for angular-formly and some of the other angular-formly related repositories like the bootstrap types?  Commits have pretty much died since April and I would hate to see formly go un-maintained.

**Comment by kentcdodds** [comment]
> I would hate to see formly go un-maintained.

Likewise. I've stopped watching the repos because I can't really help out anymore. My plan was to hand over control to anyone making pull requests, but nobody has really done that consistently. This tells me that either nobody's willing to step up to the plate of ownership or angular-formly is done.

I think at this point, @BarryThePenguin is probably the best candidate for ownership. What do you say @BarryThePenguin?

**Comment by sumitasr** [comment]
@kentcdodds W

**Comment by sumitasr** [comment]
@kentcdodds I use angular-formly in one of my dashboard application's production code and would love to help as a contributor.

**Comment by kentcdodds** [comment]
@sumitasr, I'll add you to the read-only collaborators. Start making PRs and I'll give you write access :)

**Comment by nbfontana** [comment]
Hello @kentcdodds , I would like to use angular-formly on mine [app-quickstart](https://github.com/GoHD/app-quickstart) Application that's based in Angular on the Front-end and Java at the Back-end. Could you add me as a read-only collaborator?

**Comment by TeChn4K** [comment]
Is Formly dead ?? :'(

**Comment by kentcdodds** [comment]
I'm fairly confident that formly is still a prime solution for building forms with AngularJS. It's been steadily growing in the number of downloads since I posted this almost a year ago. Formly's not dead. But based on the fact that the library has had very little development (and no active maintainers), but still growing in popularity tells me that it's "done."

Formly is no more dead than AngularJS. It's just done.

**Comment by kentcdodds** [comment]
Another interesting fact: angular-formly comes up (basically) first in pretty much every search criteria on npm for "angular forms": https://www.npmjs.com/search?q=angular%20forms

I think it's safe to say that angular-formly is the most popular abstraction for forms with angular.

**Comment by LuigiDAmico** [comment]
Hi Team AngularFormly,

Some quick questions:
- What are the number of user downloads in the last month?
- Do we have active owner(s) / contributors of this project? (i see pushes are very scarce at the moment)

@kentcdodds 🥇 Massive up to you for this project!

**Comment by kentcdodds** [comment]
@LuigiDAmico, from the README badge, you can see there are about 12,000 downloads on npm per month. It's extremely hard to tell from download numbers how many users there are. There are no active contributors or maintainers, so I've kept ownership of the project, but I don't watch the repo so I'm not sure how the community is doing (as far as people helping one another out or people finding the answers they need). If you want to contribute, please start helping out in the community.

I think that the project is more-or-less "done" based on the fact that there are rarely new issues filed on the project and no critical issues and rarely any pull requests. It's helped tens (hundreds) of thousands of developers build better forms with AngularJS :)
