### ISSUE TITLE
Fix auto-release

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#643]
If someone wants to look at why the `semantic-release` part of [this build](https://travis-ci.org/formly-js/angular-formly/builds/111567902) failed, that would be great. We wont get new versions of angular-formly released until this is resolved.

**Comment by BarryThePenguin** [comment]
The problematic commit 28c648dc83cb75ded78e5d984a81cfd19c544e1c

Now just trying to figure out what went wrong/how to restore it...

**Comment by BarryThePenguin** [comment]
@kamilkisiela do you still have reference to 28c648dc83cb75ded78e5d984a81cfd19c544e1c, it looks like the branch referencing the commit was deleted, or was overwritten by a force push. Are you able to restore it?

**Comment by BarryThePenguin** [comment]
Either that or @kentcdodds will need to publish manually...

**Comment by kentcdodds** [comment]
If I publish manually, will things go back to normal?

**Comment by BarryThePenguin** [comment]
Sounds like it. The latest release on npm (7.5.0) has a gitHead of 28c648dc83cb75ded78e5d984a81cfd19c544e1c. That no longer exists in git history for some reason. So `semantic-release` falls over when it tries to compare all commits since that specific commit

**Comment by kentcdodds** [comment]
Alrighty, released `7.5.1`. I'll merge #639 after I verify [this](https://github.com/formly-js/angular-formly/pull/641#issuecomment-188634110) is fixed with the new release.

**Comment by kamilkisiela** [comment]
I'm ofline for few days. Is it working now? Do you need any help?

About commit, I don't have that commit in my local branch.

**Comment by vltr** [comment]
Hi! Is this related to the fact that the 8.0.0 of the bower package doesn't comes with the generated dist files while npm package does?

**Comment by kentcdodds** [comment]
Looks like bower's broken as well... I'm actually tempted to stop officially supporting bower and direct people to the solution in #589 with npmcdn.com

**Comment by vltr** [comment]
Wow. Good article referenced in #589. I think I might migrate all my dependencies to npm as well :smile:

**Comment by vltr** [comment]
@kentcdodds almost forgot! Made this example some days ago: http://jsbin.com/fepilo/7 :smiley: 

And I'm already using version 8 from npm :wink:

**Comment by kentcdodds** [comment]
Ah! Neat! Want to add it to the examples site? https://github.com/formly-js/angular-formly-website/blob/master/CONTRIBUTING.md#creating-an-example

**Comment by vltr** [comment]
@kentcdodds yeah, I'll love to. I also made an integration with Leaflet, but I'll create an example later (time!) :smiley:

**Comment by JordanBelford** [comment]
```jspm install angular-formly``` installs 7.5.2, which is broken because there is no dist directory.

For now I am just installing 7.3.9 with ```jspm install angular-formly=github:formly-js/angular-formly@7.3.9```

Installing from npm grabs 8.0.0, but I there is no 8.0.0 release or tag on github, as far as I can tell. What's that about?

**Comment by BarryThePenguin** [comment]
Took a bit of messing around. But I think this is fixed now. Some release notes have gone missing. Anyway to build those manually? Anyone want to give it a go?

**Comment by BarryThePenguin** [comment]
Looks like we got this sorted

**Comment by kentcdodds** [comment]
Thank you for the help @BarryThePenguin!
