### ISSUE TITLE
No dist directory with bower install

### ISSUE THREAD

**Issue by JessyRiordan** [formly-js/angular-formly#648]
When installing formly with bower there is no `dist` directory, specifically `dist/formly.js`.

It is not in the repository either.

Am I missing something?

**Comment by kentcdodds** [comment]
Hi @JessyRiordan, yes, this is being tracked in #643, thank you for your patience (and help!)

**Comment by JessyRiordan** [comment]
Awesome thanks! :smile:

**Comment by BarryThePenguin** [comment]
Hi @JessyRiordan, can you see if this is fixed in the latest version?

**Comment by JessyRiordan** [comment]
@BarryThePenguin 

It is fixed! :smile_cat:
