### ISSUE TITLE
Custom Validations select is double the label.

### ISSUE THREAD

**Issue by berdemer** [formly-js/angular-formly#652]
[jsBin](https://jsbin.com/recuji/edit?html,js,output) When used in conjunction Custom Validators and select is double the label. best regards

**Comment by kentcdodds** [comment]
A wrapper without defined `name` or `type` will be set as the `default` template. This could probably be made more clear in [the docs](http://docs.angular-formly.com/docs/formlyconfig#setwrapper)

> You can have a default (used by all templates), named template wrappers, and typed template wrappers (used by fields with the specified type)

If you give the first wrapper a name, or `types`, you'll see this behavior is corrected: https://jsbin.com/tafiwa/edit?html,js,output

In the future, please ask questions in the chat: http://chat.angular-formly.com thanks!

**Comment by kentcdodds** [comment]
Just realized that perhaps you didn't ask this in the chat because you legitimately thought it was a bug. Thanks for the reproducible example! That made it much easier to help you :sparkles:
