### ISSUE TITLE
8.0 + Model Changes not updating form

### ISSUE THREAD

**Issue by TheMcMurder** [formly-js/angular-formly#656]
Code is the same in these two examples:

8.0.3 : http://jsbin.com/holiro/2/edit?html,css,js,output
7.5.1 : http://jsbin.com/jivojo/3/edit?html,css,js,output

Notice that when the model changes in 7.5.1 the form updates but when the model changes in 8.0.3 the form no longer changes

**Comment by JacoBezuidenhout** [comment]
+1 same problem here

**Comment by franzeal** [comment]
Saw the same thing and reverted back.

**Comment by BarryThePenguin** [comment]
@kwypchlo, are you able to look into this? I'm assuming it's related to the breaking change that was introduced in #639. It may be that it just needs to be documented a little more.

**Comment by JordanBelford** [comment]
Are there any other breaking changes with 8.0?

**Comment by melnac** [comment]
I have the same problem. What can i do to resolve or workaround the problem ? I am using v8.0.3 and all my application is now broken. Resolution is very urgent. Thanks in advance.

**Comment by BarryThePenguin** [comment]
@melnac until this get's sorted you'll have to use a version before 8.0.0

**Comment by melnac** [comment]
thanks for reply. Where i can get a version before 8.0.0. I use formly via cdn...

**Comment by BarryThePenguin** [comment]
According to @TheMcMurder jsbin above, it's available at https://npmcdn.com/angular-formly@7.5.2

**Comment by melnac** [comment]
many thanks, i will try

**Comment by kwypchlo** [comment]
I prepared pull request #657 that fixes that issue, sorry for the inconvenience.
@BarryThePenguin could you take a look?

**Comment by abodacs** [comment]
+1 same problem here

**Comment by BarryThePenguin** [comment]
This looks good now in 8.0.4. Thanks for your quick assistance @kwypchlo :runner: :dash:

**Comment by JacoBezuidenhout** [comment]
Ah great!! Thanks guys!!

**Comment by kentcdodds** [comment]
Thanks @kwypchlo!

![giphy](https://cloud.githubusercontent.com/assets/1500684/13674615/0d155626-e693-11e5-84fe-1b87244a44a7.gif)
