### ISSUE TITLE
how can i call a function of my controller after complete field in formly? :(

### ISSUE THREAD

**Issue by pichlou** [formly-js/angular-formly#683]

**Comment by Blaze34** [comment]
What do You mean "complete field"?
Maybe You have some [live](http://jsbin.com/) example?

**Comment by pichlou** [comment]
when dynamic field is completed,call a function,i.e:when complete creating select or input element,i'm calling my custom javascript function in my controller,element is not exist with access it by selector,but it is available in my page elements with specific class,this mean element in controller not create completely
is there a function that i call my custom javascript function after complete assign element specification? :(

**Comment by Blaze34** [comment]
I don't know any callbacks.
As an option You can use
```
templateOptions: {
  callback: () => { ... }
}
```
and in template add `ng-init="to.callback()"`

It's just idea =)

**Comment by pichlou** [comment]
when dynamic field is completed,call a function,i.e:when complete creating select or input element,i'm calling my custom javascript function in my controller,element is not exist with access it by selector,but it is available in my page elements with specific class,this mean element in controller not create completely
is there a function that i call my custom javascript function after complete assign element specification? :(

**Comment by pichlou** [comment]
thanks for your answer,my format is json,and problem really is this,in json format i cant use function in callback or link function :))
