### ISSUE TITLE
Am getting a error while referring a directive in JSON file in Angular formly

### ISSUE THREAD

**Issue by DeveBj** [formly-js/angular-formly#689]
Hello Guys,

Am getting the below error in my console, when am referring a directive in a json file, please do help me to get it clear 

**Error: [$compile:nonassign] Expression 'field.model || model' used with directive 'formlyField' is non-assignable!
http://errors.angularjs.org/1.4.7/$compile/nonassign?p0=field.model%20%7C%7C%20model&p1=formlyField
    at AngularFormly?v=sa4duocMTcTg_JhSyJYMQTujdzUOyBnxvWWeouhNJbc1:1
    at w (AngularFormly?v=sa4duocMTcTg_JhSyJYMQTujdzUOyBnxvWWeouhNJbc1:1)
    at y (AngularFormly?v=sa4duocMTcTg_JhSyJYMQTujdzUOyBnxvWWeouhNJbc1:1)
    at Object.<anonymous> (AngularFormly?v=sa4duocMTcTg_JhSyJYMQTujdzUOyBnxvWWeouhNJbc1:1)
    at w.$digest (AngularFormly?v=sa4duocMTcTg_JhSyJYMQTujdzUOyBnxvWWeouhNJbc1:1)
    at w.$apply (AngularFormly?v=sa4duocMTcTg_JhSyJYMQTujdzUOyBnxvWWeouhNJbc1:1)
    at updateModel (ReportSelector:875)
    at HTMLInputElement.options.onSelect (ReportSelector:883)
    at e.n.extend._selectDate (jqueryui?v=rRrNQPNPngUeInkPjaarch2Kd5VIusAQRRIYxX7Od0E1:1)
    at e.n.extend._selectDay (jqueryui?v=rRrNQPNPngUeInkPjaarch2Kd5VIusAQRRIYxX7Od0E1:1)**

**Comment by kwypchlo** [comment]
Hello, can you provide a fiddle for your case? There is only one place in the whole code where expression `field.model || model` is used and it never caused any troubles (so far).

**Comment by DeveBj** [comment]
hello, it got resolved, now am stuck up with the validation part, I have created a jquery Ui datepicker directive which am applying it to the JSON file like this 
"ngModelAttrs": {
                    "datePicker": {
                        "attribute": "date-picker"
                    }}
it's working fine, am using this directive for both From and To date, I need to validate that To date must not be lesser than the From date (ie: To Date must be greater than the From Date ), for this I have created a DIrective and it's working finr in Plain HTML Elements, in the HTML input elements am assigning the To date ng-model to the validation directive in the From date lets say like this: 
```
<input type="text" ng-model="fromdate" valueupdate="fromdate"  datepicker datecheck="todate" />
  <input type="text" ng-model="todate" datepicker   />
```
If you see in the above code of from date am introducing a attribute called valueupdate and my ditrective name for checking the from and to date in datecheck, am assigning the To date ng-model to the from date datecheck directive like this datecheck="todate", I need to do this in the JSON file to apply that datecheck validation directive, Please help me in this regards
