### ISSUE TITLE
Angular formly is not working/displaying in Firefox and safari browesr

### ISSUE THREAD

**Issue by pavithra-r** [formly-js/angular-formly#702]
I am using angular-formly in one of my project and it is working fine in chrome browser and in android mobile. i have followed http://angular-formly.com/#/  this tutorial to develop this functionality. But when i try in firefox,safari and in iphone it is not displaying and no console errors also. Any suggestions ?

**Comment by sumitasr** [comment]
@pavithra-r Which version of formly are you using ? And can you share your code with something like http://jsbin.com/ ?

**Comment by pavithra-r** [comment]
Hi sumitasr,
 thank you so much for your response.

Formly version that i have used in my project:
    "angular-formly": "^8.2.1",
    "angular-formly-templates-bootstrap": "^6.3.2",
    "api-check": "^7.5.5"
    "angular": "~1.3.8"

http://jsbin.com/tapuha/9/edit?html,js,output
The similar code only am following in my project but we are using bower components not a cdn link.

Then our project structure and coding style also little different so in jsbin i cant able to put my code properly.sorry for that.
The code that i used inside my project ,
https://jsbin.com/dukeva/3/edit?html,js,output

Then in one more js file i have added this code,

(function() {
   'use strict';
   //Angular Formly 
    var app = angular.module('app.formly', ['formly', 'formlyBootstrap','ngAnimate'])
})();

In Google Chrome am getting the output like this,
![image](https://cloud.githubusercontent.com/assets/18478881/17240680/89adb410-558a-11e6-8db6-ef95690f0da2.png)

In Mozila Firefox,

![image](https://cloud.githubusercontent.com/assets/18478881/17240716/b566b0fc-558a-11e6-97cd-a3fe6c145472.png)


Am fresher and am new to this technology am not getting how its working fine in google chrome,android mobile and not displaying in mozile,safari,iphone.

Once Again thanks for your help.

**Comment by icruces** [comment]
@pavithra-r Have you checked with the Firefox debugger if the form is generated in the DOM? I would review the css of the form or its container.

**Comment by pavithra-r** [comment]
@icruces Form is generated but that paramaters(input textbox,textarea) are not repeating in firefox.( not generated from controllers)

**In Firefox:**
![image](https://cloud.githubusercontent.com/assets/18478881/17246118/aee831fc-55a7-11e6-82d4-a5ceb516e6ca.png)




**In googlechrome:**
![image](https://cloud.githubusercontent.com/assets/18478881/17246280/a25151f2-55a8-11e6-9ad2-5228167007b0.png)

![image](https://cloud.githubusercontent.com/assets/18478881/17246291/aebf02fe-55a8-11e6-95de-0714ff56e703.png)

![image](https://cloud.githubusercontent.com/assets/18478881/17246297/b869cf28-55a8-11e6-821e-56dc9fb88695.png)

**Comment by kiran8143** [comment]
Formly has this issues in safari ,IE and mobile browsers also.
Some time's the validation messages over lap. I have give up using angular formly for client projects

**Comment by kiran8143** [comment]
Formly has this issues in safari ,IE and mobile browsers also.
Some time's the validation messages over lap. I have give up using angular formly for client projects

**Comment by pavithra-r** [comment]
Hi ,
 I had figured out that issue, it is due webcomponents.js.For map I had  installed the google map bower component in that webcomponent.js having some issue.
Once I comment this script, I'm able to the see angular form in all the browser.
