### ISSUE TITLE
Model is not updated when input is inside angular component

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [formly-js/angular-formly#718]
When a custom type is wrapping an input which is an angular component, changes made to passed in value inside that component  are not propagated back to the formly model.

This does work as expected when input is inside a directive though. I assume it's related with two-way vs one-way data binding.

Is this a bug or do I need some extra logic to propagate changes back from a component?

Here's a [jsbin](http://jsbin.com/lakuqov/1/edit?js,output).

**Comment by smajl** [comment]
You are right, it is related to one-way and two-way binding. You are using one-way binding in your component, so things are going one way, right? Just use `=`. Nobody said you have to use `<` only in components...

**Comment by ivanvoznyakovsky** [comment]
@smajl you're right. I was trying to follow angular's docs saying `Inputs should be using < and @ bindings.`, but this does not work in this case.
closing as not related to formly
