### ISSUE TITLE
Dynamic async validation message

### ISSUE THREAD

**Issue by harm-less** [formly-js/angular-formly#730]
Hello,

I can't seem to figure out if it's even possible or not. [This demo](http://angular-formly.com/#/example/other/unique-value-async-validation) is pretty much what I want to achieve, but I'd like the server message to be shown in the message (dynamic message).

Even if I turn the ```message```'s value to a method, the server's response (in this case the message from the thrown error) can't be retrieved. Am I missing something or is this a feature missing?

**Comment by U-like** [comment]
I think you're looking for something like this http://jsbin.com/zafoyi/2/edit

**Comment by harm-less** [comment]
That seems to do exactly what I need. Thank you so much for explaining this to me!

**Comment by U-like** [comment]
Glad to help! :wink:
