### ISSUE TITLE
Documenation site is broken

### ISSUE THREAD

**Issue by looser** [formly-js/angular-formly#744]
http://docs.angular-formly.com/

returns a broken site

![formly](https://user-images.githubusercontent.com/463137/28963812-cfca4f18-790a-11e7-99db-c948124cb01b.png)

**Comment by Vinoth18** [comment]
Hi @looser,

I can access the site via http://docs.angular-formly.com/

Regards,
Vinoth

**Comment by looser** [comment]
Alright! Who knows which server had a little issue.

Can be closed!
