### ISSUE TITLE
Integrate coveralls.io

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly#78]
A suggested in #73

**Comment by sparty02** [comment]
@kentcdodds I need your help on two things to make this happen:
1. Establish the angular-formly repo at coveralls.io.  When you sign in with your github creds, it'll be obvious what to do.
2. Add an environment variable in travis called "COVERALLS_REPO_TOKEN".  The value for this will be provided after you establish the repo in coveralls.

**Comment by kentcdodds** [comment]
Done and done :+1: Thanks! This will inspire me to increase the coverage of the codebase. I'm sure it's pretty low right now considering I just started writing tests for it a few months ago :-/

**Comment by sparty02** [comment]
Thanks!  It's actually at 51% so you technically have a majority of the codebase tested....  :wink:

**Comment by sparty02** [comment]
P.S.  Coveralls has some cool features, so poke around whenever you get some spare time.  Some interesting ones include notifications (by default it includes comments in PRs regarding coverage, but you can also have it alert you in slack, email, etc) and the ability to fail based on a level of coverage or amount of decreased coverage.  Pretty nifty....

**Comment by kentcdodds** [comment]
Yeah, I use coveralls for [api-check](https://github.com/kentcdodds/apiCheck.js) (which fails if it has anything less than 100% code coverage :-D). Thanks for doing this. I think that I'm going to put some time into writing more tests to bring the coverage up before I add the badge to the readme though. It's a little embarrassing... I'll try to get that done asap. Thanks!

**Comment by kentcdodds** [comment]
Closing this in favor of a single issue
